onivim/oni2

- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/Oni_Model.re
- src/Model/Sub.re
- src/Model/Sub.rei
- src/Store/FileExplorerStore.re
- src/Store/StoreThread.re
__Issue:__ The focused file in the explorer is not switching reliably. If you open multiple files, and then click the tab of a file to focus it, the explorer won't auto-scroll to the file until the key is pressed.
__Defect:__ The `BufferEnter` event was used to detect when the focused file is changed, but it's not reliable (ie, it's in the process of being phased out). Previously, we always kept the Vim state in sync with the editor state at all times - so `BufferEnter` would be dispatched from Vim during this synchronization.
However, we switched to a 'push' model - where we push the state on a keypress or other API calls. This means that our state can be the 'source of truth', but it also means that this event - like `BufferEnter` isn't necessarily reliable to use, since libvim's view …
> fix(explorer): Focused file not switching reliably

- docs/docs/getting-started/installation.md
Since OSX 10.12 is EOL by Apple (and we don't have a good way to test it at the moment, since Azure CI machines don't have 10.12 VM images) - remove the note in the docs about 10.12 support.
Closes #902
> docs(installation): OSX - Remove note on 10.12 support

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Core/LanguageConfiguration.re
- src/Core/LanguageConfiguration.rei
- src/Model/VimContext.re
- src/reason-libvim/Context.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/Core/LanguageConfigurationTest.re
- test/reason-libvim/AutoIndentTest.re
For auto-indent, we were basing our calculation purely off the previous line. However, this is not sufficient to handle some of the rules that show up in the indentationRules, like `indentNextLinePattern`. 
The rules that VSCode extensions follow are the same as textmate, defined here: https://macromates.com/manual/en/appendix
To be able to handle the `indentNextLinePattern`, which has some non-local effects, we need additional context to the auto-indent handler.
> refactor(libvim): AutoIndent - more context for indentation calculation

- src/Feature/Editor/ContentView.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Helpers.re
- src/Feature/Editor/SurfaceView.re
Another refactoring in preparation for word-wrap (#1969 ) - pull the lines for rendering from the editor (which is aware of wrapping), rather than the buffer directly (which is not aware of the view / wrapping).
> refactor(editor): Pull view lines from Editor instead of external buffer

- src/Feature/Editor/GutterView.re
The line number rendering should be using the new `bufferLineByteToPixelPosition` methods, to account for incoming features like codelens or word-wrapping.
> fix(editor): Line number positioning

- scripts/osx/run.sh
__Issue:__ When running `oni2` with the latest builds, on OSX, it is staying attached to the terminal process. The expected behavior is it should detach, unless `-f` or `--nofork` are passed - in which case it should stay attached.
__Fix:__ Run `Oni2` instead of `Oni2_editor`.
Looks like this is a regression from https://github.com/onivim/oni2/pull/1927 - I still see the `ONI2_BUNDLED` environment variable get passed, so I think this is OK. @zbaylin - is there anything else I should check here?
> fix(cli): OSX - 'oni2' command is not forking by default

- src/reason-libvim/Vim.re
- test/reason-libvim/AutoIndentTest.re
__Issue:__ When pressing `O` (open a new line above) on a line that increases indentation, the new line would be indented (even though it is _above_ the line).
__Defect:__ I assumed the comparison line coming from `libvim` is always the previous line, but it's actually the source line - our auto-indent callback assumes it's the previous line.
__Fix:__ Pass the previous line instead of the source line to the callback, to properly evaluate auto-indent.
> fix(autoindent): Open-above

- src/UI/QuickmenuView.re
This was noted by user papasmurf on Discord. As of now, the command palette/other quick menus don't contract to the size of the number of items. This PR adds a `numItems` param to the `dropdown` style and a `rowHeight` value to `Constants` to calculate the appropriate height of the quickmenu.
GIF:
> fix(QuickMenu): contract to only the number of available items

- src/Feature/Hover/Feature_Hover.re
- src/Feature/Hover/Feature_Hover.rei
- src/Feature/SignatureHelp/Feature_SignatureHelp.re
- src/Feature/SignatureHelp/Feature_SignatureHelp.rei
This fixes the multiple hovers issue @bryphe noted in #1973. The request now takes an editor, and the view checks that it is the same when displaying.
> fix(hover & signature help): check what editor the request was sent from

- src/Feature/Editor/OverlaysView.re
There was a regression in the completion-overlay positioning from https://github.com/onivim/oni2/pull/1953 - we were incorrectly adding the `gutterWidth` to the `y` (vertical) position as opposed to the `x` (horizontal) position.
> fix(completion): Positioning regression

- src/Feature/Layout/EditorGroupView.re
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/UI/EditorView.re
__Issue:__ Our completion UI would show up in all visible editor windows, like:
__Defect:__ This looks like a regression from #1977 - the `isActive` field is hardcoded to `true`, and the completion rendering uses that flag to decide which split to render on. 
__Fix:__ Wire up the `isActive` property - which is being set elsewhere, but just not plumbed through.
Future work:
- The completion should be its own feature project, and keep track of the editor we make the request (like we're doing for hover and signature help).
> fix(editor): Completion showing up in multiple windows

- src/Components/Tabs.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Msg.re
- src/Feature/Editor/SurfaceView.re
This fixes #1994. I tested it on multiple directions/settings on my MacBook Pro's trackpad, and it all followed the system config.
> fix(editor): add horizontal scrolling to tabs and editor

- src/reason-libvim/Vim.re
- test/reason-libvim/AutoIndentTest.re
__Issue:__ The fix in #1976 missed a case - opening-above when the previous line is an empty line. In that case, we would erroneously think we needed to correct for indentation, when in reality we did not.
__Fix:__ Implement test case covering this case; don't correct when the previous line is empty.
> fix(autoindent): Open above with empty previous line

- src/Components/HoverView.re
This fixes #1999. Before we had an inner node that was moving the position, but this removes that and just changes the anchor point's position.
> fix(components): Fix HoverView positioning issues with `Top

- docs/docs/for-developers/building.md
Tiny change to recommend the latest version of `esy` in the docs, rather than specifically `0.6.2` since there was some issues that were fixed in the later version and aligns the docs with the CI (#1869, #1866).
This seems like the best way to prevent us having to change every update, or alternatively we could stick a link in to the CI config to recommend using what we use in the CI.
> docs(installation): Update esy version in docs

- src/Store/KeyBindingsStoreConnector.re
__Issue:__ Some of the `Control+W` window commands aren't working:
- `Control+W, V` to open a vertical split
- `Control+W, S` to open a horizontal split
__Defect:__ These used to be handled by `libvim`, and forwarded up to us - but we need first-class bindings for it now that we're handling all of the window commands (and management) in the Onivim layer.
__Fix:__ Add default bindings for these.
Fixes #2019
> fix(keybindings/#2019): Add <C-W>V/<C-W>S default bindings

- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Model.re
- src/Feature/Layout/Msg.re
- src/Feature/Layout/View.re
This adds `groupId` to `GroupTabClicked` instead of assuming the clicked tab is in the active group and crashing if it isn't.
Probably fixes #2011, but I can't be entirely sure since there' no repro. I can;t see what else it could be though, and this is a likely cause and sketchy assumption.
> fix(layout/#2011): assert failure on GroupTabClicked

- src/Feature/Layout/Configuration.re
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Model.re
- src/Feature/Layout/View.re
- src/Store/Features.re
This adds a "single tab mode" that hides the tab bar and restricts each group to a single tab. The effect of this is that `:q` will always close the split/group even if several buffers have been opened in it.
There is one caveat, however. If single tab mode is enabled when there are multiple tabs in a group, the extra tabs won't disappear immediately. Only when another buffer is opened will they be replaced. Any fix I can think of for this would be excessively complex for something that is designed to always be on or off, not toggled mid-session, so I doubt it's really worth it to fix it.
Addresses #592 - This should be the final piece of the puzzle for this, depending on how complete the support needs to be at this point.
> feat(layout/#592): layout tabs - part 3 - single tab mode

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Core/Utility/ListEx.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Model.re
- src/Model/Actions.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Goto.re
- src/reason-libvim/TabPage.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- src/reason-libvim/dune
- test.esy.lock/index.json
This wires up the `:tab*` commands and `gt/gT`.
Depends on https://github.com/onivim/libvim/pull/211
Addresses #592
> feat(layout/#592): layout tabs - part 2 - `:tab*` commands and `gt/gT`

- docs/docs/configuration/settings.md
Documents the settings added in #2013 and #2032
> docs: add section with layout configuration settings

- src/Feature/Editor/BufferViewTokenizer.re
- src/Feature/Editor/CursorView.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/SurfaceView.re
Refactoring to remove parts of the editor from going directly against a raw buffer line, in support of implementing word wrap in #1969
> refactor(editor): Add getCharacterAtLocation function, use with CursorView

- src/Core/BufferLine.re
- test/Core/BufferLineTests.re
Fix a crash exposed by the word wrap work in #1969
> fix(editor): Exception in BufferLine.getByteFromIndex

- bench/lib/Helpers.re
- src/Core/Config.re
- src/Core/Config.rei
- src/Core/dune
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Msg.re
- src/Feature/Formatting/Feature_Formatting.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Model.re
- src/Model/Actions.re
- src/Model/EditorScope.re
- src/Model/EditorVisibleRanges.re
- src/Model/Oni_Model.re
- src/Model/State.re
- src/Model/VimContext.re
- src/Store/CompletionStoreConnector.re
- src/Store/Features.re
- src/Store/StoreThread.re
- src/Store/VimStoreConnector.re
- src/UI/EditorView.re
For word-wrap - we need to know whether the minimap is enabled. Previously, we only kept track of this at render time, but it needs to around for the wrapping logic to know about the available buffer space. This change adds an editor subscription to track the minimap setting, and update editors if necessary.
> refactor(editor): Config subscription, internalize minimap state

- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
__Issue:__ When `experimental.editor.smoothScroll` is enabled, the mouse interactions would feel fuzzy or laggy
__Defect:__ Smooth scroll was being initiated in mouse gestures, but for mouse input, we shouldn't delay or animate.
__Fix:__ For the mouse-driven gestures - we set an `isScrollAnimated` flag to `false` - and when the scrolling happens another way (ie, via cursor movement) - we set it to `true`.
> fix(editor): Fix mouse interactions with smooth scroll

- node/request.js
- src/Core/NodeTask.re
- src/Core/NodeTask.rei
- src/Core/Oni_Core.re
- src/Core/dune
- src/ExtensionManagement/Oni_ExtensionManagement.re
- src/ExtensionManagement/Oni_ExtensionManagement.rei
- src/Extensions/Oni_Extensions.re
- src/Service/Net/Service_Net.re
- src/Service/Net/Service_Net.rei
- src/Service/Net/dune
- src/Store/CommandStoreConnector.re
- src/bin_editor/HealthCheck.re
- src/bin_editor/dune
- test.json
- test/ExtensionManagement/InstallerTests.re
- test/OniUnitTestRunner.re
- test/OniUnitTestRunnerCI.re
- test/OniUnitTestRunnerServiceNet.re
- test/Service/Net/RequestTests.re
- test/Service/Net/TestFramework.re
- test/Service/Net/dune
- test/dune
For extension management, we need a way to query the `open-vsx.org` directory - this adds a `Service_Net` service project with a `Request.json` function, to help with this. Also adds some test infra and a health-check for making a `json` request.
Unfortunately, there isn't a Luv-based JSON request OCaml module at the moment - we have `fetch`, but it uses `Lwt`, and we need `Lwt.main_run` to execute it - which I'm not sure we can parallelize with our app execution (`Lwt.main_run`) is blocking. So for now - I defer the work of making a request to our bundled `node`. Hopefully, in the future, we can switch to a pure OCaml+Luv-based solution for making requests.
> feat(extensions): Add Service_Net + JSON requests

- src/CLI/Oni_CLI.re
- src/CLI/Oni_CLI.rei
- src/Service/Extensions/Service_Extensions.re
- src/Service/Extensions/Service_Extensions.rei
- src/Service/Extensions/dune
- src/bin_editor/Oni2_editor.re
- src/bin_editor/dune
- src/bin_launcher/Oni2.re
- test/Cli/IntegrationTest.re
This adds a `--query-extension` CLI parameter, like: `oni2 --query-extension redhat.java`, which queries the open-vsx.org catalog and returns some info, like:
```
Extension Language Support for Java(TM) by Red Hat:
- Description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- Homepage: https://github.com/fbricon
- Download Url: https://open-vsx.org/api/redhat/java/0.63.0/file/redhat.java-0.63.0.vsix
- Versions:
- Version latest: https://open-vsx.org/api/redhat/java/latest
- Version preview: https://open-vsx.org/api/redhat/java/preview
- Version 0.63.0: https://open-vsx.org/api/redhat/java/0.63.0
- Version 0.62.0: https://open-vsx.org/api/redhat/java/0.62.0
- Version 0.61.0: https://open-vsx.org/api/redhat/java/0.61.0
- Version 0.60.0: …
```
> feat(extensions/#1018): Implement CLI extension query

- src/reason-libvim/Native.re
- src/reason-libvim/Undo.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test/reason-libvim/Helpers.re
- test/reason-libvim/UndoTest.re
__Issue:__ Sometimes, the formatting changes that would come from the extension host would not be un-doable.
__Defect:__ 
There were a couple of bugs here:
First, when making a format request, the format provider can sometimes send edits that are out of range. For example, when formatting a buffer that is 90 lines long, sometimes the edits will actually say they are editing up to line 94. This part is handled OK - we should handle this gracefully.
However, when we were communicating the undo region, prior to applying the edits, we would use the end line from the format request, that could be out of range.
We'd hit this logic:
```
if (top >= bot || bot > curbuf->b_ml.ml_line_count + 1)
return FAIL; // rely on caller to give an error message
```
- the `u_save` function would not create an …
> fix(formatting/#2052): Undo is not working consistently with formatting

- src/Service/Extensions/Service_Extensions.re
- src/Service/Extensions/Service_Extensions.rei
- src/bin_editor/Oni2_editor.re
This hooks up an API call for us to query against the open-vsx registry for extensions. There's no UI exposed for this, yet, but some output is shown when running `--query-extension`, ie:
`oni2 --query-extension java` results in:
```
Showing extensions 0 - 16 of 16
redhat.java:
- Name: Language Support for Java(TM) by Red Hat
- Description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- Url: https://open-vsx.org/api/redhat/java
- Version: 0.63.0
---
vscode.java:
- Name: Java Language Basics (built-in)
- Description: Provides snippets, syntax highlighting, bracket matching and folding in Java files.
- Url: https://open-vsx.org/api/vscode/java
- Version: 1.46.1
---
vscjava.vscode-maven:
- Name: Maven for Java
- Description: Manage Maven projects, …
```
> feat(extensions): Add search API to query open-vsx store

- src/Core/NodeTask.re
The 'detached' flag causes a new console window to be allocated on Windows - similar issue to #1744 / #1746
> fix(windows): Remove 'detached' flag for NodeTask

- src/Exthost/Client.re
- src/Exthost/ExtensionActivationReason.re
- src/Exthost/ExtensionId.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Request.re
- test/Exthost/ActivationEventsTest.re
- test/Exthost/ExtensionsTest.re
- test/Exthost/LanguageFeaturesTest.re
- test/Exthost/Test.re
The vscode extension host exposes a `deltaExtensions` API - an API where we can load extensions on-demand (right now, we only load extensions on startup).
This is helpful for two use cases for us:
1) When installing an extension, we can activate it immediately, without needing the user to restart the extension host or editor
2) We could make our extension loading on startup asynchronous, and stream extensions to the `deltaExtensions` API as we load (right now, extension loading is totally synchronous on startup - not ideal for startup perf!)
This adds an API for calling into via our `Exthost` module, along with some simple test cases.
> refactor(exthost): Add $deltaExtensions API

- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/InitData.re
- src/Exthost/Extension/Manifest.re
Change property extensionKind to list of strings as described in
https://code.visualstudio.com/api/advanced-topics/remote-extensions#:~:text=%22extensionKind%22%3A%20%5B%22workspace,extensions%20fall%20into%20this%20category
The property extensionKind have only
"extensionKind": ["workspace"]
"extensionKind": ["ui"]
"extensionKind": ["ui", "workspace"]
"extensionKind": ["workspace", "ui"]
Therefore the old way "extensionKind":"workspace" or "extensionKind": "ui"
is not valid anymore and has also be updated in InitData.re
Fixes #2097
> fix(exthost): Successful install and load extension (flutter/dart) (#2097)

- src/Store/KeyBindingsStoreConnector.re
Fix regression from #2092, which breaks entering visual block mode.
> fix: Revert change to Control+V binding

- src/Feature/Extensions/Model.re
- src/Service/Extensions/Query.re
- src/Service/Extensions/Service_Extensions.rei
__Issue:__ There was a race condition in our search experience - if a long-running query gave results after a short-lived query, it would displace the more recent one.
__Defect:__ We always assumed the latest query was the right one.
__Fix:__ Verify the search text for the query results matches the current search text
> fix(extensions): Fix stale results when searching extensions

- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/InitData.re
- src/Service/Extensions/Catalog.re
Several first-party extensions rely on telemetry info being set in the extension host - we weren't sending it in the proper form. We don't actually populate or track these - so we just use 'Anonymous'.
> fix(exthost): Populate TelemetryInfo for extensions

- src/Feature/Extensions/ItemView.re
Temporary fix / workaround to avoid the hang in #2140 - searching the 'p' character would bring in an extension that had an emoji as a final character - and then a bug in our shaping / text-overflow would hang when we tried to shorten & ellipsize the text.  This works around it by removing the `textOverflow(Ellipsis)` style
> fix(extensions/#2140): Avoid hang in #2140 by removing text-overflow ellipsis

- src/Feature/Extensions/Model.re
- src/Service/Extensions/Effects.re
- src/Service/Extensions/Management.re
- src/Service/OS/Service_OS.re
__Issue:__ There were a few bugs with the uninstall experience:
1) The error messages coming from luv weren't readable via `Printexc.to_string`
2) On OSX, we were getting 'too many open files' error for large extensions
3) The uninstall notification was an 'error' even though it should be success'
__Fix:__
1) For luv exceptions, use `Luv.Error.strerror` to get a more readable form
2)The `rmdir` was heavily parallelized - this moves the operation to be sequential, which doesn't open as many files. It's a bit slower, so we may want to look at clustering or combining some of the operations up to a fixed limit.
3) Use proper notification kind
> fix(extensions): Fix extension uninstall blockers

- src/Feature/Extensions/ListView.re
The extensions pane was resizable, but the contents would not grow / stretch to fit the resized sidebar.
This fixes by removing the width constraint.
> fix(ux): Extension list should expand to fit sidebar

- src/reason-textmate/Grammar.re
- src/reason-textmate/Theme.re
__Issue:__ In testing themes downloaded from open-vsx.org, some were crashing the editor on load.
__Defect:__ There was some code that was using `Option.get`, assuming that the file load would always be successful. Apparently - this isn't always the case.
__Fix:__ The code was very strange - it used `let%bind` for a monadic result, but didn't bother transforming from the option monad to the result monad... This transforms the `Option` to a `Result` monad, and flatMaps to return the final result.
> fix(theme): Crash when XML not found

- bench.esy.lock/index.json
- docs/docs/configuration/settings.md
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Core/dune
- src/Service/Font/Service_Font.re
- src/Service/Font/Service_Font.rei
- test.esy.lock/index.json
- test/Core/ConfigurationParserTests.re
This fixes our current `editor.fontLigatures` flag to be able to take in a string of features, similar to what VSCode has.
I.e. `"editor.fontLigatures": "'ss02'"` enables the second stylistic set.
This is achieved through a custom parser using Angstrom. 
Fixes #1294
> feat(font): stylistic sets & other OpenType features

- src/Model/Actions.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
As of right now, we only support dropping _files_ onto the editor. This adds the behavior that if you drop a folder/directory onto the editor, it will change the directory in the same way that `:cd x/y/z` changes the directory.
> feat(editor): folder drag and drop

- .ci/esy-check-hygiene.yml
- docs/website/sidebars.json
A trailing comma was causing the docs to fail to build (and blocking nightly builds) - this adds a CI check for the documentation to prevent it from happening in the future, and fixes the issue.
> docs: fix trailing comma

- integration_test/lib/SyntaxServerTest.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/GrammarInfo.re
- src/Exthost/GrammarInfo.rei
- src/Exthost/LanguageInfo.re
- src/Exthost/LanguageInfo.rei
- src/Feature/Syntax/Feature_Syntax.re
- src/Feature/Syntax/Feature_Syntax.rei
- src/Service/Syntax/Service_Syntax.re
- src/Service/Syntax/Service_Syntax.rei
- src/Store/StoreThread.re
- src/Syntax/GrammarRepository.re
- src/Syntax/GrammarRepository.rei
- src/Syntax/Protocol.re
- src/Syntax_Client/Oni_Syntax_Client.re
- src/Syntax_Client/Oni_Syntax_Client.rei
- src/Syntax_Server/Oni_Syntax_Server.re
- src/Syntax_Server/State.re
- src/Syntax_Server/State.rei
- src/Syntax_Server/TreesitterRepository.re
- src/Syntax_Server/TreesitterRepository.rei
- src/bin_editor/HealthCheck.re
This refactoring is intended to help un-block https://github.com/onivim/oni2/pull/2119
That PR is failing with an error: `Invalid_argument "output_value: abstract value (Custom)"` - which is happening when we try to send the `LanguageInfo` over to the syntax-server via the `Marshal` module. The root cause is that we are trying to serialize `OnigRegExp` objects, which are really C pointers with no custom serialization/deserialization - and we get this error when trying to send them via marshal.
However, we really only need to find grammar paths in the syntax server - we don't need all of the extra language information and configuration. This PR splits up language info into a grammar info that is a subset, and is just focused on locating grammars.
Apart from all the plumbing (changing …
> refactor(exthost): Split LanguageInfo / GrammarInfo 

- src/Feature/Editor/Draw.re
This was my mistake when I pulled out the drawing of the tab icon from the deprecated Skia API in #2113. The tab icon was appearing as a check mark -- now it appears correctly.
> fix(editor): set UTF-8 encoding for tabPaint

- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/UI/EditorView.re
__Issue:__ With smooth scroll on, when switching between editors at different scrolls, the editor would 'smooth scroll' to the new position. This is actually a bit jarring when switching files.
__Defect:__ The component instance was 'common' between the editors - the reconciler didn't know it needed to be changed, and that it should reset animations. 
__Fix:__ This creates a per-editor `Brisk_reconciler.Key.t` - like the key property in React - to ensure that each editor gets mounted / unmounted when changing, which fixes the scroll issue because there is no previous state.
> fix(editor): Fix 'smooth scroll' when switching between editors

- src/Exthost/Msg.re
__Issue:__ The java extension was sending a `float` as the status bar priority, which we we weren't handling.
__Fix:__ Update our decoder to parse the float and coerce to an int. May have to revisit to see if a `float` would be more appropriate (from JS - there is just the `number` type).
> fix(exthost): Status Bar - handle float priority

- src/Core/ConfigurationTransformer.re
- src/Exthost/Configuration.re
- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Msg.re
- src/Store/ExtensionClient.re
__Issue:__ Several extensions - like Java, clangd, etc - offer to persist various options, like `clangd.path`, or `  "java.configuration.checkProjectSettingsExclusions": false`. They do this via the `updateConfigurationOption`/`removeConfigurationOption` API.
__Defect:__ We weren't handling these requests, or persisting them in the user configuration.
__Fix:__ We already have the machinery to tweak the user configuration (we do this for setting themes, for example), but we we weren't handling these requests.
> feat(exthost): Implement $updateConfigurationOption/$removeConfigurationOption

- extensions/reason-vscode/package.json
- src/Store/Features.re
This shows the formatter display name after a successful format operation:
> Formatting: Show formatting display name on success

- src/Exthost/Command.re
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Exthost/SCM.re
- src/Feature/SCM/Feature_SCM.re
- src/Feature/SCM/Feature_SCM.rei
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/StatusBar/dune
- src/UI/Root.re
- test/Exthost/LanguageFeaturesTest.re
__Issue:__ The SCM provider from the exthost was sending status bar commands, but we weren't showing them - it's helpful context, like the current branch and current state of the repro:
__Fix:__ Wire up the status bar commands from the SCM provider, show in status bar
> feat(scm): Wire up status-bar commands

- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Msg.re
- src/Store/ExtensionClient.re
This hooks up the `$tryOpenDocument` API, which is helpful for picking up the language server logs.
> feat(exthost): Implement MainThreadDocuments API

- src/Core/BufferLine.re
- src/Core/BufferLine.rei
- src/Feature/Editor/ContentView.re
- src/Feature/Editor/Editor.re
This fixes a small bug in the `getIndexFromPixel` case (formerly `getByteFromPixel`) - in the traversal, we were mixing byte indices with character indices. Yet another case where having this enforced by the type system would help!
Specifically, we would call `getIndex(~byte)` on byte positions, which would return a character index, and then pass that into `loop` - so `loop` now is operating on character indices, but we'd pass those again into `getIndex(~byte)`, which would return unpredictable results - and give us an artificially low result, because if we're assuming the index is a byte position, for multi-byte characters, that would put us earlier in the string.
This fixes the codepath by operating only on indices - the downside is we can't rely on `lengthInBytes` anymore, so we have …
> Normalize byte / index conversion

- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/InitData.re
- src/Exthost/Extension/Scanner.re
- src/Store/ExtensionClient.re
- test/Exthost/Test.re
__Issue:__ The `rust-analyzer` extension would fail when trying to determine where to get the `rust-analyzer` language server.
__Defect:__ The rust extension uses the `releaseTag` in the `package.json` to decide where to find the server (ie, `nightly` vs a tagged branch). First, we were not passing this value at all, and second, the publish script to release `rust-analyzer` on open-vsx is not properly populating this value (https://github.com/open-vsx/publish-extensions/issues/106)
__Fix:__ The not-passing-the-value is a class of issues we had - we were not passing through anything that we did not parse, although extensions expect to have the full package.json available (this was also an issue with the C# extension - fixed in #2184 ). Instead of just trying to add these one-by-one, this …
> fix(extensions): Unblock rust-analyzer extension

- src/Feature/Extensions/ItemView.re
- src/Feature/Extensions/ListView.re
- src/Feature/Extensions/Model.re
Since we do not currently implement the 'delta' API for adding / remove extensions in the extension host (and picking up new languages / configurations) - the editor needs to be restarted after picking up new extensions.
This just adds a small notification to notify that a restart is required.
> fix(extensions): Add 'restart required' notification after installation

- src/Feature/LanguageSupport/Completion.re
__Issue:__ As described in #2234 - the fuzzy matching strategy was ignoring a complete match.
__Defect:__ Off-by-one case in our filtering logic - we should still show the complete match, so that the details / documentation are visible. Regression from #2202 
__Fix:__ Fix filter logic
Fixes #2234
> fix(completion/#2234): Show direct match

- src/Feature/Extensions/DetailsView.re
- src/Feature/Extensions/Model.re
- src/Service/Extensions/Catalog.re
- src/Service/Extensions/Service_Extensions.rei
__Issue:__  The scala metal extension fails to install
__Defect:__ Some extensions don't have a README defined - like https://open-vsx.org/extension/scalameta/metals We assume there is a readme field, and our parsing fails if there is not one.
__Fix:__ Make readmeUrl an optional field
__Related:__ #2243
> fix(extensions): Readme field should be optional

- src/Core/Utility/OptionEx.re
- src/Store/Persistence.re
- src/bin_editor/Oni2_editor.re
__Issue:__ When minimizing the window, on windows, we persist some extreme negative values (`-32000`) for `x` and `y`, causing the window to be shown offscreen.
__Fix:__ This is band-aid / hack for 0.5.0 - but we sanitize values past a certain threshold (-2000) and adjust them to be centered. 
A more complete fix would:
- Not persist `x`/`y` when Revery window is minimized (need to hook up the `isMinimized` API)
- Check the bounds of the current displays, such that we can have more complete validation, instead of an arbitrary constant.
Fixes #2229
> fix(persistence/#2229): Bad window position on restore

- package.json
- scripts/generate-mit-readme.js
The license field should point to the EULA: https://github.com/onivim/oni2/blob/master/Outrun-Labs-EULA-v1.1.md
Also updated the MIT-relicense script so that the field gets properly set back to `MIT` when relicensing commits here: https://github.com/onivim/oni2-mit
Fixes #2260 - thanks @SqrtMinusOne for catching this!
> fix(metadata/#2260): License field in package

- docs/docs/using-onivim/language-features.md
It was previously `gd` (the mapping for go-to-definition)
> docs: fix hover keybinding

- scripts/release.js
__Issue:__ When running Onivim 2 on a dual-GPU Mac, Onivim would only use the discrete GPU (which is more expensive for battle life).
__Defect:__ By default, when creating an OpenGL context, OSX prefers the discrete GPU. The [`NSSupportsAutomaticGraphicsSwitching`](https://developer.apple.com/documentation/bundleresources/information_property_list/nssupportsautomaticgraphicsswitching) attribute is necessary to allow use of the integrated GPU.
__Fix:__ Add `NSSupportsAutomaticGraphicsSwitching: true` to our `Info.plist`
Fixes #2090
> fix(osx/#2090): Prefer integrated to discrete GPU

- src/Store/ExtensionClientStoreConnector.re
__Issue:__ When saving in a folder that has multiple git repos, or when saving a file from a repo other than the active one, a menu will pop up asking to clarify the repo.
__Defect:__ After save, we send the `git.refresh` command to get an up-to-date view of the source control.  The git source control extension would try and infer what repository to refresh: https://github.com/onivim/vscode-exthost/blob/c7df89c1cf0087ca5decaf8f6d4c0fd0257a8b7a/extensions/git/src/commands.ts#L2399 - this would be fine if there was only one repository. However, if there were multiple, the extension would open a pop-up to disambiguate.
__Fix:__ The command takes a 'hint' URL to specify which repository - having the file path is an acceptable hint, so sending the filepath along with `git.refresh` does not …
> fix(scm/#2226): Command submodules showing on save

- src/Feature/LanguageSupport/Completion.re
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/GlobalColors.re
Hooks up the `symbolIcon.*` theme colors to the completion view
> fix(ux): SymbolIcon theme colors

- bench.esy.lock/index.json
- bench.esy.lock/opam/lwt_ppx.2.0.1/opam
- bench.esy.lock/opam/ppx_deriving.4.5/opam
- bench.esy.lock/opam/ppx_tools_versioned.5.4.0/opam
- bench.esy.lock/opam/ppxfind.1.4/opam
- bench.esy.lock/opam/ppxlib.0.13.0/opam
- bench.esy.lock/opam/reason.3.6.0/opam
- esy.lock/index.json
- esy.lock/opam/lwt_ppx.2.0.1/opam
- esy.lock/opam/ppx_deriving.4.5/opam
- esy.lock/opam/ppx_tools_versioned.5.4.0/opam
- esy.lock/opam/ppxfind.1.4/opam
- esy.lock/opam/ppxlib.0.13.0/opam
- esy.lock/opam/reason.3.6.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/lwt_ppx.2.0.1/opam
- integrationtest.esy.lock/opam/ppx_deriving.4.5/opam
- integrationtest.esy.lock/opam/ppx_tools_versioned.5.4.0/opam
- integrationtest.esy.lock/opam/ppxfind.1.4/opam
- integrationtest.esy.lock/opam/ppxlib.0.13.0/opam
- integrationtest.esy.lock/opam/reason.3.6.0/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/lwt_ppx.2.0.1/opam
- test.esy.lock/opam/ppx_deriving.4.5/opam
- test.esy.lock/opam/ppx_tools_versioned.5.4.0/opam
- test.esy.lock/opam/ppxfind.1.4/opam
- test.esy.lock/opam/ppxlib.0.13.0/opam
- test.esy.lock/opam/reason.3.6.0/opam
__Issue:__ The `master` (nightly) builds were failing, with this error:
```
error: build failed with exit code: 1
build log:
Install: /cygdrive/c/Users/VssAdministrator/.esy/3______________________________________________________/s/revery__s__esy_harfbuzz-2.6.8000-2c0b225d
error: command failed: "bash" "-c" "./esy/configure-windows.sh" (exited with 127)
esy-build-package: exiting with errors above...
building @revery/esy-harfbuzz@2.6.8000
esy: exiting due to errors above
```
__Defect:__ There's an issue with the latest `cmake` install on Windows - it's no longer installing correctly in a way that provides the `cmake` executable.
__Fix:__ `cmake` was removed as a dependency for harfbuzz and replaced with a `./configure` script: https://github.com/revery-ui/esy-harfbuzz/commit/380833bb511ace …
> fix(ci): Harfbuzz build failure on master/nightly

- src/Core/ConfigurationDefaults.re
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Feature/SideBar/Feature_SideBar.re
- src/Feature/SideBar/Feature_SideBar.rei
- src/Store/SideBarReducer.re
- src/UI/Dock.re
- src/UI/Root.re
- src/UI/SideBarView.re
This PR adds a configuration setting allowing the user to put the sidebar on the right side. This is accomplished by creating a list of the "surface" components, and reversing their order if the setting is set to `right`. The default CSS lays out the components correctly.
> feat(workbench) adds configurable sidebar position

- src/UI/EditorView.re
Makes things more consistent and simple by passing the buffer to the `Editor` component instead of finding it again.
> refactor(editor): pass buffer to Editor component

- src/Syntax/TextmateTokenizerJob.re
- src/reason-textmate/ThemeScopes.re
- src/reason-textmate/TokenTheme.re
- test/reason-textmate/TokenThemeTests.re
__Issue:__ Our scope-selection strategy was not correct in some cases - particularly, the precedence in which we would apply the scopes.
For example, in #1933 - with the dracula theme - there'd be a case where a token would have the following textmate scopes:
- `support.function.console.js`
- `meta.function-call.js`
- `source.js`
For the dracula theme, there is a `source` selector that is intended to be a fallback - however, it was taking precedence over some of the other theme selectors that should've been applied, like `meta.function-call`.
This would cause the entire source file to be highlighted with the `source` scope selector, instead of the more specific ones.
__Defect:__ We apply selectors in reverse order (first, we apply any selectors matching `source.js`, and then …
> fix(theme/#1933): Scope matching precedence

- docs/docs/configuration/settings.md
As the commit says, this PR updates some of the docs regarding `workbench` settings. It adds missing ones and removes one extraneous closing parentheses.
> docs(settings) adds missing workbench config settings

- src/Components/KeyDisplayer.re
- src/Feature/InputText/Model.re
- src/Feature/InputText/Selection.re
- src/Feature/InputText/View.re
Updates input component to handle Unicode characters properly
> fix(i18n): handle unicode characters properly in Input

- src/CLI/Oni_CLI.re
- src/CLI/Oni_CLI.rei
- src/bin_editor/Oni2_editor.re
- src/bin_launcher/Oni2.re
By default, Onivim will try to find the best renderer (either software or hardware, preferring hardware) - but this adds a CLI flag that overrides this behavior.
For example, with the default settings, my integrated GPU gets picked up:
But if I run with `esy run -f --gpu-acceleration=software`, Onivim will pick up the Apple OpenGL software renderer:
This is a step towards #1558, but for software rendering to be useful, we need to improve & streamline our rendering strategy.
> feat(cli): Add option to override default renderer selection

- src/Store/KeyBindingsStoreConnector.re
__Issue:__ We have several key-bindings that are intended to be specific to MacOS (ie, `Cmd+W`), but these are active on Windows and Linux as well. This causes unintuitive behavior and collisions with other tools that expect these keys to not have application-specific functionality.
__Defect:__ The `isMac` condition key wasn't used for mac-specific bindings
__Fix:__ Add `isMac` condition to MacOS specific bindings
Fixes #2316
> fix(input/#2316): Command+* bindings are active on Windows/Linux platforms

- src/Syntax/GrammarRepository.re
- src/reason-textmate/Grammar.re
- src/reason-textmate/SimpleXml.re
- src/reason-textmate/Theme.re
This fixes an issue in #2307 - when there is a non-existent grammar, we could crash.
There were two places that were potentially throwing an exception - a call to `Yojson.Safe.from_file` and `SimpleXml.of_file` - these both return a `result` and an `option`, respectively, and it'd be expected that errors might be encapsulated in those - but both functions turn out not to be total and have scenarios that can throw.
This replaces `Yojson.Safe.from_file` in this path with `JsonEx.from_file`, which is total, and changes `SimpleXml.of_file` to return a `result` that is total.
Related #2307
> fix(textmate/#2307): Crash when trying to load non-existent grammar

- src/reason-libvim/BufferInternal.re
Fixes #2331.
I think this is the cause of #2331, as I can't repro it on mac and Windows I believe this can cause a crash as a terminal isn't allocated when launched normally, which would explain why it is fine with `-f` on Windows.
> fix(crash/#2331): Remove debug prints

- src/Exthost/CompletionContext.re
- src/Exthost/Exthost.rei
- src/Feature/LanguageSupport/Completion.re
__Issue:__ When manually invoking completion (via `Control+Space` or `Control+N`), a completion session would not always be initiated, as described in #2300 
__Defect:__ When completion was manually invoked, we would look for a completion meet based on trigger characters to start the session. 
__Fix:__ There won't always be a completion meet available when manually invoking - in the manual-invoke case, we'll use the cursor position as the meet position, and send appropriate context (triggerKind) to the extension host in this case.
> fix(completion/#2300): Manual invoke not working as expected

- .ci/esy-check-hygiene.yml
- package.json
- scripts/lint.sh
- src/Core/NodeTask.re
Related to #2333 - this is a quick-and-dirty lint script to help verify inadvert `print_endline`, `prerr_endline`, etc are not introduced accidentally in commits.
Was looking for a more robust, full-fledged lint tool for OCaml / ReasonML - but couldn't find anything. Would be a really nice addition! Hopefully at some point we can replace this tool with a real linter.
> fix(ci): Simple lint check

- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/View.re
- src/UI/EditorView.re
This adds a tooltip to show the fullpath of items in the editor tabs:
Fixes #2335
> fix(editor/#2335): Add tooltip for path

- src/Feature/Editor/EditorConfiguration.re
__Issue:__ Warnings were shown in the logs about no default for `editor.lineHeight`, ie: 
```
[30m[43m[WARN] [0;30m[0m    +0ms [90mOni2.Core.Config[0m : Missing default value for `editor.lineHeight`
```
__Defect:__ The`lineHeight` configuration spec wasn't included in the editor contributions, so the default was never registered
__Fix:__ Add to contributions
> fix(editor): Default not set for lineheight configuration

- integration_test/Regression2349EnewTest.re
- integration_test/dune
- src/Core/Utility/Path.re
- src/Exthost/LanguageInfo.re
__Issue:__ `:enew` would crash the editor
__Defect:__ We were crashing when trying to infer the language type from the filename - in this code: https://github.com/onivim/oni2/blob/d3b6eb51c168474079c3a4f3bd8142bc62667cd2/src/Exthost/LanguageInfo.re#L136
The `Rench.Path.filename` (which uses `Fpath` under the hood) - is not robust against an empty filename.
__Fix:__ Don't crash in that case - if it's an empty file name, just use the default ("plaintext") filetype. Add a regression test so we can ensure this doesn't break again in the future.
Longer term, I'd like to look at moving towards a strongly-typed solution for file path / name management - would like to integrate: https://github.com/facebookexperimental/reason-native/tree/master/src/fp
Fixes #2349
> fix(vim/#2349): Crash on :enew

- bench.esy.lock/index.json
- bench.esy.lock/opam/charInfo_width.1.1.0/opam
- esy.lock/index.json
- esy.lock/opam/charInfo_width.1.1.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/charInfo_width.1.1.0/opam
- package.json
- src/Core/Mode.re
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/Theme/GlobalColors.re
- src/Model/ModeManager.re
- src/reason-libvim/Mode.re
- src/reason-libvim/Native.re
- src/reason-libvim/Operator.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test.esy.lock/opam/charInfo_width.1.1.0/opam
- test/reason-libvim/ModeTest.re
__Issue:__ As described in #2357 , we weren't showing any context around a pending operator in the status bar - this is really a step backward.
__Fix:__ This picks up https://github.com/onivim/libvim/pull/218 so that we get some context around the current pending operator, and we show it in now in the statusbar:
This fixes the operator-pending part of #2357 - we're missing showing the in-progress count of a command, though.
> fix(vim/#2357): Part 1 - Show pending operator in status bar

- src/Exthost/Exthost.rei
- src/Exthost/Files.re
- src/Exthost/Request.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/ExtensionClient.re
- src/Store/ExtensionClientStoreConnector.re
__Issue:__ When saving a file in a non-git repo, we get an annoying dialog popping up.
__Defect:__ When we save, we send a `git.refresh` command - this was a hack in #1282 to get the git provider to refresh. This wasn't ideal before, because it doesn't work for other providers, and it strong arms the git extension (the git extension actually waits to refresh until is idle, which this avoids) - but it's even worse now that we have the dialog boxes more fully hooked up. Previously, we'd ignore this dialog, but now it is getting in the way on save.
__Fix:__ Instead of strong-arming a `git.refresh` command - the provider is actually set up to listen to file system events. This change sends a modified event on save, which hits the expected codepath on the git SCM provider to update …
> fix(scm/#2358): Dialog popping up on save in non-git repos

- src/Feature/Editor/EditorConfiguration.re
__Issue:__ Running `:set nonumber` when `editor.lineNumbers` is set to `relative` or `on` would not turn off line numbers. The Vim setting should take precedence.
__Defect:__ We were treating the 'off' state the same as a not-set state.
__Fix:__ Handle `off`/`no` differently than not set.
> fix(vim/#888): Fix case where number is explicitly turned off

- src/Core/BufferLine.re
- src/Feature/LanguageSupport/Hover.re
Tiny change to stop these tiny empty hover elements:
I also changed the debugging output in BufferLine since it really heavily hits the logs, and moved it behind `trace`  so you need to do `--trace` rather than `--debug`. On my Mac it can actually slow down the rendering and scrolling as well (MacBook Air with Kitty terminal), but also because it can pollute the user logs making it harder to find the real issue.
> fix(completion): don't show empty hover windows.

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Feature/Extensions/Feature_Extensions.re
- src/Feature/Extensions/Feature_Extensions.rei
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/Feature_Theme.rei
- src/Model/VimContext.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/ColorScheme.re
- src/reason-libvim/CommandLine.re
- src/reason-libvim/Context.re
- src/reason-libvim/Effect.re
- src/reason-libvim/GlobalState.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/ColorSchemeTest.re
- test/reason-libvim/CommandLineTest.re
This plumbs through the colorscheme command & completion (via https://github.com/onivim/libvim/pulls).
It provides a `colorSchemeProvider` so that libvim can know about our available colorschemes, and provides the following functionality:
- Onivim themes can be set via `:colorscheme <theme-name>`
- `:colorscheme` by itself opens up the theme picker
> feat(vim): Colorscheme ex command synchronization

- docs/docs/configuration/settings.md
- src/Feature/Editor/CursorView.re
- src/Feature/Editor/Draw.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorConfiguration.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/GutterView.re
- src/Feature/Editor/IndentLineRenderer.re
- src/Feature/Editor/Minimap.re
- src/Feature/Editor/OverlaysView.re
- src/Feature/Editor/SurfaceView.re
- src/Feature/Editor/YankHighlights.re
- src/Feature/SignatureHelp/Feature_SignatureHelp.re
- src/Model/Actions.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
- src/editor-core-types/PixelPosition.re
- src/editor-core-types/PixelPosition.rei
- src/editor-core-types/PixelRange.re
- src/editor-core-types/PixelRange.rei
This implements a visualization when yanking text (a revamp of #986, using our new editor pixel conversion APIs on the editor surface):
__TODO:__
> feat(ux): Yank highlights

- src/Feature/Editor/EditorConfiguration.re
__Issue:__ When using `:set rnu`, the current line number doesn't show - this is a bit misleading, given that our default is to show absolute line numbers.
__Fix:__ Change the default when _only_ `:set rnu` is used to show the absolute line number for the current line. This can be disabled by additional running `:set nonumber` if desired.
> fix(vim): Fix ':set rnu' default

- src/Core/Uri.re
- src/Core/Utility/Path.re
- src/Core/Utility/ResultEx.re
- src/Exthost/Msg.re
- test/Core/UriTests.re
- test/Exthost/Test.re
- test/Exthost/lib/Node.re
- test/Exthost/lib/ResultEx.re
__Issue:__ The `matklad.rust-analyzer` extension wasn't working on Windows... an error dialog would come up after every request, making the extension unusable.
__Defect:__ Our logic for serializing URLs wasn't correct. VSCode normalizes back-slashes to forward slashes, and we weren't doing that: https://github.com/onivim/vscode-exthost/blob/c7df89c1cf0087ca5decaf8f6d4c0fd0257a8b7a/src/vs/base/common/uri.ts#L306
This meant, for a path like `D:\hello-rust\src\main.rs` we were sending a URL like this:
```file:///d%3A%5Chello-rust%5Csrc%5Cmain.rs```
When we should be sending one like this:
```file:///d%3A/hello-rust/src/main.rs```
__Fix:__ Add backslash normalization.
There was also an issue where the status bar `$setEntry` API wasn't being deserialized properly - we were expecting `priority` …
> fix(exthost/#2282): Fix URI serialization on Windows

- extensions/xml/cgmanifest.json
- extensions/xml/package.json
- extensions/xml/package.nls.json
- extensions/xml/syntaxes/xml.tmLanguage.json
- extensions/xml/syntaxes/xsl.tmLanguage.json
- extensions/xml/xml.language-configuration.json
- extensions/xml/xsl.language-configuration.json
We've had several requests for XML syntax highlighting. We still need a good automated way to pull extensions from VSCode - but in the meantime, I'll bring over the XML extension.
With this extension, XML syntax highlighting is available out of box:
Fixes #2332
> feat(extensions/#2332): Add XML extension

- src/Feature/Pane/Feature_Pane.re
- src/Feature/Pane/Feature_Pane.rei
- src/Model/GlobalCommands.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/StoreThread.re
__Issue:__ The toggle-problems-pane command (bound to Control+Shift+M/Command+Shift+M) wasn't working. The command and key-binding had no effect.
__Defect:__ The 'workbench.actions.view.problems' command wasn't actually wired up to our action.
__Fix:__ 
- Move the 'workbench.actions.view.problems' to a contributed command from the Pane feature
- Move the Control+Shift+M / Command+Shift+M bindings to contributed keybindings from the Pane feature
- Wire up the logic for showing / hiding the problems pane.
Fixes #2408 - still need to wire up vim-style navigation to it, though (in the spirit for #528)
> fix(pane/#2408): Toggle Problems Pane not working

- integration_test/ExCommandKeybindingTest.re
- integration_test/ExCommandKeybindingWithArgsTest.re
- integration_test/dune
- src/Store/KeyBindingsStoreConnector.re
A simple change that allows keybindings to invoke ex commands directly, and could address quite a few of the requests in #1423. The downside of doing this instead of implementing proper commands is of course that they won't be discoverable through the command palette, but this doesn't prevent proper commands to be added either, so I think it might be a nice convenient stop-gap solution to unblock people at least.
Example:
```
{key: "kk", command: ":split", when: "editorTextFocus"}
```
Let me know if you think this is a viable approach @bryphe, then I'll add a few integration tests before it's merged.
Fixes #807
> feat(keybindings): execute keybinding starting with : as ex command

- node/package.json
- node/yarn.lock
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Exthost/Request.re
- src/Exthost/SuggestItem.re
- src/Feature/LanguageSupport/Completion.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/ExtensionClient.re
This picks up the vscode-exthost@1.46.0, and implements several API changes:
- Additional argument for StatusBar `$setEntry` 
- Streamlined `$resolveCompletionItem` API
- Optional `CompletionKind` for suggestitems
> refactor(dependency): vscode-exthost -> 1.46.0

- node/package.json
- node/yarn.lock
- test/Exthost/TerminalServiceTest.re
Upgrade to vscode-exthost -> 1.47.1. Needs an update to the test case, as our 'noop-process' test behaves differently with the new terminal service handling logic.
> refactor(dependency): vscode-exthost -> 1.47.1

- docs/docs/configuration/key-bindings.md
Fixes a typo in the documentation
> docs(typo): change editorFocus to editorTextFocus

- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/dune
- src/Service/OS/Service_OS.re
- src/Service/OS/Service_OS.rei
- src/Store/FileExplorerStore.re
More groundwork on the path to #528 - this is some refactoring to support changing the initial load population strategy for the file explorer, which is blocking moving the explorer to its own self-contained feature.
In addition, this moves the file population story to use libuv - and importantly, not block on File I/O. Previously, we were using `Lwt.main_run` to block and populate the directory info synchronously (in addition, we were also traversing a single layer deep inside each folder, which isn't necessary for the initial population). This is actually one bottleneck on Windows start time, at least on my machine (related to #523 ). Removing this blocking is also important for moving to subscriptions, so that we can have predictable performance and running the subscription can be …
> refactor(explorer): Use luv for populating file explorer

- src/Components/InputText/Model.re
**Issue:** The InputText component does not handle ctrl + backspace correctly.
**Defect:** The key combination has no handler setup.
**Fix:** Added handlers for `<C-BS>`. Without a selection, it removes the preceding word. When there is a selection it behaves as if just `<BS>` was pressed and removes the selection.
PS. Went through the contribution guidelines and hopefully got it mostly right here. Comments/improvements welcome! :)
> fix #2281: ctrl + backspace handling in text inputs

- src/Feature/TitleBar/Feature_TitleBar.re
__Issue:__ If initiating a drag on Windows by clicking on the title bar icon or title bar text, nothing would happen. Clicking empty space would work as expected, though.
__Defect:__ The icon / text elements were stealing the mouse event.
__Fix:__ Use ```pointerEvents(`ignore)``` to prevent the mouse event from being blocked.
Fixes #2449
> fix(ux/#2449): Windows - Title bar not draggable from icon / text

- scripts/release.js
__Issue:__ As described in #2445 - the windows executables aren't getting proper app icons.
__Defect:__ We use a tool called [`rcedit`](..) to handle embedding icons in our executables.
However, on our private packaging pipeline, we're getting this error:
```
(node:8744) UnhandledPromiseRejectionWarning: Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
at ChildProcess.<anonymous> (C:\Users\VssAdministrator\.esy\source\i\rcedit__2.0.0__0ca922f4\lib\rcedit.js:69:16)
at ChildProcess.emit (events.js:210:5)
at maybeClose (internal/child_process.js:1021:16)
at Socket.<anonymous> (internal/child_process.js:430:11)
at Socket.emit (events.js:210:5)
at Pipe.<anonymous> (net.js:658:12)
```
Luckily, it also reproduced on my Windows machine. It turns out the …
> fix(windows/#2445): Packaging - Windows executables not getting proper icon

- src/Core/Filter.re
- src/Core/Filter.rei
- src/Exthost/Exthost.rei
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionItem.re
- src/Feature/LanguageSupport/CompletionItemSorter.re
__Issue:__ When `sortText` is not provided, the completion ordering could be un-intuitive.
For example:
In this case, the expectation would be that `toString` is prioritized.
__Defect:__ When `sortText` is not available, we fall back to `label` alphabetical sort.
__Fix:__ In the short-term, we can consider the length as well - with fuzzy matching, shorter matches have a higher percent match, so it's more intuitive and useful:
The fuzzy-finding work in #1566 will also accomodate this, so once that's in, we can use the fuzzy-filter score as the fall.
In addition, add test cases, so that we can catalog, document, and continue to improve the sorting behavior.
> fix(completion): Improve sorting behavior

- docs/website/siteConfig.js
I really like @eleijonmarck 's idea in #2473 / #2480 to have an Edit button - this just implements it in a slightly different way - apparently Docusaurus has an `editUrl` property: https://docusaurus.io/docs/en/site-config#editurl-string
When populated, you get a nice `Edit` button at the top of the page:
> docs: Add 'Edit' button on all pages

- docs/docs/getting-started/vim-tips.md
- docs/docs/getting-started/vscode-tips.md
- docs/website/sidebars.json
This adds two new pages in the "Getting Started" with tips for vim and vscode users. Kind of a FAQ but targeted towards specific user groups. I also think these will make it easier to contribute documentation as the format lends itself well to adding self-contained tips.
> docs: tips for users coming from vim and vscode

- docs/docs/getting-started/vim-tips.md
- docs/docs/getting-started/vscode-tips.md
Fixes for #2475. I didn't realize the titles had to be in a special preface format. Also fixes a few typos found in a second reading.
> docs: fix titles and typos on tips pages

- src/Model/ContextKeys.re
__Issue:__ Various keybindings for triggering and interacting with command-line completion (control+n, tab, arrows) were not working as expected.
__Defect:__ The quick menu context keys, to engage the appropriate key bindings, were not enabled when the command line was open.
__Fix:__ Hook up the command-line context keys.
Fixes #2477 
Fixes #2485 
Longer-term - we should pivot the 'Quickmenu' model, such that it doesn't need to be aware of every menu. We could instead make the menu component stand-alone (like input/vimlist/vimtree), and supply context keys. This would make implementing a more dynamic menu, like one with more details in the completion info, doable.
> fix(command-line/#2477): Fix completion keybindings in ':' command line

- docs/docs/for-developers/building.md
Just updates the release step, since the release is now in its own sandbox, you need to run Oni2 in that sandbox once for the binary to exist, to be copied for the release.
Arguably, the scripts should be a little smarter about this (i.e. check, error, say "Run `esy ....`).
> docs: fix release steps

- src/Components/VimList/Component_VimList.re
- src/Components/VimList/Component_VimList.rei
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Core/Tree.re
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Explorer/Feature_Explorer.rei
- src/Feature/Explorer/FileTreeView.re
- src/Feature/Explorer/FsTreeNode.re
- src/Feature/Explorer/FsTreeNode.rei
- src/Feature/Explorer/Model.re
- src/Feature/Explorer/View.re
- src/Feature/Explorer/dune
- src/Feature/Pane/DiagnosticsPaneView.re
- src/Feature/Search/Feature_Search.re
- src/Feature/Theme/GlobalColors.re
- src/Model/CommandManager.re
- src/Model/ContextKeys.re
- src/UI/SideBarView.re
This brings in the the vim-navigable-tree introduced in #2492 , and wires it up to the file explorer:
This supports some initial vim-style navigation, like j/k/zz/zb/zt. 
There are a few additional gestures I'd like to support, to be able to resolve (soon) #528 :
- Implement a search (hook up `/`, `?`, `n`, `N`) experience
- Implement cut/copy/paste (`yy`, `dd`, `pp`).
> fix(explorer/#528): #528 - Part 1 - Initial vim navigation for Explorer

- src/Components/FileIcon.re
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Explorer/Feature_Explorer.rei
- src/Feature/Explorer/FileTreeView.re
- src/Feature/Explorer/FsTreeNode.re
- src/Feature/Explorer/FsTreeNode.rei
- src/Feature/Explorer/Model.re
- src/Feature/Explorer/View.re
- src/Feature/SCM/Feature_SCM.re
- src/Feature/SCM/Feature_SCM.rei
- src/Store/Features.re
- src/Store/StoreThread.re
- src/UI/SideBarView.re
__Issue:__ After refactoring the file explorer population to be asynchronous, there was a regression, in that the initial explorer items don't have file icons:
__Defect:__ The `languageInfo` and `iconTheme` were not yet populated at the time the initial load came back.
__Fix:__ Defer the icon resolution to rendering, which will always be up-to-date. In addition, re-use the `<FileIcon />` component to show icons for SCM, too:
> fix(explorer): Initial population is not showing icons

- src/Components/VimList/Component_VimList.re
This adds several keybindings to the list/tree views for keyboard scrolling, as would be expected from a vim-navigable view:
- Control+E - scroll down a line
- Control+D - scroll down a window
- Shift+Down arrow - scroll down a window
- PageDown - scroll down a window
- Control+Y - scroll up a line
- Control+U - scroll up a window
- Shift+Up arrow - scroll up a window
- PageUp - scroll up a window
> feat(ux): Add keyboard scroll commands to list/trees

- src/Components/VimTree/Component_VimTree.re
__Issue:__ The active indent guide calculation is incorrect:
__Defect:__ There were two issues:
1) All indent levels were highlighted
2) Parent nodes at the same indentation level were not considered
__Fix:__ 
1) Only highlight active level
2) Consider nodes at the same or greater indentation level
> fix(ux): Indent guide incorrect in vimlist/vimtree

- src/Components/InputText/Model.re
This adds the Ctrl-U, Ctrl-K, Ctrl-C shortcuts from readline (bash) to InputText components (like the Find in Files search bar).
I also modified the previous implementation of removeWord (Ctrl-W / Ctrl-Backspace) to delete multiple spaces between words like the original readline implementation.
By the way, Ctrl-W no longer works in text boxes because it's used to switch between panes, so maybe it should be removed, or maybe make it so you need to press escape then Ctrl-W to be able to switch panes in a text box?
There are also some other issues with readline shortcuts in Ctrl-P and :command text boxes, I didn't find where to fix them. (the vim command text box is handled by libvim, I think?) See #2517
> feat(input): add some readline shortcuts in InputText

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/reason-libvim/Buffer.re
- src/reason-libvim/Native.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/BufferTest.re
This adds a `Vim.Buffer.loadFile` API - this reads and makes available a buffer without triggering side effects like buffer enter or bringing up a new editor.
> feat(api): Add loadFile buffer API

- src/Components/Accordion/Component_Accordion.re
- src/Feature/TitleBar/Feature_TitleBar.re
While investigating #2501 testing w/ long paths - there were cases where a long path name could overflow (and kick out the titlebar buttons).
This fixes a couple long-path overflow cases in the accordion and titlebar.
> fix(ux/windows): Long path / folder names can overflow

- src/Components/FileItemView.re
- src/Feature/Explorer/Feature_Explorer.re
__Issue:__ In some of the new UI - like the `<FileItemView />` used in search and diagnostics, and the symbol view - a `fontFamily` wasn't set, so this would fall back to a default system font in those new pieces of UI, which isn't desirable - which can either cause a mismatching font to show, or not display at all.
__Defect:__ Missed setting the `fontFamily` parameter on these new elements.
__Fix:__ Set the missing properties.
As a next step, it may make sense to have an `<OniText font />` component, that takes a `UiFont.t` as a required parameter, so it isn't missed elsewhere.
> fix(ux): Missing fontFamily setting on new <Text /> components

- src/Components/FileExplorer/Component_FileExplorer.rei
- src/Components/FileExplorer/FileTreeView.re
- src/Components/FileExplorer/View.re
- src/Feature/Explorer/Feature_Explorer.re
This wires up mouse-click behavior for the expansion/contraction of the file explorer and symbol outline in the sidebar.
> fix(explorer): Clicking accordion doesn't expand/contract sections

- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Pane/Feature_Pane.rei
__Issue:__ There were a couple problems with the bottom pane:
1) When opening, diagnostics is a more convenient default, but it defaults to opening notifications
2) Clicking the 'close' x in the corner doesn't have an effect when focused
3) Opening can be jarring
__Fix:__
1) Update the default selected pane. This way, when using `<C-w><C-j>` to open the bottom pane, diagnostics will be fixed. 
2) Fix the close behavior to release focus as well
3) Add a subtle animation on opening, and wire up a new config flag to disable it (`ui.animation`) - we can use this config flag to disable smooth scroll elsewhere, too.
> fix(ux): Fix several UX issues around the bottom-pane

- src/Core/IconTheme.re
- src/Core/Utility/Path.re
- src/Feature/Search/Feature_Search.re
- src/Feature/Search/Feature_Search.rei
- src/Store/Features.re
- src/UI/EditorView.re
__Issue:__ I've observed occassional crashes with the following exception:
```
(Invalid_argument "\"\": invalid path"):
```
__Defect:__ This appears to be coming from our `Rench.Path` utilities, which can throw - in particular, if there happens to be malformed or empty filenames coming from ripgrep.
__Fix:__ Remove usages of Rench, replace with the `Oni_Core.Utility.Path`, which are more robust and don't throw.
As a future step - I'd like to look at strongly typing our paths with [`Fp`](https://github.com/facebookexperimental/reason-native/tree/master/src/fp) and use those utilities.
> fix(crash): Remove usages of rench; replace with path utilities

- src/Feature/Clipboard/Feature_Clipboard.re
> fix(ux-windows/#2526): strip \r when pasting text with CTRL+V

- src/Components/VimList/Component_VimList.re
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Store/KeyBindingsStoreConnector.re
Fixes #2556 - adds `h` and `l` bindings to expand/collapse tree view nodes:
> fix(explorer/#2556): Implement h/l for tree view to expand & collapse

- src/Core/Tokenizer.re
- src/Feature/Editor/BufferLineColorizer.re
- src/Feature/Editor/BufferLineColorizer.rei
- test/Core/TokenizerTests.re
This makes a couple of tweaks to the `Tokenizer` and `BufferLineColorizer` API:
1) For the `Tokenizer`, store the pixel position of the token.
2) For the `BufferLineColorizer`, pivot the API such that we can reuse the same colorizer for different `startByte` values. Previously, we'd create a single `BufferLineColorizer.t` per view line (buffer line), but now, we want to reuse the same  colorizer, but apply it to different view lines. This can save us some computation to fast-forward the highlighter to the relevant byte.
Port of part of #1969 , related to #1444
> feat(editor/#1444): Part 3 - Update Tokenizer / BufferLineColorizer API

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
This picks up a couple of `libvim` fixes:
- https://github.com/onivim/libvim/pull/228
- https://github.com/onivim/libvim/pull/229
https://github.com/onivim/libvim/pull/228 was the root cause for the flakiness in cursor positioning after exiting insert mode  due to inconsistent setting of the `nomove` state variable in insert mode - so this fixes several related issues:
- Fixes https://github.com/onivim/oni2/issues/2566
- Fixes #2268 
- Fixes #1194
- Fixes #831
Possibly addresses #916 as well, but need to confirm.
> refactor(dependency): libvim -> 8.10869.61

- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionItem.re
- src/Feature/LanguageSupport/CompletionItemSorter.re
This adjusts the completion-item sorting to prefer fuzzy matches vs the extension-host-provided sort text.
Once fuzzy-matching is started, as more characters are typed, the `sortText` was still preferred over matches. This would lead to unintuitive results (like in #2235, the `forEachRange` was matched instead of `range` for the filter `ran`, because the `sortText` for `forEachRange` was `f`, whereas for `range` it was `r` - and that was used preferentially.
Fixes #2235 
The `fzy` integration in #1566 has the potential to improve this further.
> fix(completion/#2235): Prioritize fuzzy match over sort text

- src/Feature/Keywords/Feature_Keywords.re
- src/Feature/Keywords/Feature_Keywords.rei
- src/Feature/Keywords/dune
This is a revamp of #1227 - #1227 used the syntax service / syntax tokens to generate keywords, but this isn't 100% accurate (notably, tokens often will have the same highlight color as surrounding text).
Instead, this uses the `LanguageConfiguration.wordPattern` to determine word boundaries, and extract from a line or a buffer.
This implements the keyword extraction step - next item is to have the completion feature leverage this, and to ensure merging of completion items from different providers works (ie, if two providers provide the same token, we need a mechanism for merging and determining precedence).
> feat(completion): Part 1 - Add feature for keyword extraction

- src/Core/BufferLine.re
- src/Core/BufferLine.rei
- src/Feature/Editor/ContentView.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Helpers.re
- src/Feature/Editor/SurfaceView.re
Following from #2555 , #2559 , #2572  - this ports over an additional piece of functionality from #1969 for word wrapping.
This pivots the `Editor` API to provide a list of tokens via an `Editor.viewTokens` for a particular line. Before, we were picking up the entire buffer line, but in the case of word wrap, the entire buffer line isn't as useful - each view line only is concerned with the subset of the buffer line contained in the wrapped view.
> feat(editor/#1444): WordWrap - Part 4 - Editor viewTokens API

- docs/docs/configuration/settings.md
- src/Core/Utility/StringEx.re
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionConfig.re
- src/Feature/LanguageSupport/CompletionItem.re
- src/Feature/LanguageSupport/CompletionItemSorter.re
- src/Feature/LanguageSupport/CompletionMeet.re
- src/Feature/LanguageSupport/CompletionMeet.rei
- src/Feature/LanguageSupport/CompletionProvider.re
- src/Feature/LanguageSupport/CompletionProvider.rei
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/dune
- src/Store/Features.re
- test/Feature/LanguageSupport/CompletionMeetTests.re
Building off the work in #2575 - this implements a keyword completion provider:
- Abstract out completion strategies via the `CompletionProvider` signature
- Add `editor.wordBasedSuggestions` configuration for turning on/off keyword completion
- Coalesce duplicate completion items - prefer extension host items vs keyword completion, when the labels are the same
- Implement sorting - keyword items should be sorted latest
- 'Pin' the selected item when new items are coming in - otherwise, the filter order could change, and if the user completes while new items are popping in - there could be an incorrect insertion.
- Fix some issues with completion meets (not working for first character, not working inside parentheses)
Keyword completion can be disable with the following configuration:
``` …
```
> feat(completion): Initial keyword completion

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Model/VimContext.re
- src/reason-libvim/Context.re
- src/reason-libvim/GlobalState.re
- src/reason-libvim/ViewLineMotion.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/MotionTest.re
This implements handlers for `gj`, `gk`, `H`, `M`, L` - commands that are dependent on knowing about the current screen-space.
`libvim` doesn't know about the rendering metrics (ie, wrapping in #2578 ) - so this wires up handlers for those commands so that we can communicate where the destination cursor position should be for those commands, given our current editor state.
Needed for #2578
> refactor(vim): Screen-space motion

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Model/ModeManager.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/Mode.re
- src/reason-libvim/Native.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/Visual.re
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/ModeTest.re
- test/reason-libvim/MultiCursorTest.re
This change is the next step from #2584 - when the mode provided by the `Editor.t` is different from the 'real' Vim state - synchronize it. 
Brings in https://github.com/onivim/libvim/pull/231 so that we can change the visual / select easily as part of that synchronization.
> refactor(vim): Synchronize vim modes

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/Editor/Draw.re
- src/Feature/Terminal/Feature_Terminal.re
- src/Service/Terminal/Service_Terminal.re
- src/Service/Terminal/Service_Terminal.rei
- test.esy.lock/index.json
Part of the fix for this will be over in [`revery-terminal`](https://github.com/revery-ui/revery-terminal)
__TODO:__
Fixes #2374
> fix(terminal/#2374): Weird cursor jump when typing second character in terminal

- integration_test/KeySequenceJJTest.re
- src/Store/VimStoreConnector.re
__Issue:__ Keybindings that use `vim.esc`, like:
```
{ "key": "jk", "command": "vim.esc", when: "insertMode" },
```
were not working as expected - it'd look like the editor would be back in normal mode, but subsequent characters would be inserted again.
__Defect:__ This was a regression from https://github.com/onivim/oni2/pull/2593 - in the `vim.esc` case, we weren't telling the editor that the mode has switched to normal. The editor would still be in insert mode, which would be synchronized on a subsequent press.
__Fix:__ Keep the editor up-to-date when the mode changes. Update an integration test to cover this.
Thanks @CrossR for the initial investigation! Fixes #2601
> fix(input/#2601): vim.esc command not working as expected

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
__Issue:__ When opening a buffer for the first time, and running a command - the cursor is auto-centered. This is apparent (and jarring) when using a command like `G`.
__Fix:__ Pick up libvim fix: https://github.com/onivim/libvim/pull/232
> fix(editor): First command in new buffer auto-centers cursor

- docs/docs/using-onivim/integrated-terminal.md
- src/Feature/Terminal/Feature_Terminal.re
Tiny change to bring in a modification that I've been running locally for a bit. (Seeing the other terminal PR made me actually spend 2 mins and look it up!).
Apparently, shells on macOS should be login shells by default, at least according to the stackoverflow answer I've linked. VSCode also defaults to `["-l"]` on macOS, and links the to the same answer in their code, so I would say it should be fine.
Fixes #1548
Fixes #1161
> fix(terminal/#1548): use login shell for macOS

- scripts/lint.sh
- src/bin_editor/Cli.re
- src/bin_editor/Oni2_editor.re
__Issue:__ As described in #2507 - the feedback when installing an extension isn't very useful.
__Fix:__ Check to see if there are similar extensions in the extension catalog, if so, suggest them as alternatives:
```
Bryans-Mac-mini:oni2 bryphe$ oni2 --install-extension csharp
Failed to install extension: csharp
Did you mean one of these extensions?
- muhammad-sammy.csharp
- vscode.csharp
- pflannery.vscode-versionlens
- robole.snippets-ranger
```
Fixes #2507
> fix(cli/#2507): Better feedback when extension can't be installed

- docs/docs/configuration/settings.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorConfiguration.re
__Issue:__ Since scrolling is now handled entirely by Onivim in #2597 , the `scrolloff` setting needs to be handled here too.
__Fix:__ Implement configuration, and account for scrolloff when cursor is near boundaries. Small refactor to share the configuration-setting code across editor creation and configuration changed.
__TODO:__
> feat(editor): Add `:scrolloff` / `editor.cursorSurroundingLines` setting

- docs/docs/configuration/extensions.md
- docs/docs/configuration/key-bindings.md
- docs/docs/for-developers/building.md
- docs/docs/using-onivim/command-line.md
- docs/docs/using-onivim/visual-mode.md
Small change to include all the builds deps for Fedora 32. I've updated the Revery deps already, since that is just in the Wiki there and doesn't need a PR.
Also just updated to explain what the 3 build steps do, a common question I see is "The bootstrapping is taking ages! The build is going to take even longer..." when really the build step is a few seconds since 99% of the work happens in the bootstrap bit. (We can't swap the steps around as eventually you hit an error as the bootstrap files are needed and getting and error during the build would cause even more questions).
Fixes #2611.
> docs(core/#2611): improve build docs and dependencies 

- src/Feature/Editor/Editor.re
__Issue:__ As described in #2590 - when using go-to definition, or entering a find item in the search list, the editor will navigate to the definition but will slide, with the cursor outside the viewport, which is a pretty jarring experience.
__Defect:__ We were trying to scroll to the cursor before the editor has been sized - this leads to invalid results when trying to figure out the `scrollX` and `scrollY`.
__Fix:__ Don't scroll to the cursor until the editor has a size set. If it is the first time setting the size, we'll center the cursor in the viewport.
Fixes #2590 
Fixes #1168
(Technically, #1168 was actually fixed by #2597 - but noticed it here looking at related issues)
> fix(editor/#2590): Go-to-definition / search causes the editor to slide

- bench.esy.lock/index.json
- bench.esy.lock/opam/ocaml-migrate-parsetree.1.8.0/opam
- bench.esy.lock/overrides/opam__s__conf_m4_opam__c__1_opam_override/package.json
- esy.lock/index.json
- esy.lock/opam/ocaml-migrate-parsetree.1.8.0/opam
- esy.lock/overrides/opam__s__conf_m4_opam__c__1_opam_override/package.json
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ocaml-migrate-parsetree.1.8.0/opam
- integrationtest.esy.lock/overrides/opam__s__conf_m4_opam__c__1_opam_override/package.json
- package.json
- release.esy.lock/index.json
- release.esy.lock/opam/ocaml-migrate-parsetree.1.8.0/opam
- release.esy.lock/overrides/opam__s__conf_m4_opam__c__1_opam_override/package.json
- test.esy.lock/index.json
- test.esy.lock/opam/ocaml-migrate-parsetree.1.8.0/opam
- test.esy.lock/overrides/opam__s__conf_m4_opam__c__1_opam_override/package.json
Pick up a couple `libvim` fixes:
- https://github.com/onivim/libvim/pull/233
- https://github.com/onivim/libvim/pull/234
> refactor(dependency): libvim -> 8.10869.67

- manual_test/cases.md
- scripts/osx/run.sh
- scripts/release.js
- src/Core/ShellUtility.re
- src/Core/ShellUtility.rei
- src/bin_editor/Oni2_editor.re
Continuation of the fix started in #2614 
Related to #1161 and #1548 - there is another bug with `PATH` on OSX. When running Onivim from finder, the Onivim process won't get shell environment variables like `PATH`. 
So you get a very small list of `PATH` variables:
This is problematic for the extension host, as well - some extensions look for binaries in the user's current PATH, and if we're not sending the full terminal PATH, some of these utilities could be missed. Likewise for Vim shell commands (ie, `:!`).
It turns out, this isn't a problem unique to Onivim.... happens to Electron apps too, ie: https://stackoverflow.com/questions/62067127/path-variables-empty-in-electron  So we use a similar strategy to the [`fix-path`](https://github.com/sindresorhus/fix-path/blob/8f12bec72ee4319638a4 …
> fix(osx/#1161): PATH not available when launching from Finder

- src/Input/Keybindings.re
- src/Input/Keybindings.rei
- src/Model/Actions.re
- src/Store/InputStoreConnector.re
- src/editor-input/EditorInput.re
- src/editor-input/EditorInput.rei
- src/editor-input/KeyPress.re
- src/editor-input/Modifiers.re
- test/editor-input/InputTest.re
__Issue:__ As described in #1691 - mapping to `gt` would cause Vim commands - like `gg` to not work as expected. These sorts of input issues are important to fix as the [externalized mapping](https://github.com/onivim/libvim/pull/236) commands are hooked up - to be able to support `map`, `inoremap`, etc in Onivim properly.
__Defect:__ When the `gt` binding was added, and `gg` was run - the expected behavior would be that, in our EditorInput / keybindings, the following sequence would take place:
- First `g` pressed, put on pending keys - it could be the start of a `gt` binding
- Second `g` pressed - `gt` binding isn't a candidate anymore, flush both `g`s (should return effects like `[Unhandled(g), Unhandled(g)]`.
However, when the second `g` was pressed, only a single `g` would be …
> fix(input/#1691): Keybindings - extra key needed to be pressed with gt keybinding

- src/Feature/SideBar/Feature_SideBar.re
__Issue:__ #2639 - clicking on the sidebar button doesn't toggle whether the sidebar is open or closed, just focuses or unfocuses the sidebar.
__Defect:__ There was common logic being used for the 'click' gesture and the shortcut key (ie, `Control+Shift+E`/`Cmd+Shift+E`) - the shortcut key toggles focus, but the click gesture has a bit different behavior - it should switch to the pane if it is not current, or if its, toggle the visibility of the sidebar.
__Fix:__ Implement this separate logic for the click gesture
Fixes #2639
> fix(sidebar/#2639): Clicking on dock buttons doesn't toggle

- extensions/reason-vscode/src/index.js
__Issue:__ Onivim bundles a Reason / OCaml extension - by default, it tries to use the `ocamllsp` available via `esy`, and then falls back to `rls`.
__Defect:__ Onivim wasn't handling the OPAM case, or other cases where `ocamllsp` might be available in the environment without `esy`. 
__Fix:__ If we don't have `esy`, or we can't find `ocamllsp` via `esy`, try the `PATH` too
With this change - if I run Onivim from an OPAM project, with or without esy, I get `ocamllsp` provided by the OPAM switch.
..and then get my nice ocamllsp features like hover (`gh`), go-to-definition (`gd`), completion, etc:
Fixes #2641
> fix(extension/#2641): ocamllsp not picked up from OPAM project

- src/Core/Utility/StringEx.re
- src/Feature/Vim/Feature_Vim.re
- src/Store/VimStoreConnector.re
- fixed issue #2624 
- fixed by searching from the back of the input instead of front
- added an accompanying `let%test`. I'm 100% new to ReasonML so please let me know if I missed something which I likely did. I don't precisely know what `let%test` does
> fix(): fix tab completion in quick menu for multiple argument commands

- extensions/shellscript/package.json
enable syntax-highlighting for dash shell scripts
> add dash shell

- src/Core/Constants.re
- src/Feature/Editor/Editor.re
This adds a double-click handler to the editor surface - selecting a token in select mode or visual mode, depending on the current mode.
> fix(editor): Double-click to select token

- docs/docs/configuration/settings.md
This seems to have been forgotten when the setting was promoted to default in #2237.
> docs: remove experimental.editor.smoothScroll

- scripts/linux/package-linux.sh
This reverts ad136eef1867e14e67a2a0e0c31a3945d02d83f1/#2254 
The workaround is broken since the server hosting the binary seems to be down entirely, and the issue seems to have been fixed.
> fix(packaging): esy @release create fails on linux

- docs/docs/for-developers/building.md
- Mention issue [esy/esy#1099](https://github.com/esy/esy/issues/1099) for Linux users.
- Update root binary folder created by `esy '@release' create`.
- Explain where the binary of Oni2 is actually generated, current documentation is false since no `_release` folder is created in the root folder of the Oni2 repo.
- I ran into an issue when running `esy '@release' create`, it was saying it failed since `esy '@release' install` had not been run prior to running it, so I added this line in the documentation.
Hope theses changes will help people to build Oni2 more easily.
> docs(infrastructure/esy#1099) fix docs to describe reality

- manual_test/cases.md
- src/Core/ShellUtility.re
__Issue:__ If the shell initialization script prompts for input, as in #2659 , Onivim 2 would hang when launched from dock or finder.
__Defect:__ When launching from dock or finder, we open up a terminal to query the current PATH (since the PATH isn't available by default for applications). In the case of blocking input, Onivim would hang.
__Fix:__ Close the `stdin` of the terminal process upon launch, before reading any lines, which could block.
> fix(osx/#2659): Launching from dock

- Oni2.opam
- OniBench.opam
- OniIntegrationTests.opam
- OniUnitTestRunner.opam
- dune-project
- libvim.opam
- textmate.opam
- treesitter.opam
Instead of listing dummy .opam files, it's possible to define packages in the
dune-project file.
> Move package definitions to dune-project

- src/Store/ExtensionClient.re
__Issue:__ Intermittently - on both my developer machines (and, I believe, the same failure causing the extension host unit tests to fail in investigating #2675) - the extension host can fail to start. The `node` process is created, and `bootstrap-fork.js` is run - but the `AMD_ENTRYPOINT` environment variable is not set in this particular case.
__Defect:__ It seems that the problem stems from some interaction between `Luv.Env.environ()` and passing those environment arguments to `Luv.Process.spawn`. I suspect that it is some GC issue - the manifestation was dependent on allocated bytes. This made it a bit tricky to investigate, as turning on logging (either to a file or to the terminal) - would actually make the problem go away! 
I fell back to investigating via pushing logs to a native …
> fix(exthost): Intermittent environment issue

- src/Exthost/Transport/Exthost_Transport.re
- test/Exthost/Test.re
- test/Exthost/lib/Node.re
- test/Exthost/lib/Waiter.re
- test/OniUnitTestRunnerCI.re
There's some flakiness in the exthost test - intermittently, on CI, the extension host tests will fail.
This change adds some more logging to track down and get closer to the issue (as well as failing fast in the test, to help make it easier to investigate)
> refactor(test): Exthost - Additional logging for tests

- .ci/esy-build-steps.yml
- .ci/run-integration-tests.yml
There's a couple of sources of intermittent failures in `esy install` and `esy build`:
- Network / timeouts when acquiring sources for `esy install`
- Failures building OCaml on Windows - there will be issues with initial build, like:
```
config.status: executing libtool commands
1 [main] make 12538 child_info_fork::abort: \??\C:\npm\prefix\node_modules\esy\node_modules\esy-bash\.cygwin\bin\cyggmp-10.dll: Loaded to different address: parent(0xCD0000) != child(0x170000)
make: Makefile.common:44: fork: Resource temporarily unavailable
make -C runtime BOOTSTRAPPING_FLEXLINK=yes ocamlrun.exe
0 [main] make 12556 child_info_fork::abort: \??\C:\npm\prefix\node_modules\esy\node_modules\esy-bash\.cygwin\bin\cyggmp-10.dll: Loaded to different address: parent(0xCD0000) != child(0x170000)
make: fork: …
```
> chore(ci): Add retry for initial esy install / esy build

- test/OniUnitTestRunnerCI.re
I've been seeing intermittent failures on OSX with an `Exception Sys_blocked_io` when running the unit tests: https://dev.azure.com/onivim/oni2/_build/results?buildId=14135&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=c46197d7-212e-55e5-cfb1-808ec43d5033&l=2626
I've never seen this error running tests locally, so I suspect it may be due to the Azure Pipelines agent and the way logs are consumed. This change experiments with turning down the log level when running CI tests, to see if that hypothesis is correct and to avoid that error.
If this works - the tests could log to a file, and then in the case of an error, they could be output.
> chore(ci): Investigate Sys_blocked_io - reduce log output for CI tests

- src/Exthost/Exthost.rei
- src/Exthost/Request.re
- src/Service/Exthost/Service_Exthost.re
- test/Exthost/LanguageFeaturesTest.re
__Issue:__ Occassionally, there could be errors when querying the document symbols via the [`$provideDocumentSymbols`](https://github.com/onivim/vscode-exthost/blob/4b9db577f1e2349ef9073a26182687aa450c2787/src/vs/workbench/api/common/extHost.protocol.ts#L1388) API.
__Defect:__ The API could return `undefined` or a list of symbols - we weren't handling that case.
__Fix:__ Handle the `undefined` case
> fix(exthost): Document symbols can return undefined or null

- src/Feature/Search/Feature_Search.re
__Issue:__ If the search results have focus, clicking the search text focuses the search sidebar, but not the text itself.
__Fix:__ Switch focus to the search text when clicking it
> fix(search): Bugfix when clicking search when results has focus

- bench.esy.lock/index.json
- bench.esy.lock/opam/bigarray-compat.1.0.0/opam
- bench.esy.lock/opam/ppx_deriving.5.1/opam
- bench.esy.lock/opam/ppxlib.0.15.0/opam
- esy.lock/index.json
- esy.lock/opam/bigarray-compat.1.0.0/opam
- esy.lock/opam/ppx_deriving.5.1/opam
- esy.lock/opam/ppxlib.0.15.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/bigarray-compat.1.0.0/opam
- integrationtest.esy.lock/opam/ppx_deriving.5.1/opam
- integrationtest.esy.lock/opam/ppxlib.0.15.0/opam
- package.json
- release.esy.lock/index.json
- release.esy.lock/opam/bigarray-compat.1.0.0/opam
- release.esy.lock/opam/ppx_deriving.5.1/opam
- release.esy.lock/opam/ppxlib.0.15.0/opam
- test.esy.lock/index.json
- test.esy.lock/opam/bigarray-compat.1.0.0/opam
- test.esy.lock/opam/ppx_deriving.5.1/opam
- test.esy.lock/opam/ppxlib.0.15.0/opam
- test/reason-libvim/MacroTest.re
This picks up https://github.com/onivim/libvim/pull/247, which fixes some bugs around the `:norm` ex command (found while working on `vim-surround` compatibility) - and happens to fix #934 as well.
> fix(vim/#934): Fix macro with global command

- src/Service/Extensions/Catalog.re
- src/Service/Extensions/Service_Extensions.rei
__Issue:__ As described in #2698 - installation fails when installing the `sianglim.slim` open-vsx extension
__Defect:__ Our parser for the extension details was expecting a required `repositoryUrl` property, but it should be optional.
__Fix:__ Make `repositoryUrl` and optional parameter.
It looks like I'm getting some syntax highlights with it, as well:
Fixes #2698
> fix(extensions/#2698): Install fails for sianglim.slim extension

- test/reason-libvim/EvalTest.re
https://github.com/onivim/libvim/pull/247 picked up in #2697 actually fixes #941 as well - this adds a test case to cover it, too, though.
> fix(vim/#941): Normal command across range

- src/Exthost/Exthost.rei
- src/Exthost/Request.re
- src/Service/Exthost/Service_Exthost.re
- test/Exthost/LanguageFeaturesTest.re
__Issue:__ Some extensions would show an error like:
```
[ERROR] [16.666s] Exthost.Client : Request 26 for $provideDocumentHighlights failed with error: ParseFailedException("Expected a list, but got null")
```
in the console.
__Defect:__ `$provideDocumentHighlights` can return `undefined`, but we were expecting it to always return with a `list`.
__Fix:__ Model `undefined` in the API
> fix(exthost): $provideDocumentHighlights - update API to allow for null / undefined return

- integration_test/ClipboardChangeTest.re
- integration_test/dune
- src/Store/VimStoreConnector.re
- src/reason-libvim/Yank.re
__Issue:__ When the `vim.useSystemClipboard` setting is set to yank-only, changes are still pushed to the clipboard - in other words, changes are treated like yanks instead of deletes.
__Fix:__ Treat changes as a separate entity when it comes to yanks; use the same setting as deletes. If there is a use-case, we could also add another option to specify whether changes should be pushed to the clipboard independently of deletes, but in the meantime, it certainly makes more sense to treat them as deletes instead of yanks.
Fixes #2694
> fix(clipboard/#2694) - change operator being treated like yank instead of delete

- src/Components/Animation/Component_Animation.re
- src/Components/Animation/Component_Animation.rei
- src/Components/Animation/Spring.re
- src/Components/Animation/dune
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Msg.re
- src/Feature/Editor/dune
- src/Service/Time/Service_Time.re
- src/Service/Time/Service_Time.rei
This is the first part of the fix for #2407 - addressing the hanging scroll timers. This moves away from the hook-based timers, which can potentially leave timers hanging (and have a complicated timing dependency), and replaces it with a model/subscription based approach, which should be more reliable. In particular, the subscriptions used here never leave an `interval` hanging - it's always a one-off fire when the spring animation is active.
This uses the `Spring` model from Revery, but wraps it in a component module (`Component_Animation`), and provides a wrapper model and subscriptions to use. It's sort of a baby-step into migrating our animations from hook-based to model-based.
__TODO:__
- Replace additional problematic hook-based animations (color transition, status …
> fix(perf/#2407): Part 1 - Replace smoothscroll timer hook with model-based animation

- src/Store/KeyBindingsStoreConnector.re
__Issue:__ Binding to some ex commands - like `:enew` - aren't working as expected. In the `:enew` case, no buffer is opened.
__Defect:__ The effects are being ignored, so there is no buffer transition
__Fix:__ Re-use the effect logic in `VimStoreConnector` to handle this (use the `VimExecuteCommand` action).
Fixes #2604
> fix(input/#2604): Ex keybinding fails

- src/Feature/Editor/EditorConfiguration.re
Possibly I'm missing something here, but this just looks like it wasn't hooked up?
> fix(configuration): hook up missing render whitespace option

- src/Core/BufferLine.re
- src/Core/BufferLine.rei
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Store/Features.re
__Issue:__ The codelens would also be positioned at the beginning of the line - it doesn't look correct on indented lines:
__Fix:__ Position the codelens in-line with leading whitespace
> fix(codelens): Match indent to bufferline

- src/Components/Animation/Component_Animation.re
- src/Components/Animation/Component_Animation.rei
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/Minimap.re
- src/Feature/Editor/SurfaceView.re
- src/Feature/Editor/YankHighlights.re
- src/Store/Features.re
Fixes  another hanging-hook-timer in #2407 - moves the yank highlight animation from hook-based to model-based animation.
In addition to removing the chance of a hanging-hook-timer, this fixes a bug where the yank-highlight animation could be replayed when navigating between editors.
Related to #2407
> fix(perf/#2407): Part 2 - Move yank highlights to model-based animation

- azure-pipelines.yml
Set up the Ubuntu builds to run on `master`, and save the cache - to help speed up PR builds
> chore(ci): Populate esy cache for Ubuntu builds

- docs/docs/configuration/key-bindings.md
Also see second commit that removes references to `menuFocus`
> docs: Add explorer contexts to key-bindings.md

- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionProvider.re
- src/Feature/LanguageSupport/CompletionProvider.rei
__Issue:__ When there is a failure getting details for a completion item - as in #2752 - Onivim crashes.
__Defect:__ When there is a `DetailsError`, we were clearing out the set of completion items. This broke our logic in trying to maintain the selected item - causing an array out-of-bounds exception to be thrown. 
__Fix:__ In the case of an error getting details, we should not crash, and we should maintain the current set of items.
Fixes #2752
> fix(completion/#2752): Don't clear out items on details error

- .ci/esy-build-steps.yml
This changes `esy @release run --version` → `esy @release run --help`
As of right now, when we try to run the binary to create it for release, we get a linking error on macOS since we try to dynlink `Sparkle.framework` in a scenario that is explicitly disallowed by the kernel.
However, since the `--help` CLI flag means the program is terminated before we try to link the framework, we don't get this failure.
It's not a huge deal, but I think it makes more sense to have a failure that actually means failure rather than a failure that means success and we allow it to proceed.
> fix(ci): remove unneeded failure in release creation

- manual_test/cases.md
- src/Core/Buffer.re
- src/Store/QuickmenuStoreConnector.re
- src/bin_editor/Oni2_editor.re
- src/bin_editor/dune
__Issue:__ Onivim may crash on OSX with `Cmd+P` when launching from finder for the first time
__Defect:__ The default directory for Onivim was set to the `Documents` folder. However, Onivim may not actually have permission to access this folder due to OSX's sandboxing. 
__Fix:__ If we don't have permission, don't set a workspace and fall-back to `Cmd+P` opening active buffers.
https://github.com/onivim/oni2/pull/2711 helped this particular scenario, by setting up state and UI for the case where no workspace is opened / the working directory is not valid. However, there is still the case that we may have persisted the `Documents` folder, and we could still get that or another invalid folder coming from persistence. Therefore, we need to check permission for the folder prior to changing …
> fix(workspace/#2742): OSX - Crash with Cmd+P on first launch

- src/Feature/Workspace/Feature_Workspace.re
With #2711 , we now have an 'Open Folder' button when no workspace is opened:
This just implements a small tweak to always have the `Workspace: Open Folder` option available in the command palette, even when one is currently opened (for changing folders).
Fixes #730
> fix(workspace/#730): Open Folder button

- src/UI/Dock.re
Fixes #1131 , removes another case that could leave a hanging timer like #2407
> fix(ux/#1131): Remove initial dock animation

- src/Feature/Theme/GlobalColors.re
__Issue:__ On startup, for a couple frames, the statusbar is bright blue - this is jarring on load.
__Defect:__ The bright-blue is the default statusbar color, and is used until the theme is loaded. 
__Fix:__ Use a more subtle, semi-transparent color for light/dark backgrounds, so the transition is smoother.
> fix(ux): Flashing statusbar on startup

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/Notification/Feature_Notification.re
- src/Feature/Notification/Feature_Notification.rei
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Pane/Feature_Pane.rei
- src/Feature/Pane/NotificationsPaneView.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
- src/UI/Root.re
- src/reason-libvim/Clear.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Goto.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/MessageTest.re
This integrates the `messages` ex command with the pane view, and sets up keyboard navigation for the message elements:
(...need to adjust FPS settings on my gif recorder - much smoother in real-time)
__Todo:__
> feat(vim): Hook up ':messages' / ':messages clear' ex commands

- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Store/Features.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
This is some refactoring to make it easier to pick up some ambient state around the current `libvim` environment - this is needed for #2758 . 
Once https://github.com/onivim/libvim/pull/250 is integrated, we'll use this revised plumbing to track when we're in a 'sub-mode' - like insert literal - and handle the input in a special way for that case (always forwarding it to Vim, ignoring key bindings).
Previously, the mode changes would only be tracked in the active editor, which means they could get missed when we're in command line mode or other global states.
This will also be useful in addressing https://github.com/onivim/oni2/issues/1159, as we can also use a 'sub-mode' to represent the substitute-with-confirmation case.
> refactor(vim): Move mode context to Feature_Vim

- src/Feature/LanguageSupport/Completion.re
Fix a couple typos in `Completion.re` for shortcut keys - thanks @neutronstein for catching these!
> fix(completion): Shortcut typos

- src/Core/Utility/StringEx.re
- src/Feature/Editor/IndentLineRenderer.re
__Issue:__ There were several visual glitches with the active-indent renderer (visible in a screenshot posted in #2353)
Issue 1:
The indent guide would overlap some text
Issue 2:
When word-wrapping is active, the indent guide would go through wrapped lines:
When codelens is active, the indent guide would go through the lens:
__Defect:__
All of these issues stem from two core problems:
1) If the indentation goes to the end of the file, we'd treat the end coordinate as being at 0 pixels - causing us to draw upward instead of downward (issue 1)
2) When drawing the active line, we'd just draw over all the buffer lines, with no context about word wrap or codelens (issue 2 & 3)
__Fix:__
Tweak the algorithm a bit - it was a two-pass algorithm before, where we'd draw the inactive, and then draw …
> fix(editor): Fix several bugs with the active-indent renderer

- src/Feature/Editor/ContentView.re
- src/Feature/Editor/Selection.re
__Issue:__ When word wrap is enabled, and we're at the bottom of a document w/ a bunch of wrapped lines, sometimes the selection rendering would behave unexpectedly or not render fully.
__Defect:__ When rendering the selection (and some other content, like diagnostics...) we'd be treating _view lines_ as _buffer lines_. When word wrap is off, those are 1 to 1, so the bug is hidden - but when it is on, it causes the bug described - depending on the delta between view lines and buffer lines, the selection may be rendered partially or not at all.
__Fix:__ Convert the view line to buffer line for the necessary APIs
> fix(editor): Fix bug in selection rendering when wordWrap is enabled

- docs/docs/configuration/settings.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/EditorConfiguration.re
We've had an experimental implementation of word wrap - this promotes it to a non-experimental feature.
The configuration setting is:
`editor.wordWrap` and can be `true` or `false` (`"on"` and `"off"` are also accepted - and will extend to support columns as well). In addition, this adds a brief documentation blurb in our settings: https://onivim.github.io/docs/configuration/settings 
This is a breaking change, in that if you were using `experimental.editor.wordWrap`, you'll need to update your configuration to `editor.wordWrap`
Fixes #1444
> fix(editor/#1444): Promote experimental.editor.wordWrap -> editor.wordWrap

- node/download.js
- node/package.json
- node/yarn.lock
- src/Core/Kernel/StringSet.re
- src/Core/NodeTask.re
- src/Core/Oni_Core.re
- test/OniUnitTestRunnerCI.re
__Issue:__ Extensions are not downloading correctly from `open-vsx`. This impacts both installing from command-line, and within Onivim.
__Defect:__ The `open-vsx` service updated their download service to be backed by azure blobs, and sends a 302 redirect - we weren't handling redirects in our download logic.
__Fix:__ Handle redirects using the `follow-redirect` node module.
> fix(extensions): Extensions failing to download from open-vsx

- src/CLI/Oni_CLI.re
- src/Core/Kernel/Log.re
- test/Cli/CliTest.re
__Issue:__ While investigating the OSX 10.13 scaling issues, I noticed the `--trace` log level wasn't working as expected.
__Defect:__ When `--trace` was set, it could get reverted a couple of ways 
__Fix:__ Fix cases where `--trace` could get reset or lowered when specified on CLI, add some tests to cover these.
> fix(cli): Fix --trace level not being set correctly

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
- test/reason-libvim/InsertModeEdit.re
This picks up https://github.com/onivim/libvim/pull/252, which fixes the repeat-count for `i`, `a`, `A`, `o`, etc, and adds a simple test case here.
Fixes #809
Fixes #2190
> fix(vim/#809): Insert-mode repeat count not handled correctly

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- test/Feature/Editor/EditorTests.re
__Issue:__ When moving the mouse in an empty buffer, there could be a potential crash
__Defect:__ On getting a mouse move, we look to see if there is an identifier under the cursor (ie, for hover). However, there was a missing bounds check - so it was possible for us to look out of range of the current buffer.
__Fix:__ Verify the byte position is in range before trying to pull out an identifier.
Fixes #2800
> fix(editor/#2800): Crash on moving mouse in empty buffer

- CHANGES_CURRENT.md
- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/Manifest.re
- src/Feature/Extensions/DetailsView.re
- src/Feature/Extensions/Model.re
- src/Service/Extensions/Catalog.re
- src/Service/Extensions/Service_Extensions.rei
__Issue:__ Some of the extensions posted on `open-vsx` have a public namespace - meaning anyone can  publish to it. 
__Fix:__ We should display a notification letting the user know about this, so they can decide if they want to verify the extension further. This adds a UI on the details page:
Fixes #2345 
Thanks @fanantoxa for logging the bug!
> fix(extensions/#2345): Implement warning if the namespace is public

- CHANGES_CURRENT.md
- node/request.js
- src/Core/NodeTask.re
__Issue:__ On Windows / OSX, sometimes the extension details would fail to be fetched.
__Defect:__ There was a race condition in our logic to use node for handling requests. If we receive the `on_exit` prior to `stdout` closing, the request will never complete.
__Fix:__ Make sure we complete when the request has exited and stdout has closed.
> fix(extensions): Intermittent request failure

- CHANGES_CURRENT.md
- src/Components/RemoteAsset.re
- src/Components/RemoteImage.re
- src/Components/RemoteMarkdown.re
- src/Feature/Extensions/DetailsView.re
This fixes a bug where we were not showing the logo image for extensions correctly.
Now, when browsing, the logo image gets loaded:
> fix(extensions): Show image in details

- CHANGES_CURRENT.md
- azure-pipelines.yml
- docs/docs/using-onivim/command-line.md
- integration_test/EchoNotificationTest.re
- integration_test/InputContextKeysTest.re
- integration_test/LineEndingsCRLFTest.re
- integration_test/LineEndingsLFTest.re
- integration_test/Regression2349EnewTest.re
- integration_test/RegressionVspEmptyExistingBufferTest.re
- integration_test/VimScriptLocalFunctionTest.re
- integration_test/VimSimpleRemapTest.re
- src/CLI/Oni_CLI.re
- src/CLI/Oni_CLI.rei
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Msg.re
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Model/Actions.re
- src/Store/Features.re
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
- src/bin_editor/Oni2_editor.re
- src/bin_launcher/Oni2.re
- test/Cli/CliTest.re
- test/Cli/IntegrationTest.re
Fixes #1861 & #2803 
__TODO:__
> fix(cli/#1861): Add CLI command to execute vim ex commands

- CHANGES_CURRENT.md
- src/Feature/AutoUpdate/Feature_AutoUpdate.re
- src/Service/AutoUpdate/Service_AutoUpdate.re
- src/gen_buildinfo/generator.re
__Issue:__ All of our build variations - `master`/`nightly`, `stable`, and `staging` default to using the `master` update channel. However, someone running the `stable` builds would likely prefer the less-frequent-but-more-vetted (and less noisy) `stable` builds for updates.
__Fix:__ Decide, based on the branch we're building from, which default update channel to use.
> fix(auto-update): Set default update channel based on build

- CHANGES_CURRENT.md
- assets/Info.plist
- assets/dune
- scripts/release.js
Fix #2816 - Use a development `Info.plist` that specifies the `NSSupportsAutomaticGraphicsSwitching` setting.
> fix(build/#2816): Use development Info.plist on OSX

- src/Exthost/OneBasedRange.re
__Issue:__ Onivim 2 wasn't correctly handling ranges from the extension host that were created with `Number.MAX_VALUE` (or, any value with any exponent...). A `ParseFailedException("Expected null or:\n while decoding a list:\n element 0:\n in field \"range\":\n in field \"endColumn\":\n Expected an int, but got 1.7976931248623157e+308\n".` was being produced.
__Defect:__ Our JSON parsing was only handling integers
__Fix:__ Use the `float` JSON decoder, which does handle exponents, and cast to an `int` - handling overflows.
This fixes the parse failure, and allows for some basic formatting - but I'm still seeing some quirks with the ReScript formatter, when updating the buffer and running the formatter again. 
Related #2820
> fix(formatting/#2820): Range overflow when parsing ranges from extension host

- CHANGES_CURRENT.md
- src/Core/Ripgrep.re
__Issue:__ The search box defaults to a regex search, which is not obvious and there is no indication to the user that it would default to regex, or feedback from an invalid regex.
__Defect:__ The default `ripgrep` behavior is to use a regex-search (which we use for executing the search) - however, we should use the `--fixed-strings` flag, which does simple string search.
__Fix:__ For find-in-files, add the `--fixed-strings` flag when calling ripgrep.
Fixes #2821
__Future Work:__
- Implement a toggle / button to enable regex search (#2599)
> fix(search/#2821): Default to simple string search for find-in-files

- CHANGES_CURRENT.md
- src/Components/ScrollShadow.re
- src/Components/VimList/Component_VimList.re
- src/Feature/Editor/InlineElementView.re
- src/Feature/Theme/GlobalColors.re
__Issue:__ We use the same shadow color for both dark and light themes. It ends up being too harsh on light themes.
__Fix:__ Tone down shadow color for light themes (and make themable).
> fix(ux): Adjust shadow for themes

- CHANGES_CURRENT.md
- src/CLI/Oni_CLI.re
- src/bin_editor/Oni2_editor.re
- test/Cli/CliTest.re
__Issue:__ Opening a single file should be quick and not incur the extra overhead of opening a folder / workspace (ie, initializing our SCM providers in the extension host). Now that we have a no-workspace-opened state, this can be fixed.
__Fix:__ Don't set a folder when a file is specified
Fixes #1983
> fix(workspace/#1983): Open single file should not open folder, too

- CHANGES_CURRENT.md
- scripts/linux/AppRun
Additional fix for #2803 - the command line arguments were getting split in the AppImage's `AppRun` - this updates the script so that they continue to be grouped when they are passed to Onivim for parsing.
> fix(cli/#2803): Quote arguments in AppRun so they don't get inadvertently split

- CHANGES_CURRENT.md
- src/Core/Kernel/IntMap.re
- test/Core/IntMapTests.re
__Issue:__ When deleting a line with a codelens, the codelens persists until the file is saved
__Defect:__ There was a bug with our shift logic - if the item would be deleted, there were cases were it could be kept (in a sparse mapping, where it wouldn't be overwritten - like the code lens / inline elements)
__Fix:__ Remove elements that are deleted in `shift`, and case to cover
> fix(codelens): Deleting line does not remove codelens

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/Buffers/Feature_Buffers.rei
- src/Model/Actions.re
- src/Service/Exthost/Service_Exthost.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/Buffer.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Listeners.re
- src/reason-libvim/Native.re
- src/reason-libvim/Split.re
- src/reason-libvim/Types.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/Window.re
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/WindowTest.re
__Issue:__ The various new-buffer commands (`tabnew`, `new`, `vnew`) weren't creating a new buffer - they were splitting the existing buffer (behaving more like `vsp`, `sp`, etc).
__Defect:__ We weren't differentiating between `vsp` and `vnew` (and others) - we were treating them equivalently.
__Fix:__ Differentiate them in `libvim` - requires https://github.com/onivim/libvim/pull/254 . Then, handle creating and using new buffers.
__TODO:__
Fixes #1455
Fixes #2753 
Fixes #2843
> fix(vim/#2753): Fix tabnew/new/vnew behavior

- CHANGES.md
- package.json
- src/UI/WelcomeView.re
Some tweaking to help facilitate monthly releases soon - `0.5.9-nightly` will be the current working build, and we'll ship `0.5.1` (december), `0.5.2` (january), etc, off of that - working towards the goals on the [timeline](https://v2.onivim.io/index.html#timeline) for `0.6.0.`
> refactor(infra): Fix versions

- CHANGES_CURRENT.md
- src/Components/Tabs.re
Fixed the problem that the left and right scroll directions are reversed on the trackpad.
When I was using onivim on my Mac, I noticed that the scrolling of the tabs was reversed to the left and right of the trackpad. This means that you are not aware that you are using a mouse that only scrolls up and down.
I can't check it with OS other than mac, so it would be helpful if you could check it.
> fix: Tab bug

- CHANGES_CURRENT.md
- src/Core/Oni_Core.re
- src/Core/WhenExpr/ContextKeys.re
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/UI/DebugInputView.re
- src/editor-input/EditorInput.re
- src/editor-input/EditorInput.rei
- src/editor-input/KeyPress.re
This refactors the `EditorInput` and `Feature_Input` modules to expose some additional information, answering the questions:
- What keybindings are currently available, given my context?
- What keys are currently consumed?
This will be useful in a couple ways:
- For the menu work in #2849 - this API can be used to dynamically look up shortcut keys
- For a feature like https://github.com/onivim/oni2/issues/756 , we can show a set of available bindings (just need to decide on the best UX) - useful as a learning feature
- For supercharging sneak (Control+g) - in cases where the gesture would map to a bound command, we could show the shortcut key for it - helping to teach some of the Onivim-specific shortcut keys.
This isn't surfaced, yet, although some of the information is available in the …
> refactor(keybindings): Add API to query current bindings & consumed keys

- CHANGES_CURRENT.md
- src/Core/Utility/LwtEx.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Outmsg.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/Features.re
- src/Store/StoreThread.re
__Issue:__ For large files, with lots of codelens, we would try and resolve many at once - this would eventually be problematic for performance.
__Fix:__ Only resolve codelens in the viewport, which is more tractable for performance, even for large files with many codelenses present.
> fix(codelens): Improve resolve strategy

- CHANGES_CURRENT.md
- scripts/release.js
- src/Feature/SideBar/Feature_SideBar.re
- src/Feature/SideBar/Feature_SideBar.rei
- src/Store/Features.re
- src/bin_editor/Oni2_editor.re
__Issue:__ Some files/folders could not be dragged-and-dropped to the dock icon for Onivim 2.
__Defect:__
1) We were missing some `plist` entries to allow arbitrary document/folder drops
2) When a folder is dropped, it'd be treating as a file
__Fix:__
1) Add the `CFBundleTypeOSTypes` plist entries
2) Use the same code path for dropping a folder on dock as we do for dragging onto the surface 
In addition, when we drop a folder, open up the explorer pane so there is some feedback on the action
Fixes #2855
> fix(osx/#2855): Dock icon drag-and-drop

- CHANGES_CURRENT.md
- src/Feature/Extensions/DetailsView.re
- src/Feature/Extensions/Model.re
- src/Service/Extensions/Catalog.re
- src/Service/Extensions/Service_Extensions.rei
This adds rating count, download count, and average rating UI for extension details:
(Currently, this doesn't pull the data for installed extensions - only ones that user hasn't installed yet)
Fixes #2862
> fix(extension/#2862): Show download count and ratings for extensions

- CHANGES_CURRENT.md
- src/Feature/Editor/EditorConfiguration.re
- src/Feature/Editor/Feature_Editor.re
__Issue:__ When scrolling with the mouse wheel, the hover could pop up randomly while scrolling - and sometimes eat subsequent mouse wheel movements 
__Defect:__ There were two issues:
1) We were only considering the mouse-position-in-screen-space for hover, when we should be considering the scroll position as well
2) The delay for `editor.hover.delay` was off due to a units error - seconds were being treated as milliseconds, causing hover to pop up  instantly
__Fix:__
1) Consider scroll space as well for the hovered subscription
2) Fix unit conversion
> fix(hover): Don't pop-up while scrolling with mousewheel

- CHANGES_CURRENT.md
- docs/docs/languages/c.md
Fix extension ids for C in documentation - fixes #2872
> docs(language): Fix documentation for C - add namespace/publisher

- CHANGES_CURRENT.md
- src/Feature/SideBar/Feature_SideBar.re
__Issue:__ On Windows/Linux, the 'Toggle Sidebar' action was bound to `Ctrl+B`, which conflicts with the vim default of scrolling up a page.
__Fix:__ Remove conflict; switch toggle sidebar binding to `Ctrl+Shift+B`
Related #2870
> fix(vim/#2870): Remove conflicting 'ctrl+b' binding

- CHANGES_CURRENT.md
- src/Components/VimList/Component_VimList.re
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimWindows/Component_VimWindows.re
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Definition.re
- src/Feature/LanguageSupport/References.re
- src/Feature/LanguageSupport/Rename.re
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Registers/Feature_Registers.re
- src/Feature/SideBar/Feature_SideBar.re
- src/Feature/SignatureHelp/Feature_SignatureHelp.re
- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Feature/Vim/dune
- src/Input/Keybindings.re
- src/Model/State.re
__Issue:__ As described in #2368, there were cases where we were not handling `Ctrl+[` as `<Escape>`.
__Fix:__ We should respect this same behavior - as @LeonT-A mentioned, this is often quicker & easier to press than reaching for `<Escape>`
This involves some refactoring, adjusting the input schema to handle bindings (key -> command), remaps (key -> key), and, eventually for #2870 , clearing commands too, but it means we'll be able to handle remaps more generally in JSON.
> fix(input/#2368): Recognize Ctrl-[ as Esc across the UI

- CHANGES_CURRENT.md
- src/Feature/Editor/EditorDiffMarkers.re
- src/Feature/Editor/EditorDiffMarkers.rei
- src/Feature/Editor/GutterView.re
__Issue:__ The diff markers would not always render in the presence of codelens / inline elements
__Defect:__ The diff marker rendering was using a naive approach to calculate the current view `y` position - just based on the `scrollY` and the `rowHeight`. This worked fine without codelens, since the line height would never be variable - but in the presence of variable-height lines, this logic doesn't work anymore.
__Fix:__ Switch to using `Draw.renderImmediate` which handles this correctly.
> fix(editor): Correct diff marker rendering in presence of codelens

- CHANGES_CURRENT.md
- node/package.json
- node/yarn.lock
- src/Store/ExtensionClient.re
Upgrade extension host to 1.51.0
Related #1058 
> NOTE: If building from source, make sure to run `node install-node-deps.js` after picking up this change.
> refactor(dependency): vscode-exthost -> 1.51.0

- CHANGES_CURRENT.md
- scripts/linux/package-linux.sh
Package building problem on Ubuntu Linux Focal 20.04: 
Permission problem removing `_release/Onivim2.AppDir/usr/bin/setup.json`.
I have add force option to make it work.
> In linux package build script, rm -f file on cleanup

- CHANGES_CURRENT.md
- manual_test/cases.md
- src/Model/VimContext.re
__Issue:__ Using a count for `L` or `H` (screen-space linewise jump) had no effect
__Defect:__ We were ignoring the `count` parameter
__Fix:__ Handle the `count` parameter, offsetting from the top/bottom of the screen, and limiting to the bounds of the screen.
Fixes #2882
> fix(vim/#2882): Fix count behavior for L/H jumps

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
Brings in fixes to esy-skia that allows it to build with clang 10.2 on Arch Linux.
> fix(dependency): esy-skia -> 91c98f6

- bench.esy.lock/index.json
- esy.lock/index.json
- integration_test/EditorFontValidTest.re
- integration_test/QuickOpenEventuallyCompletesTest.re
- integration_test/TerminalConfigurationTest.re
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Core/Filesystem.re
- src/Core/Setup.re
- src/Core/ShellUtility.re
- src/Feature/AutoUpdate/Feature_AutoUpdate.re
- src/Feature/MenuBar/Global.re
- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/TitleBar/Feature_TitleBar.re
- src/Model/ContextKeys.re
- src/Store/InputStoreConnector.re
- src/UI/Root.re
- src/UI/VersionView.re
- src/UI/WelcomeView.re
- src/bin_editor/Oni2_editor.re
- test.esy.lock/index.json
- test/Cli/IntegrationTest.re
This brings in all the OS versioning information from the recent revery PRs. I wanted to bring this in separate from #2876 since it requires a lot of changes to switch statements across the codebase.
> refactor(dependencies): update revery → f2da66e

- CHANGES_CURRENT.md
- integration_test/InputRemapMotionTest.re
- integration_test/dune
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/Feature/Vim/Feature_Vim.re
- src/editor-input/EditorInput.re
- src/editor-input/EditorInput.rei
- test/editor-input/InputTest.re
__Issue:__ All of our bindings, whether defined by `nmap` or `nnoremap`, were allowing recursive definitions. This breaks the case in #2114, where the remaps would bounce back and forth until they hit our recursion limit.
__Defect:__ We weren't gating recursive remaps, aside from the recursion limit.
__Fix:__ Define and handle no-recursive remaps correctly.
__Todo:__
Fixes #2114
Depends on #2883 
Related #1551
> fix(input/#2114): Handle `nnoremap` correctly

- CHANGES_CURRENT.md
- src/Feature/Input/ReveryKeyConverter.re
__Issue:__ Right arrow key is being treated as page-up
__Defect:__ An incorrect conversion snuck in #2902 
__Fix:__ Fix the keycode -> key mapping for right arrow key
Related #2926
> fix(input/#2926): Part 2 - Right arrow key treated as PageUp

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
This picks up https://github.com/revery-ui/revery/pull/1037 , which is the fixes the root issue of #2919  . We were not properly integrating the sdl2 hit test callback with the OCaml garbage collector, which could cause an intermittent crash on mouse gestures that engage the hit test callback.
> fix(input/#2919): Windows - Intermittent crash on mouse scroll

- CHANGES_CURRENT.md
- manual_test/cases.md
- src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c
__Issue:__ Typing a Unicode character on Windows would fail, causing a crash.
__Defect:__ The character was being encoded as UTF-16, but we were expecting UTF-8. When we went to unpack the character as UTF-8, Zed would throw an exception, since the binary data was not a valid UTF-8 character.
__Fix:__ Convert from UTF16 to UTF8 prior to sending back to OCaml.
Fixes #2926
__Todo:__
> fix(input/#2926): Part 1 - Fix windows UTF-16 / UTF-8 conversion for key presses

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/DocumentHighlights.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Service/Exthost/Service_Exthost.re
- src/Store/Features.re
__Issue:__ We were calling several language feature extension host APIs on every cursor move, or on every insert.
The APIs being called were:
1) `$provideDocumentHighlights` - called on every cursor move
2) `$provideDefinition` - called on every cursor move
3) `$provideDocumentSymbols` - called on every edit
This is problematic when holding a key or typing fast - calling an extension host API isn't cheap, so we should debounce and wait to call when the cursor / input is settled.
__Todo:__
> perf(language-features): Debounce high-frequency subscriptions

- CHANGES_CURRENT.md
- integration_test/lib/Oni_IntegrationTestLib.re
- manual_test/cases.md
- src/bin_editor/Oni2_editor.re
- src/oni2-keyboard-layout/stubs/keyboard-layout-linux.c
- src/oni2-keyboard-layout/stubs/keyboard-layout-mac.c
__Issue:__ On OSX, if the Romanji keyboard is selected, keys with modifiers (`Cmd+P`, etc) would not be processed correctly.
__Defect:__ This was a regression from https://github.com/onivim/oni2/pull/2902 - in that change, we rely on querying our `keyboard-layout` library for keymap information. However, we weren't able to get keymap information for Japanese / virtual keyboard layouts.
__Fix:__ Turns out a similar issue was encountered in the `node-native-keymap` library here: https://github.com/microsoft/node-native-keymap/commit/f735d6711a6451e8ede8fe334b5e6f6b0024e061
Ported over a similar fix for our `keyboard-layout` strategy - first, try `TISCopyCurrentKeyboardInputSource`, and if that returns `NULL`, try `TISCopyCurrentKeyboardLayoutInputSource`.
Fixes #2924
> fix(osx/#2924): Modifier keys not working with Romanji keyboard

- CHANGES_CURRENT.md
- manual_test/cases.md
- src/Feature/Input/ReveryKeyConverter.re
__Issue:__ If `<space>` is specified as the leader key, it won't be recognized in `<leader>` bindings.
__Defect:__ When `<space>` is parsed, it is recognized as `Key.Space`. However, when the space key is pressed, it was associated with `Key.Character(' ')` - so when we went to match the pressed key against bindings with leader key, they wouldn't match.
__Fix:__ Associate the pressed input key with `Key.Space` instead of `Key.Character`
__TODO:__
> fix(input/#2935): <space> key not recognized as leader

- CHANGES_CURRENT.md
- src/Components/VimList/Component_VimList.re
I'm actually not sure if there are historical reasons that we allow overscroll up to 1 element, but if not, I find it slightly annoying sometimes when I scroll with the mousewheel and get something like this (especially considering the displayed scroll bar doesn't allow the same and disappears):
This is just a simple math change so that we bound the scroll to remove overscroll.
> fix(components): remove overscroll in `VimList`

- CHANGES_CURRENT.md
- src/Core/Utility/StringEx.re
__Issue:__ When a large file is loaded, and we get the 'original content' (via a diff provider) - large files could cause a stack overflow. The file doesn't need to be too large - this could be reproduced by trying to open the `large-c-file.c` in the integration_test folder in this repo.
__Defect:__ In migrating to the virtual file system in #2868 - we use a new strategy for loading the original content. This relied on using `StringEx.removeWindowsNewLines`, which was very inefficient, and could cause a stack overflow for very large content.
__Fix:__ Add test cases to cover existing functionality; improve performance by moving to a more efficient (less allocating) and stack friendly algorithm.
> fix(scm): StackOverflow on large diff

- CHANGES_CURRENT.md
- src/Components/RemoteMarkdown.re
For some reason, explicitly setting the code block font size fixes the code block issue in extension descriptions.
This should just be a temporary fix until I can figure out *why* this is happening, but it works well for now.
Fixes #2953
> fix(markdown/#2953): explicitly set code block font size in Markdown

- CHANGES_CURRENT.md
- src/Feature/Extensions/DetailsView.re
- src/Feature/Extensions/ListView.re
- src/Feature/Theme/GlobalColors.re
__Issue:__ Some of the colors for buttons in the extensions list / details page were hardcoded
__Fix:__ Use theme colors - thanks for catching this @zbaylin 
Related #2953
> fix(ux/#2953): Extensions - remove hardcoded button colors

- scripts/release.js
Fix to remove dependency on shebang-shell-script behavior that will go away in next `esy`
> chore(ci): Prepare `esy release` for new esy version

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
__Issue:__ On a trackpad, simply moving the trackpad to the edge of the editor would auto-scroll
__Defect:__ The `isPressed*` conditions were missing checking if the mouse is down
__Fix:__ Add mouse down check
Related #2898
> fix(editor): Fix isPressed edge condition for auto-scroll

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/oni2-keyboard-layout/stubs/keyboard-layout-mac.c
- test.esy.lock/index.json
__Issue:__ On OSX, if the keyboard layout is set to a virtual layout, or in a configuration that would cause it to change when an open dialog is brought up, the application could crash. I can reproduce reliably setting the keyboard layout to `Romaji`, and then trying to open a folder.
__Defect:__ When the dialog is opened in this configuration, a `kTISNotifySelectedKeyboardInputSourceChanged` notification is produced, which calls into our `notificationHandler`. The `notificationHandler` expects the OCaml runtime to _not_ be active, and tries to acquire it - however, in this case, it actually is acquired.
Callstack is:
```
Heaviest stack for the main thread of the target process:
41  camlRevery_Native__Dialog__openFiles_inner_115 + 90 (Oni2_editor.exe + 4050506) [0x10b050e4a]
41 …
```
> fix(osx): Crash in open file / folder dialog with virtual keyboard layout

- azure-pipelines.yml
`master` (uncached) builds are failing on Windows due to timeout. The timeout is not due to a hang - the build-the-world compilation is taking that long on Windows. Bump timeout to get master green again-
> chore(ci): Increase timeout for master builds on Windows

- CHANGES_CURRENT.md
- src/Core/MenuBar.re
- src/Core/MenuBar.rei
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/Buffers/Feature_Buffers.rei
- src/Feature/Input/Feature_Input.re
- src/Feature/MenuBar/Feature_MenuBar.re
- src/Feature/MenuBar/Feature_MenuBar.rei
- src/Feature/MenuBar/Global.re
- src/Feature/MenuBar/NativeMenu.re
- src/Model/State.re
- src/Store/StoreThread.re
WIP work to integrate the `MenuBar` / `Feature_MenuBar` with the work @zbaylin did to expose an API for it in Revery: https://github.com/revery-ui/revery/pull/1024
__Todo:__
- Handle `enabled` across menu items
- Handle `visible` across menu items
- Allow toggle-able menu items
> feat(osx): Native application menu

- CHANGES_CURRENT.md
- integration_test/ConfigurationInvalidThemeTest.re
- integration_test/dune
- src/Core/ConfigurationValues.re
- src/Core/Constants.re
- src/Store/ThemeStoreConnector.re
__Issue:__ If an invalid theme is specified, there is no syntax highlighting
__Defect:__ If we fail to load/find a theme, we show an error message, but don't bother loading our default theme - this means that we get no theme colors for tokens, and fallback to just the editor background / foreground color.
__Fix:__ If we can't find a specified theme, load our default LaserWave Italic theme.
Related to #2985 , and fixes one manifestation of it, but there may still be another underlying issue.
> fix(theme/#2985): Fallback to default theme when invalid theme is specified

- .ci/esy-build-steps.yml
- azure-pipelines.yml
- scripts/windows/validate-release.ps1
Getting intermittent hangs during the health-check - check if it is due to logging, or another issue.
> chore(ci): Remove health-check output logging on Windows build

- CHANGES_CURRENT.md
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/ReveryKeyConverter.re
- src/Feature/MenuBar/NativeMenu.re
- src/Input/Handler.re
- src/editor-input/EditorInput.rei
- src/editor-input/KeyPress.re
- src/editor-input/Matcher_internal.re
- src/editor-input/Matcher_lexer.mll
- src/editor-input/Modifiers.re
- test/Input/KeybindingsTests.re
__Issue:__ As described in #2963 - Onivim was not handling the `M-` modifier correctly (according to the Vim docs, it should be handled like `A-`).
__Defect:__ We weren't parsing the `M-` modifier. In addition, the `meta` modifier used internally was ambiguous - the challenge is that `meta` means different things in the 'Vim' vs the 'Code' world - in Vim, it's used like `A-`, whereas in Code, it's used to reference the _super_ key in Linux.
__Fix:__ Handle the `M-` modifier in the same way as the `A-` modifier. Update references from `meta` to `super` to disambiguate.
> fix(input/#2963): Fix 'm-' modifier behavior

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/MenuBar/NativeMenu.re
- test.esy.lock/index.json
__Issue:__ Some shortcut keys (shortcuts used by the native-menu introduced in #2969 ) would be triggered twice. This is problematic, because some of the commands have 'toggle' behavior - and if they are engaged twice, it would produce a toggle-untoggle sequence.
__Defect:__ When a shortcut key used by the menu is triggered, we'd receive two callbacks - one for the menu item itself, and one from our input handling infrastructure. 
__Fix:__ In Revery, add a hook to know whether the menu item was triggered via a keypress or by some other gesture: https://github.com/revery-ui/revery/pull/1044 If the menu item was triggered via a keypress, ignore the menu event, and let the input handling infrastructure take care of executing the command.
> fix(osx): Don't trigger menu command if from key press

- CHANGES_CURRENT.md
- src/Components/Label.re
- src/Exthost/Command.re
- src/Exthost/Exthost.rei
- src/Feature/LanguageSupport/CodeLens.re
- src/Service/Exthost/Service_Exthost.re
- src/Store/ExtensionClient.re
- test/Exthost/LanguageFeaturesTest.re
- test/Feature/Editor/EditorTests.re
__Issue:__ Some extensions have codelenses that fail to display in Onivim
__Defect:__ Some extensions will pass a command without an `id` - our parsing logic assumed that an `id` would always be present, and thus, those codelens would fail to decode and not be shown. In addition, some extensions will use labelled icons like `${ellipsis}` in codelens, which we weren't handling.
__Fix:__ 
1) Update our `Command` model to reflect the optional id
2) Use the `Label` renderer for codelens
> fix(exthost): Fix some command / codelens parsing failures

- CHANGES_CURRENT.md
- node/package.json
- node/yarn.lock
- test/Exthost/HttpRequestTest.re
- test/collateral/extensions/oni-http-request/extension.js
- test/collateral/extensions/oni-http-request/package.json
__Issue:__ The terraform extension was failing with an error:
> Error: Activating 'hashicorp terraform' failed: The "listener" argument must be of type function. Received an instance of Object
__Defect:__ The extension was crashing here:
```
https.request(url, options, res => {
if (res.statusCode === 301 || res.statusCode === 302) { // follow redirects
return resolve(httpsRequest(res.headers.location, options, encoding));
}
```
when trying to resolve download locations for terraform releases. This was not specific to this plugin, but actually could crash in any 3-param call to `https.request`. (There are two overloads - a `https.request(options, cb)`, and `https.request(url, options.cb)`.
Because of the `agent-base` dependency that is brought in the node environment, it overwrites the …
> fix(extensions/#2981): Listener function error with 3-param https request call

- docs/docs/for-developers/building.md
The first step on [Building from Source](https://onivim.github.io/docs/for-developers/building) should be cloning the repo and cd'ing into it. 
I had my friend asking me where can they get `install-node-deps.js` from. If we were to clone repo firstly, cd into it, all the following commands in the instructions work out of the box.
Removing clone from down the line, moving it as one of the top steps.
> docs(building): reorder instruction

- CHANGES_CURRENT.md
- extensions/php/package.json
- integration_test/SyntaxHighlightPhpTest.re
- integration_test/dune
- integration_test/test-syntax.php
- src/Core/ThemeToken.re
__Issue:__ PHP syntax highlights are no longer showing by default
__Defect:__ https://github.com/onivim/oni2/pull/2889 upgraded the extensions, but the PHP extension has a new dependency on `embeddedLanguages`, which our current textmate implementation does not handle correctly
__Fix:__ Remove the `embeddedLanguages` for now - add a regression / canary test to ensure we don't break this in the future.
Fixes #2985 
Tracking `embeddedLanguage` support in #2998
> fix(syntax/#2985): PHP syntax highlights not showing

- CHANGES_CURRENT.md
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/Features.re
__Issue:__ Diagnostics weren't displaying in the elm extension
__Defect:__ Diagnostics are computed on save, but we weren't sending the appropriate event to the extension host to let it know when a save occurred.
__Fix:__ Notify extension host on save
With that, we get diagnostics:
Fixes #2640 
Related #1058
> fix(extension/#2640): Elm - Fix diagnostic display

- src/Feature/LanguageSupport/Feature_LanguageSupport.re
Missed wiring up configuration defaults in #2990
> fix(signature-help): Fix warning for 'editor.parameterHints.enabled' default

- src/Service/Extensions/Sub.re
With the current implementation, subsequent subquery was prepending the
results to the previous results while we should be appending and thus
keeping the sought match at the top
Previously:
New:
> fix(extensions/#2979): fix order of extensions

- CHANGES_CURRENT.md
- src/Exthost/Msg.re
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
__Issue:__ The codelens feature for the [VersionLens](https://open-vsx.org/extension/pflannery/vscode-versionlens) plugin wasn't showing up until the editor is scrolled.
__Defect:__ Some extensions, like VersionLens will change codelens on the fly, or via a command, and they would message that to the editor via the exthost `$emitCodeLens` event. We weren't handling this event, so we didn't know to refresh the codelens.
__Fix:__ Handle the `$emitCodeLens` event, wire up to the provider / subscription via an `eventTick` property - always  refresh the subscription when that property changes.
This fix enables the VersionLens plugin:
Related #1058
> fix(codelens): Handle $emitCodeLens event

- CHANGES_CURRENT.md
- src/Feature/Editor/EditorDiffMarkers.re
- src/Feature/Editor/EditorDiffMarkers.rei
- test/Feature/Editor/EditorDiffMarkersTest.re
- test/OniUnitTestRunner.re
- test/OniUnitTestRunnerUI.re
- test/UI/TestFramework.re
- test/UI/dune
- test/dune
__Issue:__ Encountered a crash with the callstack:
```
(Invalid_argument "index out of bounds"):
Raised by primitive operation at file "src/Feature/Editor/EditorDiffMarkers.re", line 126, characters 10-29
Called from file "src/Feature/Editor/Draw.re", line 55, characters 4-59
Called from file "option.ml" (inlined), line 26, characters 32-35
Called from file "src/Feature/Editor/GutterView.re", line 139, characters 2-243
Called from file "src/Feature/Editor/GutterView.re", line 192, characters 4-232
Called from file "src/UI/Overflow.re", line 33, characters 2-5
Called from file "src/UI/CanvasNode.re", line 31, characters 6-110
Called from file "list.ml", line 110, characters 12-15
Called from file "src/UI/Overflow.re", line 33, characters 2-5
Called from file "list.ml", line 110, characters …
```
> fix(scm): Index out of bounds when rendering EditorDiffMarkers

- CHANGES_CURRENT.md
- src/Exthost/ExtensionActivationError.re
- src/Exthost/ExtensionId.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Feature/Extensions/Model.re
__Issue:__ When an extension has a required dependency that is not installed, Onivim would fail to activate the extension silently.
__Defect:__ Onivim was not properly handling the extension activation error - usually, it's a `string`, but in the case of a missing dependency, it is a JSON object - the parser was only handling the string case.
__Fix:__ Implement a decoder to handle either case. Bubble up the activation error to the user.
Related #2676 
Related #1058
> fix(extension/#2676): Part 1 - Fix error message with missing extension dependency

- CHANGES_CURRENT.md
- src/Exthost/CodeLens.re
- src/Exthost/Exthost.rei
- src/Exthost/Request.re
- src/Exthost/SignatureHelp.re
- src/Exthost/SuggestResult.re
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- test/Exthost/LanguageFeaturesTest.re
__Issue:__ There is a memory leak in our completion items, signature help, and codelens via the extension host - may be responsible for the `SIGABRT` described in #3009 (as this can occur when the JS heap is out of memory).
__Defect:__ The extension host adds a layer on top of the language server protocol, to serve as a cache for several language features - this helps performance when resolving items. However, this caching layer relies on the client to notify it when the items are no longer in use, so they can be cleaned up. Onivim was missing this `release` step.
__Fix:__ Bake in the call to `release` in all the relevant subscriptions. This involves picking up the `cacheId` which wasn't wired up in some places (like codelens), setting up the `release*` API, and passing it back on …
> fix(exthost/#3009): Call '$release*' APIs to clean-up extension host cache

- CHANGES_CURRENT.md
- src/Exthost/Extension/InitData.re
__Issue:__ The Ionide.Ionide-fsharp extension depends on `ms-dotnettools.csharp`, which isn't available on open-vsx
__Fix:__ The best-case fix would be to have the ionide-fsharp extension published to open-vsx and have proper dependencies. In the meantime, add a temporary override to map `ms-dotnettols.csharp` -> `muhammad-sammy.csharp` to unblock the extension.
With this change - basic language features work:
Fixes #2974 
Related #1058
> fix(extensions/#2974): Add extension override for Ionide.Ionide-fsharp

- CHANGES_CURRENT.md
- integration_test/RegressionCommandLineNoCompletionTest.re
- integration_test/VimIncsearchScrollTest.re
- integration_test/VimlRemapCmdlineTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Feature/Editor/Editor.re
- src/Model/ModeManager.re
- src/Service/Vim/Service_Vim.re
- src/Store/VimStoreConnector.re
- src/reason-libvim/CommandLine.re
- src/reason-libvim/Mode.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- test/reason-libvim/CommandLineTest.re
__Issue:__ There were a couple related issues with the cursor in command-line mode:
1) When exiting command-line mode, the cursor could 'flash' at the top of the file
2) When running a search command, the viewport would not scroll to the first match
__Defect:__ Both issues stem from the fact that Onivim was ignoring editor-cursor-position changes during search. 
For the first issue, when exiting command-line mode, there would be a brief transitional state where the editor is focused in CommandLine mode, but no cursor would be available - so it would be rendered at the default (0,0) position. This would be rectified once the mode transition completed and the cursor position is reset. 
For the second issue, `libvim` was properly updating the cursor position when searching, but that cursor …
> fix(vim/#2968): Cursor management in command-line mode

- CHANGES_CURRENT.md
- src/Store/VimStoreConnector.re
__Issue:__ For command-line completion, when trying to complete a setting like `:set nosmoothscroll`, the completions don't account for the `no`:
...which is jarring, and confusing.
__Fix:__ Add a special case - when the commands are negated, prefix them with `no`, and use our existing completion machinery:
> fix(vim): Command line completion - ':set no' does not complete as expected

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
__Issue:__ On OSX, with high key repeat set (via this stackoverflow post: https://apple.stackexchange.com/questions/10467/how-to-increase-keyboard-key-repeat-rate-on-os-x) - the 'smooth scroll' exhibits some rubber-banding at the edges.
__Defect:__ When a high-key repeat is set, the input actually takes priority, and is starving the animation - so we get the cursor moving, but the smooth-scroll isn't keeping up. This can cause a bounce or rubber-banding, depending on when the animation gets executed.
__Fix:__ There was an existing strategy to mitigate this - when the jump is small, don't bother animating. This works well for holding down the `j`/`k` keys. However, there was a bug in our strategy - the delta was calculated based on the animated scroll position, and because it was …
> fix(editor): Rubber-banding while scrolling w/ high key repeat

- CHANGES_CURRENT.md
- src/Core/Mode.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Scrollbar.re
- src/Feature/LanguageSupport/DocumentHighlights.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Outmsg.re
- src/Model/ModeManager.re
- src/Store/Features.re
- src/editor-core-types/BytePosition.re
- src/editor-core-types/BytePosition.rei
- src/editor-core-types/ByteRange.re
- src/editor-core-types/ByteRange.rei
- src/reason-libvim/Mode.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- test/reason-libvim/ModeTest.re
- test/reason-libvim/MultiCursorTest.re
WIP for snippet support - Part 1 implemented a snippet parser in #2817 . This implements a handler for 'multi-select' - a way to propagate changes across placeholders in a snippet.
__TODO:__
This is laying the ground-work for the placeholder selection - allowing multiple 'selection' ranges to be edited at once:
> feat(snippets): Part 2 - Implement multi-select handler

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Core/Constants.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorConfiguration.re
- src/Feature/Editor/EditorLayout.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Scrollbar.re
- test/Feature/Editor/EditorTests.re
This adds two configuration settings:
- `editor.scrollbar.verticalScrollbarSize`
- `editor.scrollbar.horizontalScrollbarSize`
which allow for adjusting the scrollbar sizes on the editor surface:
Fixes #3036
> fix(editor/#3036): Customizable vertical/horizontal scrollbar size

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
- src/Feature/Snippets/Snippet.re
- src/Store/Features.re
This implements the initial tab-stop / cursor placement when inserting a snippet
__TODO:__
- Add test case for indentation settings
- Implement variable expansion
- Implement snippet session lifecycle + visualization
- Implement jumping between placeholders w/ tab + shift+tab
- Implement loading snippets from extensions
- Implement loading snippets from user repository
- Add documentation
> feat(snippets): Initial cursor / placeholder positioning

- CHANGES_CURRENT.md
- src/Feature/Snippets/Snippet.re
The `/t` character for snippets needs to be normalized to match the indentation settings of the current buffer - this impements that functionality and adds a basic test.
> feat(snippets): Implement whitespace normalization

- CHANGES_CURRENT.md
- bench/lib/EditorSurfaceBench.re
- src/Core/Mode.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/SnippetVisualizer.re
- src/Feature/Editor/SurfaceView.re
- src/Feature/Editor/dune
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
- src/Feature/Snippets/Snippet.re
- src/Feature/Theme/GlobalColors.re
- src/Model/ContextKeys.re
- src/Model/ModeManager.re
- src/Model/State.re
- src/Store/Features.re
- src/UI/EditorView.re
- test/editor-input/MatcherTest.re
This is the next step in implementing snippets - maintaining the lifecycle of the snippet (whether it is active), showing a visualization / pseudo-mode when it is active, and allowing jumping back-and-forth between placeholders - for a simple snippet like: `let ${1:name} = (${2:args}) => $0;`:
Still not _quite_ ready for prime-time yet, since we need to synchronize the placeholders when they are changed (in my demo - I typed out replacements that are the same length)- but getting closer.
- Implement variable expansion
- Implement synchronization of placeholders when text changes
- Implement loading snippets from extensions
- Implement loading snippets from user repository
- Add documentation
> feat(snippets): Initial session / lifecycle management

- CHANGES_CURRENT.md
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Snippet.re
This implements placeholder synchronization, such that the snippet model is updated to reflect the current line state when shifting placeholders via `tab` or `shift`+`tab`. This enables handling of more intricate snippets:
- Integrate extension-provided snippets
- Integrate user-provided snippets
- Add documentation
> feat(snippets): Implement placeholder sync

- src/Feature/Search/Feature_Search.re
- src/Feature/Search/Feature_Search.rei
- src/Model/State.re
__Issue:__ There is a warning in the log:
```
[WARN]  [ 9.443s] Oni2.Core.Config : Missing default value for `search.exclude`
```
__Fix:__ Wire up the configuration specs for `Feature_Search` to pick up default values
> fix(search): Add configuration defaults

- CHANGES_CURRENT.md
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/Feature/Input/InputStateMachine.re
- src/Store/KeyBindingsStoreConnector.re
- src/editor-input/EditorInput.rei
- src/editor-input/Matcher.re
- src/reason-libvim/Mapping.re
- src/reason-libvim/Vim.rei
- test/reason-libvim/MappingTest.re
__Issue:__ In #3049 , the `:map <Enter> o<Esc>` was being utilized even in command-line mode.
__Defect:__ `:map` should only impact normal/visual/select/operator-pending modes, and not impact insert/command-line modes.
__Fix:__ Correct the condition for the `:map` command. In addition, while looking through the logs, I realized we were missing trace logging of keybindings, so implement that as well.
Fixes #3049
> fix(input/#3049): Fix :map condition

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/Snippets/Feature_Snippets.re
- src/Store/Features.re
- src/Store/StoreThread.re
- src/reason-libvim/Mode.re
- src/reason-libvim/Vim.rei
This PR fixes some bugs with snippets integrating with language features (notably completion and document highlights).
First, when entering a snippet, the language features wouldn't be aware we've transitioned to insert/select mode, so need to notify that feature.
Second, in `select` mode, we'd render document highlights, which would be jarring as additional highlights come in around the selection.
> fix(snippets): Update completion to be aware of active snippets

- CHANGES_CURRENT.md
- integration_test/ClipboardInsertModePasteEmptyTest.re
- integration_test/Regression3084CommandLoopTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- integration_test/lib/Types.re
- src/Feature/Workspace/Feature_Workspace.re
- src/Model/Actions.re
- src/Model/GlobalCommands.re
- src/Store/CommandStoreConnector.re
- src/Store/ExtensionClient.re
- src/Store/Features.re
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
__Issue:__ #3055 introduced a regression, in the course of refactoring the `CommandInvoked` and `KeybindingInvoked` to a consolidated action, causing an infinite loop of action dispatches.
__Defect:__ Prior to the refactoring, the `KeybindingInvoked` would itself dispatch a `CommandInvoked`. After the refactoring, there were cases, hit in #3055 , where a `CommandInvoked` would itself dispatch a `CommandInvoked`, endlessly. The easiest repro is to bind a key to a command - the command would get endlessly dispatched.
__Fix:__ Remove the infinite loop and bring back the `KeybindingInvoked` action. There's a subtle difference at the moment between how these commands are treated. Add an integration test to exercise the case in #3084 
Fixes #3084 , brings back the work in #3055
> fix(input/#3084): Input loop when executing command

- CHANGES_CURRENT.md
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
- src/Feature/Snippets/dune
- src/Model/Actions.re
- src/Model/Quickmenu.re
- src/Service/Snippets/Service_Snippets.re
- src/Service/Snippets/Service_Snippets.rei
- src/Store/Features.re
- src/Store/QuickmenuStoreConnector.re
This adds an `Insert Snippet` command to the command palette (and it can be also be bound to a keypress: `"editor.action.insertSnippet"`).
When the command is executed - a menu will open, showing the available snippets for the current filetype:
> feat(snippets): Insert snippet command

- CHANGES_CURRENT.md
- src/reason-libvim/Vim.re
- test/reason-libvim/MultiCursorTest.re
__Issue:__ Auto-closing pairs weren't handled correctly in snippets, when multiple placeholders are on the same line:
__Defect:__ This is actually a bug with our 'multiple-insert-mode-cursor' support. There is a primary cursor, along with zero or more secondary cursors. The secondary cursors get sorted in descending order by position, so changes to those don't impact other cursors. However, the primary cursor needs to 'push' the secondary cursors if the position changes - it's often before all the other cursors.
The byte delta to adjust subsequent cursor positions was based on the delta in the primary cursor position. This isn't adequate, though, as in the case of auto-closing pairs - `(|)`, the cursor only moves _one_ character but _two_ characters are inserted. Therefore, we need to …
> fix(snippets): Fix auto-closing pairs failing when placeholders are on same line

- CHANGES_CURRENT.md
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Service/OS/Service_OS.re
Some additional logging to help narrow down #3092
> refactor(os/#3092): Add additional logging along readdir/node expansion path

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- integration_test/VimRemapTimeoutTest.re
- integration_test/dune
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/Model/Actions.re
- src/Store/Features.re
- src/Store/InputStoreConnector.re
- src/Store/StoreThread.re
- src/editor-input/EditorInput.re
- src/editor-input/EditorInput.rei
- test/editor-input/InputTest.re
__Issue:__ By default, in Vim, when there is a mapping like: <kbd>j</kbd><kbd>k</kbd> -> <kbd>esc</kbd>, if just <kbd>j</kbd> is pressed, there is a timeout - after 1 second, the <kbd>j</kbd> would be executed as if typed (or, if there was a smaller mapping from <kbd>j</kbd>, that would be executed). Onivim didn't support this.
__Fix:__ Add `vim.timeout` configuration, as well as support for `:set timeout` and `:set timeoutlen` configuration. 
After a key gesture is completed, and there is a potential pending mapping, start a timer. If that timer is hit, flush any pending input.
Fixes #2850
> fix(input/#2850): Add 'timeout' for remapped keys

- src/Feature/Input/Feature_Input.re
Related to #3102 - fix a bug where the default timeout is interpreted as `0.001` seconds instead of `1` second
> fix(input): Fix incorrect default input timeout

- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/InitData.re
- test/Exthost/WebviewTest.re
- test/collateral/extensions/oni-webview/extension.js
- test/collateral/extensions/oni-webview/package.json
__Issue:__ The latest `golang.go` extension fails to activate in Onivim, with this error:
```
Error activating extension: golang.go: Activating extension 'golang.go' failed: Cannot read property 'replace' of undefined.
```
__Defect:__ The latest extension creates a 'welcome' webview on startup. As part of that webview, it resolves some local file paths using the [`webview.asWebviewUri`](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content) API. We're not sending some data that the API expects (it uses a seed `webviewResourceRoot`, and runs `replace` on the string) and because this isn't provided, the extension host crashes running `replace` on a `null` string
__Fix:__ Even though Onivim doesn't currently support rendering webviews provided by extensions, Onivim …
> fix(extension/#3099): golang.go activation error

- manual_test/cases.md
- src/Store/Features.re
__Issue:__ The menu-bar items are (mostly) not executing when clicked.
__Defect:__ In #3084 , part of #3055 was reverted - a refactoring of consolidating the `CommandInvoked` and `KeybindingInvoked` actions. However, one spot was missed, causing it not to trigger correctly (in the effect handler of `Feature_Menubar`
__Fix:__ Revert the change in the `executeCommandEffect`, used by `Feature_MenuBar`, as well.
__Todo:__
> fix(menubar/#3108): Fix command invocation from menu items

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorBuffer.re
- src/Feature/Editor/EditorBuffer.rei
- src/Model/SnippetVariables.re
- src/editor-core-types/ByteRange.re
- src/editor-core-types/ByteRange.rei
- test/Feature/Editor/EditorTests.re
This adds support for the `$TM_SELECTED_TEXT` snippet variable, which was missing previously
> fix(snippets): Implement TM_SELECTED_TEXT snippet variable

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/SignatureHelp.re
- src/editor-core-types/CharacterPosition.re
- src/editor-core-types/CharacterPosition.rei
__Issue:__ When signature help is opened in a snippet, the signature-help popup can stay open as placeholders are being traversed:
(after pressing `tab` to move to the final placeholder on the next line, the signature help pop-up stays open and follows the cursor)
__Defect:__ The signature help feature doesn't know that the cursor has changed position, and doesn't have logic to clear if the position is not correct.
__Fix:__ Add a `cursorMoved` function, like for completion - if the cursor moves across a line, or more than a character, expire the current signature help session.
> fix(signature-help): Signature help staying open across snippet placeholders

- CHANGES_CURRENT.md
- manual_test/cases.md
- node/download.js
- node/package.json
- node/yarn.lock
__Issue:__ Reported on Discord - `redhat.java` extension was all of a sudden failing to install.
__Defect:__ Onivim uses the [`follow-redirects`](https://www.npmjs.com/package/follow-redirects) library to handle `302` redirects. The URL `https://open-vsx.org/api/redhat/java/0.74.0/file/redhat.java-0.74.0.vsix` actually gets redirected. `follow-redirects` has a default limit of 10MB for downloads, otherwise it will fail.
__Fix:__ Increase size limit to accommodate extensions on open-vsx, so that the download will complete.
- The download speed using `follow-redirects` seems to be slow. Hopefully, we can switch to @zbaylin 's libcurl work eventually: https://github.com/zbaylin/ocurl-luv-test
> fix(extensions): Large VSIX extensions are failing to install

- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionItem.re
__Issue:__ When multiple completion items with the same label show up, we were filtering out all but one - first, preferring items from a `requestCompletionItems` call (vs keywords, and now snippets), and then picking the one that most closely matched the sort text.
This had a couple of issues, though:
- With snippets, now, there are often cases where Onivim should show both the snippet and a completion item
- In #3032, there were cases where multiple `createContext` completions should be available (and would have different auto-import behavior).
__Fix:__ Update the de-dup behavior in #2581 to _only_ de-dup keywords
Fixes #3032
> fix(completion/#3032): Only de-dup keyword completion items

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/SignatureHelp.re
__Issue:__ In insert mode, pressing `Shift+escape` should close both the signature help and suggest pop-ups, without switching to normal mode. However, this only worked for signature help.
__Fix:__ Implement a common command to close both these, and bind to `Shift+Escape`
Fixes #3120
> fix(language-support): Implement shift+escape to close all language support popups

- CHANGES_CURRENT.md
- src/Feature/Editor/SnippetVisualizer.re
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
__Issue:__ When a snippet session is active, all visible splits would show the snippet visualizer UI.
__Fix:__ Only show the snippet visualizer for the active editor.
> fix(snippet): Only show highlight for active editor

- CHANGES_CURRENT.md
- src/Feature/Snippets/ResolvedSnippet.re
Choice items in snippets aren't fully supported yet, but in the meantime, we should still gracefully handle these by converting them to placeholders.
Discovered this in testing out the [Markdown Snippets](https://open-vsx.org/extension/robole/markdown-snippets) extension - some of the task snippets like this would fail:
```
"Insert task list": {
"prefix": "task",
"body": ["- [${1| ,x|}] ${2:text}", "${0}"],
"description": "Insert task list"
},
```
However, after this fix, they work (with the choice treated as a placeholder):
> fix(snippet): Convert choices to placeholders

- CHANGES_CURRENT.md
- src/Core/Snippet/Snippet.re
- src/Core/Snippet/Snippet_parser.mly
__Issue:__ In testing snippet extensions, a particular snippet was failing to expand for the [React - JavaScript snippets extension](https://open-vsx.org/extension/tomi/xajssnippets) - the `_mu` snippet.
__Defect:__ There is a string in that snippet of `${ value }` - we were trying to parse that as a placeholder or variable, but it was failing. It should actually be a text value.
__Fix:__ Add a case in the snippet parser to handle falling back if the placeholder-like item cannot be reoslved.
> fix(snippet): Fix special-case of parsing text if not placeholder or variable

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
__Issue:__ When scrolling to the bottom of a large file, the minimap does not scroll alongside the cursor
__Defect:__ Onivim wasn't synchronizing the `minimapScrollY` with the current scroll in some cases
__Fix:__
- Refactor the minimap-scroll-synchronization to a helper function
- Call into the scroll synchronization in the missed code paths
> fix(editor): Minimap out of sync when scrolling large files

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Feature/Editor/EditorConfiguration.re
__Issue:__ Both Vim & VSCode default to having word-wrap (soft wrap) enabled, but Onivim defaults to having it off. There isn't a reason to be different from both of their default settings.
__Fix:__ Change word-wrap (soft wrap) to be on by default.
Fixes #3149
> fix(editor/#3149): Change word wrap configuration default to be on

- CHANGES_CURRENT.md
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Feature/Editor/EditorConfiguration.re
- src/Model/VimContext.re
This moves the `editor.autoClosingBrackets` configuration option to the new configuration model. 
Functionally, this should behave the same - although it now supports filetype-specific settings, which wasn't working correctly in the old model, like:
```
"[json]": {
"editor.autoClosingBrackets": "never"
}
```
> refactor(configuration): Move auto-closing pairs to new configuration model

- CHANGES_CURRENT.md
- manual_test/cases.md
- src/oni2-keyboard-layout/stubs/keyboard-layout-windows.c
__Issue:__ On Windows, pressing a dead key (like <kbd>'</kbd>) twice would not emit any output. Curiously, composing works correctly (<kbd>'</kbd> + <kbd>a</kbd> -> `á`), and a dead character + space worked correctly too.
__Defect:__ In our keyboard-layout helper, we were calling `ToUnicodeEx`, which, confusingly, is actually side-effectful - it can change the state of the keyboard, in particular dead keys: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicodeex#parameters
__Fix:__ There is a new flag introduced in Win10 >1607 that causes that particular API call to  not change the keyboard state. With that fix, the dead keys behave as expected.
Fixes #3157
> fix(windows/#3157): Dead key fix

- CHANGES_CURRENT.md
- src/Feature/Explorer/Feature_Explorer.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
__Issue:__ If the user `:cd`'s into the same directory that is currently open in the explorer... the explorer disappears.
__Defect:__ The explorer path gets updated to a new folder, but it is set to the 'initial' state... and the subscription that manages loading the contents is keyed to the path, so it would not trigger a refresh in this case.
__Fix:__ If the new path is the same as the previous, don't reset the file explorer to the initial state.
> fix(explorer): Fix explorer disappearing when cd'ing into current directory

- CHANGES_CURRENT.md
- src/Feature/AutoUpdate/Feature_AutoUpdate.re
- src/bin_editor/Oni2_editor.re
- src/gen_buildinfo/generator.re
__Issue:__ The auto-update supports multiple update channels:
- `master` (nightly)
- `stable` 
- `staging`
The intention was that it should default to the update channel matching the build - nightly builds should default to nightly auto-updates, etc. However, this wasn't working as intended - the default was always set to `master`.
__Defect:__ The way our build script was checking the default update channel wasn't working correctly during CI builds - it would always select `"master"`.
__Fix:__ Use the version suffix to determine which update channel to use as the default
> fix(auto-update): Use update channel based on source build

- CHANGES_CURRENT.md
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Workspace/Feature_Workspace.re
- src/Feature/Workspace/Feature_Workspace.rei
- src/Store/Features.re
This fixes a couple of issues with the explorer:
1) When switching directories, the explorer could 'shrink' and only show a single row
2) When switching directories, focus would move to the explorer
> fix(explorer): Fix explorer shrinking when switching directories

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Store/Features.re
__Issue:__ As described in #3191 - pressing <kbd>enter</kbd> on a line after jumping over closing pairs could cause an errant completion to remove the closing pairs.
__Defect:__ The primary bug is that, after pressing the closing pair, completion remains open at the previous 'meet' - it should be closed after pressing the closing pair, which is a non-word character. The `cursorMoved` logic used an unreliable heuristic for deciding if the current completion meet should be kept, which failed in this case .
__Fix:__ Run the 'refine' logic, which updates the completion meet position + runs fuzzy matching on any matches, when the cursor moves. This requires a little bit of extra plumbing - bringing the current `LanguageConfiguration` as `refine` depends on it. Finally, remove the previous …
> fix(completion/#3191): Refine completions when cursor is moved w/o buffer update

- CHANGES_CURRENT.md
- src/Feature/Pane/Feature_Pane.re
__Issue:__ For some themes that have a transparent status bar color, the bottom pane tabs can peak through underneath:
__Defect:__ Onivim is always rendering the pane view, even when closed
__Fix:__ Don't render the pane when closed
> fix(ux): Transparent status bar shows pane tabs underneath

- CHANGES_CURRENT.md
- src/CLI/Oni_CLI.re
- src/bin_launcher/Oni2.re
- test/Cli/IntegrationTest.re
Fixes #3209 - thanks for logging the issue @jerabaul !
Some CLI applications use `-v` to also specify `--verbose`, if paired with other arguments - a potential improvement to consider (right now, we don't have `--verbose` logging - just `--debug` and `--trace`)
> fix(cli/#3209): Add -v version flag

- CHANGES_CURRENT.md
- src/Feature/Input/Feature_Input.re
- src/Feature/Input/Feature_Input.rei
- src/Feature/Input/KeybindingsLoader.re
- src/Model/Actions.re
- src/Model/GlobalCommands.re
- src/Store/Features.re
While investigating #3206 - I observed that the 'Preferences: Open keybindings file' was failing to actually open the file.
This looks like a regression from https://github.com/onivim/oni2/pull/3188 , which inactivated the `OpenConfigFile` action. 
This fixes it by plumbing the command back in, via the `Feature_Input` command list.
> WORKAROUND: `oni2 ~/.config/oni2/keybindings.json` on OSX / Linux
> fix(keybindings): Fix 'Open keybindings file' command

- CHANGES_CURRENT.md
- src/Feature/Configuration/GlobalConfiguration.re
Small tweak to configuration options that take font sizes - like `"editor.fontSize"` and `"terminal.integrated.fontSize"` - allow string values, if they are able to be parsed to a number.
> fix(configuration): Allow string as font size

- CHANGES_CURRENT.md
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/Buffers/Feature_Buffers.rei
- src/Feature/Buffers/dune
- src/Feature/Quickmenu/Feature_Quickmenu.rei
- src/Feature/Quickmenu/MenuItem.re
- src/Feature/Quickmenu/Schema.re
- src/Feature/Quickmenu/View.re
- src/Model/Actions.re
- src/Model/Quickmenu.re
- src/Store/Features.re
- src/Store/QuickmenuStoreConnector.re
__Issue:__ When opening the select-filetype menu (for example, clicking the filetype in the statusbar) - if there is no workspace active, the menu will show available buffers instead of filetypes.
__Defect:__ Errant logic in the QuickmenuStoreConnector.
__Fix:__ Fix errant logic, take opportunity to migrate the file-type picker to the new quickmenu feature. Requires adding icon renderer to the new quickmenu feature.
> fix(buffers): Filetype picker not working correctly w/ no workspace

- CHANGES_CURRENT.md
- src/Core/ConfigurationTransformer.re
- src/Core/Utility/ListEx.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Formatting.re
- src/Feature/LanguageSupport/Outmsg.re
- src/Feature/LanguageSupport/dune
- src/Feature/Quickmenu/Feature_Quickmenu.rei
- src/Feature/Quickmenu/Schema.re
- src/Store/Features.re
__Issue:__ When formatting a JavaScript file, or other file without a formatter installed by default, and formatting (either via the 'Format Document' command, or key sequences like `gg=G`) - there'd be a confusing 'Invalid range specified' error.
__Defect:__ There were actually several issues:
1) When falling back to the default format provider, there was an off-by-one bug that caused that error to be displayed when the whole document was requested to be formatted.
2) In the case of #3014 , there actually is a default format provider - the type script language feature provides a formatter, but it is a range formatter (not a document formatter). However, in the case where there is a range formatter but no document formatter, we can fall back to using the range formatter.
3) The case of …
> fix(formatting/#3014): 'Invalid range specified' error

- CHANGES_CURRENT.md
- development_extensions/oni-dev-extension/extension.js
- integration_test/ExtHostWorkspaceSearchTest.re
- integration_test/dune
- src/Service/OS/Service_OS.re
- src/Service/OS/Service_OS.rei
- src/Store/ExtensionClient.re
__Issue:__ Some extensions that use the `vscode.workspace.findFiles` API wouldn't work as expected - like the [Live Server](https://open-vsx.org/extension/ritwickdey/LiveServer) extension.
__Defect:__ The `maxCount` argument wasn't being used by Onivim - so for a very large folder, we might not finish traversing for a while. In addition, the `readdir` call could fail, in which case no result would be returned at at all.
__Fix:__ Implement handling of `maxCount`, and short-circuit the find-in-files once the limit is reached. This fixes the first blocking issue for #3215
> fix(extensions/#3215): Part 1 - Implement max count parameter for findFiles API

- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Store/ExtensionClient.re
This fixes part 2 of #3215 - the live-server extension has an `await vscode.workspace.saveAll()` call, which Onivim was currently not handling - since this promise never returned, the extension would not start the session.
> fix(extensions/#3215): Part 2 - Implement 'vscode.workspace.saveAll' API

- CHANGES_CURRENT.md
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Pane/Feature_Pane.rei
This removes a potentially buggy animation when the notifications / references pane opens - the animation gets glitched because it is bouncing between a view-based (the pane) and a model-based (the layout) animations. A more robust approach would be to use a model-based animation for the pane, as well.
Fixes #3245
> fix(notifications/#3245): Remove glitchy animation

- CHANGES_CURRENT.md
- scripts/osx/notarize.sh
__Issue:__ The nightly builds were out-of-date, as the notarization step of the build process was failing
__Defect:__ There was a typo in our script that caused extraction of the notarization UUID to fail debugging on the output of the `xcrun altool` command
__Fix:__ Fix typo; add some more logging to assist in debugging future issues
> fix(ci): OSX - Notarization: Fix typo in awk usage

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/InlineElements.re
- src/Store/Features.re
__Issue:__ When editing in insert mode, codelens disappear from the current line when pressing enter.
__Defect:__ The `BufferUpdate.t` is including the current line in the update, which causes the codelens to refresh, even though the line isn't changed.
__Fix:__ Use the `MarkerUpdate.t` instead, which is more minimal and does not adjust markers for the originating line.
This is actually needed for #3246 as well, because one issue with that format-on-save implementation is that it causes all code lenses to be refreshed.
> fix(codelens): CodeLens disappear when pressing 'enter' in insert mode

- CHANGES_CURRENT.md
- src/Core/MarkerUpdate.re
- src/Core/MinimalUpdate.re
- src/Core/MinimalUpdate.rei
- src/Feature/Syntax/Feature_Syntax.re
In cases where there is a scoped buffer update, like a few lines, Onivim is smart enough to shift 'markers' (syntax highlighting, codelens in #3255 , search highlights).
However, there are some cases where we get a full update - the entire buffer contents is flagged as updated. A couple of these cases are:
- Running `:e!` to re-load the file from disk - this comes through as a refresh of the entire buffer
- Some format providers provide scoped updates (ie, line-by-line). Others, however, like `ocamllsp` just send the whole buffer contents.
The problem with processing the full update is that, today, those don't shift markers - we just clear out syntax highlighting, codelens, etc. This is a poor user experience, because it causes 'flashes' of syntax highlighting disappearing, or codelens …
> fix(formatting): Compute minimal updates for buffer updates / shifting

- CHANGES_CURRENT.md
- src/Feature/Quickmenu/Schema.re
This fixes issue with smart casing while filtering items in quickmenu (theme picker, formatter picker, snippets..).
> fix(quickmenu): Fix quick menu smart case

- src/Core/Buffer.re
- src/Core/Utility/ArrayEx.re
Processing full-buffer updates are expensive - we recompute syntax highlighting for the entire buffer, we recompute minimal updates in the case of formatting, and it requires a full sync with the extension host - all expensive operations!
In some cases, this is necessary - for example, reading new data from the file system might mean the entire buffer has changed. However, in some cases, Onivim is processing full updates when it is not strictly necessary (like 'undo').
This PR does a check to see if the full update actually changes the buffer, and if not, skips applying it.
> perf(buffers): Skip applying full updates if nothing changed

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Formatting.re
- src/Feature/LanguageSupport/dune
- src/Model/State.re
This adds a `Format Document` command and shortcut key, visible in the 'Edit' menu
> fix(formatting): Add 'Format Document' menu item

- CHANGES_CURRENT.md
- src/Exthost/Exthost.rei
- src/Exthost/Request.re
- src/Exthost/SuggestItem.re
- src/Exthost/SuggestResult.re
- src/Feature/LanguageSupport/CompletionItem.re
- src/Feature/LanguageSupport/CompletionProvider.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
__Issue:__ Some completions would add duplicate characters at the beginning, like the case in #2388
__Defect:__ The returned completion list from the extension host can send a default insert/replace range, which tells exactly what characters should be inserted or replaced from the completion. This can be sent per-item, or, to save bytes over the wire, a default can be sent for the list that should be used if it is not provided per-item. Onivim wasn't handling the default insert/replace range, which is provided in the case of #2388
__Fix:__ If a default insert/replace range is provided as part of the completion list, update completion items with that insert/replace range.
Fixes #2388
> fix(completion/#2388): Use the default insert range from the suggest item list

- CHANGES_CURRENT.md
- src/Service/Exthost/Service_Exthost.re
__Issue:__ When using TabNine (#2583), most completions are inserting an extra character at the beginning - this makes it much less useful.
__Defect:__ TabNine requires the latest buffer to give correct predictions and insert/replace ranges. There was a race condition where, when the user is typing a character, we could request completions at the _new_ character position before the buffer update reached the extension host - this would give us completions where the insert range is off, causing us to insert an extra when completing.
__Fix:__ Debouncing the completion sub is enough, because the buffer update effect is processed immediately after the first round of subscriptions. 
__Next steps:__ A better, more explicit fix would be to have the completion subscription take into account the …
> fix(completion/#2583): Fix race condition between completion subscription & buffer updates

- CHANGES_CURRENT.md
- bench/lib/BufferBench.re
- bench/lib/Helpers.re
- src/Core/BufferUpdate.re
- src/Core/BufferUpdate.rei
- src/Core/MarkerUpdate.re
- src/Core/MarkerUpdate.rei
- src/Feature/Editor/Editor.re
- src/Feature/LanguageSupport/Formatting.re
- src/Feature/Snippets/Feature_Snippets.re
- src/Service/Vim/Service_Vim.re
- src/Service/Vim/Service_Vim.rei
- src/Store/VimStoreConnector.re
- src/reason-libvim/Buffer.re
- src/reason-libvim/BufferInternal.re
- src/reason-libvim/BufferUpdate.re
- src/reason-libvim/BufferUpdateTracker.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- test/Core/BufferTests.re
- test/Feature/Editor/WrappingTests.re
- test/reason-libvim/AutoIndentTest.re
- test/reason-libvim/BufferTest.re
- test/reason-libvim/MacroTest.re
- test/reason-libvim/UndoTest.re
__Issue:__ When formatting a document, the cursor doesn't move to stay in sync with the current position.
__Fix:__ Adjust the cursor position when applying formatting edits to match the previous position.
> fix(formatting): Adjust cursor position based on formatting edits

- CHANGES_CURRENT.md
- src/Core/Snippet/Snippet.re
- src/Core/Snippet/Snippet_parser.mly
__Issue:__ The `@media` sass snippet failed to expand
__Defect:__ The parser for choice snippets would fail if certain characters were part of the choices (in the case of `@media` - the `:` character in the choice was causing the snippet parse to fail). The choice parser wasn't handling concatenation of multiple tokens, and the `:` character would make it through the lexer, but would cause multiple tokens to be produced, which wasn't handled by our parser rules.
__Fix:__ Fix the string parser to concatenate multiple tokens; add test case
> fix(snippets): Fix error parsing @media sass snippet

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Outmsg.re
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Service/Vim/Service_Vim.re
- src/Service/Vim/Service_Vim.rei
- src/Store/Features.re
- src/editor-core-types/CharacterIndex.re
- src/editor-core-types/CharacterIndex.rei
- src/editor-core-types/CharacterSpan.re
- src/editor-core-types/CharacterSpan.rei
__Issue:__ Some completion providers, like TabNine, will give a replace range past the cursor, as well.
For example, in the completion case (where `|` is the cursor)
`app.get('/|')`
Selecting a completion like `', (req, res) => {` would result in an extra `'` at the end of the completion.
__Defect:__ We weren't utilizing the 'end' part of the insert / replace range
__Fix:__ Use the end column of the insert/replace range to decide how many characters _after_ the cursor to delete.
Related #2583
> fix(completion/#2583): Handle replace range after cursor

- CHANGES_CURRENT.md
- src/Model/State.re
__Issue:__ When using `control+w` to delete a word in the quick open / command palette / command line, there would be a delay before the command is executed.
__Defect:__ The window commands were active in this context, and the input state machine was waiting for the next key in the binding.
__Fix:__ Update the window command condition to exclude the quick menu and vim command line.
Fixes #3262
> fix(quickmenu/#3262): Fix delay in processing control+w in quick menu / command line

- docs/docs/configuration/settings.md
> docs(font/#3266): Add default value for 'editor.fontSmoothing'

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionMeet.re
- src/Feature/LanguageSupport/CompletionMeet.rei
- test/Feature/LanguageSupport/CompletionMeetTests.re
__Issue:__ After opening a module (ie, `open Array`), functions that are now exposed, like `max` wouldn't show up in completion.
__Defect:__ When typing (ie, `m|`), the completion meet would be at position 0 - and querying the completions at position 0 for the rescript provider wouldn't return anything.
__Fix:__ In the case where a token is at the beginning of a line, or after a space, query after the first character - this gives better results and mimics the behavior of Code. In addition,  keep track of a separate `insertLocation` which built-in keywords and snippets can use to pick up the correct insertion range.
Fixes #3258
> fix(completion/#3258): Rescript identifiers not completing with opened module

- CHANGES_CURRENT.md
- src/Store/QuickmenuStoreConnector.re
__Issue:__ When using `Control+Tab`, closed editors / terminals can pop-up in the list, which is annoying
__Fix:__ Filter the buffer pickers to the set of visible buffers.
Fixes #2009
Fixes #3275 
Related to #3247 , but there are some additional fixes needed to prune the buffer list - properly handling `bdelete`, `bwipeout`, etc.
> fix(editors/#3275): Scope control+tab to visible editors

- CHANGES_CURRENT.md
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/LanguageSupport/DocumentSymbols.re
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Search/Feature_Search.re
This fixes a few issues called out in #2002 -
1) Pressing 'enter' on symbols in the symbol outline view did not focus them
2) Symbols were in reverse order
3) Nodes with children were not focusable - added <kbd>Space</kbd> as a key that focuses w/o expanding
Fixes #2002
> fix(symbols/#2002): Fix focusing symbol in outline via keyboard

- CHANGES_CURRENT.md
- src/Components/VimList/Component_VimList.re
__Issue:__ Pressing `control+d` or `control+u` in the explorer would scroll the viewport, but not move the cursor. 
__Fix:__ Move the cursor when scrolling, like `control+d`/`control+u` do in the editor surface.
> fix(vim): Fix control+d/control+u behavior in explorer

- CHANGES_CURRENT.md
- src/Feature/Notification/Feature_Notification.re
- src/Feature/Notification/Feature_Notification.rei
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Store/Features.re
__Issue:__ After using format-on-save for some time, the notifications get quite cluttered:
This isn't really adding an user value
__Fix:__ Add a concept of ephemeral notifications, which disappear once they show - so we still show format notifications, but don't save them in the notifications pane or add them into the notification count.
> fix(formatting): Ephemeral notifications

- CHANGES_CURRENT.md
- docs/docs/using-onivim/emmet.md
This adds a documentation entry, specifying how to use Emmet in JSX/TSX files.
First part of a fix for #3283
> fix(emmet/#3283): Part 1 - Add documentation on using emmet for JSX/TSX files

- CHANGES_CURRENT.md
- src/Feature/Diagnostics/Diagnostic.re
__Issue:__ There was a potential crash when deleting lines, after processing minimal updates
__Defect:__ After shifting the diagnostics, the diagnostic line could potentially be out of range (less than 0), and when the buffer line is looked up - an exception is thrown
__Fix:__ Clamp the diagnostic line to a valid range when expanding
> fix(diagnostics): Fix out-of-range index after processing minimal updates

- CHANGES_CURRENT.md
- src/Core/Indentation.re
__Issue:__ The default formatter - our fallback when there is no language provider - could crash on a negative indent level with a `Bytes.create` exception
__Fix:__ Clamp to indentation level of 0, add test case
> fix(formatting): Crash on trying to apply negative indentation level

- CHANGES_CURRENT.md
- src/Core/Json.re
- src/Core/Json.rei
- src/Core/LanguageConfiguration.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/LanguageConfiguration.re
- src/Exthost/Msg.re
- src/Exthost/dune
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
This is work on Part 2 of #3288 - this implements a parser for `$setLanguageConfiguration` and a model for the onEnterRules.
This doesn't fix the auto-indent behavior, yet - the remaining work is:
- Merge the `$setLanguageConfiguration` configuration with the extension metadata configuration
- Use the `onEnter` rules when adding new lines in insert mode (as well as `o`/`O`)
> fix(auto-indent/#3288): Implement $setLanguageConfiguration model + parser

- CHANGES_CURRENT.md
- src/Feature/Editor/Editor.re
- src/Feature/LanguageSupport/Formatting.re
- src/Service/Exthost/Service_Exthost.re
__Issue:__ There were certain formatting edits, as described in the first part of #3288 , that were not handled correctly by Onivim. This impacted the Python extension, as well as the `clangd` extension.
__Defect:__ When receiving formatting edits, if there was a trailing newline, it would be incorrectly removed - and the formatter would end up merging lines that shouldn't be merged.
__Fix:__ Preserve trailing newlines - fixes the first part of #3288
> fix(formatting/#3288) - Part 1: Fix format edits containing a trailing newline

- CHANGES_CURRENT.md
- src/Exthost/LanguageInfo.re
- src/Exthost/LanguageInfo.rei
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Model/Actions.re
- src/Model/SnippetVariables.re
- src/Model/State.re
- src/Model/VimContext.re
- src/Store/Features.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/Reducer.re
- src/Store/StoreThread.re
- src/Store/VimStoreConnector.re
- src/UI/EditorView.re
- src/UI/Root.re
- src/UI/SideBarView.re
- test/Exthost/LanguageInfoTest.re
This is some refactoring to move the language information state into `Feature_LanguageSupport`, so it can be merged with the information provided by the `$setLanguageConfiguration` in #3302 
Some prepatory work to wire up `onEnterAction`s for #3288
> refactor(auto-indent/#3288): Move languageInfo into Feature_LanguageSupport

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Components/Accordion/Component_Accordion.re
- src/Components/FileExplorer/Component_FileExplorer.rei
- src/Components/FileExplorer/FileTreeView.re
- src/Components/FileExplorer/View.re
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Explorer/Feature_Explorer.rei
- src/Feature/Pane/DiagnosticsPaneView.re
- src/Feature/Pane/Feature_Pane.re
- src/Feature/Pane/LocationsPaneView.re
- src/Feature/Search/Feature_Search.re
- src/Feature/Search/Feature_Search.rei
- src/UI/SideBarView.re
This brings back the `workbench.tree.indent` setting:
Fixes #3305
> fix(ux/#3305): Re-implement 'workbench.tree.indent' setting

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionItem.re
__Issue:__ A combination of #3279 and #3298 caused a regression in keyword / snippet completion.
In some cases, the keyword completion would work fine - but if there was a non-word trigger character in front, that character would be consumed by the insertion.
__Defect:__ In #3279 , an `insertLocation` was added to the meet. This `insertLocation` is used for positioning the insertion. In #3298, the keywords/ snippets bake in an insert range - but from the `meet.location` instead of `meet.insertLocation`. The `meet.location` is incorrect in the situation described above, so it causes an incorrect insertion position.
__Fix:__ Pass `meet.insertLocation` to the snippet / keyword providers.
> fix(completion): Keyword completion insertion is off-by-one in some cases

- CHANGES_CURRENT.md
- src/Core/Snippet/Snippet.re
- src/Core/Snippet/Snippet_parser.mly
__Issue:__ When testing the `clangd` extension, I observed some snippet parse failures for some completions:
__Defect:__ The `,` character wasn't being parsed correctly, and wasn't treated as valid text
__Fix:__ Allow commas in placeholder / text blocks; add test case
> fix(snippets): Parse error with sprintf snippet

- CHANGES_CURRENT.md
- src/Feature/Search/Feature_Search.re
- src/Feature/Search/Feature_Search.rei
- src/Store/Features.re
This PR augments the functionality of the existing search hot key (Control+Shift+F/Command+Shift+F) - if there is a selection in the active editor, seed the input component and start a search with it.
Related #3277
> fix(search/#3277): Search selected text

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionItemScorer.re
With the work done in #3298 (and #range , it's now easier to adjust the sort / scoring algorithm to fix issues like #3136 .
This PR implements case-insensitive completion filtering, ie for golang:
and other languages:
The scoring function allows inexact matches, but penalizes the score when the case doesn't match. This gets closer to parity with VSCode's matching, although there are some nice-to-haves that aren't implemented in Onivim yet - inexact matches and misspelling/typo resiliency. Incorporating edit distance into the scoring algorithm could help improve even further, as a next step. 
Fixes #3136
> fix(completion/#3136): Case-insensitive completion filtering

- CHANGES_CURRENT.md
- src/Core/Ripgrep.re
- src/Core/Utility/LuvEx.re
- src/Exthost/Transport/Exthost_Transport.re
- src/Exthost/Transport/dune
__Issue:__ We use `libuv` (via `luv`) to communicate with the extension host, syntax highlighting, and ripgrep. 
For each 'read' from the process pipe - we are allocating a large buffer (~65k bytes), and the reads can be quite high frequency, especially in the case of the extension host when there are several highlights / completion providers / codelens providers, etc.
__Fix:__ The `luv` API allows re-use of the allocated buffer - we can leverage that, as the buffer is used ephemerally anyway and copied to bytes when used. We can avoid extra allocations by writing into the same buffer as opposed to allocating a new one for every read.
> perf(luv): Re-use allocated buffer when possible

- CHANGES_CURRENT.md
- src/Core/Glob.re
- src/Core/Glob.rei
- src/Core/Oni_Core.re
- src/Core/Utility/StringEx.re
- src/Exthost/DocumentFilter.re
- src/Exthost/DocumentSelector.re
__Issue:__  I wanted to test the state of #2380 w/ the latest exthost fixes - and I found when opening a Haskell project (ie, `oni2 my-haskell-project`), and then opening a Haskell file at the root, no language integration is provided. Curiously, Haskell files in sub-folders would get language integrations:
(The [haskell extension from Open-VSX](https://open-vsx.org/extension/haskell/haskell) is required)
This seems to also impact elixir files - they had the exact same issue - files at the root of the project did not get language integration, but files in subfolders did.
__Defect:__ The glob module we were leveraging was treating double-asterisks as a required folders - so, for example, `/my-haskell-project/**/*.hs` would match `/my-haskell-project/src/some-file.hs` but NOT …
> fix(exthost/#2380): Haskell files at root do not get language integration

- CHANGES_CURRENT.md
- src/Core/MarkerUpdate.re
- src/Core/Utility/StringEx.re
__Issue:__ A crash can potentially occur when manipulating some Unicode characters
__Defect:__ The root exception is `Zed_utf8.Invalid("at position 8: invalid start of UTF-8 sequence", "\206\186\225\189\185\207\131\206\188\206\181").` - the logic we are using to calculate the offset for bytes / characters wasn't Unicode aware. Because the difference of the strings was only calculated at the byte level - if two subsequent unicode characters had the same prefix byte, we would compare the strings mid-character, which causes a zed crash further downstream.
__Fix:__ Make `firstDifference` unicode-aware; add tests
> fix(editor): Fix crash in marker update with UTF-8 characters

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/bin_editor/Oni2_editor.re
- test.esy.lock/index.json
This picks up the `onBeforeQuit` API change in https://github.com/revery-ui/revery/commit/b746d684a8bf44391697dc80a2120cdd59f31705 so we can bring in #3326 🎉
> refactor(dependency): Revery -> b746d68

- CHANGES_CURRENT.md
- src/Feature/SCM/Feature_SCM.re
- src/Feature/SCM/Feature_SCM.rei
- src/UI/Dock.re
- src/UI/Root.re
Fix #3315 - add a badge to show current staged changes in dock:
> fix(scm/#3315): Show staged changes in dock

- CHANGES_CURRENT.md
- src/Components/LocationListItem.re
__Issue:__ The lines and characters shown in the diagnostics view are off by one 
__Defect:__ We are using zero-based line and character indices in the rendering, but the user would expect one-based so it matches up with the line numbers and positions in the editor.
__Fix:__ Use one-based positions for rendering diagnostics and locations:
> fix(diagnostics): Use one-based position in UI for diagnostics and locations

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/CompletionItemSorter.re
__Issue:__ While investigating some issues around snippets in C, I saw that the `"editor.snippetSuggestions"` configuration setting wasn't quite behaving as expected. In particular, if `"editor.snippetSuggestions": "top"` is set, I'd expect user-created snippets to be at the top of the completion context menu.
__Defect:__ Some language extensions, like clangd, are really good about providing almost every completion as a snippet, even though they might not be categorized as a 'snippet' completion type. There's a difference between the completion kind being a snippet and the insert text rules being a snippet. We were using the latter to sort, but we should've been using the former.
__Fix:__ Use the completion item kind instead of the insert text rules to decide if an item is a snippet.
> fix(completion): Fix snippet sorting in presence of snippet completions

- CHANGES_CURRENT.md
- src/Exthost/CacheId.re
- src/Exthost/CodeAction.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Exthost/Request.re
- src/Exthost/Selection.re
- src/Exthost/Span.re
- src/Service/Exthost/Service_Exthost.rei
- test/Exthost/LanguageFeaturesTest.re
- test/collateral/extensions/oni-language-features/extension.js
This is the first part of implementing code-actions - wiring up the various extension host protocol APIs:
- `$registerQuickFixSupport` - registration of code action providers, including documentation
- `$provideCodeActions` - querying the available code actions, based on a line span or a selection
- `$resolveCodeAction` - get the workspace edit associated with a code action
- `$releaseCodeActions` - clean up code actions when the session is complete
This also implements a simple integration test, as a sanity check that parsing basic code actions work as expected.
> feat(code-actions): Implement extension host protocol

- .ci/clean-windows-deps.yml
__Issue:__ CI is failing on Windows at the 'Remove Java' step
__Defect:__ VM images were updated: https://github.com/actions/virtual-environments/commit/0cf21e451224281a74a004ae22fd456b5bad0f2b
__Fix:__ Use `JAVA_HOME` environment variable
> chore(ci): Fix Java path for removal

- CHANGES_CURRENT.md
- src/Feature/SCM/Feature_SCM.re
__Issue:__ 
There were 3 scenarios where Onivim was showing diff markers incorrectly:
1) A file is untracked
2) A file is ignored by the .gitignore file
3) A file is tracked, but totally empty
In all of these cases - we shouldn't show the diff markers. They're just extra noise.
__Defect:__ In all of these cases, we query for the 'original' content, and get a result back - but a total empty string.
__Fix:__ When the 'original' content is empty, don't show diff markers.
Fixes #3355
> fix(scm/#3355): Don't show diff markers on untracked or ignored files

- CHANGES_CURRENT.md
- src/Feature/Clipboard/Feature_Clipboard.re
- src/Feature/Clipboard/Feature_Clipboard.rei
- src/Feature/Clipboard/dune
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Model/State.re
- src/Service/Vim/Service_Vim.re
- src/Service/Vim/Service_Vim.rei
- src/Store/Features.re
__Issue:__ Command-v should paste in normal mode, since it doesn't conflict with a Vim binding, and is the intuitive behavior.
__Defect:__ The `"editor.clipboard.pasteAction"` the keybinding was bound to only ran in insert/command line modes.
__Fix:__ 
- Allow the command to run in select, normal, and visual modes
- Ensure we have the latest state by bringing in the current vim context
- Move bindings to `Feature_Clipboard`
Fixes #3353
> fix(clipboard/#3353): Command-v should paste in normal mode

- CHANGES_CURRENT.md
- docs/docs/configuration/key-bindings.md
- src/Feature/SideBar/Feature_SideBar.re
This PR allows setting keybindings based on the currently active sidebar panel, for example:
```
[
// See the onivim documentation for details on the format:
// https://onivim.github.io/docs/configuration/key-bindings
{
"key": "<ESC>",
"command": "workbench.action.findInFiles",
"when": "sideBarFocus && textInputFocus && activeViewlet == 'workbench.view.search'"
},
{
"key": "<DOWN>",
"command": "vim.window.moveDown",
"when": "sideBarFocus && textInputFocus && activeViewlet == 'workbench.view.search'"
},
{
"key": "<UP>",
"command": "vim.window.moveUp",
"when": "sideBarFocus && !textInputFocus && activeViewlet == 'workbench.view.search'"
}
]
```
From question here: https://discord.com/channels/417774914645262338/424012160696582144/827583796835909642
> fix(input): Add context key for currently active sidebar panel

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- integration_test/FileWatcherTest.re
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Components/FileExplorer/Component_FileExplorer.rei
- src/Components/FileExplorer/FsTreeNode.re
- src/Components/FileExplorer/Model.re
- src/Components/FileExplorer/dune
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Core/FpExp.re
- src/Core/Oni_Core.re
- src/Core/UniqueId.re
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Explorer/Feature_Explorer.rei
- src/Model/State.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Service/FileWatcher/Service_FileWatcher.re
- src/Service/FileWatcher/Service_FileWatcher.rei
- src/Service/FileWatcher/dune
- src/Store/Features.re
- src/Store/StoreThread.re
- src/Store/VimStoreConnector.re
This implements a manual refresh for the file explorer, as well as an experimental setting for automatically updating the file explorer in response to changes.
To enable the file-explorer auto-update, you can set the following config:
```
"files.useExperimentalFileWatcher": true
```
Hopefully can enable it by default, soon! Keep me posted if you try it out and see any issues.
If that's not set, then there is a new Control+Shift+P command - "Explorer: Refresh". This can be bound to a key with the "workbench.files.action.refreshFilesExplorer", like:
```
{ "key": "R", "command": "workbench.files.action.refreshFilesExplorer", "when": "sideBarFocus && !textInputFocus && activeViewlet == 'workbench.view.explorer'" }
```
Fixes #3350 
Fixes #3253 
Fixes #3158
Fixes #2056
Fixes #792 
__TODO:__
> fix(explorer/#3350): Implement Reload command + file system watcher for explorer

- CHANGES_CURRENT.md
- integration_test/FileWatcherTest.re
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Service/FileWatcher/Service_FileWatcher.re
- src/Service/FileWatcher/Service_FileWatcher.rei
- src/Store/VimStoreConnector.re
__Issue:__ In #3373 , we're stat'ing on files that are just changed (not added, unlinked, moved) - this is wasteful in the general case, but in the worst case of the log-file writing, we get caught in an infinite loop of:
1) Writing to the log file
2) Detecting a change event
3) Stat'ing the log file
4) Log out the stat results
5) Goto 1...
__Fix:__ Only stat if there was a rename - don't bother stat'ing for changes.
This should unblock the log file issue; but there is still the original issue of 100% CPU usage - hopefully, since we can use the log file, we can track that down now
> fix(filewatcher/#3373): Part 1 - Don't stat on changed files

- CHANGES_CURRENT.md
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Layout.re
- src/Feature/Layout/Model.re
- src/Feature/Layout/Msg.re
- src/Model/State.re
Add a few missing window movement bindings:
- Control+w, Control-t -> move to furthermost top left
- Control+w, Control-b -> move to furthermost bottom right
- Control+w, Control+w -> move to next right/bottom, or top -left
- Control+w, Shift+W -> move to next top/left, or bottom right
> fix(layout): Window cycle binding

- CHANGES_CURRENT.md
- src/bin_editor/Oni2_editor.re
__Issue:__ When we first integrating libuv, we ran the libuv event loop multiple times with each turn of the revery event loop, to workaround some integration issues. However, this is no longer necessary, and it's expensive perf-wise (the polling can be a bottleneck when not much else is going on!)
__Fix:__ Run the libuv event loop once with `NOWAIT` for each Revery event loop iteration
> perf(libuv): Run loop once

- CHANGES_CURRENT.md
- src/Exthost/Exthost.rei
- src/Exthost/RejectReason.re
- src/Exthost/Request.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Feature/LanguageSupport/Outmsg.re
- src/Feature/LanguageSupport/Rename.re
- src/Service/Exthost/Service_Exthost.re
- src/Store/Features.re
- Handle parsing `rejectReason` from the extension
- Refactor the application of workspace edits to a more common place, so that it can be used by #3358
> fix(rename): Handle reject reason

- CHANGES_CURRENT.md
- docs/docs/using-onivim/language-features.md
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/LanguageSupport/DocumentSymbols.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/MenuBar/Global.re
- src/Feature/Quickmenu/Feature_Quickmenu.rei
- src/Feature/Quickmenu/Schema.re
- src/editor-core-types/CharacterIndex.re
- src/editor-core-types/CharacterIndex.rei
- src/editor-core-types/CharacterRange.re
- src/editor-core-types/CharacterRange.rei
- src/editor-core-types/LineNumber.re
- src/editor-core-types/LineNumber.rei
This implements a quickmenu for the symbols language feature, to make it easy to quickly navigate to a symbol:
__TODO:__
> feat(language-support): Go-to symbols menu

- CHANGES_CURRENT.md
- src/Feature/Input/ReveryKeyConverter.re
__Issue:__ Although our keybindings would properly parse `<capslock>`, the binding would never be matched, even when capslock is pressed
__Defect:__ We didn't include the case in our conversion code from Revery/SDL2 keycodes -> Onivim's editor input key variant.
__Fix:__ Add missing case.
This unblocks bindings like:
```
{ "key": "<capslock>", "command": "vim.esc" }
```
But it's not super useful, because capslock still toggles state when pressing it. Ideally, if we're using it or matching it, we could block it from altering keyboard state.
> fix(input): Add missing case for caps-lock key

- src/editor-core-types/ByteIndex.re
__Issue:__ Experimenting with the snippet replace-selection feature:
I hit a crash - there was a specific case where the snippet could try and extract past the length of the current line, causing an exception in `Zed_utf8.next`
__Fix:__ Clamp `ByteIndex.next` to length of string
> fix(snippet): Crash on replace-selection

- CHANGES_CURRENT.md
- src/Exthost/Extension/Contributions.re
__Issue:__ The local history extension fails to install with the error "Unable to locate extension"
__Defect:__ There is a failure parsing the extension manifest,  with these command json expressions:
```
{
"command": "treeLocalHistory.refresh",
"title": "Refresh",
"when": false,
"icon": "$(refresh)"
},
```
Our `"when"` expression parser only handles strings, not booleans.
__Fix:__ Extend our parser to handle booleans as well.
> fix(extensions/#3388): Local history extension doesn't install

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Feature/LanguageSupport/CodeActions.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
This adds an `editor.lightBulb.enabled` setting to the editor - which toggles a 'lightbulb` icon on/off to show if there are available quick-fixes or refactorings:
> fix(code-action): Add editor.lightBulb.enabled configuration setting

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/CodeActions.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/Store/StoreThread.re
- src/UI/EditorView.re
Fix a couple of bugs with the lightbulb showing up when 'quick fixes' are available:
1) The light bulb would be rendered across all open editors. Scope to just the active editor.
2) The light bulb would only show up if the fix had associated diagnostics, which some providers don't give. Scope to the current position, in that case.
> fix(code-action): Fix a couple bugs around lightbulb+quickfixes

- CHANGES_CURRENT.md
- docs/docs/getting-started/vim-tips.md
Fixes #3407 
We have a separate documentation on formatOnSave here: https://onivim.github.io/docs/using-onivim/formatting#format-on-save
> fix(docs/#3407): Missing link on vim tips page

- src/Feature/Editor/Editor.re
- test/Feature/Editor/EditorTests.re
__Issue:__ When word-wrap is enabled (the default), and you type across a word-wrap boundary in insert mode, there could be an inadvertent and unnecessary scroll.
__Defect:__ There is logic in the editor to ensure the cursor is in view, within a `scrollOffX` value (default of 2 characters on the border). However, this doesn't make sense when word-wrapping is on.
__Fix:__ Treat `scrollOffX` as having a value of zero when word wrap is active.
Fixes #3405
> fix(editor/#3405): Fix inadvertent scroll when typing in wrapped buffer

- CHANGES_CURRENT.md
- src/Core/WordWrap.re
- src/Feature/Editor/ScrollShadow.re
- test/Core/WordWrapTests.re
__Issue:__ Our word-wrap logic was not correctly accounting for tab widths, and therefore, files with tab indentation could show as overflowing horizontally.
__Defect:__ Tab characters were always considered as single width, regardless of settings.
__Fix:__ Use full width for tab characters in the word wrap calculation
Fixes #3372
> fix(editor/#3372): Fix word-wrap calculation with tabs

- CHANGES_CURRENT.md
- src/Store/Features.re
__Issue:__ When clicking the 'close' icon to close an editor window, closing the last editor will always close Onivim, even if there are unsaved buffer changes.
__Fix:__ If there are unsaved changes, show a modal to give the user a chance to save before quitting.
Fixes #417, needed for #3420
> fix(lifecycle/#417): Add warning when closing last file, if there are unsaved buffers

- CHANGES_CURRENT.md
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Msg.re
- src/Model/State.re
WIP fix to implement Ctrl-W, Ctrl-Q (close active split) binding
Related #1721
> fix(vim/#1721): Implement Ctrl-W, Ctrl-Q binding

- CHANGES_CURRENT.md
- src/Feature/Input/ReveryKeyConverter.re
__Issue:__ The 'control' key is itself being treated as a key-press, which can break key sequences.
For example, in this sequence of key-presses (where control is held across the duration of the key sequence):
- Control DOWN
- W DOWN
- W UP
- N DOWN
- N UP
- Control UP
The terminal-to-normal mode behaves as expected.
However, in this sequence:
- Control DOWN
- W DOWN
- W UP
- Control UP
- Control DOWN
- N DOWN
- N UP
- Control UP
This sequence of key presses does not work as expected, because the second 'Control' down is treated as an individual key press - so the `Control+\`, `Control+N` key sequence doesn't actually trigger it, as the system is seeing: `Control+\`, `Control`, `Control+N`.
__Fix:__ For the purpose of key bindings, don't treat `Control` as an individual key press - just …
> fix(input/#2778): Terminal-to-normal keybinding not working as expected

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- bench.esy.lock/opam/ppxlib.0.15.0/opam
- bench.esy.lock/opam/semver2.1.2.0/opam
- esy.lock/index.json
- esy.lock/opam/ppxlib.0.15.0/opam
- esy.lock/opam/semver2.1.2.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ppxlib.0.15.0/opam
- integrationtest.esy.lock/opam/semver2.1.2.0/opam
- package.json
- release.esy.lock/index.json
- release.esy.lock/opam/ppxlib.0.15.0/opam
- release.esy.lock/opam/semver2.1.2.0/opam
- test.esy.lock/index.json
- test.esy.lock/opam/ppxlib.0.15.0/opam
- test.esy.lock/opam/semver2.1.2.0/opam
This is needed to unblock Windows builds on master/nightly - picks up https://github.com/revery-ui/esy-libvterm/pull/5
> chore(ci): Remove libtools dependency

- CHANGES_CURRENT.md
- src/Core/Constants.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/GutterView.re
- src/Feature/Editor/OverlaysView.re
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
- src/UI/Root.re
__Issue:__ Several mouse interactions weren't working correctly, including dismissing the completion pop-up by clicking outside (#3428) as well as hovering / selecting an item via the mouse.
__Defect:__ The editor surface was hijacking the clicks, and not giving the completion pop-up a chance to respond (in addition, selecting an item wasn't hooked up).
__Fix:__ Move the completion UI to an overlay that can get access to the clicks. Plumb in mouse click / mouse hover interactions.
Fixes #3428
> fix(completion/#3428): Fix various mouse interactions with completion popup

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/Hover.re
__Issue:__ The diagnostics section in the hover popup had a `textOverflow(Ellipsis)` setting that wasn't used - however, https://github.com/revery-ui/revery/pull/1056 caused it to be picked up. Now, the diagnostics can be cut off in the hover popup.
__Fix:__ Remove `textOverflow(Ellipsis)` to bring back previous behavior.
> fix(hover): Remove textOverflow(Ellipsis) from hover diagnostics

- CHANGES_CURRENT.md
- src/Feature/LanguageSupport/DocumentSymbols.re
- src/Feature/MenuBar/Global.re
- src/Model/GlobalCommands.re
Implement feature for #3413
```changelog
Add new command `action.workbench.quickOpenBuffer` to easily navigate through buffers
```
> feat(buffers/#3413) Implement action.workbench.quickOpenBuffer

- CHANGES_CURRENT.md
- src/Core/Buffer.re
- src/Core/IndentationConverter.re
- src/Core/Oni_Core.re
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/Buffers/Feature_Buffers.rei
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/StatusBar/Feature_StatusBar.rei
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Store/Features.re
- src/reason-libvim/Buffer.re
This adds a few commands and features to make it easier to switch indent settings:
- Support for the `:set expandtab`/`:set noexpandtab` configuration setting
- Support for the `:set shiftwidth` configuration setting
- New menu items:
- Indent using tabs
- Indent using spaces
- Convert to tabs
- Convert to spaces
- Clickable status bar item to open menu
> feat(indentation): Easier space/tab indentation switching

- CHANGES_CURRENT.md
- src/Feature/Input/ReveryKeyConverter.re
- src/editor-input/EditorInput.re
- src/editor-input/KeyCandidate.re
- src/editor-input/KeyPress.re
- test/editor-input/InputTest.re
__Issue:__ The fix for #2778 (#3422) caused a regression in the control+tab menu
__Defect:__ The control+tab menu relies on a special key event, `<AllKeysReleased>`. This event requires keeping track of all pressed scancodes (like the control key). The change in #3422 totally ignored the control key, such that it's scancode wasn't being recorded - this then caused the `<AllKeysReleased>` event to be dispatched too early.
__Fix:__ Ignore the modifier for the purposes of binding candidates, such that the original blocker for #2778 is still fixed (the 'control' key press shouldn't interrupt a sequence of bindings, like `<C-W>`, `<C-Q>`). However, we still need to add the scancode to `pressedScancodes` so that we can properly engage the `<AllKeysReleased>` binding.
Related #3433
> fix(buffers/#3433): Fix control+tab regression

- CHANGES_CURRENT.md
Also corrects miss-named action (was "action.workbench.quickOpenBuffer", changed to "workbench.action.quickOpenBuffer")
> Move workbench.action.quickOpenBuffer feature under "Feature" in changelog

- CHANGES_CURRENT.md
- azure-pipelines.yml
`esy@0.6.10` changes the cache path, such that there is one less underscore in the path padding (https://github.com/esy/esy/issues/1127). Update our CI to accommodate new cache paths.
> chore(ci): Fix up cache path for esy #1172 after upgrading to esy@0.6.10

- CHANGES_CURRENT.md
- azure-pipelines.yml
Fix for a build error:
```
Total file: 1 ---- Processed file: 0 (0%)
Fail to upload '/Users/runner/work/1/a/esy-cache.tar' due to 'Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304'.
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304
---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304
--- End of inner exception stack trace ---
```
https://dev.azure.com/onivim/oni2/_build/results?buildId=16435&view=logs&j=83eba23a-9ede-5c86-668a-3657d4d2e8d1&t=caeb8a87-5847-54ed-1bb9-47821a9bb3ac&l=950 …
> chore(ci): Fix concurrent upload issue

- CHANGES_CURRENT.md
- src/Feature/Editor/ContentView.re
__Issue:__ Swift errors aren't showing on the editor surface, even though they are recognized in the error pane:
__Defect:__ The diagnostic is coming to Onivim as a zero-length range, so we render a zero-length squiggly. However, the expected behavior is that Onivim will render the squiggly under the token at that position.
__Fix:__ Render the squiggly under the token:
Related #3434
> fix(diagnostics/#3434): Swift diagnostics not showing

- CHANGES_CURRENT.md
- src/Core/Snippet/Snippet.re
- src/Core/Snippet/Snippet_parser.mly
__Issue:__ When trying to use the `print` completion snippet w/ the Swift extension, get an error:
__Fix:__ Allow colons in placeholder text
> fix(snippet/#3434): Swift print snippet fails

- CHANGES_CURRENT.md
- src/Feature/Vim/Feature_Vim.re
__Issue:__ The Control-^ binding (Control-6) to jump to an alternate file is not working as expected with Onivim.
__Defect:__ The key is sent in a way (`<C-6>`) that is unrecognized by libvim, which is expecting (`<C-^>`).
__Fix:__ Remap the key to send it in the form libvim is expecting
Fixes #3455
> fix(vim/#3455): Fix alternate-file shortcut key

- CHANGES_CURRENT.md
- src/Feature/Quickmenu/View.re
- src/UI/QuickmenuView.re
__Issue:__ The quickmenu would darken the background when open. In the case of switching themes, this is problematic... because after selecting the theme, it doesn't look the same with the darkened background removed.
__Fix:__ Remove the background darkening for the quickmenu.
Fixes #3459
> fix(quickmenu/#3459): Remove darkening of the background

- CHANGES_CURRENT.md
- src/editor-input/Matcher_lexer.mll
- test/editor-input/MatcherTest.re
__Issue:__ Binding to `gt` binds to <kbd>></kbd> instead of <kbd>g</kbd><kbd>t</kbd>
__Fix:__ Recognize just `<gt>` instead of `gt` - this is the same behavior as Vim. Note that modifier keys don't make sense in this context (`<c-gt>` isn't a key recognized by Vim), so we can simplify the parsing for the `<gt>` and `<lt>` case
Fixes #3256
> fix(input/#3256): Fix 'gt' binding parse case

- CHANGES_CURRENT.md
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Components/FileExplorer/Component_FileExplorer.rei
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Configuration/LegacyConfigurationParser.re
- src/Feature/Configuration/LegacyConfigurationValues.re
- src/Feature/Explorer/Feature_Explorer.re
- src/Feature/Explorer/Feature_Explorer.rei
- src/Feature/Search/Feature_Search.re
- src/Store/Features.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/StoreThread.re
Fix #1104 - when `files.exclude` is updated, reload the file explorer to show the result
> fix(explorer/#1104): Reload explorer when files.exclude is updated

- CHANGES_CURRENT.md
- src/Feature/Buffers/Feature_Buffers.re
__Issue:__ There were some cases where we weren't setting the last-used buffer time correctly.
__Fix:__ Instead of trying to catch every place the  buffer could change, and calling `stampLastUsed`, observe when the focused buffer has changed via a subscription, and stamp it in that case.
Fixes #3433
> fix(buffers/#3433): Stamp last used anytime the current focused buffer changes

- CHANGES_CURRENT.md
- manual_test/cases.md
- src/CLI/Oni_CLI.re
- src/CLI/Oni_CLI.rei
- src/Core/Oni_Core.re
- src/Core/SingleInstance.re
- src/Core/SingleInstance.rei
- src/bin_editor/Oni2_editor.re
- src/bin_editor/dune
- src/bin_launcher/Oni2.re
__Issue:__ On every platform, the `oni2` CLI command always opens a new window. In general, though, it's preferred to open and focus the existing window.
__Fix:__ Implement a similar strategy to [`node-single-instance`](https://github.com/pierrefourgeaud/node-single-instance/blob/master/index.js), just with native reasonml.
__Todo:__
Fixes #1250
Fixes #2947 
Fixes #3058
> fix(cli/#1250): 'oni2' command should open in existing editor

- CHANGES_CURRENT.md
- src/Core/Utility/StringEx.re
- src/Store/QuickmenuStoreConnector.re
__Issue:__ In quick-open, `Core NodeTask` should match a file called `src/Core/NodeTask.re`, but it doesn't.
__Defect:__ We're trying to use the space as a matching character, and since there are no spaces in the path, it's not matching.
__Fix:__ In the short-term, just don't consider spaces for now as a matching character (filter them out of the query). Once we have the full refine behavior in #3278 - this hack will no longer be necessary, though.
> fix(quick-open/#3473): Filter out spaces for quick open

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Exthost/Diagnostic.re
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Feature/Diagnostics/Diagnostic.re
- src/Feature/Diagnostics/Feature_Diagnostics.re
- src/Feature/Diagnostics/Feature_Diagnostics.rei
- src/Feature/Editor/Colors.re
- src/Feature/Editor/ContentView.re
- src/Feature/Editor/Draw.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorConfiguration.re
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/GlobalColors.re
- test/Feature/Diagnostics/DiagnosticTest.re
- test/Feature/Diagnostics/DiagnosticsTests.re
This implements strike-through rendering for deprecated code and fading out of unused code:
Fixes #3485
> fix(editor/#3485): Render deprecated items with strikethrough

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Core/ColorTheme.re
- src/Core/ColorTheme.rei
- src/Core/Kernel/KeyedStringMap.rei
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/Feature_Theme.rei
This adds a `workbench.colorCustomizations` configuration setting, which uses the same theme colors and formats as the [VSCode Theme Colors](https://code.visualstudio.com/api/references/theme-color)
This can be used to manually override colors, like:
Related #3495
> feat(theme): Add workbench.colorCustomizations setting to override theme colors

- docs/docs/using-onivim/command-line.md
The changes in #3469 mean using `--nofork` is no longer enough to get a new instance of `oni2` when one is already running.
This is notable when setting `oni2` as your `$EDITOR` or git editor.
To replicate the issue:
1. Open onivim2
2. On the cli, run `oni2 --nofork`
3. Note the existing instance of `oni2` is attached to
This documentation change ensures future users will have the correct setup.
> Update CLI instructions for new --new-window requirement

- CHANGES_CURRENT.md
- src/Service/OS/Service_OS.re
- src/Service/OS/Service_OS.rei
- src/Store/Features.re
__Issue:__ When trying to create a new file via the command line, like `oni2 some-new-file.txt`, and there is already an instance running, the running instance will crash.
__Defect:__ The command to open a file via a running instance was re-using logic from the drag-and-drop code, which assumes that the files / paths always exist.
__Fix:__ Make the `statMultiple` effect resilient in the case where the path does not exist.
> fix(cli): Fix opening non-existent file in second instance

- CHANGES_CURRENT.md
- src/Components/ContextMenu/Component_ContextMenu.re
- src/Feature/MenuBar/Feature_MenuBar.re
Fixes #3510 - prevent clicking inside from context menu from closing the entire context menu
> fix(ux/#3510): Fix click inside context menu - prevent from closing

- CHANGES_CURRENT.md
- src/Core/Utility/StringEx.re
- src/Feature/LanguageSupport/Completion.re
__Issue:__ In some cases, the 'detail' text for completion is massive... and it hits a degenerate case in Revery's word-wrap / ellipsizing that causes a hang.
__Fix:__ For the completion UI, constrain the amount of detail text we show, to work around the bug and prevent a hang.
> fix(completion): Fix hang when detail text is large

- CHANGES_CURRENT.md
- node/pty-helper.js
__Issue:__ When pasting text into the terminal, the text is in reverse order
__Defect:__ Our 'pty' uses node at the moment, and we send packets to the node process. In the case of pasting, these packets can get bundled together into a single buffer. The pty-helper wasn't 'unbundling' these - it just assumed buffers and packets were 1-to-1.
__Fix:__ Instead of assuming one buffer contains one packet, read the header and splice out individual packets, and refactor the packet-processing logic to be a loop.
Fixes #3513
> fix(terminal/#3513): Pasted text is in reverse order

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionConfig.re
__Issue:__ It's not straightforward to disable the `<tab>` key behavior of completion
__Fix:__ Add an `editor.acceptSuggestionOnTab` setting, which is similar to the `editor.acceptSuggestionOnEnter` setting.
> fix(completion): Add editor.acceptSuggestionOnTab setting

- CHANGES_CURRENT.md
- src/Feature/Pane/Feature_Pane.re
__Issue:__ The close (`x`) button in the pane wasn't worked
__Defect:__ Regression from #3538 - the pane-click was being handle after the close button click, causing the pane to retain focus and stay open
__Fix:__ Don't dispatch `PaneClicked` when the close button is clicked.
Would be nice to have `stopPropagation` wired up to help handle this
> fix(pane): Fix close button not working in bottom pane

- CHANGES_CURRENT.md
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Service/OS/Service_OS.re
- src/Service/OS/Service_OS.rei
__Issue:__ When opening Onivim 2 in an NFS mount directory, no files are shown.
__Defect:__ Onivim 2 uses `readdir` to populate the explorer, and uses the `dirent` struct to determine the type of the file/folder. For NFS mounts, this was coming back as `UV_DIRENT_UNKNOWN`/`DT_UNKNOWN` which caused Onivim 2 to ignore the file/folder.
__Fix:__ In the case of `Unknown` (or even a link...), use stat to figure out the actual type of the file.
Fixes #3534
Fixes #3377
> fix(explorer/#3534): Files in an NFS mount are not showing up in explorer

- CHANGES_CURRENT.md
- src/Components/FileExplorer/Component_FileExplorer.re
- src/Components/FileExplorer/FileTreeView.re
- src/Components/FileExplorer/FsTreeNode.re
- src/Components/FileExplorer/FsTreeNode.rei
- src/Core/Codicon.re
__Issue:__ Symlinks in the explorer were always showing up as files - regardless if they were links to a file or a directory.
__Defect:__ We weren't handling symlinks correctly - they were defaulting to files in the explorer.
__Fix:__ Use `stat` to figure out what the link is actually pointing to (implemented in #3567) and, for symlinks, show an arrow in the explorer UI:
Depends on #3567 
Fixes #2657
> fix(explorer/#2657): Fix symlinks showing up as empty files

- integration_test/CopyActiveFilepathToClipboardTest.re
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Components/FileExplorer/FsTreeNode.re
- src/Core/FpExp.re
- src/Core/Utility/FpEx.re
- src/Core/Utility/OptionEx.re
- src/Core/Utility/Utility.re
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/Buffers/Feature_Buffers.rei
- src/Feature/Buffers/dune
- src/Model/Actions.re
- src/Model/GlobalCommands.re
- src/Service/Clipboard/Service_Clipboard.re
- src/Service/Clipboard/Service_Clipboard.rei
- src/Store/Features.re
- src/Store/VimStoreConnector.re
Adds commands to copy the relative file path / absolute file path (ports over the existing command to `Feature_Buffers`):
Fixes #3549
> fix(clipboard/#3549): Add commands to copy absolute/relative file paths

- src/Core/LineHeight.re
- src/Core/LineHeight.rei
- src/Core/Oni_Core.re
- src/Feature/Buffers/dune
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/EditorConfiguration.re
- src/Feature/Terminal/Configuration.re
- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/Terminal/Feature_Terminal.rei
- src/Feature/Terminal/TerminalView.re
- src/editor-terminal/EditorTerminal.rei
- src/editor-terminal/Font.re
- src/editor-terminal/TerminalView.re
Last part of the work for #3062 - inherit line-height from the editor, and add `terminal.integrated.lineHeight` setting to overide.
Fixes #3062
> fix(terminal/#3062): Inherit line-height from editor

- CHANGES_CURRENT.md
- src/Components/VimList/Component_VimList.re
- src/Feature/Buffers/dune
__Issue:__ Scrolling through the extensions list while searching for extensions is frustrating, because the view always resets - making it hard to focus on any particular item while the search is in progress.
__Defect:__ When new items came in, the current item would be focused, which is usually the top item. However, if there is a mouse scroll, that should be taken into consideration, too.
__Fix:__ Preserve scroll when repopulating the list, if possible.
Fixes #3551
> fix(extensions/#3551): Preserve scroll when updating list, if possible

- CHANGES_CURRENT.md
- src/Service/Registration/Service_Registration.re
Fix case where spaces are copied before / after license key string -
> fix(registration): Trim license key string prior to submitting to API

- CHANGES_CURRENT.md
- src/oni2-keyboard-layout/stubs/keyboard-layout-mac.c
__Issue:__ Crash when switching input language on OSX
__Defect:__ The change in https://github.com/revery-ui/revery/pull/1072 means that the runtime is no longer released - however, when the input changes,  the keyboard handler was trying to acquire the runtime, causing a crash.
__Fix:__ Remove release/acquire runtime calls in the keyboard handler on OSX
Fixes #3614
> fix(osx/#3614): Hang on IME

- CHANGES_CURRENT.md
- docs/docs/for-developers/building.md
Just copies over and tidies up the steps for the Linux Dockerfile based build. Should hopefully help some of the people who are having issues/don't want to install the other deps.
> docs(build): add steps for the Docker based build

- CHANGES_CURRENT.md
- src/Feature/Layout/Feature_Layout.re
__Issue:__ When using 'sneak' to enter a buffer from another focus point, the buffer gets selected, but focus doesn't go to the editor.
__Defect:__ The focus is implicitly relying on the 'click' to focus the editors.
__Fix:__ When clicking on a tab, use the `Focus(Center)` outmsg to ensure that the editors have focus.
An alternative approach to fixing this would be to create separate `msg`'s for Sneaks - ie, adding an `EditorTabSneaked` to `EditorTabClicked`. This might better communicate the state of the system (it's really just the sneak gesture that requires this extra focus), but it seemed a bit overkill.
Fixes #2569
> fix(sneak/#2569): Focus buffer when entering via sneak

- docs/website/pages/en/tips-and-tricks.js
- Correct typo when moving split upwards (control+l -> control+k)
- 'Move' is ambiguous - it could be mean actually moving the split. Switch the verbiage to make this less ambiguous.
> docs(layout): Fix window split navigation shortcut and description

- src/Feature/Editor/Editor.re
- When clicking on a line in the minimap, center that line in the editor (if we can).
- Account for reserved space (ie, codelens or other inline elements)
Fixes #3618
> fix(minimap/#3618): Center clicked minimap line

- ThirdPartyLicenses.txt
- src/Components/FeatherIcons.re
- src/Components/FeatherIcons.rei
- src/Components/SVGIcon.re
- src/UI/Dock.re
Now that we have SVG support in Revery, I think it makes sense to swap out some of the old Font Awesome icons we have for parameterize-able SVG icons. 
The Font Awesome icons are great, but they aren't meant to be rendered at the size we are currently, leading to stroke widths that look too thick, etc.
I chose to use [Feather Icons](https://feathericons.com) to replace the ones in the dock since they are configurable and MIT-licensed, but if anyone has any better ideas, let me know!
**Before:**
**After:**
The beautiful thing about the SVGs is that they're configurable -- I created an `SVGIcon.t` which takes a size, stroke-width, and color and re-writes the SVG accordingly.
> refactor(dock): use SVG icons in dock

- CHANGES_CURRENT.md
- src/Feature/Editor/EditorBuffer.re
> fix(editor/#3629): Fix missing line number / cursor when deleting entire file

- CHANGES_CURRENT.md
- src/Core/Ripgrep.re
- src/Core/Ripgrep.rei
- src/Feature/Search/Feature_Search.re
- src/Service/Ripgrep/Service_Ripgrep.re
- src/Service/Ripgrep/Service_Ripgrep.rei
Part 3 continuing #3641 and #3654. This adds two search boxes to include and exclude certain files, like in VSCode:
https://user-images.githubusercontent.com/4527949/120844665-bd079600-c53d-11eb-9fd6-034e30950e7b.mov
> feat(search): add include/exclude file boxes

- CHANGES_CURRENT.md
- src/Feature/Exthost/Feature_Exthost.re
Fixes #3335 - most of the work was done in #3571 , but this contains a small fix for selection bounds:
> fix(extensions/#3335): Fix add to user dictionary command

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Store/VimStoreConnector.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/CommandTest.re
Fix #3680 - respect the `isSilent` flag for executing output commands
Pick up https://github.com/onivim/libvim/pull/264
> fix(vim/#3680): Respect silent flag for output command

- CHANGES_CURRENT.md
- src/Feature/SideBar/Feature_SideBar.re
- src/Feature/SideBar/Feature_SideBar.rei
- src/Model/Focus.re
- src/Model/Focus.rei
- src/Store/Features.re
- src/UI/Root.re
- src/UI/SideBarView.re
This PR fixes some window navigation issues when navigating into the sidebar.
1) In Zen mode, prior to this fix, the user could `Control+W L` or `Control+W H` into the sidebar, but the sidebar would be offscreen - very confusing.
2) When the sidebar is closed, `Control+W L` or `Control+W H` (depending on if the sidebar is on the left or right) will temporarily open the sidebar while it is focused, much like the bottom pane.
Related to #3681
> fix(sidebar/#3681): Always focus sidebar on unhandled left/right window movement

- CHANGES_CURRENT.md
- development_extensions/oni-test-extension/extension.js
- development_extensions/oni-test-extension/package.json
- integration_test/ExtHostFileSystemTest.re
- integration_test/dune
- src/Exthost/Client.re
- src/Exthost/Exthost.rei
- src/Exthost/Protocol/Exthost_Protocol.re
- src/Exthost/Protocol/Exthost_Protocol.rei
- src/Exthost/Reply.re
- src/Feature/FileSystem/Feature_FileSystem.re
- test/Exthost/FileSystemTest.re
__Issue:__ The nim extension #3685 was failing to activate.
__Defect:__ The extension is expecting the storage folder to be created, but this is failing. The folder should be created by the extension host here: https://github.com/microsoft/vscode/blob/fc0ee4e4bc28d8efe5d576827d3bacdd919f3e7f/src/vs/workbench/api/common/extHostStoragePaths.ts#L60 - however, the `$stat` result is not throwing an exception, as expected by that code.
__Fix:__ When a file/folder is not available via `$stat`, send the response as an error, so it properly bubbles up to extensions as an extension.
Fixes #3685
> fix(extension/#3685): Fix nim activation error

- CHANGES_CURRENT.md
- src/Feature/Terminal/TerminalView.re
__Issue:__ When scrolling using the mousewheel / trackpad in terminal, the direction is the opposite the expected.
__Defect:__ Regression from https://github.com/onivim/oni2/pull/3645 - when refactoring to track the scroll in the model, the mousewheel direction wasn't normalized like it was in the editor/scrollable lists.
__Fix:__ Normalize mouse-wheel factor so the scroll direction is correct and consistent with the rest of the UI.
Fixes #3711
> fix(terminal/#3711): Normalize scroll direction from mouse wheel

- CHANGES_CURRENT.md
- scripts/linux/AppRun
- scripts/linux/package-linux.sh
__Issue:__  On some Linux distros (ie Fedora 34) with Gnome 40, the AppImage fails to start
__Defect:__ Newer version of gnome / glib have deprecated the `antialiasing` setting. Onivim bundles GTK in the AppImage, but doesn't bundle glib settings - so querying the glib settings queries an updated set that isn't compatible with the older, bundled GTK.
__Fix:__ Follow the example of Inkscape and bundled the compiled glib settings for the corresponding version, to be more resilient in a differing installed GTK version and to avoid this mismatch: https://gitlab.com/inkscape/inkscape/-/merge_requests/3120/diffs
Fixes #3706 
Fixes #3697 
Fixes #3528
> fix(packaging/#3706): Linux: Package compiled glib settings to avoid incompatibility

- CHANGES_CURRENT.md
- src/editor-input/EditorInput.re
- src/editor-input/KeyCandidate.re
- test/editor-input/InputTest.re
__Issue:__ In the specific case of specifying a remap, where some of the remapped keys are used in another binding, the remapped keys could be emitted in the wrong order.
__Defect:__ The emitted keys in this case were being incorrectly reversed.
__Fix:__ Fix the accumulation of remapped keys, such that they work both in the special case exposed by #3729 and the more general cases.
Fixes #3729
> fix(input/#3729): Fix remapped keys executing in wrong order

- CHANGES_CURRENT.md
- docs/docs/configuration/key-bindings.md
- src/Components/VimList/Component_VimList.re
- src/Components/VimTree/Component_VimTree.re
- src/Components/VimTree/Component_VimTree.rei
- src/Core/TreeList.re
- src/Feature/Search/Feature_Search.re
- src/Feature/Search/Feature_Search.rei
- src/Model/State.re
Implement #3713 - add default keybindings (F4 / Shift F4) to move to next /previous search result in the search pane.
Fixes #3713
> feat(search/#3713): Default keybindings for next/previous search result

- CHANGES_CURRENT.md
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Model.re
- src/Feature/Layout/Msg.re
- src/Model/State.re
Related to #1721
This implements the Control+W, C binding (similar to the Control+W, Q binding: #3420 - except doesn't close the last split).
> fix(layout): Wire up window close command (Control+W, C)

- CHANGES_CURRENT.md
- src/Exthost/Edit.re
- src/Service/Vim/Service_Vim.re
__Issue:__ The [trailing spaces](https://open-vsx.org/extension/shardulm94/trailing-spaces) plugin isn't working as expected - there is a statusbar message reporting that trailing spaces have been removed... but they aren't actually removed.
__Defect:__ There were two problems:
1) The `$tryApplyEdits` API wasn't parsing single-edits correctly in the case where the text property is null as opposed to a string
2) In the `null` case, if there was no text on the line, the line would be completely removed
__Fix:__
1) Correctly parse the text property - handling either null or a string
2) When text is null, treat it as an empty string
> fix(extension): Fix edit application from trailing spaces plugin

- CHANGES_CURRENT.md
- integration_test/RegressionLayoutTabSingleEditor.re
- integration_test/RegressionVspEmptyInitialBufferTest.re
- integration_test/dune
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Model.re
- src/Store/Features.re
__Issue:__ Using `:tabnew` or `:tabedit` (or Control+T in #3733) would create a new vim-style layout tab, but there'd be an extra 'editor tab' in the initial window split.
__Defect:__ There was an extra copy/create of the editor in the layout code.
__Fix:__ Remove extraneous copy
__Todo:__
> fix(tabs/#3150): Multiple 'editor tabs' open with tabnew/tabedit

- CHANGES_CURRENT.md
- bench/lib/FilterJobBench.re
- docs/docs/configuration/key-bindings.md
- src/Model/Actions.re
- src/Model/GlobalCommands.re
- src/Model/State.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/VimStoreConnector.re
- src/UI/QuickmenuView.re
- test/Model/FilterJobTest.re
Fix #564
Fix #2232
A rough first pass, but adds default bindings for selecting items from the quick open to open in current/vertical/horizontal/new tab.
Binds aren't finalised, so some input there would be nice (Ctrl-s and Ctrl-v are the defaults in Fzf in vim which is why I went with them).
> feat(quickopen): Add binds to open in splits to Quick Open

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Core/Ripgrep.re
- src/Core/Ripgrep.rei
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Search/Feature_Search.re
- src/Service/Ripgrep/Service_Ripgrep.re
- src/Service/Ripgrep/Service_Ripgrep.rei
- src/Store/QuickmenuStoreConnector.re
- src/Store/RipgrepSubscription.re
__Issue:__ Searching (whether via `Control+P` or find-in-files) would ignore symlinks, both symlinked directories and files.
__Defect:__ We weren't  supplying the `--follow` argument to ripgrep
__Fix:__ Supply `--follow` when calling `ripgrep`, but add configuration setting to disable this (`search.followSymlinks`)
Fixes #1588
> fix(search/#1588): Follow symlinks when using ripgrep by default

- CHANGES_CURRENT.md
- src/Feature/Editor/EditorDiffMarkers.re
Fix #3648.
Very tiny change! Perhaps I'm missing something here, but it looks like the diff markers don't need to include this offset, at least in the calc for the y pos.
Before / After:
https://user-images.githubusercontent.com/10038688/125708244-36845971-c357-4b89-8e53-a0fa3e24775e.mov
If you look at the two add markers, in the before on the left they move about when scrolled.
On the right, they stay locked on the actual lines that changed.
They should be attached to the three comment lines (above and below the long comment line).
(Sorry for the short video, only allowed 10MB here!).
Assuming this is sensible, just needs the changelog updating.
> fix(minimap/#3648): Fix minimap diff marker position

- CHANGES_CURRENT.md
- package.json
Fixes #3769
To be honest I'm not sure whether it was broken or just didn't work on my pc. Hoping it's the first scenario, I've decided to submit a PR.
Also,  should this PR be included in `CHANGES_CURRENT.md`?
> fix(build/#3769) Fix npm watch command

- CHANGES_CURRENT.md
- scripts/windows/publish.ps1
Updated codesigning cert for Windows build (requires codesign certificate password update)
> chore(ci): Updated codesign cert

- CHANGES_CURRENT.md
- bench/lib/Helpers.re
- docs/docs/configuration/settings.md
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Feature/Configuration/Feature_Configuration.rei
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/TitleBar/Feature_TitleBar.re
- src/Feature/TitleBar/Feature_TitleBar.rei
- src/Model/State.re
- src/Store/Features.re
- src/UI/Root.re
- src/bin_editor/Oni2_editor.re
__Issue:__ There are several quirks on Windows with the 'undecorated' Windows style - issues like:
- #3730 
- #3071 
- #3063 
__Fix:__ These can be deal-breakers for use as a daily editor, so until we have those fixed for the 'undecorated' Windows, change the default setting to use the native titlebar. 
This introduces a new setting - `window.titleBarStyle` that can be `"native"` or `"custom"`. The `"custom"`  titlebar looks nicer, because it is themed and custom rendered, however it has the above quirks. On Windows, change the default to `"native"`.
In addition, this pushes up the configuration loading sooner in the startup cycle, so we can pick up configuration settings like `"window.titleBarStyle"` prior to opening the window.
__Todo:__
> feat(windows): Customizable title bar style

- .ci/clean-windows-deps.yml
- CHANGES_CURRENT.md
- azure-pipelines.yml
- scripts/windows/publish.ps1
- scripts/windows/verify-signtool.ps1
- The new codesigning certificate requires a newer version of `signtool` - need to update the build VM
- `signtool` on `windows-2019` is in a different location than `vs2017-win2016`
> chore(ci): Additional fixes for codesigning/publish on windows

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Core/Ripgrep.re
- src/Core/Ripgrep.rei
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Search/Feature_Search.re
- src/Service/Ripgrep/Service_Ripgrep.re
- src/Service/Ripgrep/Service_Ripgrep.rei
- src/Store/QuickmenuStoreConnector.re
- src/Store/RipgrepSubscription.re
__Issue:__ There is no way to configure Onivim to ignore the `.gitignore` files when searching (via the Control+P quickopen or find-in-files)
__Fix:__ Add a setting `search.useIgnoreFiles`, which defaults to `true`, and specifices whether Control+P/find-in-files should take the ignore files into consideration.
Fixes #3792
> fix(search/#3792): Add setting to control '--no-ignore' flag for ripgrep

- CHANGES_CURRENT.md
- docs/docs/for-developers/free-license.md
There were a couple of items that I thought were obvious / implied, but perhaps not apparent enough:
1) The PR must be complete work (fully resolves the root cause or fully implements a feature - not a 'hack')
2) The PR must be merged.
I added these into the license key bounty docs to make sure these criteria are clear.
> fix(docs): Clarify license key bounty guidelines

- CHANGES_CURRENT.md
- src/Exthost/SuggestItem.re
Fix #3787 
__Issue:__ Completion items were coming with `null` value in the JSON, for example: 
```
{
...
'c': null,
...
}
```
(Note that the completion item JSON format uses a condensed field name to minimize data over the wire, see: https://github.com/onivim/vscode-exthost/blob/fc0cb0ba738b856da6ab36d0efe0aa3446959a98/src/vs/workbench/api/common/extHost.protocol.ts#L1383)
This was causing parsing to fail.
__Defect:__ Our parser was expecting the `detail` field (along with others) to either be present as a string or not present at all. The parser wasn't resilient in the case where the field was there, but `null`.
__Fix:__ Instead of using `field.optional`, use `field.withDefault` along with a `None` default value.
__Future work:__
Potentially `field.optional` should just work like this …
> fix(extension/#3787): Fix completion item parsing resiliency

- LICENSE.md
- README.md
- docs/docs/other/faq.md
This change converts the source code license to MIT, from a proprietary EULA.
Unfortunately, as I haven't been able to contribute much to the project lately - I'm hoping this can help lower the barrier to entry to contributing (it's already really hard as it is, due to the technology used!) This will also make it easier to use Onivim with source-based package managers like AUR.
I'd like to open the downloads as well down the road, but there's still a few things I need to get figured out before I can do that.
> docs: Convert source code to MIT license

- .gitattributes
After these changes: 
Up to that moment, C is main, mostly because of [vendored sqlite](https://github.com/onivim/oni2/blob/fda6bf7f3bb8caa6bc66225d36886a07a7a1579a/bench/reason-treesitter/sqlite3.c)
> Fix linguist tool configuration
