onivim/oni2

- src/editor/bin/Oni2.re
Port over the simple prototype for using a font-awesome icon via Revery.
> Prototyping: Font-awesome

- Oni_UI.opam
- package.json
- src/editor/UI/Root.re
- src/editor/UI/dune
- src/editor/bin/Oni2.re
- src/editor/bin/dune
This adds an `Oni_UI` module where we can put UI-related components, and factors out our existing 'Hello, World' UI to a `<Root />` component.
Next step is to actually build out some interesting UI components!
I'll be porting over some of the mocked-up UI components from the prototyping:
- `<Tab />`, `<Tabs />`
- `<Editor />`
> Initial UI Module

- esy.lock/index.json
- package.json
This picks up https://github.com/esy-packages/esy-cmake/pull/15
> Bugfix: Pick up fix for 'esy-cmake'

- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/UI/Editor.re
- src/editor/UI/Root.re
This adds a notion of tabs to the `State.t` for the application, and uses that to drive the UI.
As a next step - we should hook up the `tabline_update` `redraw` notification from Neovim, and hook it up to our reducer / state management, so we are getting the latest values from Neovim.
> State: Use tab state from application state

- src/editor/Core/Actions.re
- src/editor/Core/Buffer.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/Types.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/StatusBar.re
- src/editor/bin/Oni2.re
- test/editor/Core/BufferTests.re
- test/editor/Core/Helpers.re
WIP to start tracking buffer state (and handling buffer updates) for a single buffer in Oni2.
__TODO:__
> State: Initial buffer state

- src/editor/Core/Actions.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/TokenizedBufferView.re
- src/editor/Core/Tokenizer.re
- src/editor/Core/Types.re
- src/editor/Neovim/Notification.re
- src/editor/Neovim/Types.re
- src/editor/UI/EditorSurface.re
- src/editor/bin/Oni2.re
- test/editor/Core/Helpers.re
- test/editor/Core/TokenizerTests.re
This adds a very minimal, basic cursor hooked up to the buffer-space cursor position events added in #30
> UI: Initial Cursor Implementation

- test/editor/Neovim/NeovimApiTests.re
Example of calling `nvim_call_atomic` and parsing the result
> Test: nvim_call_atomic

- src/editor/Core/EditorView.re
- src/editor/Core/State.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/UI/Minimap.re
Right now the minimap was static - it never scrolled. This changes it so that it is synchronized and moves with the current scroll region.
> UI - Minimap: Synchronize scroll

- src/editor/Core/Types.re
- src/editor/Neovim/NeovimProtocol.re
- src/editor/UI/Editor.re
- src/editor/UI/GlobalContext.re
- src/editor/UI/Tab.re
- src/editor/UI/dune
- src/editor/bin/Oni2.re
Add ability to open buffer by clicking on the tab
~~- [x] Update buffer correctly on `bufEnter` so content is not duplicated~~
This bug is present on master and relates to the fact that the `changedtick` is not being updated properly not sure exactly why but the check in the `Buffer.update` function always fails. So i'd like to separate a fix for that from this as I'm also looking into `close` functionality for the tabs and I'd like to build off of this PR
> open file functionality

- .ci/esy-check-hygiene.yml
- azure-pipelines.yml
- dune-project
- package.json
- src/editor/UI/EditorSurface.re
- src/editor/UI/Tab.re
- test/editor/Neovim/Helpers.re
Add a helper in CI for hygiene checks: consistent formatting + lockfiles
This also adds an `esy format` command that can help with formatting 👍
> CI: Enforce formatting

- src/editor/Core/Editor.re
- src/editor/Core/Reducer.re
- src/editor/UI/EditorVerticalScrollbar.re
Almost every editor function needed the line height - this refactors it to include it in the state.
> Refactoring: Include line height in editor view state

- src/editor/UI/EditorSurface.re
- src/editor/UI/FlatList.re
- src/editor/bin/Oni2.re
This fixes up the line numbers & brings back scrollwheel behavior.
> Performance: Editor Surface direct draw - part 2

- .prettierrc
- src/editor/Core/Actions.re
- src/editor/Core/ColorMap.re
- src/editor/Core/ColorizedToken.re
- src/editor/Core/Oni_Core.re
- src/editor/Core/SyntaxHighlighting.re
- src/editor/Core/TextmateClient.re
- src/editor/Core/Tokenizer.re
- src/editor/Core/Types.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/Minimap.re
- src/editor/bin/Oni2.re
- src/textmate_service/src/index.ts
- test/editor/Core/TextmateTokenizerTests.re
- test/editor/Core/TokenizerTests.re
This is starting a V1 of the buffer sync protocol for textmate highlighting (full buffer sync).
Nice to finally see some color!
> Textmate: Buffer sync protocol

- bench.esy.lock/index.json
- esy.lock/index.json
- package.json
- src/editor/bin/Input.re
- src/editor/bin/Oni2.re
This adds logic to handle some additional keys that weren't handled before (ie, lots of `<ctrl+` keys weren't handled).
> Input: Additional key handling

- src/editor/Neovim/NeovimApi.re
Fixes #86
This PR increases the timeout of NeovimApi `requestSync` to 10 seconds, and adds debugging information would this timeout fail as well.
`Msgpck` renamed to `M` for consistency with the rest.
> Fix #86: requestSync timeout not handled

- src/editor/Core/Setup.re
- src/editor/Model/Editor.re
- src/editor/bin/Cli.re
- src/editor/bin/Oni2.re
This adds some basic support for argument parsing using the OCaml `Args` module. This just allows files / directories to be passed to Onivim 2. We could expand our usage to handle additional options down the road.
> Feature: Initial CLI implementation

- extensions/vscode-reasonml/ocaml.configuration.json
- extensions/vscode-reasonml/package.json
- extensions/vscode-reasonml/reason.configuration.json
- src/editor/Extensions/ExtensionContributions.re
- src/editor/Extensions/ExtensionManifest.re
- src/editor/Extensions/ExtensionScanner.re
- src/editor/Extensions/ExtensionScanner.rei
- src/editor/Extensions/Oni_Extensions.re
- src/editor/bin/Oni2.re
This implements an initial `ExtensionScanner` that parses and loads VSCode extension metadata.
> Extensions: Implement initial extension scanner

- src/editor/Core/Filesystem.re
> Swap home location on Windows.

- bench.esy.lock/index.json
- esy.lock/index.json
- package.json
Picks up a fix in rench (https://github.com/bryphe/rench/pull/25) that fixes #213
> Dependency: rench -> 1.6.1

- src/editor/Model/Actions.re
- src/editor/Model/Commands.re
- src/editor/Store/MenuStoreConnector.re
- src/editor/UI/MenuItem.re
- src/editor/UI/MenuView.re
> Make menu items clickable and change selection on hover

- README.md
I presume one has to enter the directory that contains the package.json file before typing `esy install`
> Add step to build process

- src/editor/Core/Constants.re
- src/editor/Core/Types.re
- src/editor/Model/Diagnostics.re
- src/editor/Model/Diagnostics.rei
- src/editor/Model/Oni_Model.re
- src/editor/Model/State.re
- test.json
- test/editor/Model/DiagnosticsTests.re
- test/editor/OniUnitTestRunnerModel.re
- test/editor/dune
This implements a very simple diagnostics state management.
The next steps for this are:
- Hook up to EditorSurface so we can render in the scrollbar / minimap / editor surface
- Pipe in data from the extension host client
> Feature: Diagnostics - Initial State Management

- .ci/esy-build-steps.yml
- package.json
The `esy test` command wasn't updated, so it failed to run. I've linked that through now, and also removed the CI option from there since we don't especially need it there.
Also updated the CI to upload the JUnit test files.
> Tidy up test commands, and fix CI test upload.

- CONTRIBUTING.md
> Contributing: make installation instructions in codeblocks rather than in list

- src/editor/Core/IndentationGuesser.re
- src/editor/Core/IndentationSettings.re
- src/editor/Core/Oni_Core.re
- test/editor/Core/IndentationGuesserTests.re
- test/editor/Core/IndentationTests.re
This is the first part of implementing an auto-detect indentation option - this takes an array of lines, and figures out which indentation strategy should best match it.
> Feature: Indentation Guesser

- src/editor/Core/Range.re
- src/editor/Core/Range.rei
- src/editor/UI/EditorSurface.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/UI/Minimap.re
This change highlights the visual range in both the minimap and vertical scrollbar:
> Feature: Show visual selection in Minimap

- bench.esy.lock/index.json
- bench.esy.lock/opam/menhir.20190626/opam
- esy.lock/index.json
- esy.lock/opam/menhir.20190626/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/menhir.20190626/opam
- update-lockfiles.sh
This picks up a few bug fixes that are in `libvim` and `reason-libvim`, like #358
> Dependency: reason-libvim -> 8.10869.12001

- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/UI/EditorGroupView.re
Add 'workbench.editor.showTabs' option. Verified by setting the value to
false and make sure we don't see any tabs.
New to `reason` so let me know if I make any stupid mistakes :-P.
> Configuration - Add 'workbench.editorshowTabs' option

- src/editor/Store/ConfigurationStoreConnector.re
My attempt to implement  #366
It should work but I'm not sure I've done it the best way so don't hesitate if you see any improvement.
> Configuration: Auto-reload when saving

- CONTRIBUTING.md
Fixes #140 - adds additional pre-requisites to docs
> Fix #140 - Update CONTRIBUTING.md with additional pre-reqs

- src/editor/Store/VimStoreConnector.re
Tiny PR to pipe this through and update the explorer.
The quick open seems to just use the `cwd` already, so this isn't necessary for that.
> Hook up onDirectoryChanged to Explorer.

- src/editor/Model/Wildmenu.re
> Only increment or decrement the selected item, when items exist.

- azure-pipelines.yml
- scripts/release.js
- src/editor/Core/Cli.re
- src/editor/Core/HealthCheck.re
- src/editor/bin_launcher/Oni2.re
This adds a `--checkhealth` flag which is mostly for internal use. This will be used as a quick sanity check to validate our app bundles.
> Feature: Health checks

- src/editor/UI/Tab.re
Fix #322 - add ability to close tabs with middle click
> Fix #322 - Close tab with middle click

- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/Model/Actions.re
- src/editor/Model/CommandPalette.re
- src/editor/Model/Reducer.re
- src/editor/Model/State.re
- src/editor/UI/EditorGroupView.re
- src/editor/UI/EditorView.re
- src/editor/UI/Root.re
> implement zen mode

- src/editor/Model/FileExplorer.re
This is just a different implementation of the same thing (#377) Not sure if it's worth merging, but to me it is a bit more readable.
Feel free to close if it doesn't add any value.
> change sorting of the file explorer

- src/editor/Model/Actions.re
- src/editor/Model/Editor.re
- src/editor/Store/VimStoreConnector.re
Fix #424
Change to fix buffer walking.
I've made this WIP for now, since I want to give it a more thorough check over with a clean pair of eyes in a day or so. Its pretty confusing looking over the various types of One vs Zero indexed parts, and working out if bits should be +1 or not...
This does fix the issue, but just want to ensure it makes sense and doesn't change anything else.
> Fix Buffer Walking

- docs/docs/getting-started/why-onivim.md
Fixes #534 - thanks @dfroger for catching this!
> Fix #534 - Doc typo: Misplaced parentheses

- src/editor/Core/Cli.re
**ONLY Tested on MacOS**
Closes #579
> Fix root path explicit open on MacOS

- src/editor/Model/CommandPalette.re
- src/editor/Store/WindowsStoreConnector.re
- test/editor/Core/UtilityTests.re
Depends on the work done #605. Solves part 2 of #439 and by extension solves the issue in its entirety. 🎉
> Splits (Rotation) - Part 2

- src/editor/bin_editor/Input.re
My attempt to Fix #608.
I have not been able to test the INSERT key because I'm not sure how to simulate it on my mac 😆
> Fix #608: Input: Home / End / Insert buttons aren't working 

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Upgrades `reason-libvim` to pick up @KevinSjoberg 's change: https://github.com/onivim/reason-libvim/pull/63
> Dependency: reason-libvim -> 5c81c76

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up the `onYank` API from https://github.com/onivim/reason-libvim/pull/62
> Dependency: reason-libvim -> 490ed3f

- src/editor/Store/VimStoreConnector.re
Depends on the work done in https://github.com/onivim/reason-libvim/pull/63. This pull request add the ability to trigger window rotation using `c-w r` and `c-w R`. 🎉
> Map Vim window rotation types to actions

- src/editor/Model/Actions.re
- src/editor/Model/CommandPalette.re
- src/editor/Model/Reducer.re
- src/editor/Store/ConfigurationStoreConnector.re
Adding EnableZenMode and DisableZenMode.
I left `ToggleZenMode` in there for now. Probably we should remove it though. Not sure. Any opinions?
Fixes #634 
/cc @tcoopman as this was your idea :heart:
> add EnableZenMode and DisableZenMode actions

- extensions/go/language-configuration.json
- extensions/go/package.json
- extensions/go/package.nls.json
- extensions/go/syntaxes/go.tmLanguage.json
As requested here: #601 
I tried it a bit and the syntax highlighting seems to work for me.
> Added syntax highlighting for golang

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/editor/UI/CommandlineView.re
- src/editor/UI/EditorHorizontalScrollbar.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/MenuView.re
- src/editor/UI/OniInput.re
- src/editor/UI/Tab.re
- src/editor/UI/WildmenuView.re
- test.esy.lock/index.json
Pick up the `<Opacity />` and `<BoxShadow />` components, as well as hit testing fixes.
> Dependency: revery -> 0.26.0

- src/editor/UI/EditorGroupView.re
- src/editor/UI/FlatList.re
- src/editor/UI/MenuItem.re
- src/editor/UI/MenuView.re
- src/editor/UI/Overlay.re
- src/editor/UI/Root.re
This improves the mouse behavior in the Menu (there's still a lot missing - ie, a scrollbar) - but this fixes makes the items clickable again.
This is dependent on a fix in Revery: https://github.com/revery-ui/revery/pull/536
> Fix #665 - Part 1 - Menu items are not clickable

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This bug was causing issues getting the complete set of items from ripgrep on Mac/Linux -
> Dependency - Rench: Pick up bug fix for pipe being closed too early

- src/editor/Input/Parser.re
Kind of a hack to unblock recording a gif... need to fix this in the more general case!
> Fix control+tab display for keydisplayer

- src/editor/UI/OniInput.re
__Issue:__  Everytime QuickOpen is opened, the idle cpu usage increases. 
__Defect:__ Initially, I suspected the ripgrep process was sticking around, or some of the threads we use for I/O were not being stopped. However, the actual cause turned out to be the timer we use for cursor blinking for input was never being disposed - so every time we created a quickopen, we'd actually trigger a timer that would cause a re-reconciliation, re-layout, and re-render of the UI. The root cause is actually in brisk-reconciler here: https://github.com/briskml/brisk-reconciler/pull/40
__Fix:__ For now, we'll turn off the cursor blinking since it degrades performance. However, we'll need to fix https://github.com/briskml/brisk-reconciler/pull/40 at some point!
> Fix #304 - Idle CPU usage increases every time QuickOpen is used

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up a few perf improvements
> Dependency: reason-textmate -> 1.2.0

- bench.esy.lock/index.json
- bench.esy.lock/opam/dune-configurator.1.0.0/opam
- bench.esy.lock/opam/lwt.4.3.0/opam
- bench.esy.lock/opam/ppx_deriving_yojson.3.5.1/opam
- esy.lock/index.json
- esy.lock/opam/dune-configurator.1.0.0/opam
- esy.lock/opam/lwt.4.3.0/opam
- esy.lock/opam/ppx_deriving_yojson.3.5.1/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/dune-configurator.1.0.0/opam
- integrationtest.esy.lock/opam/lwt.4.3.0/opam
- integrationtest.esy.lock/opam/ppx_deriving_yojson.3.5.1/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/dune-configurator.1.0.0/opam
- test.esy.lock/opam/lwt.4.3.0/opam
- test.esy.lock/opam/ppx_deriving_yojson.3.5.1/opam
Pick up fix for issues finding `libonig.2.so` on some Linux platforms
> Dependency: reason textmate -> 1.3.0

- azure-pipelines.yml
Fix build failure on Linux in CI environment
> Azure CI: Add libgl1-mesa-dev and libglu1-mesa-dev to linux environment

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This change brings in an update to `reason-sdl2` which addresses #808
> Dependency: revery -> 3f1655e

- docs/MOTIVATION.md
Also, this is a bit outdated so consider it a nudge as well ;) Very interesting and enlightening though!
> Fix typos in MOTIVATION.md

- extensions/theme-gruvbox/.vscodeignore
- extensions/theme-gruvbox/cgmanifest.json
- extensions/theme-gruvbox/package.json
- extensions/theme-gruvbox/package.nls.json
- extensions/theme-gruvbox/themes/gruvbox-dark-hard.json
- extensions/theme-gruvbox/themes/gruvbox-dark-medium.json
- extensions/theme-gruvbox/themes/gruvbox-dark-soft.json
- extensions/theme-gruvbox/themes/gruvbox-light-hard.json
- extensions/theme-gruvbox/themes/gruvbox-light-medium.json
- extensions/theme-gruvbox/themes/gruvbox-light-soft.json
Added gruvbox themes from https://github.com/jdinhify/vscode-theme-gruvbox
> Added gruvbox themes

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This pulls in https://github.com/revery-ui/revery/pull/604 which fixes #587 by listening to the window 'exposed' event to trigger a re-render.
> Fix #587: i3 Rendering Problem (Dependency: revery -> 86bf216 )

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up a Revery fix to unblock screensaver / sleep 😬 Thanks @mrkishi for catching this!
> Bugfix: Onivim 2 blocks screensaver / sleep (Dependency: Revery -> 9ef07f3)

- azure-pipelines.yml
OSX cache restore is failing - will remove while investigating to unblock other PRs.
> CI: Remove OSX caching for now

- esy.lock/index.json
- src/Core/Utility.re
- src/Model/Wildmenu.re
- src/Store/MenuStoreConnector.re
- src/UI/EditorSurface.re
- src/UI/FlatList.re
- src/UI/ImmediateList.re
- src/UI/MenuView.re
- src/UI/Minimap.re
- src/UI/OniInput.re
- src/UI/WildmenuView.re
Split out from #858 
Fixes the first point of #818
Fixes #469 
Fixes #321 
Fixes #314 
Fixes #219
> Menu Renovation - Part 1: Easy pickings

- src/Core/Oni_Core.re
- src/Core/Ripgrep.re
- src/Core/Subscription.re
- src/Core/Subscription.rei
- src/Store/MenuJobSubscription.re
- src/Store/QuickOpenStoreConnector.re
- src/Store/RipgrepSubscription.re
Split out from #858. Based (ie. depends) on #894
This (mostly) just adds the subscription infrastructure, but does not actually employ it for anything. That comes later.
> Menu Renovation - Part 2: Subscribption Infrastructure

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This picks up @glennsl 's fix https://github.com/revery-ui/revery/pull/621
> Dependency: revery -> 2db8df7

- test/Core/UriTests.re
- test/Core/UtilityTests.re
This is (actually) intentionally submitted to oni2/master. Will clean up later :)
> Gotta break a few eggs to make an omelette!

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up revery-ui/revery#651, which fixes #963
> Dependency: revery -> b07c66e

- integration_test/lib/Oni_IntegrationTestLib.re
From #993 - we shouldn't be picking up user configuration for testing.
This can cause unpredictable test results, only-fails-on-my-machines-type-issues, and expensive investigations... along with the inconvenience of having to toggle your config for tests!
This  PR _always_ creates a configuration file for the integration tests, to avoid picking up the user configuration, but uses an empty one if no configuration is specified (so defaults would be picked up)
> Integration Test: Don't use user configuration for testing

- ThirdPartyLicenses.txt
- scripts/bootstrap.js
- scripts/linux/package-linux.sh
- scripts/release.js
- src/Core/HealthCheck.re
- src/Core/Setup.re
- src/Core/Utility.re
This is laying out some prep work to bundle `reason-language-server` with Onivim 2. Specifically, we need to ship the executables alongside the `Oni*.exe` executables - important for OSX since all the binaries need to be in one place to pass notarization.
This change:
Once this is in, we'll add the `reason-language-server` VSCode extension and pass it the appropriate config to pick up our 'vendored' binaries.
> Extension: Vendor reason-language-server binaries

- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostTransport.re
- Downgrade 'Not implemented' messages from errors -> warnings
- Downgrade 'Unmatched reply' messages from errors -> warnings
> ExtHost: Downgrade a few errors -> warnings

- docs/docs/using-onivim/command-line.md
> Docs: Update CLI page according to Logging changes [no-ci]

- docs/docs/for-developers/contributing.md
Just a brief description added to our developer docs around branch naming-
> Docs - Developer: Document branch naming

- src/UI/EditorSurface.re
This just helps sort out issues I was seeing where you could click outside the buffer and the selected line would seem to move. (I.e. open Oni2 and just click in the buffer that isn't line 1).
For now I've gone with a "don't move at all" but I could see that "move to the last line" would also be nice, so any opinions?
> Only move the selected line if there is actually a line to move to.

- src/Core/Ripgrep.re
- src/Model/FilterJob.re
- test/Model/FilterJobTest.re
Fixes #818 
Addresses #1017 
This gist of this is just a switch from using `list` to `Queue.t` for the processing in `FilterJob` and `Ripgrep` to prevent the reversion that naturally occurs when working recursively with `list`s. But since `Queue.t` is a mutable data structure this wasn't just a slot-in replacement. So while I was at it I also took the opportunity to clean these modules up a bit and remove a lot of the imperativeness from them.
> Fix #818 - Non-deterministic Fuzzy search results

- src/Store/CommandStoreConnector.re
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/QuickmenuStoreConnector.re
> Emulate vscode's ctrl+tab behaviour

- bench/lib/FilterJobBench.re
- src/Model/FilterJob.re
> Fix #1037 - Quickopen not showing full set of results

- src/Core/Ripgrep.re
- src/Core/Ripgrep.rei
- src/Store/QuickmenuStoreConnector.re
- src/Store/RipgrepSubscription.re
Closes #860
added `--hidden` flag to rg cmd
added globs to rg command using filesExclude config, this makes
filter results like .git node_modules etc.
> Include hidden files in quick open

- src/Syntax_Client/Oni_Syntax_Client.re
With #1135 , there was a change for an intermittent exception - this fixes it by 'safely' closing the channels.
> Bugfix: Fix BADF exception

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Downgrade revery, until we fix the key-repeat issue.
> (Temporary) Fix for #1149: Downgrade revery 99441c7 -> d2fd73b

- src/Store/SyntaxHighlightingStoreConnector.re
- src/Syntax_Server/Oni_Syntax_Server.re
Fixes #1144 (Need to test on non-Windows)
Clean up the language server process when finished.
> Cleanup syntax server process

- docs/docs/configuration/settings.md
- docs/docs/for-developers/building.md
- docs/docs/using-onivim/command-line.md
Just updates the CLI docs.
Hoping to get the Linux "Add to PATH" stuff sorted soon.
> Update PATH docs.

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up @glennsl 's `Effect.map` API: https://github.com/bryphe/isolinear/pull/7
> Dependency: isolinear -> 2.3.0

- src/Components/InputModel.re
Small improvements for input navigation:
- Positions cursor to beginning on pressing `Home`
- Positions cursor to the end on pressing `End`
> Updates input model to handle keypress of Home/End buttons

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/bin_editor/Oni2_editor.re
- test.esy.lock/index.json
This should address #1222 , by picking up https://github.com/revery-ui/revery/pull/716, which brings back @CrossR 's fix https://github.com/revery-ui/revery/pull/704
> Dependency: revery -> 7ede78a

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
FYI, @glennsl - this picks up the box shadow changes to unblock #1211
> Dependency: revery -> 8aa55f3

- azure-pipelines.yml
- bench.esy.lock/index.json
- bench.esy.lock/opam/conf-pkg-config.1.1/opam
- bench.esy.lock/opam/ctypes-foreign.0.4.0/opam
- bench.esy.lock/opam/ctypes.0.15.1/opam
- bench.esy.lock/opam/integers.0.3.0/opam
- bench.esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
- bench.esy.lock/overrides/opam__s__ctypes_opam__c__0.15.1_opam_override/package.json
- esy.lock/index.json
- esy.lock/opam/conf-pkg-config.1.1/opam
- esy.lock/opam/ctypes-foreign.0.4.0/opam
- esy.lock/opam/ctypes.0.15.1/opam
- esy.lock/opam/integers.0.3.0/opam
- esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
- esy.lock/overrides/opam__s__ctypes_opam__c__0.15.1_opam_override/package.json
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/conf-pkg-config.1.1/opam
- integrationtest.esy.lock/opam/ctypes-foreign.0.4.0/opam
- integrationtest.esy.lock/opam/ctypes.0.15.1/opam
- integrationtest.esy.lock/opam/integers.0.3.0/opam
- integrationtest.esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
- integrationtest.esy.lock/overrides/opam__s__ctypes_opam__c__0.15.1_opam_override/package.json
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/conf-pkg-config.1.1/opam
- test.esy.lock/opam/ctypes-foreign.0.4.0/opam
- test.esy.lock/opam/ctypes.0.15.1/opam
- test.esy.lock/opam/integers.0.3.0/opam
- test.esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
- test.esy.lock/overrides/opam__s__ctypes_opam__c__0.15.1_opam_override/package.json
This will exercise shipping w/ Skia (even though Skia isn't used yet)
> Dependency: revery -> eeda678

- src/Core/Uri.re
- src/Core/Uri.rei
Also adds a `query` field, as that's used for the `git` scheme.
> SCM: Add support for git and custom schemes to Uri

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This brings in the fix for the build failure on Arch Linux
> Dependency: reason-harfbuzz -> 0848520

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
> [WIP] Upgrade to OCaml 4.9.0

- src/Feature/Search/Feature_Search.re
> Bugfix: Don't clear search results when query hasn;t changed

- node/package.json
- node/yarn.lock
- scripts/osx/codesign.sh
Bring back `vscode-exthost@1.33.4`, and fix the code sign / notarization issues.
> Dependency: vscode-exthost -> 1.33.4

- src/Components/ContextMenu.re
- src/Components/ContextMenu.rei
- src/Components/Tooltip.re
- src/Components/Tooltip.rei
- src/UI/FileTreeView.re
- src/UI/Root.re
I'd add a screenshot but, you know, it's a tooltip...
> File Explorer: Add tooltips

- bench.esy.lock/index.json
- bench.esy.lock/opam/psq.0.2.0/opam
- esy.lock/index.json
- esy.lock/opam/psq.0.2.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/psq.0.2.0/opam
- package.json
- src/Components/ContextMenu.re
- src/Components/CustomHooks.re
- src/Components/FlatList.re
- src/Components/Input.re
- src/Components/LocationList.re
- src/Feature/Editor/SurfaceView.re
- src/UI/TreeView.re
- test.esy.lock/index.json
- test.esy.lock/opam/psq.0.2.0/opam
Update Revery + brisk-reconciler - bring in `Hooks.ref`
> Dependency: Revery -> a525e7f

- src/Store/QuickmenuStoreConnector.re
Small change that resets the focused element when the text in the search field changes
> feat: Reset focus index when the input changes

- docs/docs/using-onivim/command-line.md
- src/Core/Cli.re
- src/Core/Kernel/Log.re
- src/Core/Kernel/Log.rei
- src/bin_launcher/Oni2.re
Adds a `--quiet` CLI option that sets the log level to `error`.
> Add peace and --quiet

- docs/docs/for-developers/building.md
0.6.0 is the latest version currently available. I currently am looking to try building and it appears 0.6.2 is not a thing yet?
Not sure what the right answer is, but making an assumption here :)
> Update Esy Version Required

- bench.esy.lock/index.json
- bench.esy.lock/opam/cmdliner.1.0.2/opam
- bench.esy.lock/opam/ppx_deriving_yojson.3.5.2/opam
- esy.lock/index.json
- esy.lock/opam/cmdliner.1.0.2/opam
- esy.lock/opam/ppx_deriving_yojson.3.5.2/opam
- integration_test/dune
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/cmdliner.1.0.2/opam
- integrationtest.esy.lock/opam/ppx_deriving_yojson.3.5.2/opam
- package.json
- scripts/docker/centos/Dockerfile
- test.esy.lock/index.json
- test.esy.lock/opam/cmdliner.1.0.2/opam
- test.esy.lock/opam/ppx_deriving_yojson.3.5.2/opam
This integrates the address sanitizer (ASAN, via `-fsanitize=address`), to help validate our runtime behavior.
> Tests: Integrate address sanitizer in integration_test (on Linux)

- src/Feature/SCM/Feature_SCM.re
Fixes #1358 
The SCM UI is very preliminary, but no reason to not have a scrollbar when adding it is so trivial.
I'm also looking at fixing the extension list, but that's trickier because it involves the FlatList, with all its edge cases.
> add scroll bar to SCM Pane (fix #1358)

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Fixes #1357  - picks up https://github.com/onivim/reason-libvim/pull/95
> Fix #1357: Replace mode not shown

- src/Service/Terminal/Service_Terminal.re
We weren't handling key presses like `Control+C` in the terminal... this is a problem if you want to be able to kill running processes
> Bugfix - Terminal: Handle characters like <C-c> in the terminal

- azure-pipelines.yml
- Cancel pending PRs
- Add `README.md` to exclude path
> CI: Improve pipeline triggers

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up upgrades to SDL2 and Skia
> Dependency: revery -> 26b1161

- src/Core/IndentationGuesser.re
- test/Core/IndentationGuesserTests.re
> Bugfix: prevent IndentationGuesser from considering a single space as indentation

- src/Store/QuickmenuStoreConnector.re
Several updates to wild menu:
So it happen miss between what editor have and vim have.
> Proper mouse click handling for wild menu

- src/Store/CommandStoreConnector.re
- src/Store/IndentationStoreConnector.re
> Add command to manually trigger indentation detetction

- src/Feature/Editor/CursorView.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/SurfaceView.re
Removed in #1464. I don't know what I was thinking and the QA department is on vacation...
> Bugfix: bring back the insert mode cursor

- docs/docs/using-onivim/command-line.md
If there's a better place for this, please let me know!
> Add Documentation for Git Default Editor

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Core/Theme.re
- src/Feature/Theme/GlobalColors.re
- test.esy.lock/index.json
Picks up libvim fixes for:
- https://github.com/onivim/oni2/issues/1417
- https://github.com/onivim/oni2/issues/1092
(Fixes #1417 and #1092 )
> Dependency: reason-libvim -> 0640e6b

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Service/Font/Service_Font.re
- src/Service/Syntax/Service_Syntax.re
- src/Service/Terminal/Service_Terminal.re
- src/Store/StoreThread.re
- test.esy.lock/index.json
Upgrade to the latest `isolinear` API
Depends on:
> Dependency: isolinear -> b17ce17

- src/Core/Buffer.re
- src/Core/Buffer.rei
- src/Store/IndentationStoreConnector.re
- src/UI/EditorGroupView.re
Fixes #1190 (with a bit of help from #1465)
> Guess indentation on heuristically assumed paste into empty buffer

- README.md
Small grammar fixes and update year
> Grammar fixes -- README.md

- src/Feature/Editor/EditorConfiguration.re
...needs a bit more polish and fixing before we could consider enabling it by default 😉
> Bugfix: Fix experimental smooth scroll default

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Fixes #1520 by picking up https://github.com/onivim/libvim/pull/193
> Dependency: reason-libvim -> 3ead103

- .ci/clean-linux-deps.yml
- .ci/run-integration-tests.yml
- azure-pipelines.yml
- scripts/docker-test.sh
Looking at recent CI runs - I'm seeing several where the linux machines are running out of space:
```
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
ocamlopt integration_test/AddRemoveSplitTest.exe (exit 2)
```
Another fix in the vein of #1576 and #1483
> CI - Linux: More disk space issues

- src/Store/KeyBindingsStoreConnector.re
> Bugfix: add terminalFocus to quickOpen keybinding

- docs/docs/configuration/key-bindings.md
Added in https://github.com/onivim/oni2/pull/1629
> [docs] update keybindings with new zoom additions

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This picks up https://github.com/revery-ui/revery/pull/821 , which fixes https://github.com/onivim/oni2/issues/1657
> Dependency: revery -> e108530

- docs/docs/for-developers/building.md
- Comply with new install method for MacOS
> Update building docs (#1667)

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This brings in the clang 10 build fixes and a few minor additions to `Window`
Fixes #1679
> Dependency: revery -> 9f725e0

- src/Core/Utility/ListEx.re
- src/Exthost/Diagnostic.re
- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Msg.re
- src/Exthost/OneBasedRange.re
- src/Exthost/dune
- test/Exthost/DiagnosticsTest.re
- test/collateral/extensions/oni-diagnostics/extension.js
- test/collateral/extensions/oni-diagnostics/package.json
Implement several other API notifications for the main thread:
- DocumentContentProvider
- Decorations
- Diagnostics
And add a test case for diagnostics.
> Exthost - DocumentContentProvider, Decorations, Diagnostics

- bench.esy.lock/index.json
- bench.esy.lock/opam/reason.3.6.0/opam
- esy.lock/index.json
- esy.lock/opam/reason.3.6.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/reason.3.6.0/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/reason.3.6.0/opam
> Dependency: add fs, fp, dir

- src/Feature/Changelog/Feature_Changelog.re
> fix(other/#1758): crash on missing changelog asset

- bench.esy.lock/index.json
- bench.esy.lock/opam/merlin-extend.0.5/opam
- esy.lock/index.json
- esy.lock/opam/merlin-extend.0.5/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/merlin-extend.0.5/opam
- package.json
- src/Model/Actions.re
- src/Model/State.re
- src/Store/Reducer.re
- src/UI/Root.re
- src/UI/Titlebar.re
- src/bin_editor/Oni2_editor.re
- test.esy.lock/index.json
- test.esy.lock/opam/merlin-extend.0.5/opam
Before the titlebar was hidden when the window was maximized. Now it's hidden when the window is fullscreen!
> fix(macos/#1462): fix macOS titlebar conditional rendering

- src/bin_editor/Cli.re
- src/bin_editor/Oni2_editor.re
- test.json
- test/Cli/CliTest.re
- test/Cli/Test.re
- test/Cli/TestFramework.re
- test/Cli/TestRunner.re
- test/Cli/dune
- test/OniUnitTestRunner.re
- test/OniUnitTestRunnerCI.re
- test/OniUnitTestRunnerCLI.re
- test/dune
Looking at #1784 and #1791 - we don't have good test coverage of our CLI today.
This adds some test infrastructure so that we can have some basic cases against our CLI.
> test(cli): Add some test cases to validate CLI functionality

- .ci/esy-build-steps.yml
- test/Exthost/Test.re
...and turn down number of runs until the exthost tests are stabilized.
> test(exthost): Lower verbosity - don't log out every message

- docs/docs/using-onivim/moving-in-onivim.md
Just a minor typo in the docs.
> Fix docs for search commands

- src/Store/ExtensionClient.re
Useful mostly for debugging purposes.
> chore(exthost): redirect exthost I/O streams to stdin/stderr

- src/Feature/Editor/Minimap.re
Minor fix for scrolling via minimap-drag-thumb - this records the offset (the mouse position relative to the top of the thumb), and preserves that offset while the minimap thumb is being dragged. This is a bit more predictable behavior than the previous strategy.
> fix(editor): Minimap scroll fix when dragging thumb

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Picks up some fixes and new features in Revery - LinearGradient, DPI fix for Linux.
> refactor(dependency): Revery -> 12fb2dc 

- azure-pipelines.yml
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Layout.re
- src/Feature/Layout/Positioned.re
- src/Store/KeyBindingsStoreConnector.re
This adds the ability to maximize a window, either vertically, horizontally or both, and to toggle/revert it back to the previous layout.
Fixes #1641
> feat(layout): maximize window

- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Layout.re
Implements directional resizing, meaning window size can be increased or decreased left or right specifically.
Fixes #1643 
Depends on #1917
> feat(layout): directional resizing

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This brings in https://github.com/onivim/libvim/pull/208 - an API for us to hook in to auto-indent (to decrease / increase indent when opening a line, based on language configuration).
> refactor(dependency): libvim -> 8.10869.47

- src/Core/Oni_Core.re
- src/Core/WordWrap.re
- src/Core/WordWrap.rei
- src/Feature/Editor/EditorBuffer.re
- src/Feature/Editor/EditorBuffer.rei
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Wrapping.re
- src/Feature/Editor/Wrapping.rei
- test/Core/WordWrapTests.re
- test/Feature/Editor/WrappingTests.re
Initial (WIP) implementation of word wrapping
Depends on #1953 
Related to #1957 #1444
> feat(editor/#1444): Initial word wrap data structures

- .ci/esy-check-hygiene.yml
- node/add-to-path.js
- node/check-health.js
- node/install-extension.js
- node/install.js
- scripts/bootstrap.js
- scripts/get-mit-commit.js
- scripts/release.js
...will be a good test of using the `prettier` extension for formatting.
Fixes #838
> fix(hygiene/#838): Add prettier to hygiene check

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Components/Markdown.re
- src/Feature/Hover/Feature_Hover.re
- src/Feature/SignatureHelp/Feature_SignatureHelp.re
- test.esy.lock/index.json
This fixes the following issues with Signature Help and Hover:
- no syntax highlighting
- incorrect font color
- text appearing too small
Fixes #1947
> fix(hover & signature help/#1947): various text display issues

- src/Feature/SignatureHelp/Feature_SignatureHelp.re
Fixes #2012. This is a strange bug because it means that the extension host is providing invalid indices, but this should fix it. Sorry I made a faulty assumption!
> fix(editor/#2012): Use nth_opt rather than nth in SignatureHelp

- src/Feature/Editor/BracketMatch.re
__Issue:__ When the cursor is on a closing-bracket character, the editor would highlight an outer set of brackets, rather than the set of brackets on the cursor.
__Fix:__ When the cursor is on a closing bracket, start the search before the bracket so it does not get included in the bracket count.
> fix(editor): Bracket Matching - bracket match not correct when on closing character

- README.md
I'll admit I may be a _bit_ biased in the features I decided to showcase (font variants and signature help 😆), so if anyone has any recommendations, I'd be happy to add them.
Here's the screenshot I used:
> update(README): Update screenshot to showcase new features

- src/Exthost/Color.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Msg.re
- src/Exthost/ThemeColor.re
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/Theme/dune
- src/Store/ExtensionClient.re
__Issue:__ The status bar colors were hardcoded, instead of being picked up from the extension host
__Fix:__ Parse& plumb through the color specification from the statusbar
> fix(ui): StatusBar / Exthost: Wire up theme color specification from Exthost

- src/UI/WelcomeView.re
> fix(welcome): Linux / win32 shorcut key info

- node/download.js
- src/Service/Net/Service_Net.re
- src/Service/Net/Service_Net.rei
- test/Service/Net/RequestTests.re
This adds a `Service_Net.download` API for downloading resources (`vsix`, readme, icons) to support extension discovery and installation.
> feat(extensions): Add API for downloading resources

- install-node-deps.js
- scripts/generate-mit-readme.js
- scripts/get-mit-commit.js
- scripts/template.md
- scripts/update-mit-commit.sh
This finishes up the script to automatically synchronize the [`oni2-mit`](https://github.com/onivim/oni2-mit) repo with the latest MIT-relicensed commit.
> chore: MIT-commit synchronization

- src/Components/Codicon.re
For extension installation / uninstallation - need some UI to show the operation in-progress.
This updates our codicon so that we can have a spinner when installing / uninstalling extensions.
> feat(ux): Add spin property to codicon component

- azure-pipelines.yml
Bring back cache restore, now that we have a successfully master build w/ latest changes
> chore(ci): Fix cache restore

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This includes revery-ui/revery#963, which (should) fixes #2140.
> chore(deps): upgrade revery -> 53e36af

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Components/Button.re
- src/Feature/Extensions/ItemView.re
- src/Feature/Extensions/ListView.re
- src/Feature/InputText/View.re
- src/Feature/Layout/View.re
- src/Feature/Messages/Feature_Messages.re
- src/Feature/Sneak/Feature_Sneak.re
- src/Feature/Sneak/Feature_Sneak.rei
- src/UI/Dock.re
- src/UI/MenuItem.re
- src/UI/PaneView.re
- src/UI/TreeView.re
- test.esy.lock/index.json
Fixes #1660 - was also hitting this using sneak to install / uninstall extensions - would sometimes press a 'stale' button.
> fix(ux/#1660): Sneak is incorrect on re-rendered component

- src/Feature/Extensions/DetailsView.re
- src/Feature/Extensions/Feature_Extensions.rei
- src/Feature/Extensions/ItemView.re
- src/Feature/Extensions/Model.re
- src/Store/Features.re
- src/UI/EditorView.re
Adds some contextual action buttons in the details view:
> fix(extensions): Add details action buttons

- scripts/linux/package-linux.sh
Temporary workaround for: https://github.com/linuxdeploy/linuxdeploy/issues/142
> chore(ci): Fix linuxdeploy packaging step

- src/reason-libvim/bindings.c
- src/reason-libvim/config/discover.re
- src/reason-oniguruma/bindings.c
Had to cast into proper types and change the way the struct was declared.
> fixed WARNS (struct declaration style, type casts)

- src/UI/EditorView.re
Removes an unnecessary `View` component.
> refactor(editor): remove extra view component

- docs/docs/for-developers/building.md
- How to run inline tests
- How to run duno build check
- How to run esy formatter
> Updated doc to describe more test checks that we do on CI

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/Vim/Feature_Vim.re
- src/Feature/Vim/Feature_Vim.rei
- src/Store/VimStoreConnector.re
- src/UI/Root.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Register.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test.esy.lock/index.json
- test/reason-libvim/MacroTest.re
__Issue:__ There was no UI affordance to show when a macro was being recorded (tangentially related to #2357 )
__Fix:__ Add a recording indicator while a macro is being recorded:
> feat(vim): Macro indicator in status bar

- src/Exthost/DocumentsAndEditorsDelta.re
__Issue:__ The `sass` plugin was crashing here: https://github.com/TheRealSyler/vscode-sass-indented/blob/30a573466b2736ee6a6455b298e2f8b82b024601/src/extension.ts#L44 because `vscode.window.activeTextEditor.document` was crashing - `activeTextEditor` was null.
__Defect:__ We were resetting the active editor, which was good, but the next `$acceptDocumentsAndEditorsDelta` call was clearing it out - so we'd end up back to a `null` active editor. The problem was - we were sending `null` when we really meant to not set it at all, but `null` and `undefined` mean two semantically different things for that particular field.
__Fix:__ If the active text editor is not set - send `undefined` instead of `null`.
> fix(exthost): DocumentsAndEditors API: Fix newActiveEditor field being reset

- docs/docs/configuration/key-bindings.md
> docs: add section on ex command keybindings

- bench/lib/BufferBench.re
- bench/lib/WordWrapBench.re
Splitting out of some of the remaining work in #1969
> feat(editor/#1444): Part 1 - Initial benchmark for word wrap

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
Picks up revery-ui/esy-skia#25
Fixes #2508 and #2550
> chore(deps): update Skia to fix XCode 12 bug

- src/Feature/SideBar/Feature_SideBar.re
- src/Feature/SideBar/Feature_SideBar.rei
- src/Feature/SideBar/dune
- src/Store/Features.re
> fix(explorer/#2594): Unable to toggle explorer

- src/Feature/Editor/Editor.re
- test/Feature/Editor/EditorTests.re
__Issue:__ When the horizontal scroll is shifted less than a character position, the view tokens don't shift, but the cursor does - this leads to a mismatch in cursor/token rendering. This is especially apparent in high DPI/zoomed scenarios.
Example:
__Defect:__ When requesting tokens from the Editor via `Editor.viewTokens`, the first visible character would be evaluated - all tokens would be given a pixel position relative to the first character (the first character is at pixelX=0.).  The problem, though, is if the scroll doesn't match exactly to a character boundary - that clamp-to-origin won't account for the delta between the different between the scroll position and first character.
_Fix:__ Account for the delta between the token position and scroll position, and apply to rendered …
> fix(editor): Horizontal sub-character scroll causes strange cursor rendering

- src/Feature/Editor/Editor.re
- test/Feature/Editor/EditorTests.re
Related to #1637 - also fixes for wrapped lines
> fix(editor): Fix scroll offset in wrapped lines

- src/Core/ShellUtility.re
__Issue:__ When launching Onivim from finder in OSX, the `SHELL` environment variable can actually be populated - in some cases, it may differ from the shell selected by the user (`zsh` vs `bash`).
__Defect:__ We were preferring the `SHELL` variable over the user preferences
__Fix:__ Pick the user preference shell first, if available
Related to #2686
> fix(terminal/#2686): Fix default shell resolution in OSX

- src/Feature/Buffers/Feature_Buffers.re
> fix(buffers/#2605): buffer metadata not getting updated on switch to existing buffer

- src/Feature/Notification/Feature_Notification.re
- src/Feature/Notification/Feature_Notification.rei
- src/Feature/Notification/dune
- src/Store/Features.re
> fix(perf/#2407): Part 4 - Switch to model-based animation for notification yOffset

- bench.esy.lock/index.json
- bench/lib/Helpers.re
- esy.lock/index.json
- integration_test/lib/Oni_IntegrationTestLib.re
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- src/Feature/TitleBar/Feature_TitleBar.re
- src/Feature/TitleBar/Feature_TitleBar.rei
- src/Model/State.re
- src/UI/Root.re
- src/bin_editor/Oni2_editor.re
- test.esy.lock/index.json
This also integrates the macOS titlebar height API
> chore(dependencies): upgrade revery to c93fdf5

- src/oni2-keyboard-layout/stubs/keyboard-layout-mac.c
@bryphe pointed out in #2687 that it was possible we would get stale strings in `createKeymapEntry` since we didn't know when the `autoreleasepool` would release the `NSString`s. This removes the `autoreleasepool` in favor of manually allocating and releasing the `NSStrings`
> fix(KeyboardLayout): manually allocate and release NSStrings

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
Pick up several revery fixes - wrapped pointers; display FFI
> refactor(dependency): revery -> dd47c70

- docs/docs/getting-started/installation.md
- docs/docs/using-onivim/command-line.md
> docs: Add add-to-path instructions for OSX to documentation

- CHANGES.md
- CHANGES_CURRENT.md
- dune
Related #2787 
I'd like to get a new stable build (`0.5.1`) out with some recent fixes - would be nice if it had changelogs, too.
> docs: Initial CHANGES/CHANGES_CURRENT files

- CHANGES_CURRENT.md
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
- src/Feature/Snippets/Snippet.re
- src/Feature/Snippets/Snippet_internal.re
- src/Feature/Snippets/Snippet_lexer.mll
- src/Feature/Snippets/Snippet_parser.mly
- src/Feature/Snippets/dune
This is the first step in supporting snippets - having a parser to process the snippet format, and some initial plumbing / machinery to handle snippet state.
Related to #160
> feat(snippets/#160): Part 1 - Initial snippet parser & feature plumbing

- docs/docs/for-developers/building.md
Added missing "install" in command for installing esy@latest
> Added missing "install"

- CHANGES_CURRENT.md
- src/Feature/Explorer/Feature_Explorer.re
> fix(outline/#2626): Don't wrap on overflow

- CHANGES_CURRENT.md
- src/Feature/Configuration/GlobalConfiguration.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/InlineElements.re
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/dune
Enabling toggling codelens via `:set codelens`/`:set nocodelens`
> fix(codelens): Implement toggling codelens

- scripts/docker/centos/Dockerfile
Investigating failure here: https://dev.azure.com/onivim/oni2/_build/results?buildId=14836&view=logs&j=c882114c-d251-582f-8c2b-d8284d41fa9a&t=437388a4-5c2d-5309-63f6-62c9e99d3140&l=27
> chore(ci): Investigate CentOS build failure ('unzip' / esy)

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
> refactor(dependency): revery -> 3f48f6d

- .ci/esy-check-hygiene.yml
- .ci/js-build-steps.yml
- .ci/use-node.yml
- CHANGES_CURRENT.md
- install-node-deps.js
- node/package.json
- node/yarn.lock
- scripts/bootstrap.js
- scripts/linux/package-linux.sh
- scripts/release.js
Pick up some performance improvements from node v12 -> node v14 for the extension host (notably, updating v8 from v7.x to v8.x)
Prompted by #3009 
__TODO:__
> refactor(dependency): Upgrade to node v14 LTS

- CHANGES_CURRENT.md
- integration_test/ClipboardInsertModePasteEmptyTest.re
- src/Feature/Workspace/Feature_Workspace.re
- src/Model/Actions.re
- src/Model/GlobalCommands.re
- src/Store/CommandStoreConnector.re
- src/Store/ExtensionClient.re
- src/Store/Features.re
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
__Todo:__
- Investigate wiring up the `setContext` command
- Fix issue with the explorer not showing new folder
- Fix `${git-branch}` rendering issue
Related #3042
> fix(extensions/#3042): Execute the 'vscode.openFolder' command

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Feature/LanguageSupport/Completion.re
- src/Feature/LanguageSupport/CompletionConfig.re
- src/Feature/LanguageSupport/CompletionItem.re
- src/Feature/LanguageSupport/CompletionItemSorter.re
- src/Feature/LanguageSupport/CompletionProvider.re
> feat(snippets): Add configuration for snippet ordering in completion menu

- docs/website/blog/2021-01-06-release-0.5.2.md
- docs/website/blog/2021-02-03-release-0.5.3.md
WIP for the 0.5.3 release notes
Thanks @zbaylin , @marcagba , @fanantoxa , and @jakubbaron for your contributions to this release! 🎉
> release(0.5.3): Release notes

- CHANGES_CURRENT.md
- extensions/configuration-editing/package.json
- src/Core/Filesystem.re
- src/Core/Filesystem.rei
- src/Feature/LanguageSupport/CompletionProvider.re
- src/Feature/MenuBar/Global.re
- src/Feature/Snippets/Feature_Snippets.re
- src/Feature/Snippets/Feature_Snippets.rei
- src/Feature/Snippets/dune
- src/Model/Actions.re
- src/Model/Quickmenu.re
- src/Service/Snippets/Service_Snippets.re
- src/Service/Snippets/Service_Snippets.rei
- src/Service/Snippets/SnippetFile.re
- src/Service/Snippets/dune
- src/Store/Features.re
- src/Store/QuickmenuStoreConnector.re
> feat(snippets): Implement commands for editing user snippets

- CHANGES_CURRENT.md
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Feature/StatusBar/Feature_StatusBar.re
- src/Feature/StatusBar/Feature_StatusBar.rei
- src/Model/State.re
- src/Store/ExtensionClient.re
- src/UI/Root.re
- Add interface file
- Move `"workbench.statusBar.visible"` to new configuration model
> refactor(config): Move 'workbench.statusBar.visible' to new model

- CHANGES_CURRENT.md
- docs/docs/configuration/key-bindings.md
- docs/docs/using-onivim/snippets.md
- docs/website/sidebars.json
> docs(snippets): Add initial snippets file; add to sidebar

- STAGING_SIGNOFF.md
> release(0.5.4): Run manual tests on staging build

- src/Store/VimStoreConnector.re
> fix(viml): Fix freeze when using experimental viml

- CHANGES_CURRENT.md
- integration_test/VimExperimentalVimlTest.re
- integration_test/dune
Adds a regression test to cover #3196 , and credits the fix in `CHANGES_CURRENT.md`
> test(vim/#3196):  Add regression test

- CHANGES_CURRENT.md
- docs/docs/languages/reason-ocaml.md
- docs/docs/languages/rescript.md
- docs/website/sidebars.json
> docs(rescript): Split out rescript into separate section

- CHANGES_CURRENT.md
- docs/docs/languages/c.md
Fixes #3212 - removes outdated exuberant ctags section
> docs(c/#3212): Remove exuberant ctags section

- CHANGES_CURRENT.md
- src/Exthost/Configuration.re
- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Progress.re
Related to #3321 - fix a couple of parse errors related to progress / configuration APIs
> fix(exthost/#3321): Parse error for progress and updateConfigurationOption APIs

- .ci/use-esy.yml
- CHANGES_CURRENT.md
- docs/docs/for-developers/building.md
- scripts/docker/centos/Dockerfile
> refactor(dependency): esy -> 0.6.10

- CHANGES_CURRENT.md
- node/package.json
- node/yarn.lock
- src/Exthost/Handlers.re
Bring extension host up-to-date with latest (`1.55.2`)
> refactor(dependency): vscode-exthost -> 1.55.2

- CHANGES_CURRENT.md
- docs/docs/for-developers/building.md
> fix(docs/#3467): Add 'node-gyp add 14.15.4' command

- docs/docs/for-developers/building.md
Hi, thanks for the investigation in #3467. I found that node-gyp didn't understand the "add" command, but "install" seemed to do the right thing and fixed the issue for me.
> Fix onivim#3467 documentation

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
> fix(build/#3494): Skia failing to build

- src/Feature/Editor/Editor.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/InlineElementView.re
- src/Feature/LanguageSupport/CodeLens.re
- src/Feature/LanguageSupport/Feature_LanguageSupport.rei
Fix codelens indentation introduced in #3482
> fix(codelens): Fix indentation issue with codelens

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
- src/Components/FileExplorer/Component_FileExplorer.re
Fixes #3399  - enable refresh in file explorer by default
> fix(explorer/#3399): Enable auto-refresh in explorer by default

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
Pick up fix for #3519 (Details of the issue / fix here https://github.com/revery-ui/revery/pull/1067)
Fixes #3519
> refactor(dependency): revery -> 135941b

- CHANGES_CURRENT.md
- src/Feature/Pane/Feature_Pane.re
> fix(pane/#3538): Focus pane on mouse click

- CHANGES_CURRENT.md
- src/Feature/Buffers/dune
- src/Feature/Editor/Minimap.re
> fix(minimap/#3563): Fix minimap scrollable calculation

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- bench.esy.lock/opam/merlin-extend.0.6/opam
- bench.esy.lock/opam/reason.3.7.0/opam
- esy.lock/index.json
- esy.lock/opam/merlin-extend.0.6/opam
- esy.lock/opam/reason.3.7.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/merlin-extend.0.6/opam
- integrationtest.esy.lock/opam/reason.3.7.0/opam
- package.json
- release.esy.lock/index.json
- release.esy.lock/opam/merlin-extend.0.6/opam
- release.esy.lock/opam/reason.3.7.0/opam
- src/Feature/Buffers/dune
- test.esy.lock/index.json
- test.esy.lock/opam/merlin-extend.0.6/opam
- test.esy.lock/opam/reason.3.7.0/opam
Related to #3579 - pick up https://github.com/revery-ui/revery/pull/1072
> dependency(revery): Pick up fix for resdl_SDL_PollEvent crash

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- release.esy.lock/index.json
- test.esy.lock/index.json
This picks up @zbaylin 's work to upgrade SDL2: https://github.com/revery-ui/esy-sdl2/pull/19
Fixes #2191
> refactor(dependency): SDL2 -> 2.0.14

- CHANGES_CURRENT.md
- docs/docs/configuration/key-bindings.md
Fix https://github.com/onivim/oni2/issues/2962
> docs(A-input): add next/previous tab keybinding

- azure-pipelines.yml
Seeing some build issues on the linux build:
```
(cd /home/vsts/work/1/s/_esy/default/store/b/oni2-6cbb6f15/default && /home/vsts/.esy/3____________________________________________________________________/i/ocaml-4.12.0-bfdfbfff/bin/ocamlopt.opt -w -40 -g -o src/bin_editor/Oni2_editor.exe /home/vsts/.esy/3____________________________________________________________________/i/ocaml-4.12.0-bfdfbfff/lib/ocaml/unix.cmxa -I /home/vsts/.esy/3____________________________________________________________________/i/ocaml-4.12.0-bfdfbfff/lib/ocaml /home/vsts/.esy/3____________________________________________________________________/i/ocaml-4.12.0-bfdfbfff/lib/ocaml/bigarray.cmxa -I /home/vsts/.esy/3____________________________________________________________________/i/ocaml-4.12.0-bfdfbfff/lib/ocaml …
```
> chore(ci): Disable Linux build cache, see if that fixes build error

- CHANGES_CURRENT.md
- STAGING_SIGNOFF.md
- package.json
> release(0.5.6): Manual test run

- CHANGES_CURRENT.md
- bench.esy.lock/index.json
- bench.esy.lock/opam/ppx_js_style.v0.14.1/opam
- esy.lock/index.json
- esy.lock/opam/ppx_js_style.v0.14.1/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ppx_js_style.v0.14.1/opam
- package.json
- release.esy.lock/index.json
- release.esy.lock/opam/ppx_js_style.v0.14.1/opam
- test.esy.lock/index.json
- test.esy.lock/opam/ppx_js_style.v0.14.1/opam
Pick up https://github.com/revery-ui/revery/pull/1087 to fix #3698
> fix(osx/#3698): Crash on open-with

- src/Feature/Layout/View.re
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/GlobalColors.re
> fix(editor/#3715): Add horizontal separator when editor tabs are not visible

- scripts/docker/centos/Dockerfile
- scripts/linux/AppRun
> fix(packaging/#3706) - Part 2: Add package to get missing gnome schemas for xsettings

- CHANGES_CURRENT.md
- extensions/php-language-features/out/features/hoverProvider.js
- extensions/php-language-features/out/features/phpGlobalFunctions.js
- extensions/php-language-features/out/features/validationProvider.js
- extensions/php-language-features/package.json
- extensions/php-language-features/package.nls.json
- extensions/php-language-features/tsconfig.json
- extensions/php-language-features/yarn.lock
- node/package.json
- node/yarn.lock
- src/Exthost/Handlers.re
Upgrade the extension host to 1.56.2, and pick up fix for #3737
> refactor(dependency): vscode-exthost -> 1.56.2

- CHANGES_CURRENT.md
- docs/docs/configuration/settings.md
> fix(ux/#3720): Document 'workbench.activityBar.visible' setting

- CHANGES_CURRENT.md
- src/Feature/Buffers/Feature_Buffers.re
- src/Feature/LanguageSupport/DocumentSymbols.re
- src/Feature/Quickmenu/Feature_Quickmenu.rei
- src/Feature/Quickmenu/Schema.re
- src/Store/QuickmenuStoreConnector.re
Fixes #3673 - select first menu item by default for quick menus
> fix(menu/#3763): Select first item by default

- .ci/clean-windows-deps.yml
The suffix was removed https://github.com/actions/virtual-environments/blob/9fe940e8a3cb67b6ecf0dbbcc9cb7efcc68aa008/images/win/scripts/Installers/Install-MysqlCli.ps1#L29
> ci: Update path to delete
