- src/editor/Neovim/NeovimProtocol.re
- src/editor/Neovim/Notification.re
- src/editor/Neovim/Oni_Neovim.re
- src/editor/bin/Oni2.re
- src/editor/bin/dune
This implements some basic input handling - grabbing the key events from GLFW, and hooking them up. 
There is no visualization in the UI of the state, yet, though - just outputting the message pack events from Neovim.
Some next steps for this specific PR:
- Refactor `nvim_ui_attach` into `NeovimProtocol::uiAttach`
- Refactor `nvim_input` into `NeovimProtocol::input`
- Refactor the `onKeyDown` logic to a separate module
..and then actually hooking up the UI!
> Initial input handling

- src/editor/Core/Actions.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/Types.re
- src/editor/bin/Oni2.re
This change adds tracking of the current editor font + metrics (width / height of glyphs) that are important for rendering.
> Editor font metrics

- assets/viml/dune
- assets/viml/init.vim
- src/editor/Core/Buffer.re
- src/editor/Core/Log.re
- src/editor/Core/Oni_Core.re
- src/editor/Neovim/Notification.re
- src/editor/Neovim/Types.re
- src/editor/bin/Oni2.re
This change ports over Oni's core interop `init.vim` so that we can be aware of certain events / autocmds on the front-end.
> Initial VimL Interop

- package.json
Remove builds in source (this can cause lsp clients like `reason-language-server` to fail
> Remove builds in source from package.json

- src/editor/Core/Buffer.re
- src/editor/Core/State.re
- test/editor/Core/BufferTests.re
- test/editor/Core/Helpers.re
__Issue:__ When adding a line at the end of a file (ie, `GO`), the buffer contents would disappear.
__Defect:__ Bug in our buffer update handling when the buffer update is past the extent of the buffer.
__Fix:__ Add test to exercise this case; fix buffer update logic.
> Bugfix: Buffer lines disappear when adding line at end of file

- src/editor/UI/EditorLayout.re
- src/editor/UI/Root.re
__Issue:__ Depending on the window size, there is a small gap between the editor scrollbar and the edge of the screen.
__Defect:__ Because the buffer width is a multiple of the measured character width in pixels, sometimes there is a little bit of space leftover. That ends up on the right side of the window.
__Fix:__ Include this 'leftover' space in the main buffer area, between the text and the minimap, instead of on the window edge.
> Bugfix: Editor layout - gap on right side of scrollbar

- src/editor/Core/Constants.re
- src/editor/UI/EditorLayout.re
- src/editor/UI/Minimap.re
- src/editor/UI/Root.re
This adds a 1px space between minimap lines:
> Minimap: Add spacing between minimap lines

- scripts/bootstrap.sh
To continue with my Windows issues due to spaces in paths, hit an issue with the `bootstrap` script.
```
touch: cannot touch 'Files/Documents/Git/oni2/assets/configuration/setup.json': No such file or directory
Command: creating new /cygdrive/f/User Files/Documents/Git/oni2/assets/configuration/setup.json Failed
```
I've quoted the variables now, as well as all the rest since I think its best practise in shell scripts anyways.
> Quote paths to prevent issues with paths that contain spaces.

- .ci/esy-build-steps.yml
- OniBench.opam
- bench.json
- bench/exe/Bench.re
- bench/exe/dune
- bench/lib/BenchEditorSurface.re
- bench/lib/BenchFramework.re
- bench/lib/dune
- package.json
- src/editor/Core/State.re
- src/editor/UI/Oni_UI.re
This adds infrastructure for benchmarking using the [`reperf`](https://github.com/bryphe/reperf) library. I put some simple benchmarks for our `EditorSurface` component which is doing most of the heavy-lifting right now. Benchmarks can be run via:
- `esy @bench install`
- `esy @bench build`
- `esy @bench x oni-bench`
I put a simple benchmark for an empty buffer and a buffer with a thousand lines:
```
+---------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                            |  TIME           |  MINOR GC  |  MAJOR GC  |  MINOR ALLOC  |  PROMOTED   |  MAJOR ALLOC  |
|---------------------------------------+-----------------+------------+------------+---------------+-------------+---------------| …
```
> Performance: Initial benchmarking infra

- bench/lib/BenchEditorSurface.re
- bench/lib/BenchFramework.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/FlatList.re
- src/editor/UI/Minimap.re
As mentioned in #60 , Onivim2 currently always renders the entire buffer - which is horrible for performance!
This change brings in a virtualized list (like the `FlatList` in the React-Native world), so that we only render lines that are in the current view. 
This is the first major performance bottleneck we saw - previous measurements were:
```
+---------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                            |  TIME           |  MINOR GC  |  MAJOR GC  |  MINOR ALLOC  |  PROMOTED   |  MAJOR ALLOC  |
|---------------------------------------+-----------------+------------+------------+---------------+-------------+---------------|
|  EditorSurface: Minimal state         |  0. …
```
> Performance / UI: Virtualized list rendering for buffer + minimap

- src/editor/Core/Buffer.re
- src/editor/Core/BufferMap.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/TokenizedBuffer.re
- src/editor/Core/Types.re
- src/editor/Neovim/NeovimBuffer.re
- src/editor/Neovim/Notification.re
- src/editor/UI/Commandline.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/Wildmenu.re
- src/editor/bin/Oni2.re
- test/editor/Core/BufferMapTests.re
__Issue:__ There were several strange quirks with buffer updates, like when switching buffers, having the previous buffer appended.
__Defect:__ We weren't using the `id` passed with the buffer line event to target the appropriate buffer.
__Fix:__
- Parse the `id` property and update the `BufferUpdate.t` type to include this
- Refactor the `buffer` type to `BufferMetadata.t` and consolidate with `Buffer.t`, so they can be updated in a unified way in the reducer
- Remove `activeBuffer` and use `activeBufferId` + `BufferMap.getBuffer` to derive the active buffer
- Update reducer to update metadata logic
- Update reducer to handle buffer update with the `BufferMap.update` method
- Update view logic to pick up new active buffer
> Bugfix: Buffer updates not handled correctly

- src/editor/Core/Actions.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/Types.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/FlatList.re
- src/editor/UI/GlobalContext.re
- src/editor/UI/Minimap.re
- src/editor/bin/Oni2.re
An initial implementation of smooth-scrolling (allowing our `FlatList` to have pixel offsets):
Still a few things to work out:
And then some things to track in next steps:
- Need to synchronize minimap (will do this in a separate issue)
- Set up the right scrollbar to be 'scrollable'
> Editor: Initial smooth scroll implementation

- src/editor/Core/Actions.re
- src/editor/Core/EditorView.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/Core/Types.re
- src/editor/UI/EditorSurface.re
- src/editor/bin/Oni2.re
Our current smooth-scroll implementation knows no boundaries... meaning, you can scroll past the buffer space:
This change expands our view to be array of the lines in the view, and not allow scrolling past.
> Bugfix - Scroll: You can scroll past the current view

- src/editor/Core/EditorView.re
- src/editor/Core/Reducer.re
- src/editor/Core/State.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/UI/Root.re
This change updates our view so that when the cursor moves offscreen (ie, due to a normal mode command), we'll snap the view to the cursor. This is a first round of viewport / scroll sync fixes. Next up will be hooking up `zz`, `zb`, `zt`, etc.
> Scroll: Synchronize normal mode cursor position with scrollview

- test/editor/Neovim/Helpers.re
This can cause issues if a developer has a custom config that conflicts.
> Run unit tests without an init.vim.

- assets/viml/init.vim
- src/editor/Core/Actions.re
- src/editor/Core/EditorView.re
- src/editor/Neovim/Notification.re
- src/editor/bin/Oni2.re
This adds support for `zz`, `zb`, and `zt` in our view layer. It hooks up basic interop so that we can call 'oni' commands from the Viml world, and wire them through to our state management infrastructure.
> View: Handle zz, zb, zt in our view layer

- package.json
- scripts/bootstrap.sh
[[ ]] syntax is in bash, not sh, so we should be more explicit in using bash in the script.
This most likely works on other distros because of a link to bash from sh, but failed when I tried on Ubuntu.
> Fix a "[[ not found" build error.

- bench/lib/BufferBench.re
- src/editor/Neovim/Notification.re
This adds a set of benchmarks around buffer update:
```
+----------------------------------------------------------------------------------------------------------------------------------------------+
|  BENCHMARK                                      |  TIME               |  MINOR GC  |  MAJOR GC  |  MINOR ALLOC  |  PROMOTED  |  MAJOR ALLOC  |
|-------------------------------------------------+---------------------+------------+------------+---------------+------------+---------------|
|  Buffer: Add lines to empty buffer              |  1.22300958633      |  334       |  67        |  24359        |  1627      |  100002627    |
|-------------------------------------------------+---------------------+------------+------------+---------------+------------+---------------|
|  Buffer: Insert …
```
> Performance: Add benchmarks for buffer update

- src/editor/Core/Theme.re
- src/editor/Core/Tokenizer.re
- src/editor/UI/CommandlineView.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/UI/EditorView.re
- src/editor/UI/MenuItem.re
- src/editor/UI/Minimap.re
- src/editor/UI/Root.re
- src/editor/UI/Tab.re
- src/editor/UI/WildmenuView.re
- test/editor/Core/TokenizerTests.re
This enhances our `Theme` module to also include token colors with scopes, and a method `getTokenColor` to get color for a token given a set of scopes (currently hardcoded). This plumbs through to our `tokenize` method, which now will report the color based on what the theme says - still need to hook up scopes and theme colors for this to actually be useful.
> Theming / Textmate: Add getTokenColor to theme

- src/editor/Core/ColorMap.re
- src/editor/Core/Oni_Core.re
- src/editor/Core/TextmateClient.re
- src/textmate_service/src/index.ts
- test/editor/Core/TextmateTokenizerTests.re
It turns out the textmate themes have a pretty complicated scope selector system (almost like CSS!). It also turns out that `vscode-textmate` can handling that matching, and return a minimal set of token information via `tokenizeLine2`. We'll leverage this instead of implementing that scope-matching ourselves for now.
This adds a `textmate/setTheme` request to the textmate service, which responds with a new colormap (when it sends colorized tokens, it just sends indices to the map to minimize traffic)
> Textmate - theme loading

- src/editor/Core/TextmateClient.re
- src/editor/Core/Theme.re
- src/textmate_service/src/index.ts
- test/editor/Core/TextmateTokenizerTests.re
This sets up some initial integration of `tokenizeLine2`, which sends us color information in a packed format - this hooks up to that call, and verifies we can unpack it and get the correct coloring info per-theme.
> Textmate: Hook up 'tokenizeLine2'

- src/editor/Core/Actions.re
- src/editor/bin/Oni2.re
This spins up the textmate server on launch, sets a hardcoded grammar (just reason for now), sets a default theme, and starts hooking up some logging in response to events from the textmate client (currently - gets the color map when the theme loads). 
The `node` process by itself is fairly lightweight - it has a minimal impact on startup time and starts out ~10MB (much lighter than the processes used by Electron, at least!)
We'll want to set up discovery of all the extensions that provide grammars, and hook them up as part of this initialization step.
> Textmate: Launch textmate server on startup

- src/editor/UI/FlatList.re
- src/editor/UI/Minimap.re
This refactors our minimap to use the new `<OpenGL />` node introduced in revery-ui/revery#381 - this greatly reduces layout/reconciliation cost because we no longer need to apply reconciliation/layout to individual minimap elements.
This is a big step forward but still isn't as efficient as it could be - the next step would be to batch up the draw calls and minimize the overhead there. We're making lots of small GL calls that could be avoided with batching.
> Performance: Start using direct OpenGL calls for minimap

- src/editor/UI/EditorSurface.re
- src/editor/bin/Oni2.re
This change uses the new `<OpenGL />` node for drawing text in the buffer surface; avoiding the cost of reconciliation and layout for that layer.
> Performance: Use immediate mode drawing for buffer surface

- package.json
- scripts/bootstrap.sh
I've removed the bash specific syntax, since its actually not needed here, and swapping to bash caused cygwin to not be loaded on systems with the Linux sub-system (I think).
Long term, using nodejs here is probably easier, or writing scripts for each system.
> Revert bash change.

- src/editor/bin/Oni2.re
- test/editor/Neovim/Helpers.re
This adds the `--noplugin` flag for now, so that we get a predictable baseline for nvim integration to start (we'll later explore the way to include VimL plugins). I believe this might be the root cause of #86 crashing.
> Bugfix: Add '--noplugin' flag

- bench/lib/BufferBench.re
- src/editor/Core/Buffer.re
- src/editor/Core/Buffer.rei
- src/editor/Core/BufferMap.re
- src/editor/Core/Editor.re
- src/editor/UI/EditorSurface.re
- test/editor/Core/BufferMapTests.re
- test/editor/Core/BufferTests.re
- test/editor/Core/Helpers.re
This change abstracts the `Buffer.t` so consumers don't rely on the internal implementation being a linear array. This is important as we implement optimizations and changes to the internal buffer model - like #80 - so that consumers can rely on a consistent API.
> Refactoring: Buffer module interface

- src/editor/Core/Buffer.re
- src/editor/Core/Buffer.rei
- src/editor/Core/Editor.re
- src/editor/Core/EditorLayout.re
- src/editor/Core/Oni_Core.re
- src/editor/UI/EditorHorizontalScrollbar.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/bin/Oni2.re
This adds a horizontal scrollbar on the editor surface when buffer lines exceed the editor surface area, and implements boundary scrolling behavior when the cursor moves to the beginning / end of a line that would cause the viewport to scroll.
> UI: Horizontal scrollbar

- src/editor/Extensions/ExtensionScanner.re
- src/editor/Extensions/ExtensionScanner.rei
- src/editor/Extensions/TextmateClient.re
- src/editor/bin/Oni2.re
This removes the hardcoded scope we send to our textmate service, and sends out the full set of scopes from the grammars we parse from extension metadata.
> Extensions: Send scopes from plugins to the textmate service

- assets/viml/init.vim
- src/editor/Core/Oni_Core.re
- src/editor/Core/StringMap.re
- src/editor/Extensions/ExtensionScanner.re
- src/editor/Extensions/ExtensionScanner.rei
- src/editor/Extensions/TextmateClient.re
- src/editor/Model/LanguageInfo.re
- src/editor/Model/Oni_Model.re
- src/editor/Neovim/NeovimBuffer.re
- src/editor/bin/Oni2.re
This leverages the `contributes: language` section and `contributes: grammar` sections of the VSCode extension JSON to pick the right language ID for a file, to find the right textmate scope, in order to apply textmate highlighting.
This fixes the existing behavior / bug where everything is highlighted with 'reason' syntax (removes the hardcoding).
> Extensions: Use filetype from VSCode extension

- src/editor/UI/FontAwesome.re
- src/editor/UI/FontIcon.re
- src/editor/UI/Tab.re
This change puts the modified 'dot' in the same spot as the 'close' indicator (standard UX paradigm used by other editors).
It also refactors the code a bit and adds a home for FontAwesome constants, as well as a helper `<FontIcon />` component for rendering icon fonts.
> Fit & Finish - Tab: Use same location for modified/close indicator

- README.md
Saw a few comments on twitter about this, when really we should just be linking straight to revery so there is one source of truth and we don't require any specific packages.
The only thing that we require that Revery does not is the `windows-build-tools` for the TextMate service. I've not tried this on Windows yet, so not 100% the easiest way of installing it.
> Add note on required build packages.

- assets/configuration/configuration.json
- src/editor/UI/Tab.re
- src/editor/UI/Tabs.re
This change primarily resets the tabline mode to `buffers` as that maps to files and was causing it to seem like the tabs were not rendering properly
It also adds a border between tabs, as an interim measure till we have `inset` shadowing in revery
> Reset configuration to buffers mode, add borders to tabs

- assets/viml/init.vim
- src/editor/Model/Tokenizer.re
- src/editor/bin/Input.re
__Issue:__ Using a dead key to compose a character (for example, typing a `ä` with two keystrokes - `"` and `a` would take multiple tries to get it to write to the buffer. Then, when it finally took, the cursor position would be off.
__Defect:__ There were a couple issues blocking this:
- We were sending the character as a one-byte char, even when it was encoded. In some cases, this would throw an exception, in others, we simply wouldn't send the right thing. Downstream, in our string parsing, we need to treat the buffer strings as UTF8.
- We were using the `col` VimL function, which returns a `byte` position 
__Fixes:__
- Use `Zed_utf8` for working with the buffer strings. Send the full UTF8 string, not just a one-byte char.
- Use the `virtcol` function instead of `col`
> Fix #170 - Dead key / encoding issues

- src/editor/bin/Oni2.re
__Issue:__ `:q` doesn't quit Onivim 2
__Defect:__ `:q` does close the `nvim` process, but we weren't listening to the Neovim process close event
__Fix:__ If the `nvim` process closes, with a success status code (`0`), we'll also close the Onivim 2 process via `App.quit`
> Bugfix: ':q' doesn't quit Onivim2

- src/editor/Extensions/ExtensionHostClient.re
- src/editor/Extensions/ExtensionHostInitData.re
- src/editor/Extensions/ExtensionHostProtocol.re
- src/editor/Extensions/ExtensionManifest.re
- test/editor/Extensions/ExtensionClientTest.re
- test/test_extensions/oni-api-tests/extension.js
- test/test_extensions/oni-api-tests/package.json
This brings in a simple test extension that we can use to test interop of the VSCode API surface.
Right now, we only test that the extension gets activated - later, we can extend it to round-tripping and handling API messages.
> Extension Host: Extension info / activation

- src/editor/Extensions/ExtensionHostClient.re
- src/editor/Extensions/ExtensionHostInitData.re
- src/editor/Extensions/ExtensionHostProtocol.re
- src/editor/Extensions/ExtensionScanner.re
- src/editor/Extensions/Oni_Extensions.re
- test/editor/Extensions/ExtensionClientHelper.re
- test/editor/Extensions/ExtensionClientTest.re
This adds a test case to validate the flow of us sending a command (`extension.helloWorld`) to a VSCode plugin, and having it respond (our test plugin just sends an information message via `vscode.window.showInformationMessage`). 
A few things needed to be fixed / tweaked on the way:
- Added a helper for testing the extension client to remove some of the boilerplate
- Fix a bug with the `main` path in the extension manifest - needs to be mapped to an absolute path
- Workspace wasn't being sent along with the init data
- We weren't handling Error responses at all (still needs to be improved, so that we can pick up the payload and show a reasonable message)
> Extension Host: Test for executing command against VSCode extension

- src/editor/bin/Oni2.re
__Issue:__ Text would be clipped in some lines:
__Fix:__ Clamp text to integer y coordinates
> Bugfix: text clipped in fractional lines

- src/editor/Core/Ripgrep.re
- src/editor/Core/Ripgrep.rei
- src/editor/Store/QuickOpenStoreConnector.re
__Issue:__ Even after closing QuickOpen, the ripgrep process is still running.
__Fix:__ 
- In `Ripgrep` module, return a dispose function so that consumers can kill the process.
- In `QuickOpen`, use `Ripgrep`'s dispose when the menu closes
Fixes #203
> Fix #203: Stop ripgrep process when QuickOpen is closed

- src/development_extensions/oni-dev-extension/extension.js
- src/editor/Core/Types.re
- src/editor/Extensions/ExtensionHostProtocol.re
- src/editor/Store/ExtensionClientStoreConnector.re
- test/editor/Extensions/ExtensionClientTest.re
- test/editor/Extensions/dune
This adds support for sending the document enter event (`ExtHostDocumentsAndEditors` - `$acceptDocumentAndEditorsDelta`).
> Feature - Extension Host: Document enter event

- src/editor/bin/Oni2.re
- src/editor/bin/PreflightChecks.re
Fix for #193 - add a module where we can place checks and establish invariants for the runtime of the application. The first check validates that we can find a `HOME` directory.
> Fix #193: Add place to start 'pre-flight' checks

- src/editor/Neovim/NeovimApi.re
- src/editor/Neovim/NeovimProtocol.re
__Issue:__ For `nvim_input` calls (the API call we make to Neovim to send keystrokes), we were blocking on a response. There's actually no need for us to block the thread (which is the rendering thread at the moment!) for this, since we do not act on the result.
__Fix:__
- Add a `request` method to the nvim api, which is a fire-and-forget non-blocking method when we don't need a return result.
- Use the `request` method for `input` instead of `requestSync`.
> Performance: Reduce input delay

- src/editor/Model/Actions.re
- src/editor/Model/LanguageInfo.re
- src/editor/Model/Reducer.re
- src/editor/Model/State.re
- src/editor/Store/StoreThread.re
- src/editor/Store/TextmateClientStoreConnector.re
- src/editor/UI/StatusBar.re
This wires up the `LanguageInfo` so that it can be used in the status bar, and can show the derived value. Pre-req for #181
> Status Bar: Filetype detection

- src/editor/Core/Types.re
- src/editor/Model/Reducer.re
- src/editor/bin/Input.re
Add an `inputControlMode` for neovim externalized components so that we can specify their input behaviour. This fixes #216, as previously the input mode was `editorText` so the mapping for the quickopen was still valid whilst the commandline was open, which it shouldn't be.
This also opens the door for allowing oni specific binding for neovim gui externalisations :man_shrugging:
> Fix #216: add Neovim menu focus to input control mode

- src/editor/Model/Reducer.re
- src/editor/Store/MenuStoreConnector.re
- src/editor/Store/StoreThread.re
- src/editor/bin/Oni2.re
This updates our `Window.setShouldRenderCallback` to properly test if the state has changed - if not, we shouldn't bother rendering.
With the change to use `isolinear`, we now have a high-frequency action in the form of `Tick`. We need to make sure not to update the state unnecessarily with that action, otherwise we'll always get renders - fixed a bug to that effect.
> Performance: Don't render when state hasn't changed

- src/editor/Model/Indentation.re
- src/editor/Model/Oni_Model.re
- src/editor/UI/StatusBar.re
This adds some UI to show the current indentation settings for the active buffer:
> Feature - Status Bar: Show indentation settings

- src/editor/Model/Reducer.re
- src/editor/Model/State.re
Name any buffer's with an empty name `untitled` rather than `[no name]`. This is a bit of a break from what neovim does, I think untitled is more commonly used in other editors and *to my mind* reads better.
Also don't create dummy buffers and dummy state, these aren't necessary as neovim starts with an empty buffer so we don't need to create one beforehand
> Rename no name buffer to untitled

- src/editor/UI/Minimap.re
Adding minimap mouse support for scrolling.
[x] Click to move thumb immediately
[x] Drag to scroll
was able to mimic implementation from Revery Slider.
Completes: #159 
PS: please let me know of any improvements that could be made or better practices implemented as I'm just getting started with ReasonML.
> Minimap mouse support

- test/editor/Model/BufferViewTokenizerTests.re
The `BufferViewTokenizer` tests weren't updated with whitespace settings / parsing - this change gets them green and passing again.
(#241 fixes the root cause - we weren't properly failing CI builds when tests failed!)
> Bugfix: Get BufferViewTokenizer tests green again

- Outrun-Labs-EULA-v1.0.md
- README.md
Move from the CC-BY-NC-ND to our official EULA, and implement 'time-bomb' dual-license.
> Documentation: Updated and (hopefully final!) EULA

- src/editor/Extensions/ExtensionHostProtocol.re
- test/editor/Extensions/ExtensionClientHelper.re
- test/editor/Extensions/ExtensionClientTest.re
- test/test_extensions/oni-activation-events-tests/extension.js
- test/test_extensions/oni-activation-events-tests/package.json
Add test cases that validate activation events can be sent from the Onivim front-end to the VSCode extension process (and that the VSCode extension gets activated correctly)
> Test: Extension Host - Activation Events

- bench/lib/EditorSurfaceBench.re
- bench/lib/Helpers.re
- src/editor/Extensions/ExtensionHostClient.re
- src/editor/Model/Editor.re
- src/editor/Model/EditorGroup.re
- src/editor/Model/EditorMetrics.re
- src/editor/Model/Oni_Model.re
- src/editor/UI/EditorGroupView.re
- src/editor/UI/EditorHorizontalScrollbar.re
- src/editor/UI/EditorSurface.re
- src/editor/UI/EditorVerticalScrollbar.re
- src/editor/UI/Minimap.re
__Issue:__ When the cursor moves outside the viewport, the viewport doesn't scroll - it's not usable to work with a document outside the viewport.
__Defect:__ This is a regression from #269 , the change to add an `EditorGroup`. The sizing information (editor pixel width / height, as well as character width / height) did not make it to individual `Editor` instances, and the `EditorGroup` was not leveraging it. Therefore, the `Editor`s had default settings for their metrics - a character width/height of 1, which made the viewport seem very large.
__Fix:__ It doesn't really make sense to store the metrics per-Editor, since all editors in an editor group will have the same metrics. Therefore, I've moved tracking these metrics to the `EditorGroup`, and I plumb the metrics through the reducer …
> Bugfix - Regression: Scroll not working

- src/editor/Extensions/ExtensionHostClient.re
- src/editor/Extensions/NodeProcess.re
This is the remaining fix for #206 - we'll suppress `stderr` piping and only log it when debug logging is enabled.
We could potentially abstract / move this to `reason-jsonrpc` 🤔
> Bugfix - NodeProcess: Only log stderr when debug logging is activated

- src/editor/Store/CommandStoreConnector.re
Missed the `menu.close` event in #278 - thanks @Akin909 for catching it (sorry about the regression!).
> Bugfix - Regression: Escape doesn't close QuickOpen

- src/editor/Neovim/NeovimApi.re
__Issue:__ There was an intermittent crash on `List.hd` in the `NeovimApi` method, here:
https://github.com/onivim/oni2/blob/69dc89dc4c596c45055ac4c479f17baecd48a038/src/editor/Neovim/NeovimApi.re#L164
The curious aspect of this is that there is a check that we received a message, and that check passed, but when we want to actually find the response message for the request we sent - there would be no message present. We assume there is with the call to `List.hd`, so that crashes and burns.
__Defect:__ The condition in the `Utility.wait` is actually incorrect - it's only checking to see if _any message_ came back from Neovim, when actually, we need to check if _any message matching our requestId__ came in. The crash is occurring when a _different message_ comes in (perhaps from a 'fire and …
> Bugfix: Crash - exception on 'List.hd' call

- src/editor/UI/EditorSurface.re
Always show at least one 1 char in visual mode. This doesn't change visual block mode as I don't think that works that way in terminal neovim (unless the `virtualedit` options are changed).
Before:
After:
> Visual Mode Changes

- src/editor/UI/Minimap.re
This is a fix for one part of #250
> Right now, you have to click once to start a dragging behavior. To end the dragging behavior, you need to click a second time.
> Releasing click stops scrolling

- src/editor/UI/Minimap.re
This is a fix for a part of #250 
> Also, right now it works on any mouse button. It should be kept on the left button only.
> Only scroll on left click

- README.md
This is the other part of fixing #268 - ensuring that external contributions to the project are immediately open.
The CLA has been updated here: https://gist.github.com/bryphe/bf98297731dd69b9b580ca1d7fd2b90e to reflect that external contributions are immediately dual-licensed upon inclusion.
In addition, clarified this in the README.
(Unfortunately, if you've signed the first CLA, you'll be prompted again - sorry about that!)
> Update CLA clause - v1.1

- Outrun-Labs-EULA-v1.1.md
- README.md
Fix #268 - loosen a few of the restrictions in the EULA:
- Remove section 1.4e - competitor clause
- Remove section 2.1a - remove non-commercial conjunction clause
- Loosen restriction on 3.1.b 
We actually were able to address almost every question in that #286 , which is great! The only clause we needed to retain from the feedback was 4.1. 
We'll address that particular issue by making the CLA more permissive - allowing contributors to relicense their contributions under MIT, if desired.
> Update EULA v1.0 -> v1.1

- assets/configuration/keybindings.json
- src/editor/bin/Input.re
- src/editor/bin/Oni2.re
This addresses https://github.com/onivim/oni2/issues/263
I had a hard time writing test cases for this, mainly because I didn't really know how to create a Key-Event object to pass to the corresponding method. Since the rest of `Input` isn't tested so far, I assume, others had similar issues?
I'd be happy for feedback either way, since this is my first contact with real world Reason.
> Change command modifier for MacOS to Cmd

- src/editor/Core/Constants.re
- src/editor/Model/FileExplorer.re
- src/editor/UI/FileExplorerView.re
This PR adds some error handling to the calls to get the folders and files for the file explorer, if an error is encountered trying to resolve subdirs we abort returning an empty children list and log the error. This allows the function to populate as much as possible.
> Add error handling to Explorer

- README.md
Hi !
In the README.md , I believe it could be cool to add a link to the file https://github.com/onivim/oni2/blob/master/docs/MOTIVATION.md
Actually there is no link into the README.md, therefore probably a reader could not read this very important document. Often a reader doesn't check the Github tree to see if under the folder doc there is a such important document !
Thanks in advance ;-)
> Documentation: add a link to MOTIVATION.md

- src/editor/Core/Constants.re
- src/editor/Core/Theme.re
- src/editor/UI/EditorLayoutView.re
- src/editor/UI/EditorView.re
- src/editor/UI/Minimap.re
- src/editor/UI/Tab.re
- src/editor/UI/TreeView.re
This adds the `sideBar.background` and `sideBar.foreground` theme colors - building on the file explorer by @Akin909 👍 
- Some minor fit-and-finish tweaks (use backgroundColor/foregroundColor on all the text elements, so we get gamma corrected text). 
- Update header to be the same color as the sidebar.
- Factor tabHeight to constant, reuse for sidebar header
> Theming: Add sideBar theme colors

- src/editor/UI/EditorGroupView.re
Regression from #306 - we were using the editor id to look up the buffer, and get the title. However, the 'editor id' and 'buffer id' are not necessarily in sync.
__Fix:__ Get the `bufferId` from the editor and use that for resolving the buffer
> Bugfix - Regression: Editor not showing correct buffer title

- src/editor/Core/Constants.re
__Issue:__ When opening Oni2 in some folders, the startup time would be quite long (ie, opening the root directory of the drive).
__Fix:__ The population logic was traversing up to 5 levels deep, which is expensive in a big folder. Since we only show a single level for now, we can restrict to a single level for the initial load. Verified that expanded later worked as expected.
> Performance - Startup: Limit initial population of FileExplorer to 1 level

- azure-pipelines.yml
- src/editor/Core/Job.re
- src/editor/Model/Menu.re
- src/editor/Store/MenuStoreConnector.re
- src/editor/UI/MenuView.re
__Issue:__ When results are streamed in the QuickOpen menu, and a search query is typed, we can sometimes get unpredictable results.
There were two problems here:
1) We filter the `commands` with the query as they come in. The problem is, if we press `Backspace`, we won't get these results back. 
2) When `commands` come in via the `MenuUpdate` action, we weren't actually filtering them. So this meant that if you typed `foo` and `bar` came in after you typed the query - `bar` would show up erroneously in the results.
__Fix:__
1) Create a separate `commands` and `filteredCommands`. `commands` is the full set of unfiltered commands, whereas `filteredCommands` is `commands` with the search query filter applied.
2) Append the new commands to `commands` first, and then apply the filter on the …
> Bugfix: Fix menu search logic for streaming results

- src/editor/Model/EditorGroup.re
__Issue:__ Clicking on the buffer tab doesn't do anything
__Defect:__ We were dispatching a `ViewSetActiveEditor` command, but never handling it
__Fix:__ Handle the `ViewSetActiveEditor` in the `Editor` reducer, and actually set the `activeEditor` state if applicable
> Bugfix: Clicking on buffer tab doesn't select buffer

- src/editor/Core/Types.re
- src/editor/Model/Buffer.re
- test/editor/Model/BufferTests.re
__Issue:__ When saving or re-opening a file with `:e!`, the buffer contents get duplicated in the window. A simple repro is to open a file, and then:
- `e!`
- `G`
- `zz`
__Defect:__ When saving or re-opening, we get a 'full' buffer update - this comes in as the `endLine` being `-1`. However, because of the conversion - the new `libvim` approach uses one-based indices, whereas the previous approach uses zero-based indices - a bug was exposed in applying the buffer updates.
__Fix:__ Don't pattern match on `ZeroBasedIndex`, instead, convert the index to the desired base (0 or 1) and then work with it. The buffer updates use zero based indices, so we convert that, and check if the endline is less than 0. Added a test to cover this case.
> Bugfix: Duplicate contents on buffer save

- src/editor/Store/StoreThread.re
- src/editor/Store/VimStoreConnector.re
- src/editor/bin/Oni2.re
In the transition from Neovim -> Libvim, our handling of command-line arguments was lost. This brings back opening files from the CLI. 
I'll bring back setting the current directory - want to wire up the change directory API to libvim so that the internals are connected (in other words - have libvim own the state of the current directory, and have methods to change directory, get the current directory, and know when the current directory has changed)
> Add CLI file argument handling back

- bench/lib/BufferViewTokenizerBench.re
- src/editor/Model/BufferLineColorizer.re
- src/editor/Model/BufferLineColorizer.rei
- src/editor/Model/BufferViewTokenizer.re
- src/editor/Model/Oni_Model.re
- src/editor/Store/VimStoreConnector.re
- src/editor/UI/EditorSurface.re
- test/editor/Model/BufferViewTokenizerTests.re
We use a module called `BufferViewTokenizer` to split up tokens in the editor surface for rendering. We batch up tokens that have common properties (same foreground / background color).
Much of the logic for that 'batching' was baked-in to the BufferViewTokenizer - it accounted for syntax highlighting, and selection ranges, but we need to generalize it further to enable visualizations for things like matching bracket pairs and search highlights.
To accomodate this, I'm generalizing the colorizer into a separate method that takes an index `i` and returns  `(backgroundColor, foregroundColor)` tuple. This colorizer handles all the details of things that impact background / foreground color. This means the `BufferViewTokenizer` doesn't need to know details about selection, theme, or anything …
> Refactoring: Extract colorization logic from BufferViewTokenizer

- src/editor/Store/IndentationStoreConnector.re
- src/editor/UI/EditorSurface.re
__Issue:__ For files with 2-spaces-per-indent-level, the indent line guides are still rendering at 4 spaces.
> Bugfix: Indent line guides not rendering correctly

- src/editor/Store/VimStoreConnector.re
__Issue:__ Several keys aren't properly handled by `libvim` - we prune those out so we don't send them. This manifests in a few ways: 
- `<SHIFT>` gets interpreted literally, like in #360 
- `<S-C->` puts `libvim` in a blocking mode and crashes Onivim 2
__Fix:__ We should make `libvim` itself more robust in the face of these inputs - but for now, we'll sanitize these on the Onivim 2 side.
Fixes #360
> Fix #360 - Add a few additional keys to ignore on the Vim side

- src/editor/Core/Log.re
- src/editor/bin_editor/Oni2_editor.re
__Issue:__ When there is an unhandled exception, it doesn't get logged to the log file specified by the `ONI2_LOG_FILE` environment variable.
__Fix:__ Add an unhandled-exception handler that ensures the exception details get flushed.
> Logging: Log unhandled exceptions to log file

- src/editor/Store/StoreThread.re
In `master`, we are currently spinning up the Node extension host process, and even sending buffer updates to it - but it is not being used (we haven't implemented a subset of the protocol for language services, yet!). So for our July builds, I'll turn this off, since it is not adding any functionality, and it is hasn't been thoroughly tested.
We still are shipping a vendored `node` binary because, at the moment, our textmate highlighting comes from JS. 
The plan for our Aug - Oct work is to switch that textmate highlighting strategy to native, and use `node` to host the extension host process. (So shipping the vendored `node` isn't wasted work - we'll need it to host the extension host process anyway, even with the textmate highlighting is moved to a native strategy)
> Release - Disable extension host for July builds

- bench.esy.lock/index.json
- esy.lock/index.json
- package.json
- src/editor/UI/Dock.re
- src/editor/UI/TreeView.re
- test.esy.lock/index.json
When testing #377 with a local `link:` resolution to Revery, I noticed this wasn't upgraded to the latest Revery (so there were a few minor fixes needed). Figured it was a good time to upgrade to latest.
> Dependency: revery -> 0.22.0

- src/editor/Model/Actions.re
- src/editor/Model/Buffer.re
- src/editor/Model/Buffer.rei
- src/editor/Model/Buffers.re
- src/editor/Store/LifecycleStoreConnector.re
- src/editor/Store/StoreThread.re
- src/editor/Store/VimStoreConnector.re
__Issue__: `:q` and family isn't behaving as expected - `:q` should close the current 'tab', and `:qall` should close everything.
__Defect__: We haven't hooked up the new quit handlers from libvim / reason-libvim.
__Fix:__: Hook up the quit handler.
> Bugfix: ':q' doesn't work as expected

- bench/lib/TokenizerBench.re
- src/editor/Core/Tokenizer.re
- src/editor/Model/BufferViewTokenizer.re
- src/editor/Model/Editor.re
- src/editor/UI/EditorSurface.re
- test/editor/Model/TokenizerTests.re
__Issue:__ When there are long lines on a file, even the parts that are offscreen are being rendered - this is wasteful and can incur a tangible performance penalty on rendering as described in #139 
__Defect:__ We just tokenize the entire line, even parts that are offscreen.
__Fix:__ Only tokenize + render the part of the line that is on-screen.
> Fix #139 - Don't render parts of lines that are offscreen

- bench.esy.lock/index.json
- esy.lock/index.json
- package.json
- test.esy.lock/index.json
This picks up a few crash fixes in `reason-libvim` - there were various crashes occurring while using the commandline in OSX / Linux (thanks @CrossR for finding these!):
- https://github.com/onivim/reason-libvim/pull/49
- https://github.com/onivim/reason-libvim/pull/50
> Dependency: reason-libvim -> 8.10869.16001

- src/editor/Core/ConfigurationValues.re
- src/editor/Model/EditorLayout.re
- src/editor/UI/EditorSurface.re
__Issue:__ The `editor.lineNumber` default of `Relative` is confusing, especially if you've never encountered it in Vim before. Even Vim doesn't default to this setting. It's an opinionated remnant of my config.
__Fix:__ Change the default to `On` which is more in-line with other editors. In addition, I noticed `off` wasn't being picked up - so I added a fix for that as well.
Fixes #374
> Fix #374 - Change editorLineNumber default to 'on'

- scripts/release.js
- scripts/windows/BuildSetupTemplate.js
- scripts/windows/setup.template.iss
- src/editor/Core/Setup.re
__Issue:__ When running Onivim 2 locally in the build environment, we drop a `setup.json` file that points to where various dependencies are, like: `node`, `rg`, the textmate service `index.js`, and the bundled extensions. However, in a packaged environment, we just have these dependencies local to the binary (the exact relation is dependent on the platform) - so we don't want to just package a `setup.json` from the build environment and try and load things from build-environment paths.
__Fix:__ In the case a `setup.json` isn't present (aka, a packaged environment), point to executable-relative reference directories, and don't include `setup.json` in the package. In addition, include the missing vendored dependencies (`node`, `rg`, textmate service, and bundled extensions) in the package.
> Packaging: - Windows: Include vendored ripgrep / node binaries

- src/editor/Core/Ripgrep.re
__Issue:__ In starting to investigate #304 , I noticed that the `--sort` flag for Ripgrep was actually slowing it down.
__Defect:__ In the documentation for the `--sort` flag (https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#common-options):
```
Force ripgrep to sort its output by file name. (This disables parallelism, so it might be slower.)
```
__Fix:__ Turn off the `--sort` flag for now to enable parallelism and speed up the ripgrep search
@Akin909 - was there any particular reason functionality-wise to have this `--sort` flag? If it was to implement a most-recently-used experience, we could potentially implement that outside of ripgrep. Let me know if you have any concerns with this change 👍
> Perf: Remove sort flag from Ripgrep

- bench/lib/EditorSurfaceBench.re
- src/editor/UI/EditorGroupView.re
- src/editor/UI/EditorSurface.re
__Issue:__ When window splits are open, and you switch to insert mode (ie, via `i`, `a`, etc), cursors on _all splits_ change to insert mode. This is unexpected and visually jarring - which file am I editing?
__Defect:__ The current mode is 'global' to the UI - the cursor style is a function of that current global mode - so all cursors would pick that up. 
__Fix:__ For now - only adjust the cursor style for the 'active' editor group. 
Fixes #414
> Fix #414 - Cursor split display

- src/editor/Store/VimStoreConnector.re
__Issue:__ The `:sav` command wasn't being handled properly by the UI. When the `:sav` command is executed, the buffer stays the same (same id), but the associated file changes. We don't reflect this in the UI, so it was confusing, and worse, the filetype wouldn't be picked up.
__Defect:__ An `onFilenameChanged` event was added to `reason-libvim` but we weren't using it here.
__Fix:__ Hook the `onFilenameChanged` event and dispatch a buffer enter in response.
> Bugfix: ':sav' command not handled properly

- scripts/release.js
- src/editor/bin_launcher/Oni2.re
- src/editor/bin_launcher/dune
Onivim 2 has two processes - a launcher process (Oni2) and the actual editor process (Oni2_editor). This split is primarily for Windows, to detach from the console process, but we use them on all platforms for consistency (there is relatively low overhead for the launcher process on Linux/MacOS).
However, we were bringing in some heavyweight dependencies - Revery needs various graphics libraries, and the launcher was dependent on Oni_Core (which was dependent on Revery). This would necessitate packaging deps for both Oni2/Oni2_editor.
This vendors a little bit of code from Revery (just the env stuff we need from the launcher), so that we don't need to bundle the dependencies twice
> Packaging: Minimize launcher deps

- .ci/js-build-steps.yml
- .ci/use-node.yml
- src/textmate_service/install.js
- src/textmate_service/package.json
- test/editor/Extensions/ExtHostTransportTests.re
- test/editor/Extensions/ExtensionClientTest.re
__Issue:__ In the current packaged builds, we are bringing in the full set of developer dependencies in the textmate_service's `node_modules` folder - it ends up being pretty huge (~150MB).
__Fix:__ For packaging, we should only be using the production dependencies, which reduces it to about 25% in size.
> Use production dependencies for textmate

- integration_test/AddRemoveSplitTest.re
- integration_test/lib/Oni_IntegrationTestLib.re
- src/editor/Store/StoreThread.re
- src/editor/Store/WindowsStoreConnector.re
- src/editor/Store/dune
- src/editor/UI/EditorView.re
- src/editor/UI/Oni_UI.re
The current design of window management relies on the UI to be instantiated to set up the initial splits - this hurts testability and means duplicated logic in our integration tests to simulate the 'real' environment.
(This was hit while setting up the `workbench.activityBar.visible` and `workbench.sideBar.visible`, it's a prepatory refactoring to enable those configuration options).
> Refactoring: Move initial view setup to store

- assets/configuration/configuration.json
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/Model/Selectors.re
- src/editor/Model/WindowManager.re
- src/editor/Store/WindowsStoreConnector.re
- src/editor/UI/EditorView.re
- src/editor/UI/Root.re
This change adds the following configuration settings:
- `workbench.statusBar.visible` (bool)
- `workbench.activityBar.visible` (bool)
- `workbench.sideBar.visible` (bool)
Together with the existing `workbench.editor.showTabs` and `editor.minimap.enabled` setting, it can provide a more minimal UI experience:
> Configuration: Additional settings for minimal UI

- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/Core/Constants.re
- src/editor/Model/Actions.re
- src/editor/Model/Buffer.re
- src/editor/Model/Buffer.rei
- src/editor/Model/Buffers.re
- src/editor/Model/SyntaxHighlighting.re
- src/editor/Store/TextmateClientStoreConnector.re
Our current textmate syntax highlighting strategy, found [here]( https://github.com/onivim/oni2/tree/master/src/textmate_service/src) leaves a lot to be desired in terms of performance. It's not incremental, and is slow (doesn't use results of previous optimizations).
Rather than invest further in it, for now, I'm disabling it for 'large' files (which is a relatively small limit - 1000 lines or so). This is to ensure a fast and performant user experience - I don't want this work-in-progress feature to detract from user experience. 
Once we implement #161 - a native textmate highlight implementation - we'll bump that limit back up!
> Performance: Throttle syntax highlighting

- src/editor/Store/VimStoreConnector.re
This is the first part of bubbling `libvim` messages up into Onivim. This simply hooks the `Vim.onMessage` event and logs out messages as we get them.
> Feature: Message handler (part 1)

- integration_test/AddRemoveSplitTest.re
- integration_test/InsertModeTest.re
- integration_test/RegressionCommandLineNoCompletionTest.re
- integration_test/TypingBatchedTest.re
- integration_test/TypingUnbatchedTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/editor/Store/StoreThread.re
__Issue:__ When typing very quickly during an operation that takes more than a frame, the typing events can get out of order. This is visible when opening a very large file and searching for something like `/abc`.
__Defect:__ Ideally, we wouldn't have any slow operations that take time in this way - but this exposed a defect in the way we handle input events. When multiple input events come in, and we haven't flushed them via 'runEffects', they'll get executed in _reverse order_ - this is a very frustrating experience!
__Fix:__ As we append the list items in the events linked list in reverse, we need to reverse again when we flush events to get the correct order.
> Bugfix: Fast typing while searching can give out-of-order characters

- src/editor/UI/TreeView.re
__Issue:__  Mouse doesn't switch to a pointer over explorer, so it doesn't feel like the items are clickable.
__Defect:__ There seems to be a bug with `Clickable` where the `cursor(MouseCursors.pointer)` style isn't being set correctly when merging. We should revisit the `Style.merge` concept as part of https://github.com/revery-ui/revery/issues/489
__Fix:__ Set the `cursor(MouseCursors.pointer)` explicitly on the ItemRenderer, in lieu of the longer term fixes in https://github.com/revery-ui/revery/issues/489
Fixes #375
> Fix #375 - Cursor should be pointer in treeview

- src/editor/Core/Cli.re
Small thing that I noticed whilst testing.
I think technically this is different to Nvim/Vim default behaviour. However, it is also pretty jarring to do `esy run ~/my/new/file.re` but have the explorer show the Oni2 dir still.
We could alternatively follow the VSCode way of working where we just don't open anything when given a file, but not sure that is preferable either.
> Use the basedir of a file when needed for folder selection.

- azure-pipelines.yml
- scripts/windows/publish.ps1
- scripts/windows/verify-signtool.ps1
This change sets up infra for codesigning using `signtool.exe` - just needs `CODESIGN_CERTIFICATE` and `CODESIGN_PASSWORD` specified via the environment.
> Packaging - Windows Codesigning

- README.md
- scripts/get-mit-commit.js
Even though it is early, I thought that adding a placeholder repo [`oni2-mit`](https://github.com/onivim/oni2-mit) which contains our MIT licensed code would help clarify how the dual-licensing will work.
I also added a script that gets the current MIT licensed commit (18 months back). We'll hook up an Azure Pipeline job to sync the MIT repo daily.
> MIT Commit Helper Tool / Time-delay license clarifications

- scripts/osx/publish.sh
__Issue:__ CI machines would hang when getting to the `codesign` step of the build process.
__Defect:__ It seems calling `codesign` was triggering the UI to prompt for a password.
__Fix:__ Researching a few places... I found we needed a couple additions:
- Using the `-A` or `-T` parameter for importing the certificate
- Using `set-key-partition-list`
Found a reference here: https://stackoverflow.com/questions/39868578/security-codesign-in-sierra-keychain-ignores-access-control-settings-and-ui-p and in the TravisCI docs: https://docs.travis-ci.com/user/common-build-problems/#mac-macos-sierra-1012-code-signing-errors
> Packaging - OSX: Fix hang on OSX when codesigning

- scripts/windows/setup.template.iss
__Issue:__ Our setup / install program for Windows installs Onivim 2 by default in `\Program Files (x86)`, which isn't correct - our windows builds are all x64 today.
__Fix:__ Run InnoSetup in x64 install mode, documented here http://www.jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls
> Windows: Use x64 install mode

- integration_test/RegressionVspEmpty.re
- integration_test/dune
- src/editor/Store/VimStoreConnector.re
When splitting, we should use the current buffer if no buffer was specified via `vsp` (same behavior as Vim)
> fix (bug fix): vsp does not use current file

- src/editor/Model/Editor.re
__Issue:__ When scrolling manually with the mouse, and moving the cursor, the view does not reset - this is confusing because the cursor is being manipulated off-screen.
__Fix:__ When the cursor moves, reset the scroll to reflect the current topline / editor view.
> fix(bug fix): Moving cursor does not reset view after scrolling

- bench.esy.lock/index.json
- bench.esy.lock/opam/ppxlib.0.8.1/opam
- bench.esy.lock/opam/topkg.1.0.1/opam
- esy.lock/index.json
- esy.lock/opam/ppxlib.0.8.1/opam
- esy.lock/opam/topkg.1.0.1/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ppxlib.0.8.1/opam
- integrationtest.esy.lock/opam/topkg.1.0.1/opam
- package.json
- scripts/windows/BuildSetupTemplate.js
- test.esy.lock/index.json
- test.esy.lock/opam/ppxlib.0.8.1/opam
- test.esy.lock/opam/topkg.1.0.1/opam
Fix #468.
This adds the file associations.
There was also a few other issues:
- Reg keys were pointing at "Onivim2.exe" rather than "Oni2.exe" which meant it didn't work even with the associations.
- Was pointing to the old app icon location (I couldn't see a real .ico file anywhere, so you may need to add one yourself @bryphe, since currently there is no App Icon).
- The setup in Oni wasn't setup to deal with arrays of extensions very well, so I've swapped that.
> [Windows] File Associations

- src/editor/bin_editor/Oni2_editor.re
If given a directory that doesn't exist as a command line argument, ie, `oni2 /some/fake/directory`, Onivim 2 will crash on startup. This handles that case, as it should be non-fatal.
Once we have a message UI, we should communicate this to the user as well.
> fix(bug fix): Crash if directory passed that doesn't exist

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This upgrades Revery to pick up a few commits, including a fix for #461 , as well as a new API to unblock #457 / #442
> fix(dependency): revery -> 3f932c5

- scripts/release.js
The packaged OSX app had really blurry text - this only reproduced when running from the `Onivim2.App` bundle, and not when building from source.
It turns out there is this `Open In Low Resolution` setting that was checked by default:
Added `NSHighResolutionCapable: true` to our plist fixes it
> fix(bug fix): OSX app package opens in low resolution mode

- src/editor/Model/Editor.re
Looks like the combination of #457 and #432 without the CI running between caused a type conflict.
As far as I know, this should be a 1 based index since its a line, so I've fixed that.
> Fix type conflict.

- src/editor/Model/Editor.re
__Issue:__ When moving the cursor, the viewport would scroll.
__Defect:__ The index being used to store the last `topLine` in `Editor` is 0-based, but we were converting it to 1-based whenever the cursor moved - this would increment it by 1.
__Fix:__ Use `Index.toInt0` to use a zero-based index.
> fix(bug fix): cursor movement scrolls viewport

- scripts/release.js
- src/editor/Core/Setup.re
This was another egregious bundle fail - we had extensions, textmate service, and camomile as siblings to `MacOS` which isn't what the bundle format expects. These should all live in `Onivim2.App\Contents\Resources` instead of directly in `Onivim2.App\Contents`
> #510 - Part 2 - Move extensions, textmate service, and camomile to Resources

- scripts/linux/AppRun
The `export` statements in our bash scripts were incorrectly quoted, which could cause problems in some shells when running Onivim 2 via the `AppRun` file (as an `.AppImage`).
> Fix #533 - Incorrect quotes in AppRun

- src/editor/Core/HealthCheck.re
This adds a healthcheck to verify we can run the bundled `node` executable. This was an issue that came up while working on the signing / hardened runtime (the `node` executable stopped running) - so we should check and verify that it still works after the code-signing process.
> Feature - Health checks: Add healthcheck for executing node

- scripts/osx/publish.sh
- scripts/release.js
Enabling a [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime_entitlements) is a requirement for the notarization step, however, without any entitlements, the `node` process will not run (it relies on JIT'ing, which is blocked by default with the hardened runtime).
This change turns on hardened runtime for code-signing / notarization _and_ includes an `entitlements.plist` file to enable the set of entitlements needed to get node running.
> Fix #510 - Part 3 - Enable 'hardened runtime' on OSX

- docs/docs/getting-started/installation.md
Due to issues with #501 , and the notarization, we'll be using the archive `Onivim2.tar.gz` on Mac (and later - pivot to a `zip`)
> Docs: Tweak installation steps

- scripts/osx/validate-release.sh
- scripts/release.js
- src/editor/Core/HealthCheck.re
__Issue:__ There were several non-executable files, like fonts, images, and configuration in the binary folder. This is not allowed per the MacOS bundle format, and causes issues with signing / notarization.
__Fix:__ We'll store the files in `Resources` and symlink them, so that the executable can pretend they are local. This is the quickest fix, but longer term we may want to specify these locations via our `Setup` module.
> Fix #510 - Part 4 - Fix up Onivim2.App/Contents/MacOS directory

- src/editor/bin_launcher/Oni2.re
- src/editor/bin_launcher/dune
> Fix #552: Filter out rogue -psn argument

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This brings in the `glfwGetClipboardText` and `glfwSetClipboardText` APIs so we can start integrating them for #506
> refactor(dependency): reason-glfw -> 3.2.1027

- src/editor/Core/ConfigurationDefaults.re
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- test/editor/Core/ConfigurationParserTests.re
This is my first attempt at tackling part one of #460. I'm totally new to Reason and the project in general so any feedback is much appreciated.
A few questions that arose as I implemented this:
- Is the preferred way to run the tests using `npm test`?
- When I finished the implementation I ran `npm run format`. It threw an error (containing a diff) on me. Rerunning the command did not throw and error and terminated successfully. Is that expected?
- I tried to add a test case for parsing a list of integers. I noticed that the parsed values come back flipped. I assume it's due to the fact that we do ` [v, ...accum]` instead of ` [...accum, v]`. I didn't want to change this behaviour as I had a feeling it might be due to performance reasons. Is that the case?
> Editor Rulers (Part 1 - Add a Configuration Setting)

- src/editor/Core/ConfigurationDefaults.re
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/UI/EditorSurface.re
- test/editor/Core/ConfigurationParserTests.re
Given any rulers present in `editor.rulers` they will be rendered in the viewport. The color is currently hardcoded and will be fixed in part three of #460 
This pull request depends on the work done in #573, so be sure to merge that first.
> Editor Rulers (Part 2 - Pick up configuration setting and render)

- docs/docs/using-onivim/configuration.md
Add documentation for the `editor.rulers` configuration option. Was not entirely sure how we want the type signature to be. I could see `list(int)`, `[int]` and `list of int` and in the end I settled on the latter.
> Add documentation for `editor.rulers` option

- src/editor/bin_editor/Input.re
Delete doesn't work for me (and some other people on Discord) at the moment, and adding a resolution here seems to work.
One thing I'm not 100% on is if I should be using `"DELETE"` here, or if I need some other representation? I.e, I see that `KEY_BACKSPACE` returns `Some("C-h")`, which is the terminal equivalent as far as I know.
> Add resolution for delete key.

- src/editor/Core/Utility.re
- src/editor/Model/WindowTree.re
- test/editor/Core/UtilityTests.re
- test/editor/Model/WindowTreeTests.re
This was a lot more challenging than I initially thought. I had to wrap my head around the `WindowTree` and the type `t` and the data structure it represents. Thinking about the problem from a functional perspective didn't help. 🙂
In #439, I said you can't rotate a split that is adjacent a Parent. While this is true, I could not come up with a good reason for why we shouldn't allow it. So the implementation allow it.
I've added two functions to the `WindowTree`:
- **rotateForward** - Given an id and the current tree, it will rotate all splits, confined within the same `Parent`, one step to the right, for the matching split. If no matching split is found, it returns the current tree.
- **rotateBackward** - Given an id and the current tree, it will rotate all splits, confined within the …
> Splits (Rotation) - Part 1

- src/editor/Core/Cli.re
Problem: 
- When you open the app via the app icon, `Sys.getcwd`, which is used to find the `workingDirectory` returns `"/"` on MacOS.
- I am not sure how this works on linux, but I am assuming its the same.
Possible Solution:
- Instead of defaulting to workingDirectory, this change looks for the `$HOME` env variable which is usually set on MacOS and Linux. It uses that as the default directory
- It only uses this directory if a file or directory was not passed in as an argument. 
- If the `$HOME` env var is not found, it will default to the working directory 
Re-submitting #578, on a different branch, more discussion are on that PR.
As @CrossR pointed out, one downside of this approach is that you would always have to explicitly call the folder you want to open. 
For example before this …
> Launch app in user directory on Linux and MacOS

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Fixes #519 
There were several issues with our scroll events - described by `libvim` PRs:
https://github.com/onivim/libvim/pull/158
https://github.com/onivim/libvim/pull/157
https://github.com/onivim/libvim/pull/156
These are now in `master` - however, there was one remaining issue - the `<c-f>` key wasn't working as expected. It turns out there was a Revery bug causing it to resolve to the wrong key - https://github.com/revery-ui/revery/pull/533
This picks up that last Revery fix, so this should be last fix needed to unblock the scroll events described by #519 .
> Fix #519 - Scroll movements don't work

- scripts/release.js
Could be being dumb, or is there a nicer way to do the package.json loading?
That said, I've found that running `esy create-release` in any folder that isn't the root causes me issues already.
> Populate Mac version based on package.json

- src/editor/Store/CommandStoreConnector.re
Add the ability to setup keybindings for moving between windows. I've tested this by setting defaults since we're not currently reading the `keybindings.json` file.
Solves https://github.com/onivim/oni2/issues/565.
> Setup window movement commands

- docs/docs/for-developers/building.md
- scripts/osx/create-symlink.sh
- scripts/osx/run.sh
- scripts/release.js
When developing on Mac, it's helpful to be able to point an `oni2` symlink to the local release bundle for testing or usage. 
We don't have any automation for this today, so this adds a couple scripts to help out:
- `run.sh` - helper script to run the app / pass args
- `create-symlink.sh` - helper script to create an `oni2` symlink in `/usr/local/bin` that points to the local dev environment.
__TODO:__
> DX - OSX: Add scripts to create `oni2` symlink

- integration_test/lib/Oni_IntegrationTestLib.re
- src/editor/Core/ConfigurationDefaults.re
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/Store/ConfigurationStoreConnector.re
- src/editor/Store/StoreThread.re
- src/editor/bin_editor/Oni2_editor.re
Fixes #495 
I've been pretty much following the instructions from the issue. There are a couple of things I'd like to fix, but I'm not sure how:
* opening Oni like that still loads a folder, so using the file switcher is possible and one can open more files which does not disable zen mode, that may be confusing.
* when starting Oni with one file, disabling zen mode and then changing the config file will re-enable zen mode every time since the `reloadConfigurationEffect` runs every time the configuration changes
Let me know what you think.
> add zenModeSingleFile

- docs/docs/using-onivim/configuration.md
- src/editor/Core/ConfigurationDefaults.re
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/UI/TreeView.re
Added a new entry to handle the intent size of tree explorer
```json
{
"explorer.indentSize": 4
}
```
Before this, the indent size was hardcoded (2) and the tree explorer could look too narrowed for some users.
The `itemRenderer` (`TreeView.re`) now receives the state so it can get the explorer indent size from the configuration and it simply uses it instead of the old hardcoded value.
> Change the indent size in the tree explorer

- integration_test/CopyActiveFilepathToClipboardTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/editor/Model/Actions.re
- src/editor/Model/CommandPalette.re
- src/editor/Store/StoreThread.re
- src/editor/Store/VimStoreConnector.re
- src/editor/bin_editor/Oni2_editor.re
I'm currently using atom and this is one of my most used commands. Whenever I work on a test and I want to run that test only I use that command to the the path of the file I'm currently editing. Or basically if I want to do anything on the terminal with the file I use this.
I hope this is useful for other's as well.
> add CopyActiveFilepathToClipboard action

- src/editor/Store/VimStoreConnector.re
I could reproduce `alt-shift` and `win-shift`. Not sure if there are more keys, I'll open more PRs if I find some.
fixes #415
> ignore more keys to ignore on the vim side

- docs/docs/for-developers/building.md
We were missing a step prior to `esy create-release` - we need to run `esy x Oni2` to get `esy` to set up the install layout in esy's cache - the `esy create-release` scripts expects this to have happened.
> Documentation: Fix create-release instructions

- src/editor/UI/OniInput.re
Fixes #218 
__Issue:__ The `<C-w>`, `<C-h>`, and `<C-u>` weren't being handled in our input for the menu.
__Fix:__ Handle them. This adds code specific to our `OniInput` element, but it would be interesting to investigate adding some sort of interop with Vim's handling (and definition of word!)
> fix(bug fix) - #218 - Add handling for <c-h>/<c-w>/<c-u> in QuickOpen

- src/editor/Syntax/Oni_Syntax.re
- src/editor/Syntax/TreeSitterScopes.re
- src/editor/Syntax/TreeSitterScopes.rei
- test/editor/Syntax/TreeSitterScopesTests.re
We're working on tree-sitter has a native syntax highlighting alternative to TextMate grammars. Much of the work for that is happening here: https://github.com/onivim/reason-tree-sitter (which adds a ReasonML API for tree-sitter).
When parsing with `tree-sitter`, for example, a simple JSON document like `[1, "2"]`, we end up with a syntax tree like:
```
(value (array (number) (string (string_content))))
```
The problem is - there aren't any theming solutions at the moment that theme the syntax tree directly. And, we want to leverage VSCode themes, which use textmate selectors.
Therefore, we need a mapping - a way to take the tree-sitter syntax tree, and resolve nodes to textmate-scopes. It turns out Atom has the same issue, and implement a mapping format - the JSON mapping is defined …
> Native Syntax Highlighting - Part 2 - Tree Sitter -> TextMate Scope Mapping

- src/editor/bin_editor/Input.re
Our key binding code is expected the tab character to resolve as `<tab>` (and for #661, control+tab should resolve as `<C-TAB>`). 
This adds a fix to resolve `\t` -> `TAB` to support that scenario. Depends on https://github.com/revery-ui/revery/pull/539
> bugfix: resolve tab character to <TAB>

- bench.esy.lock/index.json
- esy.lock/index.json
- integration_test/RegressionFileModifiedIndicationTest.re
- integration_test/dune
- integrationtest.esy.lock/index.json
- package.json
- src/editor/Model/Actions.re
- src/editor/Model/Buffer.re
- src/editor/Model/Buffer.rei
- src/editor/Model/Buffers.re
- src/editor/Store/VimStoreConnector.re
- test.esy.lock/index.json
This fixes #600 - we weren't really paying attention to the `modified` flag coming from Vim. This would sometimes happen serendipitously when we'd get updated metadata... but most times not.
This picks up a new API from `reason-libvim`: `Vim.Buffer.onModifiedChanged` which lets us know when the modified state of a buffer changes, so we can pick it up and show it in the UI. Added here: https://github.com/onivim/reason-libvim/pull/66
> Fix #600 - Unsaved / modified file indication is not reliable

- integration_test/InputIgnoreTest.re
- integration_test/dune
- src/editor/Input/Filter.re
Fixes #657 - we were missing a case in our input filter
> Fix #657 - Command+Alt insert characters on Mac

- src/editor/Syntax/TextMateScopes.re
- src/editor/Syntax/TextMateTheme.re
- src/editor/Syntax/TextMateTheme.rei
- test/editor/Syntax/TextMateThemeTests.re
Pre-req for #677 - this simplifies the JSON parsing so we don't have to maintain a separate color map
> TextMate Theme: Use colors instead of indices

- extensions/json/README.md
- extensions/json/package.json
- extensions/json/syntaxes/tree-sitter-json.json
- src/editor/Extensions/ExtensionContributions.re
- src/editor/Syntax/TreeSitterScopes.re
- src/editor/Syntax/TreeSitterScopes.rei
- test/editor/Extensions/TextmateTokenizerTests.re
- test/editor/Syntax/TreeSitterScopesTests.re
This adds an extension to the `grammar` contribution section, allowing us to specify a path to a file that has tree-sitter scope mappings. When this is provided, we'll prefer tree-sitter parsing over textmate parsing.
> Native Syntax Highlighting - Tree Sitter: TS scope map path

- docs/docs/using-onivim/configuration.md
- src/editor/Core/ConfigurationParser.re
- src/editor/Core/ConfigurationValues.re
- src/editor/UI/CommandlineView.re
- src/editor/UI/MenuItem.re
- src/editor/UI/MenuView.re
- src/editor/UI/NotificationsView.re
- src/editor/UI/OniBoxShadow.re
- src/editor/UI/Root.re
- src/editor/UI/WildmenuView.re
Was fixing up some of the non-gamma-corrected text places, so figured I could fix #688 along with this
There were a few fit-and-finish issues:
- The shadows are too intense. I toned them down a bit, but they still need work - in particular, the implementation in Revery fades to an opaque color, even with the alpha channel set (which is a bug) and makes them much harsher than they should be. Ideally we'd want them to be more subtle by blending to a mostly transparent value (like `rgba(0, 0, 0, 0.2)`).
- Refactored to a common shadow component used across the app.
- Added a configuration setting - `ui.shadows` that can be used to enable / disable shadows (if there aren't shadows, we add a 1px border around the elements)
- Several places in the UI had non-gamma-corrected text, which makes it …
> Fix #688 - Shadow & Gamma fixes

- src/editor/Core/Types.re
- src/editor/Extensions/ColorizedToken.re
- src/editor/Model/BufferLineColorizer.re
- src/editor/Model/BufferLineColorizer.rei
- src/editor/UI/EditorSurface.re
This change introduces a new token for representing syntax highlights. This removes the indirection with the `ColorMap` from the textmate service, because it isn't necessary in the reason world (the memory overhead is already smaller due to the use of pointers / immutable references), and simplifies downstream code in the new, native syntax highlight strategy.
This introduces a temporary type - `ColorizedToken2` - and maps the rendering / editor surface APIs to use this (and shims to convert the old `ColorizedToken` to this new one). Once we've fully migrated to native syntax highlighting, we can remove the old `ColorizedToken` and rename `ColorizedToken2` -> `ColorizedToken`
> Native Syntax Highlighting: Refactor to ColorizedToken2

- src/editor/Core/Log.re
- src/editor/Model/Actions.re
- src/editor/Model/Reducer.re
- src/editor/Store/StoreThread.re
- src/editor/Store/ThemeStoreConnector.re
One blocker for integrating tree-sitter is that we don't currently load the theme information on the Reason side - the node process we use for syntax highlighting currently handles both the syntax tokenization and application of the theming.
This change is needed to hook up the tree-sitter syntax tree and the syntax map to actual theme information - this loads theme in the reason side so we have it available as part of our model. Necessary to move #663 further
> Theming: Load tokenTheme for use with tree-sitter

- docs/docs/other/faq.md
The `i` was missing in the URL here!
(Also, I'm excited about the direction this project is going!)
> Update faq.md to fix broken link to early access portal.

- bench/lib/BufferBench.re
- src/editor/Model/Actions.re
- src/editor/Model/Buffer.re
- src/editor/Model/Buffer.rei
- src/editor/Model/Buffers.re
- src/editor/Model/EditorGroupReducer.re
- src/editor/Store/CommandStoreConnector.re
- src/editor/Store/ExtensionClientStoreConnector.re
- src/editor/Store/IndentationStoreConnector.re
- src/editor/Store/StoreThread.re
- src/editor/Store/TextmateClientStoreConnector.re
- src/editor/Store/VimStoreConnector.re
- src/editor/UI/EditorGroupView.re
- src/editor/UI/StatusBar.re
- test/editor/Model/BufferTests.re
- test/editor/Model/BuffersTests.re
This is a prepatory refactor to help simplify some aspects of syntax highlighting / language services.
For these features - it's important to be able to easily query the filetype (and, down the road, change filetype). Currently, we'd always query the file type against the `LanguageInfo.t`, but this is awkward, because that construct has to be passed around everywhere that needs it, and there's no faculty for changing the filetype.
This changes the model so that on `BufferEnter` we have an initial filetype (which would we could change later), and flattens the `Buffer.t` object to make it less awkward to query properties like path / filetype.
> Refactoring: Model - Add filetype for buffer

- integration_test/MenuFilteringSmartCaseTest.re
- integration_test/ZenModeSingleFileModeTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/editor/Core/Cli.re
- src/editor/Store/ConfigurationStoreConnector.re
- src/editor/Store/StoreThread.re
I realized with #713 that we didn't have a test around the single-file zen mode case, and we didn't really have the infrastructure to easily write such a test, either.
I added a few things to our integration test framework to make this testable:
- Ability to specify a custom configuration string
- Ability to specify cli options
And then added a test to verify the 'single-file' zen mode scenario. These additional features for our integration test also mean we can test scenarios we couldn't before (invalid config, certain command line arguments, etc).
> Test: 'Single file' zen mode

- src/editor/Core/Job.re
This adds a `Job.getProgress` API, with a parameter for the creator of job to specify how to show progress. This will be used in #695 to help with the animation.
> API - Job: Add method for getting progress

- src/editor/Core/Range.re
- src/editor/Core/Range.rei
- src/editor/Model/Editor.re
- src/editor/Model/EditorVisibleRanges.re
- src/editor/UI/Minimap.re
One issue with the current round of tree-sitter work in #663 is that, on every render, we are re-calculating highlights for all the visible lines - every frame.
This is expensive, because it involves:
1) Traversing the tree-sitter syntax tree to get the node encompassing the line
2) Getting the set of terminal syntax tokens for that node / line
3) Resolving the syntax tokens to textmate scopes
4) Resolving the textmate scopes into colorized token bounds based on the theme
We shouldn't need to do this every frame - instead, we can calculate these on demand when the view changes, or when a buffer update comes in. The first step in this on-demand calculation is being able to easily get the set of visible lines in the viewport for a buffer, and that's what this `EditorVisibleRanges` provides. …
> API: Get visible ranges for buffer

- src/editor/Core/Job.re
- test/editor/Core/JobTests.re
__Issue:__ `Job.tick` was only running a single iteration of the worker function
__Defect:__ We weren't passing the latest `current` ref in the tick function
__Fix:__ Always past the latest `Job.t` iteration
> Bugfix: Fix 'tick' in Job and add unit test

- src/editor/Core/Range.re
- src/editor/Core/Range.rei
- src/editor/Core/Types.re
- src/editor/Model/Diagnostics.re
- src/editor/Model/Diagnostics.rei
- test/editor/Model/DiagnosticsTests.re
This adds a `message` property to our `Diagnostic.t` type, as well as a helper for getting diagnostics at position (to be used by #725)
> API - Diagnostics: Message + getDiagnosticsAtPosition

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Fixes #738 by updating libvim / reason-libvim dependencies with the fix (https://github.com/onivim/libvim/pull/162)
> Dependency: reason libvim -> 8fc399d

- src/editor/UI/EditorSurface.re
While undoing and redoing with a selection active, there was a bug where the viewport might get rendered with an out-of-range selection - this would cause us to try and query for a line that isn't available in the buffer.
> Bugfix:  Crash while undoing / redoing

- src/editor/Core/Job.re
- src/editor/Syntax/TextMateSyntaxHighlights.re
- src/editor/Syntax/TextmateTokenizerJob.re
This change gives a 'bonus' time for syntax highlighting when we first open a buffer - 25ms budget from the 2ms/frame that we normally spend on it.
> Syntax Highlighting: Add extra time for first highlight render

- src/editor/Core/ConfigurationValues.re
Turning on native syntax highlighting - if everything goes OK, will remove this flag and remove our legacy textmate implementation.
> Enable native textmate highlighting by default

- src/editor/Core/IntMap.re
- src/editor/Core/Types.re
- src/editor/Syntax/TextmateTokenizerJob.re
- test/editor/Core/IntMapTests.re
One small implementation detail that was missed when moving from the 'external' textmate to the 'native' textmate implementation was an optimization - when a buffer update comes in, and adds/remove lines, we preemptively shift the highlights to match the new lines.
This helps minimize unstyled frames, especially in the minimap.
Previously, the `shift` method was specific to a buffer-lines data structure, but this makes it generally applicable to any `IntMap` (might be useful for other cases.... like shifting search highlights or diagnostics!)
> Bugfix: Shift tokens when applying delta updates

- src/Model/Actions.re
- src/Model/Reducer.re
- src/Model/State.re
- src/Store/CommandStoreConnector.re
- src/Store/MenuStoreConnector.re
- src/Store/QuickOpenStoreConnector.re
- src/UI/MenuView.re
- src/bin_editor/Input.re
This is a change that is needed by both #779 (for the nested menu) and #780 (for proper handling of SDL's concept of text input), so I'm pulling it out separately.
This simplifies our input model - we were manually setting an `inputControlMode` on our state, which required additional `dispatch`'s to keep in sync with our state. It turns out this can instead be fully derived by our current state, which simplifies our state management by removing the synchronization.
> Refactoring: Remove inputControlMode from state

- src/Model/Actions.re
- src/Model/Editor.re
- src/UI/EditorSurface.re
- src/UI/FlatList.re
- src/UI/GlobalContext.re
- src/UI/Minimap.re
- src/bin_editor/Oni2_editor.re
Fix #817 - fix case where `OnMouseUp` wouldn't get picked up by capturing.
__Issue:__ We'd use a `React.Hooks.effect` to listen to the capture with an `Always` flag - that relied on an `isCapturing` value to be set. So to start capturing, there'd be this sequence of events:
- `mouse down` -> update scroll position
(re-render, run effect hook - no capturing)
- update `setActive`
(re-render, run effect hook - capturing)
The problem is - there is a frame where we are 'capturing' but we haven't yet called `Mouse.setCapture` - and if a `mouseup` happens in that time, we lose it and just get stuck capturing.
__Fix:__ Don't use the effect to listen to events - use it just to track if we need to dispose the handler (with an `OnMount` instead of `Always` flag - so we'd only call the dispose if the …
> Fix #817 - Minimap improvements

- bench.esy.lock/index.json
- bench.esy.lock/opam/lwt.4.4.0/opam
- esy.lock/index.json
- esy.lock/opam/lwt.4.4.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/lwt.4.4.0/opam
- package.json
- src/Store/ThemeStoreConnector.re
- test.esy.lock/index.json
- test.esy.lock/opam/lwt.4.4.0/opam
Right now, some tokens are inadvertently set to a wrong default - like `#FFF` - which makes them show up too brightly.
This lets us send the `uiTheme` configuration from the theme to reason-textmate.
> Bugfix - Themes: Fix dark/light resolution when specified via uiTheme

- src/Store/FontStoreConnector.re
This is additional logging to help diagnose #820 - in particular, to figure out if we are failing at **shaping** (getting the `glyphId`s that we sent to freetype - that would mean the failure is in `harfbuzz`), or if the failure is actually in the rendering of the glyph in `freetype`.
Unfortunately, we didn't log enough to get this information - so this addresses that gap.
This doesn't fix the issue - but hopefully give enough for the next level of investigation.
> #820 - Additional logging

- scripts/osx/notarize.sh
Check the returned notarization UUID value; if invalid - fail the script. We should fail instead of publishing un-notarized builds.
> OSX - Notarization: Check for returned notarization UUID

- azure-pipelines.yml
- src/Store/StoreThread.re
- src/bin_launcher/Oni2.re
__Issue:__ When launching via `PATH`, on Windows, the `Oni2.exe` was not finding the correct `Oni2_editor.exe` - it was a relative path specified instead of an absolute path.
__Fix:__ On Windows, use `Sys.executable_filename`, which seems to consistently return the full path in all scenarios tested (powershell, cmd, from path, running exe directly).
__Test:__ Update our CI test to properly exercise this case so we don't regress it again
> Fix #872 - Windows: Onivim2 does not launch correctly from CLI

- .ci/use-node.yml
- azure-pipelines.yml
...and trying to install it again is giving us errors. Unfortunately the default node 6.x isn't sufficent, though.
Related issues:
https://github.com/microsoft/azure-pipelines-tasks/issues/11627
https://github.com/microsoft/azure-pipelines-tasks/issues/11626
https://github.com/nodejs/build/issues/1993
> CI: Upgrade to node 10.x

- src/Model/Title.re
- test/Model/TitleTests.re
> Bugfix: Separator when variable is missing

- docs/docs/using-onivim/configuration.md
I was testing zoom values and broke the editor (#907), so I had to figure out where the config file was in order to fix my editor. This pull request documents its location.
> Document where the config file is on the config documentation page

- src/Core/ConfigurationParser.re
- src/Store/ConfigurationStoreConnector.re
There were two problems:
- We were allowing invalid values like `ui.zoom` of `0`, which made the editor unusable - this is very frustrating because there is no entry point to fix or update the editor.
- We were only accepting float values like `1.0` for the setting... so you could hit the above case by using a value of `1` which is invalid.
This issue updates the store connector to make sure the zoom isn't set to a lower value than `1`, as well as our configuration parsing for float values - there is no reason not to accept integers as well.
> Fix #907 - Don't allow invalid values for ui.zoom setting

- scripts/bootstrap.js
- src/Core/Setup.re
- src/Extensions/ExtHostTransport.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/StoreThread.re
- test/Extensions/ExtHostTransportTests.re
- test/Extensions/ExtensionClientTest.re
- test/test_extensions/oni-activation-events-tests/extension.js
- test/test_extensions/oni-activation-events-tests/package.json
- test/test_extensions/oni-api-tests/extension.js
- test/test_extensions/oni-api-tests/package.json
This wires up the 'ExtHostStoreConnector' - which is how the VSCode extension host gets connected to Onivim's store.
Currently, there is only very limited integration:
- Status bar
- Sending buffer updates
And brings back the tests / test extensions we used in our unit tests.
This is the core piece that we need to extend to add more functionality from the VSCode extensions. In particular, we now have UI support for the following:
- Notifications
- Completions
- Diagnostics
- QuickInfo
So the next step will be to connect that to our existing UI (we also need to bring some of the richer extensions, like TypeScript/JavaScript to utilize it!)
> Exthost: Bring back the ExtHostStoreConnector

- Outrun-Labs-EULA-v1.1.md
I wish Github's diff was better...
The change is from "the this Agreements" to "this Agreement"
> Fix typo in EULA

- src/Merlin/MerlinProtocolConverter.re
- src/Model/Actions.re
- src/Model/Diagnostic.re
- src/Model/Diagnostic.rei
- src/Model/Diagnostics.re
- src/Model/Diagnostics.rei
- src/Model/HoverCollector.re
- src/Model/Oni_Model.re
- src/Store/MerlinStoreConnector.re
- src/UI/EditorSurface.re
- src/UI/EditorVerticalScrollbar.re
- src/UI/HoverView.re
- src/UI/Minimap.re
- test/Model/DiagnosticsTests.re
A few refactorings to prep diagnostics for integration with exthost:
- Add a `clear` method to `Diagnostics`
- Move `Diagnostic` to its own module, outside of `Diagnostics`
- Refactor such that the `change` method and `DiagnosticsSet` action use a `Uri.t` instead of a `Buffer.t`, since this is more convenient to use from the exthost
> Refactoring: Tweaks to Diagnostics for exthost integration

- development_extensions/oni-dev-extension/extension.js
- src/Core/Range.re
- src/Core/Range.rei
- src/Core/Utility.re
- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostProtocol.re
- src/Model/Actions.re
- src/Model/Diagnostics.re
- src/Model/Reducer.re
- src/Store/ExtensionClientStoreConnector.re
- test/Extensions/ExtHostProtocolTests.re
This adds handler for the Diagnostics `$changeMany` and `$clear` calls from the VSCode extension host.
- Document via types the incoming data
- Deserialize from JSON RPC
- Coerce to types that are used by our Model
- Dispatch actions when we get updates
> ExtHost: Initial diagnostics integration

- extensions/csharp/.vscodeignore
- extensions/csharp/cgmanifest.json
- extensions/csharp/language-configuration.json
- extensions/csharp/package.json
- extensions/csharp/package.nls.json
- extensions/csharp/snippets/csharp.json
- extensions/csharp/syntaxes/csharp.tmLanguage.json
- extensions/csharp/test/colorize-fixtures/test.cs
- extensions/csharp/test/colorize-results/test_cs.json
This brings over the C# plugin from VSCode, to enable syntax highlighting.
Once we have LSP support - we'll also be able to leverage language features.
> Extensions: Port C# plugin from VSCode

- development_extensions/oni-dev-extension/extension.js
- src/Extensions/ExtHostClient.re
- src/Store/ExtensionClientStoreConnector.re
This adds an integration to the VSCode extension's [`OutputChannel ` API](https://code.visualstudio.com/api/references/vscode-api#OutputChannel), which is important for debugging - because it allows us to capture logs from the extensions (and exposes logging from language servers, which log through `connection.console`).
> ExtHost: Hook up OutputService

- src/Store/QuickmenuStoreConnector.re
- src/UI/QuickmenuView.re
This fixes a bug introduced in #914 where closing the menu in any way other than pressing `Esc` would retain focus, and therefore not forward input to `libvim`. This is a known bug in revery-ui/revery#412, which had a workaround that was only partly removed and not replaced.
> Fix quickmenu retaining focus after being closed

- test/Extensions/ExtensionClientHelper.re
On Windows, sometimes the exthost doesn't initialize within the timeout in the unit tests. This bumps the timeout to give some breathing room for that initialization step.
> Test: Bump timeout for exthost initialization test

- src/Core/ConfigurationDefaults.re
- src/Input/Keybindings.re
- src/Input/Keybindings.rei
- src/Input/Oni_Input.re
- src/Model/Actions.re
- src/Model/State.re
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/StoreThread.re
- src/bin_editor/Oni2_editor.re
This is an extension of @CrossR 's work in #875 to load keybindings. 
A few additions on top of #875:
- Move our 'default' built-in bindings to `KeyBindingsStoreConnector`, which we augment when load the file (this also incorporates the `fixed` bindings that were in the handler)
- Add just a scaffold / template for `keybindings.json` to point to docs + add keybindings. We should look at an even nicer experience down the road, but this is at least customizable!
- Support reloading of keybindings like we do for config
- We should show error messages when there is a failure to load bindings - there is no indication of parse failures at the moment
- There is a decent amount of duplication between `KeyBindingStoreConnector` and `ConfigurationStoreConnector` - if we have an …
> Input: Support loading / reloading of keybindings.json

- integration_test/QuickOpenEventuallyCompletesTest.re
This check:
```
[INFO]  WAITER (Quickmenu is loading is true): Iteration: 1
``` 
was failing intermittently on the CI machine.
It looks like, in some cases, the loading finishes quickly - we can see Ripgrep and the  filtering / processing occurring:
```
[DEBUG] [Job] Starting FilterJob
[INFO] [Job] FilterJob ran 1 iterations for 1.00135803223e-05s
[DEBUG] [Job] Detailed report: Name: FilterJob
- Pending work: - Pending Work
-- totalItemCount: 0 -- allItems: 1 -- itemsToFilter: 1
- Completed work: - Completed Work
-- allFiltered: 0 -- uiFiltered: 0
[DEBUG] [Job] Starting RipgrepProcessorJob
[INFO] [Job] RipgrepProcessorJob ran 1 iterations for 5.00679016113e-06s
[DEBUG] [Job] Detailed report: Name: RipgrepProcessorJob
- Pending work: Byte chunks left: 0
- Completed work:  (no printer) 
``` …
> IntegrationTest - QuickOpenEventuallyCompletes - Make loading check less strict

- azure-pipelines.yml
The cache path:    
```
ESY__CACHE_INSTALL_PATH: /Users/runner/.esy/3__________________________________________________________________/i
```
had an incorrect amount of padding (`_`) after changing the user name.
> CI: Fix esyi path

- azure-pipelines.yml
There is a bug with the windows build cache strategy; but let the MacOS / Linux ones work - so we can at least cache those builds.
> Remove windows publish build cache for now

- development_extensions/oni-dev-extension/extension.js
- extensions/vscode-reasonml/package.json
- src/Extensions/ExtHostClient.re
- src/Model/Actions.re
- src/Model/Commands.re
- src/Store/CommandStoreConnector.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/StoreThread.re
This hooks up contributed commands (commands specified in an extension's manifest) to be visible and executable from our command palette.
> ExtHost - Commands: Hook up contributed commands

- development_extensions/oni-dev-extension/extension.js
- development_extensions/oni-dev-extension/package.json
- integration_test/ExtHostBufferUpdatesTest.re
- integration_test/dune
- src/Extensions/ExtHostProtocol.re
- src/Store/ExtensionClientStoreConnector.re
This fixes and adds an integration test for buffer synchronization cases between Onivim 2 <-> VSCode extension host.
This adds a helper command for development that sends the full-text of a buffer back, for debugging and verification.
> ExtHost - Test: Verify buffer updates

- src/Model/Actions.re
- src/Store/ConfigurationStoreConnector.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/VimStoreConnector.re
- src/Store/WindowsStoreConnector.re
- src/UI/FileExplorerView.re
- src/bin_editor/Oni2_editor.re
This just adds + tests the new `option(Position.t)` parameter for the `OpenFileByPath` action independently of #971 (Locally, I hooked it up to use a hardcoded position for the file explorer - seemed to work OK now!)
> Feature: Add position to OpenFileByPath action

- src/Core/Types.re
- src/Model/Actions.re
- src/Model/CompletionMeet.re
- src/Store/CompletionStoreConnector.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/MerlinStoreConnector.re
- src/Store/VimStoreConnector.re
- test/Model/CompletionMeetTests.re
This is a refactoring to carry the `Position.t` in the `CompletionMeet.t`, so we have the context (both line / column) available for requesting completions in the exthost.
In addition, this fixes a bug where we were always sending a hard-coded position for completion.
Need for #957
> Completion: Refactor to carry position in completionMeet 

- bench/lib/EditorSurfaceBench.re
- bench/lib/Helpers.re
- bench/lib/ReducerBench.re
- src/Model/Editor.re
- src/Model/Editor.rei
- src/Model/EditorGroup.re
- src/Model/EditorGroup.rei
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Store/WindowsStoreConnector.re
- src/UI/EditorGroupView.re
- src/UI/EditorLayoutView.re
- src/UI/EditorSurface.re
- src/UI/EditorView.re
I might have gotten a bit carried away with this, but to my defense I _wanted_ to go a lot further! Initially I just wanted to add a few interfaces to get a better overview of what's in each module, but then it snowballed a bit.
The changes are roughly as follows:
- Add .rei
- Hide internal implementation details as much as possible, to have better control of potential invariants and to have the flexibility to change it without breaking external code.
- Mirror the type definition from `Actions`  so it's easier to look up, so `open Actions` isn't needed to bring the fields into scope and so unnecessary type annotations can be removed in the implementation. That the type is initially defined elsewhere is now a minor detail that doesn't otherwise affect how it's used.
- Replace …
> Refactoring: Editor model cleanup

- src/Syntax/NativeSyntaxHighlights.re
This uses the packed-module technique like @glennsl used for subscriptions, in order to implement dynamic binding / polymorphism for the syntax highlight strategies. This tucks the implementation behind the `SyntaxHighlighter` type.
> Refactoring - Syntax Highlighting: Use packed module

- src/UI/EditorSurface.re
__Issue:__ When typing text into a css file, the entire buffer would disappear:
__Defect:__ This was specific to just CSS files - I couldn't reproduce it in other file types. It turns out that we were getting diagnostics, and this was causing the `<HoverView />` to show up. The `<HoverView />` was the problematic element - even if we just returned `React.empty`, the buffer would disappear (and all buffers would disappear, because there is another bug where the HoverView is not scoped to a particular buffer).
__Fix:__ It appears this was introduced with the latest Revery bump - we might be a hitting case we didn't hit before in the reconciler, with the correct positioning change. I fixed this by 'nesting' the HoverView a level, which would preserve the root `<View />` for the …
> Fix up reconciliation of HoverView

- bench.esy.lock/index.json
- bench.esy.lock/opam/fmt.0.8.8/opam
- bench.esy.lock/opam/logs.0.7.0/opam
- bench.esy.lock/opam/stdlib-shims.0.1.0/opam
- esy.lock/index.json
- esy.lock/opam/fmt.0.8.8/opam
- esy.lock/opam/logs.0.7.0/opam
- esy.lock/opam/stdlib-shims.0.1.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/fmt.0.8.8/opam
- integrationtest.esy.lock/opam/logs.0.7.0/opam
- integrationtest.esy.lock/opam/stdlib-shims.0.1.0/opam
- package.json
- src/Core/Cli.re
- src/Core/Log.re
- src/Core/Log.rei
- src/Core/dune
- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostTransport.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/FontStoreConnector.re
- src/Store/InputStoreConnector.re
- src/Store/StoreThread.re
- src/bin_editor/Oni2_editor.re
- src/bin_launcher/Oni2.re
- test.esy.lock/index.json
- test.esy.lock/opam/fmt.0.8.8/opam
- test.esy.lock/opam/logs.0.7.0/opam
- test.esy.lock/opam/stdlib-shims.0.1.0/opam
This switches over to using dbuenzli's `logs` library. It's at feature parity and backwards compatible with the old `Log` module, but now also prints in shiny colors!
I've also added some preliminary namespace support using tags as a proof of concept, and I think we should be able to have a namespace hierarchy with both fixed and ad hoc namespaces., filtering and hash-based coloring. I'd like to add that too before merging this, but have to do a bit of research to find a good way to do the filtering first.
> Switch to using "logs" as the logging framework

- src/UI/EditorSurface.re
This is a regression from #1003 - the 'overlay' that contains the diagnostics and completions was taking over mouse events, and not letting them be handled by the editor.
Unfortunately, we don't currently have test coverage for this - something we should explore adding so that we can verify simple scenarios like mouse-click build-over-build and protect against regressions of this class.
> Bugfix: Mouse events not making it to editor

- src/Model/Buffer.re
- src/Model/Buffer.rei
- src/Model/Buffers.re
- src/Model/FilterJob.re
- src/Store/QuickmenuStoreConnector.re
This addresses a few issues from #1017:
- Sorting Ctrl+Tab menu by MRU
- Initial "flickering" in Ctrl+Tab and Ctrl/Cmd+Shift+P menus
The flickering issue was caused by FilterProcessingJob reversing the items while processing them because it uses lists instead of queues when processing. The fix here is just to bypass filtering entirely if there's no filter. Note however when a filter is applied, this will still cause similarly ranked items to appear in reverse order. Probably not an issue in practice, but might be worth considering using a queue here anyway to alleviate it.
Note also that this doesn't fix the non-determinism of the Ctrl/Cmd+P menu. That definitely does need to use a queue during processing.
> Sort Ctrl+Tab menu by MRU

- integration_test/LanguageCssTest.re
- integration_test/LanguageTypeScriptTest.re
- src/Core/Uri.re
- src/Core/Uri.rei
- test/Core/UriTests.re
- test/Extensions/ExtensionClientTest.re
__Issue:__ There was a discrepancy in the way we were serializing Uris on Windows, and the way the VSCode extension host handles them.
In particular, the VSCode extension host expects a slash prefix - we were sending paths like `C:/test.css`, but the VSCode extension host expected them as `/C:/test.css`. This meant that the URIs we sent VSCode for buffer enter / updates, and then the URIs we'd receive for diagnostics would be out-of-sync. So we'd get them, but when we'd go to look them u p, the URls wouldn't match.
__Fix:__ Use the same convention as the VSCode exthost - always prefix with a `/` character, and ensure the drive letter is lowercase.
Fixes #1019
> Fix #1019 - ExtHost / Windows: Diagnostics not showing on windows

- src/Core/Utility.re
- src/UI/EditorSurface.re
This is some prepatory work for #1026 - this adds some UI to the editor surface to show underlines when necessary. 
his is turned off for this PR, but with #1026 , we'll bring back the 'renderUnderline' for the tokens when a definition is available at the cursor position.
While going through the EditorSurface code, I've also called out several refactorings: https://github.com/onivim/oni2/projects/10#card-30388562
> Feature: Editor - getTokenAtPosition + underline rendering

- src/Core/Ripgrep.re
- src/Model/Actions.re
- src/Model/FilterJob.re
- src/Store/FilterSubscription.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/RipgrepSubscription.re
- src/Store/StoreThread.re
- src/Store/VimStoreConnector.re
- src/UI/FlatList.re
- src/UI/OniInput.re
Bugs fixed:
- Input prefix multiplied like rabbits. Caused by not properly distinguishing between the actual value and the value to display, which should include the prefix.
- Filtered items where duplicated. Caused by the FilterJob revamp earlier today, although I still don't understand how it could have worked before without this fix either.
- Ripgrep seemed to never complete, causing the loading animation to animate forever and ever. Root cause was that `onComplete` was called when the ripgrep process had completed, but the processing still hadn't, triggering further `onUpdate` calls that set the state to `Loading`.
- FlatList was overflowing its container when displaying many items initially. Caused by the initial height estimation overriding the later measurement. It now uses the …
> Various quickmenu bugfixes

- integration_test/SyntaxHighlightTextMateTest.re
- integration_test/SyntaxHighlightTreesitterTest.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- integration_test/some-test-file.json
This adds some simple, sanity-check syntax highlight tests for both 'TextMate' and 'Treesitter' strategies - to help protect against regressions in #922
> Syntax Highlight Integration Tests

- src/Model/BufferLineColorizer.re
- src/Model/BufferLineColorizer.rei
- src/UI/EditorSurface.re
- test/Model/BufferLineColorizerTests.re
__Issue:__ The way we figured out the 'colorization' state of tokens was very efficient. 
Previously, we'd create an `Array.t` _the entire length of the line_ - and then apply syntax coloring to each cell of the array. This is problematic, and wasteful, for large lines - we only care about colorizing within the visible view.
This change scopes this colorization process to just the visible size of the line, which is very helpful for large lines.
A further improvement would be to not require the `List.rev(..)` of the tokens, but we should have #922 come in prior to that, as #922 changes the shape of the syntax highlight model.
> Perf - Editor: Scope colorization of line to active view

- src/Core/BufferUpdate.re
- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/FsTreeNode.re
- src/Model/FsTreeNode.rei
- src/Model/Workspace.re
- src/Store/FileExplorerStore.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/VimStoreConnector.re
- src/UI/FileExplorerView.re
- src/UI/FileTreeView.re
- src/UI/LocationListView.re
- src/UI/TreeView.re
This highlights the current buffer in the file explorer, opens all directories in the path to the current buffer and scrolls the view so it's visible. You'd think this would be pretty straight forward, but unfortunately it is not.
One issues is that the path to the current buffer might only be partially loaded. We therefore need to traverse the tree until encountering an unloaded directory, load that asynchronously, wait for the result and then try again. This works fine as it is now, but is a bit complicated.
Another issue is that it should only scroll to the focused item on `BufferEnter`, but currently does so whenever the focus changes AND even just when opening a directory since that updates the tree including node ids and hence causes comparison of the node path to fail. The root …
> File explorer focus

- src/UI/EditorSurface.re
Fixes #1045 
We should only be showing suggestions and the other hover elements in the _active_ split - currently, they'd show in all splits with the same buffer.
> Fix #1045: Only show suggestions in active split

- src/Core/Ripgrep.re
- src/Core/Utility.re
- src/Model/FilterJob.re
- src/Store/FilterSubscription.re
- test/Core/UtilityTests.re
- test/Model/FilterJobTest.re
Performance-wise the only significant difference is that adding items takes twice as long because the length of each chunk is computed twice, inside each of the queues it is added too. Previously it could be computed once since the total count was dealt with separately.
TODO:
> Implement and use immutable queue for Ripgrep and FilterJob

- src/Model/FsTreeNode.re
- src/Model/FsTreeNode.rei
- src/Model/Workspace.re
- src/UI/FileTreeView.re
So far I've just added logging. I'm not sure how to find good test cases for this. A good test case would be a file that's both deep in the hierarchy, is nested in directories with many items and also listed late in those directories.
The worst case I found had `toNodePath` use 2e-05s.
I also found that focus does not work when the workspace is set to root (`/`) though. I need to look into that before I implement the hashing.
> File Explorer performance tweaks

- src/Model/Diagnostic.re
Fix #1052 - used zero-based index for measuring length of buffer line
> Fix #1052: Crash with diagnostic at end of file

- src/UI/EditorSurface.re
If there was a highlight (from a document highlight provider) __and__ an available definition - we would draw the highlight on top of the underline, so it wouldn't be visible. We should draw the underline on top of the highlight.
> Bugfix: Go-to definition underline not showing up w/ highlight

- src/Core/Log.re
When a crash occurs in the OCaml code, even if logging isn't enabled, we'll write an `onivim2-crash.log` file - at least giving the exception message, which can give us an idea of the class of error.
> Debug: Write a 'crash log' whenever Onivim 2 crashes - so it is more actionable

- src/Store/VimStoreConnector.re
When using either characterwise visual mode (`v`) or blockwise visual mode (`<c-v>`), the selection highlights would be off by one column.
> Fix off-by-one bug in the visual range integration

- azure-pipelines.yml
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Core/Cli.re
- src/Core/Log.re
- src/Core/Log.rei
- src/bin_launcher/Oni2.re
__Issue:__ There seems to be a hang on Windows intermittently when running the integration tests & health checks on CI.
I can actually reproduce it locally with `esy '@integrationtest' run` in Powershell. It seems there are some errant term codes that cause the console to expect input even after the processes end. This might be a combination of the colorization + some threaded output we get from the syntax server.
In any case, turning off the colors fixes the hang for me locally, so I added a CLI option `--no-log-colors` and use it for the health checks, and turned off colored output for the integration tests on Windows.
> CI: Fix hang for Windows when running integration tests / health check

- src/Store/FileExplorerStore.re
Fixes #1070 - a crash when trying to edit a directory.
It's a bit of a mystery why we are hitting this case in packaged builds, but _not_ in development builds / running the executable directly.
This prevents the crash, but the focus behavior is not correct (it doesn't actually focus the directory).
> Fix #1070: Crash when running ':e ~/some/directory' in OSX build

- azure-pipelines.yml
It looks like we were still getting colored output on CI, with the command:
```
Oni2.exe -f --checkhealth --no-log-colors
```
With the way the CLI parsing is done - the health check was being run before applying the `--no-log-colors`. In #1065 , the CLI parsing will be fixed to apply all the arguments prior to running commands like health-check. But in the short-term, this puts `--no-colors` before `--checkhealth` to unblock CI builds.
> CI: Move --no-log-colors before checkhealth

- src/Model/WindowTree.re
- test/Model/WindowTreeTests.re
Fixes #1071 
__Issue:__ In certain cases, the editor surface wouldn't expand to fill up the available space after removing a split.
__Defect:__ When a split is removed, we filter out all the 'empty' splits. However, there was a case missed - if, after filtering, a parent has 0 children, we'd leave it around (and it would take up space) - but that should be removed too.
__Fix:__ Remove parent with 0 children after filtering.
> Fix #1071: Empty editor split

- azure-pipelines.yml
- scripts/windows/validate-release.ps1
Missed one spot that was still hanging - the `Oni2.exe -f --checkhealth` call line in our windows validation script. This adds `--no-log-colors` to it, too.
> CI: Add --no-log-colors to validation

- src/Core/Utility.re
- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/FsTreeNode.re
- src/Model/FsTreeNode.rei
- src/Model/Workspace.re
- src/Store/FileExplorerStore.re
- src/Store/QuickmenuStoreConnector.re
- src/UI/FileExplorerView.re
- src/UI/FileTreeView.re
- src/UI/LocationListView.re
- src/UI/TreeView.re
This implements basic keyboard navigation (up arrow/down arrow) and selection (enter) _within_ the file explorer. There's no way to use the keyboard to focus the file explorer, however, so it's not very useful for end-users yet. And because of the mechanism used to capture keyboard input it also blocks all keybindings. But it's useful for testing keyboard input and relatively self-contained, so I'm submitting this now to try to keep PRs manageable.
Addresses #528
> File Explorer Keyboard Navigation - Part 1

- src/Model/Actions.re
- src/Store/CommandStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/SearchStoreConnector.re
- src/UI/SearchPane.re
Fixes #1054 (At least partially)
Adds a new keybinding to toggle Search, and gives focus to the input when pane is opened. Unfortunately it's not very practical to focus the input outside the view as it would require storing the input ref in the state or a global. So instead the hotkey just toggles the pane. We can revisit this once I've changed the focus mechanism so it's controlled bottom-up.
> Search hotkey

- scripts/windows/validate-release.ps1
Looking at the CI failure for #1087 (<https://dev.azure.com/onivim/oni2/_build/results?buildId=8227&view=logs&j=16afaa31-88f2-57dc-4c6f-57177f9c64fc&t=11c2e412-6171-5c8e-1aae-001304ca28f3>), I realized there was still another place I missed `--no-log-colors` for Windows in #1078 and #1079.
This fixes the remaining spot so hopefully no more hangs of that class in CI.
> CI: Add --no-log-colors to missed windows health check

- src/Core/Theme.re
The `editorRuler.foreground` color was always hardcoded, regardless of theme - this picks it up when available.
> Bugfix - Theming: Pick up editorRuler.foreground theme color

- docs/docs/configuration/extensions.md
- docs/docs/using-onivim/command-line.md
- docs/website/sidebars.json
- src/bin_launcher/Oni2.re
Some of the docs are a bit duplicated between CLI/Extensions. Arguably for a flagship feature, I think we should have a distinct page for extensions, so this can hopefully be the start of that.
I also updated the CLI flag text and added it for every flag, such that they show up, and aligned them all.
> Docs - Update Docs/CLI Help Text.

- src/Core/Cli.re
- src/Store/ConfigurationStoreConnector.re
- src/Store/StoreThread.re
- src/Store/SyntaxHighlightingStoreConnector.re
- src/bin_launcher/Oni2.re
This adds a few additional CLI commands:
- `--disable-syntax-highlighting` - don't start up syntax server or do highlight
- `--disable-configuration` - don't load configuration on startup
- `--disable-extensions` - don't load extensions
to assist in troubleshooting.
> CLI: Add CLI options to assist with troubleshooting

- .ci/swap-xcode.yml
- azure-pipelines.yml
This is just a test to change the macOS CI to use Xcode 8, which is compatible with macOS 10.12 (to my knowledge). I think this means we'd be compatible with 10.12, though I could be very wrong.
A quick look in my CI looks like there is some build failures over in `esy-sdl2`, so opening just so some people with more understand than me can see.
> CI/Builds - Support macOS 10.12

- src/Core/Utility.re
- test/Core/UtilityTests.re
This is laying the groundwork for handling configuration properly from extensions, which define configuration settings, and wiring them up into the extension host.
When we send configuration updates to the extension host, there are two things we need:
- A list of keys that have changed, with the full-path, like `typescript.suggest.enabled`.
- The fully-expanded configuration, like: ` { "typescript": { "suggest": { "enabled": true } } } `
We're missing both of these pieces today (well, we hard-code them specifically for the typescript / javascript language services - but that doesn't scale to bringing in new extensions).
This adds a couple of utilities that let us expand JSON into the fully-expanded format, and also gather a list of keys. These utilities will enable us to bring in the …
> Extension - Configuration - Part 1: Initial configuration utilities

- src/Store/TitleStoreConnector.re
> Add missing editor/folder specific title vars

- src/bin_editor/HealthCheck.re
A couple of the `node` health-checks were failing intermittently in Windows. This is an attempt to refactor to use our `NodeTask` API (which should be reliable - we are using it to run various node scripts) to compare the reliability.
> Bugfix: Health-check flakiness

- src/Core/Utility.re
- src/Extensions/ExtensionContributions.re
This change implements parsing / reading of the `configuration` section of VSCode extensions.
We need this to be able to provide the extension host with the appropriate set of defaults on initialization (and later, the metadata can be used to provide an improved configuration experience).
> Extensions - Configuration - Part 2: Parse configuration info

- src/bin_editor/Oni2_editor.re
Noticed a stray log prior to initializing the syntax server - we override the logging strategy in the syntax server to not write to a file (for now), so we want to defer logging until after initialization.
We should probably enforce this more strictly...
> Bugfix: Remove stray log

- src/Core/Log.re
Still seeing hangs on Windows output - this change disables log colors completely. Hopefully this helps make the healthchecks more reliable.
> CI: Disable log colors completely in Windows

- src/Core/Ripgrep.re
- src/Core/Utility.re
- src/UI/SearchPane.re
- test/Core/UtilityTests.re
Fixes #1113. Stack Overflows be gone.
I had to provide stack-safe implementations of both `List.concat` and `List.map`. It also still seems to lock up after a few hundred thousand search results. Perhaps we should impose some kind of limit, like vscode does. Not sure what exactly their limit is as it seems to vary by query, but it seems to be in the range of 25,000-50,000.
> Fix stack overflow crashes with a large number of search results

- scripts/windows/validate-release.ps1
We're seeing hangs in the run of `--checkhealth` when we run in a powershell script:
...somehow, we're still getting some colored output / escape codes.
This validation isn't very necessary - we have better validation (via running in `cmd.exe` to regression test #872 ) - we should just leverage that. At least, lets see if that is more reliable.
> Windows - CI: Remove powershell health check

- src/UI/QuickmenuView.re
The menu looks a bit naked without the input, but I'm hoping that's just because it's unfamiliar. If not, we could add a heading to cover its bald head. :tophat:
> Hide unused input for EditorsPicker (Ctrl+Tab menu)

- src/Extensions/ExtensionManifest.re
> Fix #1138 - vscode-python - Make 'author' parsing less strict

- .ci/esy-check-hygiene.yml
Instead of running `yarn audit` manually all the time - we should include it in our hygiene checks (to ensure node dependencies we ship are always in good shape, build-over-build).
> Yarn: Add audit checks build-over-build

- src/Input/Keybindings.re
- test/Input/KeybindingsTests.re
__Issue:__ We changed our `when` syntax from a nested array, like `[["editorTextFocus"]]` to real expressions, like "editorTextFocus && !insertMode".
__Defect:__ We didn't have a backwards-compatible way to parse keybindings with the old syntax. We should, so that we don't break configurations.
__Fix:__ Add parsing to handle the previous `when` syntax, too.
Fixes #1152
> Fix #1152: Key binding regression w/ legacy 'when' syntax

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This picks up @CrossR 's libvim fix for #561 - fixing an issue where the opcount isn't correct in various situations: https://github.com/onivim/libvim/pull/177
The fix also has a nice set of test cases for various opcount-related functionality, like `2d2d`, `4dd`, etc.
Fixes #561
> Fix #561 - 'ndd' deletes n^2 lines

- src/Input/Keybindings.re
- test/Input/KeybindingsTests.re
__Issue:__ The format of our `keybindings.json` underwent a revamp to be closer in terms of compatibility with VSCode. 
However, in some older versions of Onivim 2, we dropped our default keybindings in a file - these would override the newer defaults, and some of the command names changed. Specifically:
- `quickOpen.open` was changed to `workbench.action.quickOpen`
- `commandPalette.open` was changed to `workbench.action.showCommands`
Fixes #1160 
__Fix:__ The JSON structure of the legacy format is different, so we can detect that case, and run an upgrader to address this change.
> Fix #1160: Command Palette / Quickopen key bindings not working in some cases

- src/UI/PaneView.re
- src/UI/WelcomeView.re
This adds `overflow(Hidden)` to the welcome screen container. This might be something we want more generally across all the 'buffer renderers', as we add them.
In addition, a couple small tweaks:
- Adds a `backgroundColor` to the bottom pane
- Adds some dynamic sizing to the keybindings - so they collapse a bit as the view gets smaller. It's still not ideal when the window is very small, but in that case, we could consider hiding them.
Fixes #1156
> Fix #1156 - Welcome screen overflows

- extensions/php/.vscode/launch.json
- extensions/php/.vscode/tasks.json
- extensions/php/.vscodeignore
- extensions/php/build/update-grammar.js
- extensions/php/cgmanifest.json
- extensions/php/language-configuration.json
- extensions/php/package.json
- extensions/php/package.nls.json
- extensions/php/snippets/php.snippets.json
- extensions/php/syntaxes/html.tmLanguage.json
- extensions/php/syntaxes/php.tmLanguage.json
- extensions/php/test/colorize-fixtures/issue-28354.php
- extensions/php/test/colorize-fixtures/issue-76997.php
- extensions/php/test/colorize-fixtures/test.php
- extensions/php/test/colorize-results/issue-28354_php.json
- extensions/php/test/colorize-results/issue-76997_php.json
- extensions/php/test/colorize-results/test_php.json
I slightly lied in the issue (https://github.com/onivim/oni2/issues/707), this wasn't as easy as just copying over.
It looks like the second part of the JSON was confusing Oni2, ([this part](https://github.com/microsoft/vscode/blob/af59519833a55eed13db8c9be4175395a400d3b2/extensions/php/package.json#L40-L51)). With that, we just treated it as HTML by the looks of things, rather than HTML. Removing it gives proper syntax in pure PHP files at least.
Is that known, or should I raise an issue?
> Add PHP extension.

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Store/KeyBindingsStoreConnector.re
- test.esy.lock/index.json
__Issue:__ Pressing `Cmd+W` closes the entire app. This is problematic because in OSX, `Cmd+W` generally closes the active tab. Breaks muscle memory!
__Defect:__ In `SDL2`, there is a default menu handler set up for closing a window. We don't currently override or set the menu, so this gets used - and it breaks our ability to hook in and add 'user-space' handling of the menu.
__Fix:__ The full fix will be to define our own application menu in Revery, but since we don't have that yet - this disables the 'Close' menu item in SDL2 (https://github.com/revery-ui/esy-sdl2/pull/8) and adds a handler for `Cmd+W` to close the active editor.
Fixes #1169 and #992
> Fix #1169 / #992 - Command+W should close current window

- .gitattributes
This change enables syntax highlighting correctly and may improve readability on the GitHub.
> Recognize all re files as Reason

- src/ExtensionManagement/Oni_ExtensionManagement.re
Should fix most of the common issues people have when trying to install an extension with a relative path.
> Make relative extension path absolute.

- src/bin_launcher/Oni2.re
Fix #1158
For some of the extension commands, like `--install-extension` and `--uninstall-extension`, we were not sending output to the console.
__Issue:__ We have a 'launcher' process in `Oni2` (mainly for Windows) that spawns the actual editor process - we need to specify when the stdout/stdin pipes should stay 'attached'. If they aren't, then we'll lose the output in the terminal.
__Fix:__ For `--install-extension`, `--uninstall-extension`, and `--list-extensions`, have them stay attached. The `-f` flag can be used to get additional debug logging.
> Bugfix: Show message for install-extension result

- src/Core/Cli.re
- src/Core/Log.re
- src/Core/Log.rei
In investigating the logs for #1185 , I saw that the '--debug' flag was being passed, but we weren't actually get stack traces, like would be expected.
It turns out that we are only recording backtraces if the environment variable is set on initialization (`ONI2_DEBUG=1`). If the `--debug` flag is set, we don't actually call `record_backtrace`.
This updates our logic so that, if either the environment variable is set (ie, `Timber.isDebugLoggingEnabled()` is true to start), or if the `--debug` flag is passed - we'll run `Printexc.record_backtrace` so we can get a better exception message.
> Bugfix - Logging: Hook up '--debug' to also provide stacktraces

- src/bin_editor/Oni2_editor.re
- src/bin_launcher/Oni2.re
Fix a couple of issues with the version output:
- Change `Onivim2.major.minor.patch` -> `Onivim 2 (major.minor.patch)`. 
- Remove hardcoded version in the 'usage' section.
Fixes #1221
> Fix #1221: Clean up version output

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
In addition to using native printf to avoid crashing on Windows, this:
- appends to the log file, so multiple processes can safely log to the same file. An optional `truncate` argument can be passed to `setLogFile`, which the main process can use to start from scratch each time.
- timestamp added to the log file header
- uses black foreground for all log levels, since that seems to be most legible with normal terminal colors
> Dependency: timber -> ae5de6c

- .ci/esy-build-steps.yml
- .ci/js-build-steps.yml
- docs/docs/for-developers/building.md
- node/package.json
- node/yarn.lock
This brings in vscode-exthost@1.33.5, in preparation for wiring up the terminal service APIs
__TODO:__
> Dependency: vscode-exthost -> 1.33.5

- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/FsTreeNode.re
- src/Model/FsTreeNode.rei
- src/Store/FileExplorerStore.re
- src/UI/TreeView.re
This implements scrolling to follow focus, and does so using a spring. It also refactors a few FsTreeNode functions to be more consistent with he rest, using string paths instead of node paths.
The scrolling logic has become a bit complicated, but could be simplified a bit with a spring hook that included a setter. It would also be nice to have a way to do "hard" transitions, like when scrolling with the mouse wheel, as it currently feels a bit sluggish.
> File Explorer - scroll to follow focus + spring + minor refactor

- src/Components/MessageBox.re
- src/Model/Actions.re
- src/Model/Buffers.re
- src/Model/Modal.re
- src/Model/State.re
- src/Store/LifecycleStoreConnector.re
- src/Store/StoreThread.re
- src/UI/Modals.re
- src/UI/Root.re
- src/bin_editor/Oni2_editor.re
Fixes #610
The message is a bit unbalanced, both visually and in terms of "scanability". It would be better to lead with a very short question summarizing the decision to be made, and then expand on it. We can tweak this later though, but it would be nice to have rich text support to be able to more easily to so.
A neat keyboard interface is planned for a subsequent PR.
> Warn when closing window with unsaved changes

- src/Components/Input.re
Code it wasn't counting full input value since that cursor was off to the left for a size of prefix.
This fixes this bug. Now cursor
in place:
> Fixes cursor position for menu dialog with prefixes

- docs/docs/for-developers/building.md
- src/Core/Setup.re
This adds some documentation describing on how to test / work with the extension host (it's useful to add logging to it when things go wrong!)
Also, when I was testing locally, what I'd often do is remap the `setup.json` to point to my local vscode exthost build. I made that a bit easier in this PR by providing a `ONI2_EXTHOST` env variable that can be used to override this setting - that just needs to point to a `vscode-exthost` folder (should be built, of course!).
> Development / Documentation: Add instructions for working with exthost

- src/Components/ContextMenu.re
- src/Components/ContextMenu.rei
- src/Components/Oni_Components.re
- src/Components/dune
- src/Model/Actions.re
- src/Model/Notifications.re
- src/Model/State.re
- src/Model/StatusBarModel.re
- src/Store/ContextMenuStore.re
- src/Store/StoreThread.re
- src/UI/Root.re
- src/UI/StatusBar.re
Although perhaps more importantly, this adds a ContextMenu component for general use.
> Add ContextMenu to Notification Status Bar item

- ThirdPartyLicenses.txt
- src/Core/Diff.ml
- src/Core/Diff.mli
This adds the diff algorithm from camlp5 directly, instead of the Jane Street derivate because their interface is actually significantly different. This one essentially returns a list of adds and a list of deletes, while the Jane Street one returns a list of pointers to the lines that are the same in both. The former seems much easier to work with to me at least.
I've added a copyright notice and link to the original to the top of each file. Is that sufficient or should I add it to `ThirdPartyLicenses.txt` as well?
> SCM: Add diff algorithm, borrowed from camlp5

- azure-pipelines.yml
- scripts/windows/BuildSetupTemplate.js
Simpler / lower risk fix than #1241 and #1248 - just point the installer + shortcut to 'Oni2_editor.exe'. Should be transparent to the user, running `Oni2.exe` still works as expected.
> Windows: Point installer / shortcut to Oni2_editor.exe

- bench.esy.lock/index.json
- docs/docs/for-developers/contributing.md
- esy.lock/index.json
- integration_test/lib/Oni_IntegrationTestLib.re
- integrationtest.esy.lock/index.json
- package.json
- src/Core/Cli.re
- src/Core/Job.re
- src/Core/Kernel/Log.re
- src/Core/Kernel/Log.rei
- src/Extensions/ExtHostTransport.re
- src/Feature/Search/SearchSubscription.re
- src/Input/Expression.re
- src/Input/Handler.re
- src/Store/ExtensionClientStoreConnector.re
- src/Store/FilterSubscription.re
- src/Store/FontStoreConnector.re
- src/Store/RipgrepSubscription.re
- src/Store/VimStoreConnector.re
- src/Syntax/TextmateTokenizerJob.re
- src/Syntax_Client/Oni_Syntax_Client.re
- src/UI/EditorSurface.re
- src/bin_launcher/Oni2.re
- test.esy.lock/index.json
This updates both Revery and timber, since the timber API has breaking changes. Depends on https://github.com/revery-ui/revery/pull/731.
Adds a new trace log level, and a new CLI option to enable it: `--trace`
> Dependency: revery -> 1ccda2b; timber -> ae065bb

- docs/website/sidebars.json
It was removed in #905 for non-obvious reasons, possibly unintentional.
> [docs] Add installation page back in the sidebar

- azure-pipelines.yml
The Windows cache path changed from `esy@0.5.8` to `esy@0.6.0` - this fixes it.
> CI: Fix cache path

- docs/docs/for-developers/architecture.md
Many seem understandably confused by the bad error message when running `esy @test run` without first running `esy @test install`, so a reminder in the docs seems like a good idea.
> [docs] Add reminder to run `esy @test install` before `esy @test run`

- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- test/Core/ConfigurationParserTests.re
This was due to a bug in parseStringList in ConfigurationParser. This
also affected `files.exclude`.
> Fix #1272: Evaluate experimental.viml commands in correct order

- bench/lib/EditorDiffMarkersBench.re
- development_extensions/oni-dev-extension/extension.js
- src/Core/Buffer.re
- src/Core/Buffer.rei
- src/Core/Oni_Core.re
- src/Core/Theme.re
- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostClient.rei
- src/Extensions/ExtHostProtocol.re
- src/Model/Actions.re
- src/Model/SCM.re
- src/Model/State.re
- src/Store/ExtensionClientStoreConnector.re
- src/UI/EditorDiffMarkers.re
- src/UI/EditorDiffMarkers.rei
- src/UI/EditorSurface.re
- src/UI/Minimap.re
- src/UI/Oni_UI.re
- src/UI/dune
- test/OniUnitTestRunner.re
- test/OniUnitTestRunnerUI.re
- test/UI/EditorDiffMarkersTest.re
- test/UI/TestFramework.re
- test/UI/dune
- test/dune
Part of the SCM extension integration, this adds diff makers to the editor and minimap showing the changes made to the current file relative to its checked-in or staged counterpart.
This implementation differ from vscode's in that they show the whole block as modified if there are both additions and deletions overlapping in said, while this implementation is more granular in a sense, showing a line as modified only if there's both an addition and deletion on that line, and otherwise treating them as stand-alone additons and deletions. For example, in the above screenshot. the deletion at the end of the first block would not be present in vscode.
This is functionally ready to be merged, although there;s still plenty of room for improvement:
> SCM: Editor diff markers

- src/Core/Oni_Core.re
- src/Core/SCMDecoration.re
- src/Core/Theme.re
- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostClient.rei
- src/Extensions/ExtHostProtocol.re
- src/Model/FileExplorer.re
- src/Model/FileExplorer.rei
- src/Model/SCM.re
- src/Store/ExtensionClientStoreConnector.re
- src/UI/FileTreeView.re
This adds Source Control decorations to the file explorer, ie. embellishments showing the source control resource state of files. It also adds some list theme colors and uses those properly.
There are some uncertainties here though:
I'm not sure how vscode updates the SCM. Currently we execute `git.refresh` on `BufferUpdate`, which isn't great because it happens too frequently and of course only works for git. There is unfortunately no save action/event though, so `BufferUpdate` seems like the best approximation for now.
I'm also not sure what some of the values we get actually are. The type of the payload as defined in the protocol, of which I have yet to figure out the first two, is:
```
export type DecorationData = [number, boolean, string, string, ThemeColor, string];
```
I don't know …
> SCM: File Explorer decorations

- integration_test/EditorFontFromPathTest.re
- scripts/release.js
Add the reason-language-server executable in the `executable` section for code-signing - it was being missed by our code-signing script because it was put in the `Resources` directory instead of the `MacOS` directory of the app bundle.
> Bugfix: Add RLS as executable in OSX release script

- integration_test/EditorFontFromPathTest.re
- src/Feature/Editor/EditorSurface.re
Reported as a comment on the Patreon post - thank you Eric! https://www.patreon.com/posts/onivim-2-v0-3-0-32839297
Clicking on a line number, or the diff line on the editor surface, causes an ` Invalid_argument("index out of bounds"): ` error. This is because it calculates the position as if it were part of the line - but it is before the line - so we end up with a negative column - which crashes when we try to look up the text at the position.
@glennsl has a more thorough fix coming as part of revamping / refactoring the EditorSurface - but this is a quick fix in the meantime to keep it from crashing.
> Bugfix: Crash when clicking on line number

- integration_test/EditorFontFromPathTest.re
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Core/Constants.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/EditorLayout.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/EditorVerticalScrollbar.re
- src/Feature/Editor/Minimap.re
- src/Model/EditorReducer.re
- src/Model/EditorVisibleRanges.re
- src/UI/FileTreeView.re
- src/UI/SideBarView.re
- src/UI/Tab.re
- test/Core/ConfigurationParserTests.re
__Issue:__ If there is an error parsing `editor.fontSize` today - the editor defaults to the font size to _`0`_, which is a horrible default. It's a really poor user experience to hit this when experimenting with configuration, and becomes difficult to recover from if you can't see the text.
__Fix:__ Add more resilient parsing for `editor.fontSize`:
- Handle floats
- Handle strings
- In the case where there is an error parsing, revert to default
- In the case where a value is too small, use the minimum size
Fixes #1286 - thanks for logging the issue, @johnridesabike!
> Fix #1286: Invalid font size causes text to be invisible

- node/package.json
- node/yarn.lock
Related to #1290 - temporary fix to re-enable notarization
> Downgrade to vscode-exthost@1.33.4 to fix notarization, temporarily

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Feature/Editor/BufferViewTokenizer.re
- test.esy.lock/index.json
Pick up several performance improvements in the Skia layer:
- `recalculate` phase improvements: https://github.com/revery-ui/revery/pull/754
- Caching of paint objects for nodes: https://github.com/revery-ui/revery/pull/756
- Speed up performance of setting Paint color: https://github.com/revery-ui/revery/pull/755
__TODO:__
> Revery: Pick up additional perf improvements from Revery & Reason-Skia

- docs/docs/for-developers/building.md
Add a note in our build docs about the 'Too many open files' error on MacOS ( #1276 )
> Docs: Add note about 'Too many open files' error on macOS

- src/Store/ExtensionClientStoreConnector.re
> Fix #1304: prevent git.refresh when no providers to avoid notification storm

- src/Components/ContextMenu.re
- src/UI/OniBoxShadow.re
Both the quick menu and context menu drop shadows had disappeared, but for different reasons. The context menu shadow disappeared because the color alpha channel started working and ti was set to a tiny amount, and the quick menu shadow disappeared because it's not rendered unless there's also a background color.
> Fix box shadows

- src/UI/MenuItem.re
Apparently we need `NoWrap` now.
The icons are still a bit misaligned, as are the file explorer icons, but I think it'd be better to try to get baseline alignment right in Revery before adjusting this.
> Bugfix: Make QuickMenu icons show again

- development_extensions/oni-dev-extension/extension.js
- development_extensions/oni-dev-extension/package.json
This adds a command to show the list of `vscode.workspace.workspaceFolders`, for debugging (to show the workspace info from the perspective of a plugin):
FYI @glennsl - added this based on our convo today.
I took a look at the git extensions, and I think this is an interesting spot:
https://github.com/onivim/vscode-exthost/blob/8ebec0403c19a038932368df8c89e4676e923dd2/extensions/git/src/model.ts#L69
It uses the following APIs:
- `vscode.workspace.onDidChangeWorksapceFolders`, which we should support today
- `vscode.window.onDidChangeVisibleTextEditors`, which isn't currently supported (this might be how it decides to refresh?)
- `vscode.workspace.onDidChangeConfiguration` - not yet supported (planning on implementing this with #1157 )
- `vscode.workspace.createFilesystemWatcher` - not …
> Developer: Add command to show the list of workspaceFolders

- src/UI/FileTreeView.re
#1330 added a new use of `SCMDecoration` while #1327 renamed it to `Decoration`, causing a build failure but not a merge conflict. This renames the new use as well.
> Fix build failure caused by merges overlapping without conflict

- bench.esy.lock/index.json
- bench.esy.lock/opam/ppx_tools.6.0+4.08.0/opam
- esy.lock/index.json
- esy.lock/opam/ppx_tools.6.0+4.08.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ppx_tools.6.0+4.08.0/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/ppx_tools.6.0+4.08.0/opam
`reason-language-server` doesn't currently support OCaml 4.9.0 (there's an open PR here: https://github.com/jaredly/reason-language-server/pull/351), which causes problems when working on Onivim's code from Onivim. 
This downgrades to 4.8.0 as a temporary workaround. However, better long-term fixes would be:
- Help get the RLS fix in for 4.9.0
- Experiment with picking up the [`ocaml-lsp`](https://github.com/ocaml/ocaml-lsp) binary, if available.
> Dependency: Downgrade to ocaml 4.8.0; update lockfiles

- src/UI/TreeView.re
This fixes a memory leak in the TreeView - it seems that the `node` was being captured in a closure and not being cleaned up. Opening / closing the explorer would lead to the memory growing relatively quickly.
I believe this was a pre-existing memory leak, but because we now allocate [additional Skia objects per-node](https://github.com/revery-ui/revery/blob/2327429ff895c780f97c2f695ac42106e21759a2/src/UI/Node.re#L72), it is now exacerbated.
I could consistently repro this leak on all platforms by opening and closing the treeview, but I suspect there were other manifestations as well. It'll be worth taking a pass over other places we use `ref` and seeing if we can have a lighter dependency - we can add additional eventso the revery event model if it makes sense.
This also seems to fix a …
> Bugfix: Memory leak in TreeView

- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostClient.rei
- src/Extensions/ExtHostClient_Terminal.re
- src/Store/ExtensionClient.re
This change adds an `ExtHostClient_Terminal` module, in a similar vein to the `ExtHostClient_SCM` module.
It exposes a set of messages and a parser for unpacking `MainThreadTerminalService` messages from the extension host to the editor, as well as a `Request` module to help with making requests to the `ExtHostTerminalService` module.
Part 2 will create a `Service_Terminal` module - a service that exposes this as a subscription and effects on top of this (with the `ExtHostClient` as a dependency).
> Feature - Terminal - Part 1: Initial extension host integration

- src/Core/Json.re
- src/Extensions/ExtensionScanner.re
It now logs the actual error message, while previously it just said there was an exception because the result was an error, ignoring the error message in the result.
Also fixes `Json.Decode.obj` so that field value decoding failures manifest as actual errors with optional fields.
> Improve error reporting from extension manifest parsing 

- integration_test/lib/Oni_IntegrationTestLib.re
- integration_test/lib/dune
This hooks up the Revery `HeadlessWindow` APIs, so that we can exercise our rendering / UI during our integration tests, to get more coverage.
Previously, this wasn't doable, because we could only render when OpenGL was present - but Skia gives us a fallback to software rendering.
> Test - Integration: Use headless rendering APIs for more coverage

- integration_test/EchoNotificationTest.re
- src/Store/VimStoreConnector.re
As part of our older notification experience (before @glennsl did the awesome UX revamp in #1184 ), we had set it up so that pressing `<ESC>` when a notification was open would clear it out.
This is still wired up, but I think it makes less sense in the current experience, since the notifications are much less obtrusive - it's not obvious that pressing 'esc' is removing them unless you watch the notification counter carefully.
> Bugfix: Don't clear notifications with <ESC>

- docs/docs/for-developers/building.md
> [docs] add libtool requirement to macOS build instructions

- src/Components/ContextMenu.re
- src/Components/ContextMenu.rei
- src/Model/Actions.re
- src/Model/Notifications.re
- src/Model/State.re
- src/Store/ContextMenuStore.re
- src/UI/Root.re
- src/UI/StatusBar.re
Uses the same hook setter trick used in Tooltip, which simplifies the API quite a bit. Also added support for multiple open menus at once in the component itself. Making sure there's only a single menu open is therefore an application-concern now, which is much cleaner.
> Use hook setter for inter-component comunication in ContextMenu

- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/Terminal/Feature_Terminal.rei
- src/Service/Terminal/Service_Terminal.re
- src/UI/EditorGroupView.re
- src/UI/TerminalView.re
This implements resize handling, such that the terminal instance is always in sync with the visual representation.
In the UI, we hook up an `onDimensionsChanged` handler for the `<TerminalView />` - if the dimensions change, we recalculate the visible rows / columns and dispatch a msg, which updates the terminal state. 
The terminal subscription manages synchronizing this - there was a bug where the order of arguments for `rows`/`columns` was reversed, so that was fixed.
In addition, we were only caring about the size of `<EditorSurface />` buffer renderers - this changes the `<EditorGroupView />` such that it sizes any buffer renderer, as the terminal relies on this to be correctly sized.
> Feature - Terminal: Handle resize

- src/Core/Cursor.re
- src/Core/Oni_Core.re
- src/Core/Theme.re
- src/Feature/Editor/BufferViewTokenizer.re
- src/Feature/Editor/CursorView.re
- src/Feature/Editor/SurfaceView.re
A few technical adjustments were needed to bring in the theme colors. The cursor was converted from a component to an immediate mode render function, and the "background", i.e. the text under the cursor, is now rendered on top of the cursor using the background color.
> Editor: Themable cursor

- src/Components/FlatList.re
- src/UI/ExtensionListView.re
This fixes it so that the extension list doesn't scrunch the search pane, and hopefully doesn't unfix something else using the FlatList. I think I've tested everything, even the completions view eventually.
I also tried to fix the Dock scrunching the status bar when the window is really small, but wasn't able to figure out the right incantation for that.
> Fix extension list scrunching the search pane

- src/Components/MessageBox.re
- src/Core/Theme.re
- src/Feature/Editor/EditorHorizontalScrollbar.re
- src/Feature/Editor/EditorVerticalScrollbar.re
- src/Feature/Search/Feature_Search.re
- src/UI/Dock.re
- src/UI/EditorGroupView.re
- src/UI/EditorView.re
- src/UI/FileTreeView.re
- src/UI/MenuItem.re
- src/UI/NotificationsPane.re
- src/UI/OniBoxShadow.re
- src/UI/QuickmenuView.re
- src/UI/Root.re
- src/UI/Tab.re
- src/UI/Tabs.re
- src/UI/TreeView.re
- src/UI/WelcomeView.re
Fixes #1073 
- The tab colors weren't picked up from the theme, now they are
- The treeview arrow color was hard-coded, now uses theme foreground color
- The theme used in #1370 depends a lot on fallback colors, which were mostly wrong in out theme settings. I've fixed up quite a few of them, but the theme architecture really needs an overhaul to be able handle this correctly.
- The dropshadow from the minimap seems like a custom style. It doesn't show up in any vscode theme I have, including the theme used in #1370.
I also brought in a few more theme colors for the tabs and activity bar, and cleaned up the tabs component a bit.
Edit: For comparison, a screenshot of vscode and oni2 before, from #1370:
> Fix bad theme fallback colors, especially for light themes

- integration_test/RegressionDeleteAllLinesTest.re
- integration_test/dune
- src/Feature/Editor/EditorDiffMarkers.re
- test/UI/EditorDiffMarkersTest.re
__Issue:__ While working on #1383 and tested the fix, I saw a crash when opening a file, and then deleting all lines (`ggdG`).
I obtained a crash log which made it pretty easy to troubleshoot: 
```
(Invalid_argument "index out of bounds"):
Raised by primitive operation at file "src/Feature/Editor/EditorDiffMarkers.re", line 60, characters 18-54
Called from file "option.ml", line 24, characters 57-62
Called from file "src/Feature/Editor/EditorSurface.re", line 181, characters 8-42
Called from file "src/UI/EditorGroupView.re", line 204, characters 10-925
Called from file "src/UI/EditorLayoutView.re", line 54, characters 12-74
Called from file "list.ml", line 92, characters 20-23
Called from file "src/UI/EditorLayoutView.re", line 37, characters 2-583
Called from file …
```
> Bugfix: Crash when deleting all lines of a file

- src/Core/Theme.re
Following from the huge improvements @glennsl made in #1380 for light themes - I noticed there's still an issue with the whitespace rendering - the 'dots' when show whitespace are on are very dark and distracting compared to the text:
__Before:__
__After:__
The value was hardcoded and not picked up from themes, previously - this loads it from the theme and brings in the same defaults as VSCode for light/dark/hc themes.
> Theming: Fix editorWhitespace.foreground defaults

- src/Feature/Editor/Draw.re
__Issue:__ When tabs are present in the editor surface, and the editor is scrolled, the tab characters stay stuck in place.
__Defect:__ We use a slightly different codepath for rendering tabs (it uses a different font) - in this code path, we were not taking into account the scroll offsets. It looks like this regressed in https://github.com/onivim/oni2/pull/1324
__Fix:__ Include scroll offsets in x/y position calculation.
Fixes #1387
> Fix #1387: Tab characters rendered in place when scrolling

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Pick up fix for memory leak in harfbuzz:
```
=================================================================
==24296==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 152 byte(s) in 1 object(s) allocated from:
#0 0x7fcb89a3c79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
#1 0x7fcb88e9792e in hb_blob_create (/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0+0x692e)
Indirect leak of 227848 byte(s) in 1 object(s) allocated from:
#0 0x7fcb89a3c602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
#1 0x8f1a3d in get_font_ot /home/vsts/.esy/3/b/reason_harfbuzz-d8c087a9/default/src/harfbuzz.cpp:52
#2 0x8f1c7d in rehb_new_face /home/vsts/.esy/3/b/reason_harfbuzz-d8c087a9/default/src/harfbuzz.cpp:85
#3 0x7137b2 in camlHarfbuzz__hb_new_face_90 …
```
> Bugfix: Harfbuzz memory leak

- scripts/release.js
Add the `com.apple.security.cs.allow-dyld-environment-variables` entitlement, to allow loading via `dylib` `@executable_path`variables.
Related to (and hopefully fixes) #1397
> #1397: OSX - Packaging: Add dyld env entitlement

- scripts/release.js
There was an error from the codesigning of  latest builds in the release portal:
```
Onivim2.app: a sealed resource is missing or invalid
file added: /Applications/Onivim2.app/Contents/Resources/node/node_modules/vscode-exthost/out/vs/workbench/services/search/test/node/fixtures/üm laut汉语/汉语.txt
file missing: /Applications/Onivim2.app/Contents/Resources/node/node_modules/vscode-exthost/out/vs/workbench/services/search/test/node/fixtures/üm laut汉语/汉语.txt
```
This removes the problematic files from our release bundle. A more complete fix that we need will be to remove all the test files from the `vscode-exthost` npm module - there's no reason to bundle this test code and fixtures with it, because they are totally unused.
> Bugfix - OSX: Remove problematic files from codesigning

- src/UI/SneakView.re
There is a Y-Axis offset for sneak items. This pushes the items partially out of the view as stated here: https://github.com/onivim/oni2/issues/1284
This PR removes the offset and fixes the first two bugs mentioned in the linked issue, which are:
- Tab navigation is half out of view
- The navigation for the directory tree (and left of) is slightly too high
I'm not sure if the offset is wanted. If it is, just reject the PR.
Old state:
New state:
> Fix: Remove y-axis offset of sneak items

- src/Core/Uri.re
- test/Core/UriTests.re
This resolves issue #1343, but I'm unable to test it on Linux or Mac
> fix: Correctly handle go to definition on Windows

- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
Would something like this work for mapping ctrl+s to save? Thoughts on alternative ways to handle it?
> allow saving of buffer with ctrl+s

- azure-pipelines.yml
- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/bin_editor/HealthCheck.re
- test.esy.lock/index.json
This will help give us some assurance that harfbuzz is still working as expected in our install packages - regardless of whether we statically or dynamically link.
> HealthCheck: Add harfbuzz healthcheck

- .ci/publish-build-cache.yml
Our caching is failing in Azure CI due to the following error: 
```
Uploading 1 files
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Total file: 1 ---- Processed file: 0 (0%)
Fail to upload '/home/vsts/work/1/a/esy-cache.tar' due to 'No space left on device'.
System.IO.IOException: No space left on device
at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
at System.IO.FileStream.FlushWriteBuffer()
at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
at System.IO.FileStream.<>c.<WriteAsyncInternal>b__110_0(Task t, Object s)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at …
```
> CI- Cache: Clear esy folder after caching

- bench.esy.lock/index.json
- bench.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- integrationtest.json
- package.json
- test.esy.lock/index.json
- test.json
Dune 2 no longer "promotes" install (and META) files to the source directory, so if we reference those the install will fail if it has not previously been built with dune 1.x. And even if it has, those files may then be stale. This fixes that by pointing to the install files in the build directory, and also requires dune 2.x.
> Bugfix: Dune 2.x proofing

- src/Model/WindowTree.re
- src/Store/WindowsStoreConnector.re
- test/Model/WindowTreeLayoutTests.re
- test/Model/WindowTreeTests.re
When creating a window split, via `:vsp` or a command, this changes the default to create the split to the right of the current split (for `:vsp`), or below the current split (for `sp`). This is a more natural default than what we had before.
As a next step, once #1436 is in, I'd like to make this configurable as well.
> Window Splits: Change default split direction to right / down

- src/Model/Actions.re
- src/Model/EditorGroup.re
- src/Model/EditorGroup.rei
- src/Model/EditorGroupReducer.re
- src/Store/CommandStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
This wraps around like VSCode.
Fixes #778 and part of #1423.
> Implement the next/previous editor commands and keybindings

- azure-pipelines.yml
Looks like the restoration of build caches for OSX (our hygiene checks + macOS10.14 build) - weren't leveraging the build caches.
> CI: Restore build cache for OSX

- src/Core/ColorTheme.re
- src/Core/ColorTheme.rei
- src/Feature/SCM/Feature_SCM.re
- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/Terminal/Feature_Terminal.rei
- src/Feature/Theme/Feature_Theme.re
- src/Feature/Theme/Feature_Theme.rei
- src/Feature/Theme/GlobalColors.re
- src/UI/Dock.re
- src/UI/StatusBar.re
- src/UI/Tab.re
- src/UI/Tabs.re
- src/UI/TerminalView.re
Refactors the ColorTheme API to (more or less) use the same `Schema` mechanism as introduced in #1436, as well as some other minor refinements.
> Theme revamp - part 2: Schema refactor

- bench/lib/EditorSurfaceBench.re
- src/Feature/Editor/CursorView.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/SurfaceView.re
- src/UI/EditorGroupView.re
Also skips rendering the cursor in inactive splits, which is consistent with both vim and vscode.
> Render non-solid cursor when window is unfocused

- src/Extensions/ExtHostClient.rei
- src/Extensions/ExtHostClient_SCM.re
Addresses #1471. The SCM extension used (fossil) exercised a scenario we hadn't encountered before, where a command is sent over without the arguments field. This is compeletely valid, but the decoder used would reject this instead of returning an empty list. This therefore adds a new custom decoder to handle this correctly.
> Bugfix: #1471 - updateSourceControl crash

- test/Extensions/ExtHostProtocolTests.re
- test/Extensions/ExtHostTransportTests.re
- test/Extensions/ExtensionClientTest.re
- test/Extensions/LanguageConfigurationTest.re
The extension tests were opening `Oni_Core_Test`, which caused the following `open TestFramework` to open the core test framework and therefore register as core tests instead of extension tests. And since (some of) these tests are very slow and not very unit-test-like, they were really slowing down the feedback loop when working on the core tests.
This removed the unnecessary `open Oni_Core_Test`  and instead brings in in `Oni_Core_Test.Helpers` in only the one place where it is actually used.
> Remove extension tests from core test project

- src/Components/FontAwesome.re
- src/Components/FontIcon.re
- src/Core/Constants.re
- src/Feature/Editor/Draw.re
- src/UI/Dock.re
- Moves the regular fontFamily into the FontAwesome module alongside the solid one
- Uses the FontAwesome module to draw tab character in Editor instead of hard-coding it with magic numbers and such
- Switch the File Explorer Dock icon to use the more light-weight regular style
> FontAwesome regular style tweaks

- docs/docs/configuration/settings.md
The referenced issue is closed as fractional scaling should be supported since the move to Skia.
> [docs] Remove outdated note on fractional scaling

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Extensions/LanguageConfiguration.re
- test.esy.lock/index.json
__Issue:__
There were a couple of broken auto-closing pair cases, when the `notIn` conditional is used.
For example, in Reason, the configuration looks like this:
```
{ "open": "{", "close": "}" },
{ "open": "[", "close": "]" },
{ "open": "(", "close": ")" },
{ "open": "\"", "close": "\"", "notIn": [ "string" ] },
{ "open": "/**", "close": " */", "notIn": [ "string" ] }
```
In the case of typing a string, like `"|"`, pressing `<BS>` wouldn't delete the pairs, and pressing `"` wouldn't pass-through. This is because the `notIn` flag would be picked up (we'd properly detect we're in a string, and disable the closing pair). However, the disabling impacting the deletion and pass-through behaviors, which is a bug.
__Fix:__
Libvim doesn't know about the `notIn` parameter, or syntax scopes at …
> Bugfix - ACP: Fix pass-through and deletion behavior with 'notIn' conditional

- development_extensions/oni-dev-extension/extension.js
- development_extensions/oni-dev-extension/package.json
- integration_test/lib/TextSynchronization.re
- src/Extensions/ExtHostClient.re
- src/Extensions/ExtHostClient.rei
- src/Feature/Notification/Feature_Notification.re
- src/Feature/Notification/Feature_Notification.rei
- src/Model/Actions.re
- src/Store/ExtensionClient.re
- src/Store/ExtensionClientStoreConnector.re
- test/Extensions/ExtensionClientHelper.re
- test/Extensions/ExtensionClientTest.re
This creates the appropriate notification based on the severity of the message coming from the extension, and appends the extension id to the message to be able to identify where the message comes from.
It's a bit of an intermediary improvement, as we should probably enrich the notification with a `source` field and need to add support for commands and such eventually.
> Carry severity and extension id from extension message to notification

- bench.esy.lock/index.json
- docs/docs/configuration/key-bindings.md
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Store/InputStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
- src/Store/VimStoreConnector.re
- test.esy.lock/index.json
__Issue:__ When pasting via `<C-v>` in the command line, we'd crash.
__Defect:__ `<C-v>` in the command line actually engages the 'insert-literal' behavior, which blocks for input (causing a hang). This root cause is addressed in https://github.com/onivim/libvim/pull/191 , removing that functionality (we can bring it back in the Onivim 2 input layer if it is desired).
__Fix:__ In the Onivim 2 side, hook up our paste command to work with the command line too.
Related to #1233 , and might not be necessary at all with that change (especially if we move more of the command line behavior to Onivim 2)
__TODO:__
Fixes #496
> Fix #496: Crash when pasting from commandline

- bench/lib/EditorSurfaceBench.re
- bench/lib/Helpers.re
- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Feature/Editor/EditorHorizontalScrollbar.re
- src/Feature/Editor/EditorMetrics.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/EditorVerticalScrollbar.re
- src/Feature/Editor/Minimap.re
- src/Feature/Editor/SurfaceView.re
- src/Model/EditorGroup.re
- src/Model/EditorGroup.rei
- src/Model/EditorGroupReducer.re
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Model/EditorMetricsReducer.re
- src/Model/EditorReducer.re
- src/Model/EditorVisibleRanges.re
- src/Store/CommandStoreConnector.re
- src/Store/Reducer.re
- src/Store/VimStoreConnector.re
- src/UI/EditorGroupView.re
This is a refactoring in preparation for terminal-normal mode - we currently have two different font settings (one for the editor, and one for the terminal). 
However, for the terminal, it's a bit jarring if we're switching back and forth between those fonts - without any changes, we'd switch from the terminal font to the editor font when entering 'terminal normal mode'.
This is an incremental refactoring - to allow editors to have individual settings for fonts. This decouples the font-sizing from the `EditorMetrics.t` (which hopefully we can get rid of completely, soon - and allow `Editor.t` to stand on its own!)
> Refactor - Editor: Per-editor font setting

- docs/docs/configuration/settings.md
- src/Core/ConfigurationParser.re
- src/Core/ConfigurationValues.re
- src/Store/VimStoreConnector.re
This promotes the auto-closing brackets from an experimental feature to on-by-default:
Uses the `language-configuration.json` provided by extensions to pick up the list of pairs that should be completed.
If you prefer the previous behavior, please set this configuration setting:
```
"editor.autoClosingBrackets": "never",
```
> Feature - Auto-Closing Brackets: Enable by default

- src/Feature/Editor/EditorSurface.re
- src/Store/VimStoreConnector.re
- src/UI/EditorGroupView.re
When switching to "Terminal Normal" mode, this uses the terminal font and terminal background/foreground color (overriding the default editor colors), to help smooth the transition. It also disables the diff markers in this mode:
> Feature - Terminal: Use terminal font + background / foreground color

- src/Feature/Syntax/Feature_Syntax.re
- src/Feature/Syntax/Feature_Syntax.rei
- src/Feature/Terminal/Feature_Terminal.re
- src/Feature/Terminal/Feature_Terminal.rei
- src/Store/VimStoreConnector.re
This converts the terminal cell colors to syntax highlights when switching from insert -> normal mode:
It'll look even better when combined with #1517 (which preserves the font and uses the terminal background / foreground colors)
> Feature - Terminal: Preserve cell colors in transition to normal mode

- bench/lib/Helpers.re
- bench/lib/ReducerBench.re
- src/Core/Oni_Core.re
- src/Model/Actions.re
- src/Model/EditorGroups.re
- src/Model/EditorMetricsReducer.re
- src/Store/VimStoreConnector.re
- src/UI/EditorGroupView.re
- src/UI/GlobalContext.re
- src/bin_editor/Oni2_editor.re
Fixes #1525
*Issue*: With `"editor.zenMode.singleFile": false`, opening a single file caused a crash.
*Defect*: When initially rendered the size of the editor will be reported as 0, and when subtracting the height of the tabs will lead to a negative height, which when later used with `List.init` causes it to raise an `Invalid_argument` exception, thus crashing the editor.
*Fix*: Ensure the height, after subtracting the height of the tabs, is >= 0.
Note that a crash could also have been avoided here by using a standard library with saner behaviour, but that's a slightly more involved fix.
I also took the opportunity to do a bit of incremental house cleaning while I was in the general area.
> Bugfix: Don't crash when opening single file with zen mode disabled

- src/Service/Terminal/Service_Terminal.re
- src/UI/TerminalView.re
__Issue:__ There would be a crash (segfault) when vertically splitting a terminal, while in Zen mode.
__Defect:__ In this case, we'd end up setting the terminal rows & columns to `0` - which would cause problems later when the terminal accepts input.
__Fix:__ Do not allow 0-sized terminal - clamp the rows/columns to `1` or higher.
Fixes #1434
> Fix #1434: Crash when vertical splitting terminal in zen mode

- src/UI/TerminalView.re
__Issue:__ When opening another terminal in the _same window_, there'd be no output - the terminal would be blank. However, opening a terminal in a different split works OK.
__Defect:__ The terminal relies on getting size information from the UI - when the `<TerminalView />` is rendered, it hooks up an `onDimensionsChanged` callback to listen for changes in the dimension - this gets called on first render, too. This pushes the current rows / columns for the current terminal, so it gets sized correctly.
However, in the case where a new terminal was rendering in the same `<TerminalView />`, the onDimensionsChanged wouldn't get triggered, because it is the same size. (To the reconciler - it's still the same element)
__Fix:__ The ideal fix would be to have a notion of a `key` like in React, …
> Fix #1461 - second terminal in same window has no output

- src/Core/Buffer.re
- src/Core/BufferPath.re
- src/Model/BufferRenderer.re
- src/Store/BufferRendererReducer.re
- src/Store/VimStoreConnector.re
- src/UI/EditorGroupView.re
- src/UI/VersionView.re
- src/UI/WelcomeView.re
This hooks up the `:version` command to show a screen that displays the version of Onivim 2, as well as various components:
__Potential Next steps:__
- Add a sneak-able button to copy and paste
- Allow editing in read-only mode (switch to a buffer in visual mode)
- Add additional version info:
- Harfbuzz compiled / linked version
- libvim compilation flags
Fixes #538
> Fix #538 - Show version info

- src/Feature/Theme/GlobalColors.re
Fixes an issue where the `activityBar.foreground` color is not properly picked up in themes.
> Bugfix: Fix typo in activityBar.foreground color

- src/Feature/Theme/GlobalColors.re
**Issue**: Text in the SCM pane wasn't being rendered (visibly) with some themes
**Defect**: The default SideBar foreground color was unspecified, which is according to vscode's default, but where vscode has view code that handles this, we just fall back to transparent.
**Fix**: Set the default to the "global" foreground color.; This might cause problems down the line if for som reason we need to distinguish the default as unspecified, but we'll cross that bridge when we get there. This also fixes the global foreground color, which had the light and dark colors switched around.
> Bugfix: SideBar color defaults

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Core/ColorTheme.re
- src/Core/ColorTheme.rei
- src/Feature/Theme/GlobalColors.re
- test.esy.lock/index.json
**Issue**: The text under the cursor wasn't being rendered (visibly) with some themes
**Defect**: The default cursor background color was unspecified, which is according to vscode's default, but where vscode has view code that handles this, we just fall back to transparent.
**Fix**: Set the default to the opposite of the foreground color. This is what vscode does in its view code, and this just does using a default computed function instead.
> Bugfix: Cursor background default

- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/SurfaceView.re
When `experimental.editor.smoothScroll` is enabled, the editor surface would scroll smoothly, but the line number and minimap did not. The line number was particularly jarring and could sometimes detract from the smooth scroll effect.
This moves the spring hooks up to a component above, so that the animated `scrollX` and `scrollY` can be used by line numbers / minimap.
> Bugfix: (Experimental) Smooth scroll - Line number / minimap 

- src/Service/Terminal/Service_Terminal.re
__Issue:__ In the terminal, the 'down' arrow key was moving to the right...
__Defect:__ Our mapping of key -> terminal key was incorrect.
__Fix:__ Correctly map the down key to the down terminal key.
Fixes #1546
> Fix #1546 - Error in mapping Vim key to terminal key

- src/Core/WhenExpr/ContextKeys.re
- src/Core/WhenExpr/WhenExpr.re
- src/Core/WhenExpr/WhenExpr.rei
- src/Core/WhenExpr/dune
- src/Input/Keybindings.re
- src/Input/Keybindings.rei
- src/Model/ContextKeys.re
- src/Model/Oni_Model.re
- src/Store/InputStoreConnector.re
- test/Input/KeybindingsTests.re
This creates a new context keys data structure and schema, so that context keys can be defined as contributions and extended with context-specific context keys (:roll_eyes:).
> Refactor: Context Keys

- docs/docs/using-onivim/integrated-terminal.md
I noticed the video and docs were out of sync for going to terminal normal mode. The video has the right command, so this change updates the [integrated terminal docs](https://onivim.github.io/docs/using-onivim/integrated-terminal#normal-mode) to match.
> Documentation - Fix Terminal Normal Command

- src/Feature/Notification/Feature_Notification.re
Follow-up to #1591 
This reverts the notification colors to what we had pre-revamp, with one exception. I changed the warning foreground from white to almost black, because white on bright yellow isn't very legible.
Note also that in #1591 I prefixed the keys with `oni.` to distinguish them from the "standard" vscode colors. I'm trying to do that with all the keys, to prevent future collisions, so that users get a better idea of which colors won't be themed by vscode themes and that they therefore might have to tweak themselves, and for us to have a better idea of what we can freely change without breaking vscode compatibility and not have to dig around in the vscode source for.
> Revert Notification Color Defaults To Pre-Revamp Colors

- docs/docs/configuration/settings.md
Small change to align the spelling of `antialiased` in the options list and description of `editor.fontSmoothing`. I originally pasted the wrong one into my settings and thought it didn't have an impact, but after updating the spelling it was perfect.
> Documentation - Fix typos in editor.fontSmoothing

- assets/tutor/dune
- assets/tutor/tutor
- src/Store/CommandStoreConnector.re
- src/Store/VimStoreConnector.re
This adds Vim's tutor as an asset, as well as a command to open it. Addresses #1513 
There's a few problems with it still though:
We might also want to adapt the tutor a bit to our needs. I couldn't at a glance see anything that was entirely incorrect though. Even `:!` commands sort of work.
> Feature: Add Vim Tutor

- src/Feature/LanguageSupport/Diagnostic.re
- src/Feature/LanguageSupport/Diagnostics.re
- test/Feature/LanguageSupport/DiagnosticTest.re
__Issue:__ In certain conditions - like a diagnostic covering a very, very large range - we could crash when 'exploding' the diagnostic across lines.
__Defect:__ The `List.map` wasn't stack-safe, so for a very large list range, we'd hit a stackoverflow.
__Fix:__ Create a maximum acceptable length to 'explode', and use the stack-safe variant of `List.map`. Without clamping the list via `List.firstk`, we'd still hit a stack overflow in the consolidation of the Diagnostics in the `_explodeDiagnostics` when we go to flatten.
Fixes #1607
> Fix #1607 - Stack overflow in Diagnostic.explode

- src/Feature/Editor/EditorConfiguration.re
[As stated in the docs](https://github.com/onivim/oni2/blob/master/docs/docs/configuration/settings.md), the default value for `insertSpaces` should be true, not false.
> Fix insertSpaces default value

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
This picks up https://github.com/revery-ui/revery/pull/815 , which changes the default text rendering strategy to subpixel-antialiased - this fixes the issue where, when there is a scale factor applied, the text metrics aren't calculated correctly.
More details in https://github.com/revery-ui/revery/pull/815
Fixes #1592
> Fix #1592 - Default to subpixel-antialiased text positiong & rendering

- bench.esy.lock/index.json
- bench.esy.lock/opam/markup.0.8.2/opam
- esy.lock/index.json
- esy.lock/opam/markup.0.8.2/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/markup.0.8.2/opam
- package.json
- src/Syntax/GrammarRepository.re
- test.esy.lock/index.json
- test.esy.lock/opam/markup.0.8.2/opam
Brings in the changes https://github.com/onivim/reason-textmate/pull/54 and https://github.com/onivim/reason-textmate/pull/55 which added parsing of XML grammars and themes, respectively, to reason-textmate.
Has so far been tested to work with:
- https://github.com/chiragpat/tomorrow-and-tomorrow-night-operator-mono-theme
- https://github.com/glennsl/vscode-duotone-dark-faithful
- https://github.com/JustusAdam/language-haskell
Let me know if there's anything else we should test.
Fixes #912 
Probably fixes #1486 
Addresses #1471, but does not completely fix it. See comment below
> Feature: XML Theme and Grammar support

- src/Feature/Syntax/Feature_Syntax.re
- src/Feature/Syntax/Feature_Syntax.rei
- src/Service/Syntax/Service_Syntax.re
- src/Service/Syntax/Service_Syntax.rei
- src/Store/StoreThread.re
- src/Store/SyntaxHighlightingStoreConnector.re
- src/Syntax/NativeSyntaxHighlights.re
- src/Syntax/Protocol.re
- src/Syntax_Client/Oni_Syntax_Client.re
- src/Syntax_Server/Oni_Syntax_Server.re
- src/Syntax_Server/State.re
- src/Syntax_Server/State.rei
#1613 exposed a timing issue with the server (because the syntax server starts later than it did in the prior strategy) - we'd lose the theme and configuration events because they'd be sent before initialization.
A more robust strategy, and in-line with the ultimate goal of removing the `SyntaxStoreConnector` and having it purely be pure-buffer based subscriptions, is to move the theme and configuration info into the subscription. This way, we can handle the synchronization as a detail in the subscription - the consumer just pushes the theme/configuration and the subscription handles the synchronization, which is simpler to work with and manage for the consumer, as well as solving that particular timing issue in #1613.
> Refactor - Syntax: Move theme / configuration to subscription

- src/Feature/Theme/GlobalColors.re
Issue: In the file explorer, when focusing an item the text disappeared
Defect: `list.focusForeground` defaulted to `unspecified` which, unless otherwise handled, equals transparency. This is according to vscode's default definition, but they often then fall back to handling it in some other convoluted way.
Fix: Set the default for `list.focusForeground` to the color of `foreground`
> Bugfix: list.focusForeground defaulted to transparency

- src/Feature/Editor/Editor.re
- src/Feature/Editor/Editor.rei
- src/Model/EditorReducer.re
Small refactoring to move the `scroll*` methods from the `EditorReducer` to the `Editor` - part of on-going work to centralize the `Editor.t` as the source of truth for the editor view / positioning.
As a next step, I'd like to remove the `recalculate` action by pushing some notion of the current buffer contents into the editor. Aside from removing the janky recalculate flow, this is needed for word wrap (for the editor to have more context around buffer updates, so that we can implement line wrapping in response to both changes in size and buffer updates)
> Refactoring: Move scroll methods to Editor

- src/Store/CommandStoreConnector.re
- src/Store/ConfigurationStoreConnector.re
- src/Store/KeyBindingsStoreConnector.re
Added keybindings for zoom in, zoom out and zoom reset according #1423 issue.
I checked zooming behavior in VSCode and they have next logic: default value is 0, minimum is -8 and maximum is 9. Zooming step is 1 which equals to 20%.
Short summary what was done in this PR:
1. Removed minimum value of 1.0 for zooming in ConfigurationStoreConnector;
2. Added keybindings to KeyBindingsStoreConnector for <kbd>Cmd</kbd> + <kbd>=</kbd>, <kbd>Ctrl</kbd> + <kbd>=</kbd>, <kbd>Cmd</kbd> + <kbd>-</kbd>, <kbd>Ctrl</kbd> + <kbd>-</kbd>, <kbd>Cmd</kbd> + <kbd>0</kbd>  and <kbd>Ctrl</kbd> + <kbd>0</kbd>;
3. Added Commands and zoom effect handler to VimStoreConnector.
Minimum value for zooming is 0 because on lower values there is no changes in UI.
And probably there should be some logic to process …
> Add keybindings for zoom in, zoom out and zoom reset

- src/Components/FlatList.re
**Issue:** With a sufficiently long list, and short FlatList viewport, the scrollbar seemed to disappear.
**Defect:** There was no minimum size for the scrollbar thumb, so it eventually ended up being 0.
**Fix:** Constrain the minimum thumb size to 4px.
> Bugfix: disappearing FlatList scrollbar

- src/Core/Command.re
- src/Core/Menu.re
- src/Core/Menu.rei
- src/Core/Oni_Core.re
- src/Extensions/ExtensionContributions.re
- src/Extensions/dune
- src/Feature/Menus/Feature_Menus.re
- src/Feature/Menus/Feature_Menus.rei
- src/Feature/Menus/dune
- src/Model/ContextKeys.re
- src/Model/Extensions.re
- src/Model/State.re
- src/Store/QuickmenuStoreConnector.re
- src/Store/dune
This adds infrastructure to support menus that can be contributed to from both extensions and feature projects. It currently integrates the command palette, and also sets us up for showing menus with commands contributed by extensions, in particular SCM providers which rely heavily on this feature.
Depends on #1595.
TODO (in a future PR):
> Feature: Menu contributions

- src/Core/Utility/StringEx.re
- src/Feature/Editor/HoverView.re
**Issue:** When diagnostic messages spanned multiple lines, the hover window wouldn't fit the message. It wasn't tall enough, and compensated for this by being absurdly long.
**Defect:** Line breaks weren't taken into account when measuring the height and width of a piece of text. Instead it was just assumed that it would be rendered as a single line, with the height being the height of the font and the width being the number of characters multiplied by the font width.
**Fix:** Messages are now split into lines, which are measured individually and added up.
Additionally, this adds removal of extraneous indentation, i.e. indentation that occurs on every line of the message.
Fixes #1183
> Bugfix: Hover window doesn't fit diagnostic messages

- src/Feature/Editor/HoverView.re
**Issue:** Diagnistic messages were centered horizontally in the hover view, which didn't look great for lines with greatly varying lengths.
**Defect:** It seems like `alignItems(Cetenr)` was applied instead of padding under the assumption that there would be only a single line.
**Fix:** Remove centering, apply padding.
Edit: Also, don't reverse the lines of each element.
> Bugfix: don't center diagnostic messages in hover view

- src/Core/Buffer.re
- src/Core/Utility/ArrayEx.re
- src/Syntax/Protocol.re
- src/Syntax_Client/Oni_Syntax_Client.re
- src/Syntax_Server/Oni_Syntax_Server.re
- src/Syntax_Server/State.re
- src/Syntax_Server/State.rei
A perf issue we hit in #1621 (or, exposed, rather) - is the way we are sending and synchronizing buffer lines with our syntax highlight process.
We'd send the entire set of buffer lines to the syntax highlight process on every buffer update - even if just a single line changed. For small files, this isn't so bad - but for large files, it could cause a significantly delay - the event loop would send files in chunks of 8192 bytes, and so it could some time for the full set of lines to be pushed over to the syntax process.
The majority of the time, though, we don't need to send the full buffer - it's sufficient just send a small update. This implements tracking and applying delta updates.
> Perf - Syntax: Delta buffer updates 

- src/Core/Kernel/IntMap.re
- src/Feature/Syntax/Feature_Syntax.re
- src/Store/SyntaxHighlightingStoreConnector.re
I've noticed a jarring experience when deleting lines:
There'd be a temporary flash of unhighlighted or shifted lines.
We should be able to immediately accomodate this, by shifting the highlights to correspond with the buffer update - if lines were added, we shift the highlights down to map to the new lines, and vice versa for deletion. There was a bug in the way were handling deletions, though, that caused this shifting logic to not be correctly applied.
> Perf - Syntax: Fix shift on delete

- src/Store/KeyBindingsStoreConnector.re
This was a regression in the default key bindings - the conditions weren't working correctly for terminal-normal mode.
I noticed with terminal-normal mode, but there were actually several other broken bindings too.
> Bugfix: Terminal normal mode stopped working

- scripts/release.js
Seeing failures on CI like:
```
Updating D:\a\1\s\_release\win32\Oni2.exe icon
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1476
```
https://dev.azure.com/onivim/oni2/_build/results?buildId=11046&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=bb49dc73-3f54-5b89-b75a-67151df6b89d&l=22
This adds a hack to un-set the environment variables for the `rcedit` command.
> Release - Windows: Fix release script

- src/Feature/Theme/GlobalColors.re
- src/UI/SneakView.re
__`master`__:
(Note several themes are unreadable, like `Monokai` - called out in #1686)
__PR__:
(Some themes do not have an ideal contrast, but better than being totally unreadable...)
Fixes #1686
> Fix #1686 - Sneak color unreadable in Monokai theme

- src/Core/Filesystem.re
- src/Core/Filesystem.rei
- src/Extensions/ExtHostInitData.re
- src/bin_editor/PreflightChecks.re
This change means that the Windows config is always loaded from `%LOCALAPPDATA%/Oni2`, regardless of the shell used.
Previously, cmd and powershell would both load correctly but other shells such as git-bash, powershell-core and more would load from a different location, due to `HOME` being set (as far as I can tell).
EDIT: Oh I guess this is technically a breaking change...so we'll need to make sure this is advertised properly, as otherwise people who mainly used Oni2 from say git-bash, will be confused why their config gave up.
> Always load Windows config from %LOCALAPPDATA%

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
@glennsl did all the hard work of unblocking us to be able to use the 4.9.x series OCaml compiler - however, we reverted the change because reason-language-server didn't currently support 4.9.x. 
However, since we use `ocaml-lsp` now for native development, which is compatible with 4.9.x, we can safely bring back that work: https://github.com/onivim/oni2/pull/1278
...and maybe even get to 4.10.x soon.
> Dependency: ocaml -> 4.9

- bench.esy.lock/index.json
- docs/docs/for-developers/building.md
- esy.lock/index.json
- integration_test/ClipboardNormalModePasteTest.re
- integrationtest.esy.lock/index.json
- package.json
- src/Store/VimStoreConnector.re
- test.esy.lock/index.json
Pull in https://github.com/onivim/reason-libvim/pull/116 , modify clipboard provider to specify `character` mode when not multiple lines
Fixes #660 (and also `xp` behavior, when use-clipboard-on-paste is enabled)
> Fix #660 - Clipboard: Specify Character mode when not multiple lines

- azure-pipelines.yml
- scripts/docker-build.sh
- scripts/docker-test.sh
The CentOS build is taking twice as long as it should, because it's rebuilding the entire toolchain for running unit tests. This was originally done to save space; but is no longer necessary since we saved space elsewhere (removing the Android SDK, etc)
> CI - Linux (CentOS): Remove cleanup prior to tests

- integration_test/Regression1671Test.re
- integration_test/dune
Fixes #1671 + adds a regression test.
The actual fix came in https://github.com/onivim/libvim/pull/199 and was picked up here: https://github.com/onivim/oni2/pull/1694
> Fix #1671 - Buffer loses unsaved changes when switching

- src/Model/GlobalCommands.re
**Issue:** The save command had stopped working
**Defect:** In the command infrastructure refactor (#1595), the command id for the save command had been reproduced incorrectly as `workbench.action.save`
**Fix:** Change the command id back to `workbench.action.files.save`
> Bugfix: Fix broken save command

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- test.esy.lock/index.json
Actually pick up the clang 10 build fixes. Not sure why the revery update PR worked with the stale resolution. And not sure why this resolution is needed now, but without it it falls back to 0.6.0. So there you go.
> Dependency: esy-skia -> d60e5fe

- integration_test/ClipboardYankTest.re
- integration_test/ClipboardxpTest.re
- integration_test/ClipboardyypTest.re
- integration_test/dune
- src/Store/VimStoreConnector.re
This fixes a regression from https://github.com/onivim/oni2/pull/1694 (and adds test to cover the case in the future).
__Issue:__ When running `yyp`, which should yank a line and then paste it underneath, the line would actually get pasted on the same line as the line that was yanked from - this was because, in the case where we don't see a yank as multiple-lines, we'd use the `Character` paste mode. There wasn't any context when we 'yanked' to the clipboard that it should be multiple lines.
__Fix:__ When yanking a single-line, and the yank mode is `Line`, we tag it with a newline. Then, we look for the newlines to decide if we should paste linewise or characterwise.
> Bugfix: Linewise clipboard paste (yyp)

- src/Store/Reducer.re
- src/Store/SideBarReducer.re
__Issue:__ When toggling the file explorer via a key-binding, like `Control+Shift+B` - when you're in Zen mode, the file explorer toggles behind the scenes, but nothing happens from the users perspective.
__Defect:__ Even though the toggling occurs in the 'background', we never show the explorer in zen mode.
__Fix:__ When any of the activity-bar-actions are triggered, if zen mode is enabled, we exit zen mode.
Fixes #873
> Fix #873: Exit zen mode when toggling explorer

- src/Core/Utility/ResultEx.re
- src/Exthost/Client.re
- src/Exthost/CompletionContext.re
- src/Exthost/CompletionKind.re
- src/Exthost/DocumentFilter.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Msg.re
- src/Exthost/OneBasedPosition.re
- src/Exthost/Protocol/Exthost_Protocol.re
- src/Exthost/Request.re
- src/Exthost/SuggestItem.re
- src/Exthost/SuggestResult.re
- src/Exthost/dune
- src/Service/Terminal/Service_Terminal.re
- test/Exthost/LanguageFeaturesTest.re
- test/Exthost/Test.re
- test/collateral/extensions/oni-language-features/extension.js
- test/collateral/extensions/oni-language-features/package.json
This is the initial work to wire up language features to the 'v2' extension host, adding a test case for completion.
This adds a `request` API to the client which returns an `Lwt.t` promise with the response payload, and like the previous API, allows specifying a parser/transformer to convert the raw JSON to a strongly typed domain object.
> Exthost v2 - API - Completion

- src/Store/PaneStore.re
- src/Store/WindowsStoreConnector.re
**Issue:** There is actually two separate but related issues. The first is that the search input field doesn't lose focus if the pane is closed by the close button. This has probably been around since the close button got added. The other is more recent, that the editor doesn't take focus when clicked, or when a tab or editor group is selected.
**Defect:** The first issue was caused by simply not popping he search input field focus when the close button is clicked. The second was caused by #1646, more specifically [here](https://github.com/onivim/oni2/pull/1646/files#diff-0ebd45c812a44e8684925f9d3ce599aaL32-L40), where `WindowSetActive` was replaced by `EditorGroupSelected´ and the active window id removed from the window tree, which also inadvertently removed a call to …
> Bugfix #1693: closing the search pane doesn't "defocus it"

- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Model/GlobalCommands.re
- src/Store/WindowsStoreConnector.re
- src/UI/EditorLayoutView.re
- test/Model/WindowTreeLayoutTests.re
- test/Model/WindowTreeTests.re
This refactors `Feature_Layout` to support window resizing and adds a number of commands to do so. Default keybindings are unfortunately blocked by multiple levels of bugs. It will still work with custom keybindings however, if carefully selected, and the PR should still be mergeable. It's just limited in functionality.
TODO:
> feat(workspace): window/split resizing, part 1 - basic functionality and commands

- src/Exthost/Client.re
- src/Exthost/Request.re
This removes some duplication in the parse code for handling responses to requests, and standardizes it to use json decoders
> refactor(exthost) - V2 - use decoder for parsing

- src/Extensions/ExtHostClient.rei
- src/Extensions/ExtHostClient_SCM.re
- src/Feature/SCM/Feature_SCM.rei
The protocol for the `SCMRawResource` object has changed. In the previous extension host, the `SCMRawResource` type looked like this:
```
export type SCMRawResource = [
number /*handle*/,
UriComponents /*resourceUri*/,
string[] /*icons: light, dark*/,
string /*tooltip*/,
boolean /*strike through*/,
boolean /*faded*/,
string | undefined /*source*/,
string | undefined /*letter*/,
ThemeColor | null /*color*/
];
```
https://github.com/onivim/vscode-exthost/blob/8ebec0403c19a038932368df8c89e4676e923dd2/src/vs/workbench/api/node/extHost.protocol.ts#L621
In the new extension host, the `SCMRawResource` type is now:
```
export type SCMRawResource = [
number /*handle*/,
UriComponents /*resourceUri*/,
UriComponents[] /*icons: light, dark*/,
string /*tooltip*/,
boolean /*strike through*/,
boolean …
```
> refactor(exthost) - V2 - SCM - Remove unused SCMRawResource properties

- src/Exthost/Client.re
- src/Exthost/Protocol/Exthost_Protocol.re
For the v2 exthost, we would get warnings after every sent message, as we were not handling the acknowledged message we get back from the exthost.
This sets up a handler and logs it.
> fix(exthost) - Handle acknowledged message type

- src/Core/WhenExpr/WhenExpr.re
**Issue:** `Re` would raise an exception if parsing failed, which was not caught and therefore caused a crash
**Fix:** Catch the exception, recover gracefully when not in strict mode
Addresses #1729
> fix(extensions/#1729): don't crash if unable to parse regex

- src/Core/WhenExpr/WhenExpr.re
- src/Core/WhenExpr/WhenExpr.rei
- src/Core/WhenExpr/dune
- test/Core/WhenExpr/WhenExprTests.re
**Issue:** Some regexes in the GitLens extension failed to parse
**Defect:** It seems to have been caused by the use of negative lookahead assertion (`(?!...)`), which doesn't seem to be valid Perl regex syntax.
**Fix:** Switch to using Oniguruma instead.
Should fix #1729 (though I haven't tried all the regexes) 
```changelog
some gitlens regex patterns failed to parse
<breaking>As this switches to a different regex engine, there's a chance that it might break other extension regexes.</breaking>
```
> fix(extensions/#1729): some gitlens regex patterns failed to parse

- .ci/run-integration-tests.yml
We run `esy cleanup` to try and save disk space on CI machines, but this no longer necessary (and doubles the build time...), since we delete several large SDKs from the linux machines
> chore(ci): Remove integration test clean-up

- assets/changelog.xml
- assets/dune
- bench.esy.lock/index.json
- bench.esy.lock/opam/lambda-term.3.0.1/opam
- esy.lock/index.json
- esy.lock/opam/lambda-term.3.0.1/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/lambda-term.3.0.1/opam
- package.json
- scripts/generate-changelog.js
- src/Feature/Changelog/Feature_Changelog.re
- src/Feature/Changelog/Feature_Changelog.rei
- src/Feature/Changelog/dune
- src/Model/BufferRenderer.re
- src/Model/GlobalCommands.re
- src/Store/CommandStoreConnector.re
- src/Store/VimStoreConnector.re
- src/UI/EditorGroupView.re
- src/UI/dune
- test.esy.lock/index.json
- test.esy.lock/opam/lambda-term.3.0.1/opam
This adds a nifty changelog, as well as an "update" screen that opens after updating, showing all changes since the last version used and, more importantly, any breaking changes users should be aware of.
The changelog is based on the conventions outlined in #1718, and is automatically generated from the commit log and PRs by a script intended to be run during the nightly build, to be packaged together with the releases. The script takes two arguments, the path to the changelog file and an optional authentication token for the GitHub API to increase the rate limit.
> feat(other): add changelog

- src/Store/ExtensionClient.re
__Issue:__ On Windows, when launching the app, the user would be spammed by console windows.
__Defect:__ We sent the wrong flags for spinning up libuv process - we want the extension host to be 'invisible', which the `windows_hide*` flags handle... However, we were also sending the `detached` flag, which is problematic, because, being detached from the parent, means the console windows would become visible whenever the extension host decides to spawn shell commands (which happens frequently with the git extension!)
__Fix:__ Don't use `detached` - the reason we'd consider it is to ensure the extension host process dies when Onivim 2 dies, but that is already baked into the extension host logic (and covered by this test: https://github.com/onivim/oni2/blob/3f50e8d54971a75f11faf617c5a84f40695 …
> bugfix(windows/#1744): Many console windows open on startup

- node/package.json
- node/yarn.lock
__Issue:__ Even after fixing the code-signing notarization issues in #1742 , there was still a Gatekeeper dialog reporting that the app bundle is damaged.
__Defect:__ When we upgraded the `vscode-exthost` dependency, our script that removed extraneous files (like test cases) didn't make it to the new dependency. At best, these extraneous files take up extra space... worst case, they break gatekeeper validation:
__Fix:__ Remove these extraneous files (test folders, css, .js.map files) for the `vscode-exthost` NPM package we use.
Fixes #1747
> bugfix(osx/#1747): Gatekeeper reporting application bundle as damaged

- node/package.json
- node/yarn.lock
Another round of fixes for #1747 - it turns out there were still additional paths I missed in https://github.com/onivim/vscode-exthost/pull/23 that are now addressed in https://github.com/onivim/vscode-exthost/pull/24
Validated locally that there no errors after codesigning... but I'll wait until the portal build is confirmed fix before I close #1747, this time!
> refactor(exthost/#1747): Upgrade exthost to 1.45.6

- bench.esy.lock/index.json
- bench.esy.lock/opam/decoders-yojson.0.3.0/opam
- esy.lock/index.json
- esy.lock/opam/decoders-yojson.0.3.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/decoders-yojson.0.3.0/opam
- package.json
- src/Feature/Editor/Minimap.re
- src/Store/Persistence.re
- test.esy.lock/index.json
- test.esy.lock/opam/decoders-yojson.0.3.0/opam
**Issue:** Every time Oni2 was opened in a previous workspace the window size would grow from what was persisted before is some form of scaling was used.
**Defect:** The window size was persisted using pixel size, but restored using screen coordinates, which would have it grow by the scaling factor each time.
**Fix:** Add a function upstream in Revery to get the window size in screen coordinates and persist that instead.
> fix(technical/#1749): ballooning window size

- bench.esy.lock/index.json
- bench.esy.lock/opam/decoders-yojson.0.4.0/opam
- esy.lock/index.json
- esy.lock/opam/decoders-yojson.0.4.0/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/decoders-yojson.0.4.0/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/decoders-yojson.0.4.0/opam
I got a bunch of deprecation warnings in #1752 causing me to pin to an older version and follow up on it with this. But seems like I was on an outdated tree and the warnings were fixed already in #1708, so this is just to bump it back up to 0.4.0.
> chore(dependency): ocaml-decoders -> 0.4.0

- assets/changelog.xml
- scripts/generate-changelog.js
Before the XML tags for commits had integer literals, which XML does not support. This PR simply changes the attributes to be wrapped with double quotes.
It also adds a note about using the script to generate changelogs locally.
> fix(changelog): Correct invalid XML attributes

- bench.esy.lock/index.json
- bench.esy.lock/opam/conf-pkg-config.1.2/opam
- esy.lock/index.json
- esy.lock/opam/conf-pkg-config.1.2/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/conf-pkg-config.1.2/opam
- package.json
- test.esy.lock/index.json
- test.esy.lock/opam/conf-pkg-config.1.2/opam
This picks up a fix for #1755 from reason-sdl2 - https://github.com/revery-ui/reason-sdl2/commit/4b79da99a9905dae9d36e43f3bcf753482cb59b4
The issue is that, depending on where the added `resizeListener` is hit - we may not be certain of whether the OCaml runtime system is acquired or released. We'd need to check the entry points for that function, and make sure we're releasing prior to a codepath that could hit it.
In the case of #1755, we could add `caml_release_runtime_system` and `caml_acquire_runtime_system` around the `SDL_MaximizeWindow` call - but we need to inventory & investigate and see what other code paths from the OCaml side could hit this (ie, `SDL_MinimizeWindow`, etc), so we can be confident in our fix.
Fixes #1755
> bugfix(osx/#1755) - fix hang on maximize

- src/Model/State.re
__Issue:__ There were warnings showing up in the log for both syntax and terminal settings that no default value as available.
__Fix:__ Add configuration contributions to initial configuration creation.
> bugfix(configuration) - Fix 'no default' errors for syntax/terminal configuration

- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Syntax_Server/State.re
__Issue:__ When opening a file from Onivim 2 (ie, `oni2 some-file.json`), syntax highlighting wouldn't be triggered until reloading the file or changing something. This was the same issue causing the `SyntaxHighlightTreesitterTest.exe` to fail.
__Defect:__ Regression from https://github.com/onivim/oni2/pull/1745 - when the syntax server gets `BufferStartSyntaxHighlighting` message in the new subscription model, it should start doing the work of highlighting. However, it wasn't - it would only start once a `BufferUpdate` came through.
__Fix:__ Create the syntax highlighter (which does the work of highlighting) on that `BufferStartSyntaxHighlighting` message, which will queue work and cause token updates to be sent to the client.
> fix(syntax): regression in first-load syntax highlighting

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Components/LocationList.re
- test.esy.lock/index.json
__Issue:__ On a scaled display - ie, setting `GDK_SCALE` in Linux, or scaled display settings in Windows, every launch of the app would cause the window to grow.
__Defect:__ More fully described here: https://github.com/revery-ui/revery/pull/840 - but the gist is, the initial window creation expected window sizes that were _scaled_, whereas we were reading _unscaled ones_ due to an inconsistency in Revery's API. This meant that every time persistence saved a window size, it would grow by the scale factor.
__Fix:__ Clean up the revery API to use a consistent coordinate space for window creation, setting the size, getting the size, and listening to size changed events. 
Related to #1749, but we should also be more robust in the case window creation fails: …
> fix(persistence/#1749): window growing on each launch in scaled display

- src/Model/Actions.re
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Model/State.re
- src/Store/CommandStoreConnector.re
- src/Store/VimStoreConnector.re
- src/Store/WindowsStoreConnector.re
- src/Store/dune
This removes the imperative `AddSplit` action, to help streamline the path we take when we open a file.
This moves the `addSplit` to just a function call - and removes the need for a special initialization effect to create the initial window split, as it just gets baked into the actual model.
> refactor(layout): Remove imperative AddSplit action

- src/Model/Actions.re
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Store/VimStoreConnector.re
Another round of streamlining the `dispatch`s that happen in the `openFileByPath` effect - this removes the `EditorGroupAdd` imperative action with a function call, to help reduce timing dependencies and streamline the open code path.
> refactor(editor): Remove imperative EditorGroupAdd action

- test/Core/Helpers.re
- test/OniUnitTestRunner.re
- test/OniUnitTestRunnerCore.re
- test/OniUnitTestRunnerExtHost.re
- test/OniUnitTestRunnerInput.re
- test/OniUnitTestRunnerModel.re
- test/OniUnitTestRunnerUI.re
- test/dune
Same issue as https://github.com/revery-ui/revery/pull/845
__Issue:__ `esy @test run` stopped producing output on all the windows devices I tried.
__Defect:__ Linking in `reason-sdl2` brings in the `-mwindows` flag, which causes the application to not allocate or attach console.
__Fix:__ Explicitly attach a console for the test runner.
> test(windows): No unit test output on windows

- src/Exthost/Msg.re
- test/Exthost/SCMTest.re
- test/collateral/extensions/oni-scm/extension.js
- test/collateral/extensions/oni-scm/package.json
This adds test cases to cover the register/unregister methods of the extension host SCM API, and also fixes a bug that was hit while editing the cases - the `$registerSourceControl` API method, although documenting the handle as a `number`, was sending us a `string` - so we'll handle that case as well.
> test(exthost): Add test case to exercise SCM API

- src/Core/Persistence.re
- src/Core/Persistence.rei
- test/Core/PersistenceTests.re
- test/Core/dune
__Issue:__ If the `store.json` is corrupt, we crash on launch - described by #1766 
__Defect:__ There are some additional error cases - like a corrupted `store.json` file - that could cause us to crash.
__Fix:__ Log out errors, but revert to defaults if we can't load the persistence file.
> fix(persistence/#1766): Blank input data

- src/Core/Uri.re
- test/Exthost/UriTest.re
- test/collateral/extensions/oni-uri/extension.js
- test/collateral/extensions/oni-uri/package.json
This adds an `$mid` field to the encoded JSON of URIs, so that the exthost marshaller can properly detect it.
> fix(exthost): marshalled URIs not revived correctly

- integration_test/Regression733Test.re
- integration_test/dune
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Model/EditorGroup.re
- src/Model/EditorGroupReducer.re
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Store/StoreThread.re
- src/Store/VimStoreConnector.re
- src/Store/WindowsStoreConnector.re
- src/UI/EditorGroupView.re
__Issue:__ There are a few ways, like #733 , where it was possible to get to a state where all buffers are closed and there is a blank screen. If that wasn't bad enough... you can't even reopen any buffers, you're just stuck on the blank screen!
__Defect:__ We'd clear out all window splits and editor groups in this case, but once they're cleared, there wasn't a way to get them back.
__Fix:__ Consolidate the 'close-editor' logic - the `editorGroups` and window layout are tightly coupled, so bring those together - we may want to think about merging these closer together. But this factors out some hard-to-follow nested reducer logic. 
Fixes #733
> fix(editor/#733): Closing last window can result in no buffers being able to opened

- azure-pipelines.yml
- scripts/docker/centos/Dockerfile
- scripts/install-git.sh
CentOS 7 defaults to having `git` v1, but we need v2 for our dependencies - this updates the script to pick up git v2+
> chore(CI): Fix CentOS 7 installation of git2

- integration_test/lib/Oni_IntegrationTestLib.re
- src/Model/Actions.re
- src/Model/EditorGroup.re
- src/Model/EditorGroup.rei
- src/Model/EditorGroupReducer.re
- src/Model/EditorGroups.re
- src/Model/EditorGroups.rei
- src/Store/WindowsStoreConnector.re
- src/UI/GlobalContext.re
- src/UI/Tabs.re
- src/bin_editor/Oni2_editor.re
- test/Model/EditorGroupsTests.re
__Issue:__ Sneak mode wasn't working when using it to switch between splits
__Defect:__ The `ViewSetActiveEditor` action was only being dispatched on the currently-active editor.
__Fix:__
- Remove the confusing nested-reducer logic here, and create a top-level function on the `EditorGroups`
- Rename the imperative `ViewSetActiveEditor` to the more descriptive `EditorTabClicked`
Along with #1776 , this fixes #1394
> fix(sneak/#1394): Navigation between splits

- src/Store/StoreThread.re
- src/bin_editor/Oni2_editor.re
- src/bin_launcher/Oni2.re
Fix #1783.
Add back the plumbing for the CLI flag to specify a custom extension folder.
> fix(cli/#1783): add back custom extension dir option

- scripts/docker/centos/Dockerfile
The link we were using was deprecated according to: https://github.com/iusrepo/announce/issues/18
> chore(CI): Fix CentOS ius repo path

- development_extensions/oni-dev-extension/package.json
- src/Exthost/Extension/Exthost_Extension.rei
- src/Exthost/Extension/InitData.re
- src/Exthost/Extension/Manifest.re
- src/Exthost/Extension/Scanner.re
- src/Store/ExtensionClient.re
- src/Store/StoreThread.re
- test/Exthost/ExtensionsTest.re
- test/Exthost/Test.re
- test/collateral/extensions/oni-activation-events/package.json
- test/collateral/extensions/oni-always-activate/package.json
- test/collateral/extensions/oni-basic-events/package.json
- test/collateral/extensions/oni-configuration/package.json
- test/collateral/extensions/oni-diagnostics/package.json
- test/collateral/extensions/oni-document-sync/package.json
- test/collateral/extensions/oni-extensions/extension.js
- test/collateral/extensions/oni-extensions/package.json
- test/collateral/extensions/oni-language-features/package.json
- test/collateral/extensions/oni-scm/package.json
- test/collateral/extensions/oni-uri/package.json
- test/collateral/extensions/oni-virtual-document/package.json
__Issue:__ The python fails with an error when trying to read the extension metadata via the `vscode.extensions` API, here:
```
const extensions = (require('vscode') as typeof import('vscode')).extensions;
// tslint:disable-next-line:no-non-null-assertion
const extension = extensions.getExtension(extensionId)!;
// tslint:disable-next-line:no-unsafe-any
const extensionVersion = extension.packageJSON.version;
```
__Defect:__ The extension IDs we were sending to the extension host were improperly constructed. To be in sync with the extension host, they should be of the form `publisher.name`.
__Fix:__ Correctly construct the extension ID.
This gets us to the next round of blockers of the Python extension - it requires the `workspace.fs` API to implemented (it uses these operations to look for …
> fix(exthost): Fix error when trying to read package metadata

- src/Exthost/Client.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Handlers.re
- src/Exthost/Msg.re
- src/Exthost/Protocol/Exthost_Protocol.re
- src/Exthost/Reply.re
- src/Store/ExtensionClient.re
- test/Exthost/ClipboardTest.re
- test/Exthost/Test.re
- test/collateral/extensions/oni-clipboard/extension.js
- test/collateral/extensions/oni-clipboard/package.json
For the next round of blockers for the extension (ie, implementing the `workspace.fs.stat` API for the python plugin), we need to be able to respond to the extensions correctly for queries like that.
This implements initial plumbing to reply back to the extension host, along with implementing a really simple API to exercise it (the `vscode.env.clipboard` API).
It would be nice to have a more type-safe way to implement this, as ultimately we are responding with just raw JSON - I believe we could use GADTs to tag the `Msg.t` with an expected return type, but I wasn't able to hook it up all the way through. Something to think about though for next steps - it'd be great to have the replies type-safe.
In addition, we want to support having asynchronous replies (for example, we don't want an …
> feature(exthost): Support sending replies from Onivim 2 -> Extension Host

- bench.esy.lock/index.json
- esy.lock/index.json
- integrationtest.esy.lock/index.json
- package.json
- src/Feature/Editor/Minimap.re
- test.esy.lock/index.json
This brings in a new and improved hook-based mouse capture API which should resolve several cases where the mouse capture gets "stuck". It was also supposed to fix the wonky minimap mouse dragging (#441), but no luck figuring that out yet. This is on par with the current behaviour though, so can still be merged as-is to unblock other tasks.
Should fix #817. ~~Might address #250. These depend a bit on interpretation though.~~
> fix(ux): mouse capture issues

- development_extensions/oni-dev-extension/extension.js
- src/Exthost/Command.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/Label.re
- src/Exthost/Msg.re
- src/Model/StatusBarModel.re
- src/Store/ExtensionClient.re
- src/Store/ExtensionClientStoreConnector.re
- src/UI/Label.re
- src/UI/StatusBar.re
- test/Exthost/LabelTest.re
- test/Exthost/StatusBarTest.re
Several of the extensions have custom status bars to help report language server state (ie, `python` shows the active interpreter, `go` lets you know if you need additional tools, etc), and this helps wire up some additional functionality:
- Execute contributed commands when clicking on status bar items
- Implement initial icon-label parsing
- Fix unescaped `"` characters in custom status bars
> feat(exthost): Additional status bar item functionality

- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Model/Actions.re
- src/Store/WindowsStoreConnector.re
- src/UI/EditorLayoutView.re
- test/Model/WindowTreeLayoutTests.re
No need to look too closely at the code, at least the `Feature_Layout` implementation, as I'm planning on refactoring this to use pixel coordinates instead of weight since I've eventually realized that this is an inherent part of the problem domain.
There's also a bit of wonkiness with the handle not properly tracking the mouse once it hits a limit. This is because the mouse coordinates from the events are relative to the window, while the handle and splits are positioned relative to their positional container, so the resizing is done through relative change, which works fine until it is constrained and the handle remains in place while the mouse continues to move. The behaviour is predictable though, and might be easier (or just different) to fix after refactoring, so I think it's fine …
> feat(workspace/#463): split resizing by mouse

- scripts/release.js
Fixes a regression in  the packaged builds, where input handling fails. Need to investigate the full fix, as this removes the capability to open files from finder (since the app delegate is no longer registered) - but fixes the input regression.
I suspect the issue is a `tty` issue - where there is a difference in the tty/channel configuration when running directly as the `CFBundleExecutable` versus being spun up by the launcher process, as was done previously. `libvim` should be agnostic of the terminal or environment - but there are still places where it's dependent on terminal on config.
> fix(macos): Crash when sending input to libvim

- bench.esy.lock/index.json
- bench.esy.lock/opam/ppx_deriving.4.5/opam
- esy.lock/index.json
- esy.lock/opam/ppx_deriving.4.5/opam
- integrationtest.esy.lock/index.json
- integrationtest.esy.lock/opam/ppx_deriving.4.5/opam
- package.json
- src/UI/Root.re
- test.esy.lock/index.json
- test.esy.lock/opam/ppx_deriving.4.5/opam
This is WIP as of now, because it fixes the overdraw for me, but I'm not sure it will be fixed for everyone. This addresses #1817 and the concerns brought up by @CrossR in #1801.
@CrossR and @bryphe, can you test this on your machines to make sure it's a universal fix? I want to make sure it works before it gets merged.
> fix(Windows): remove overdraw when maximized

- package.json
This should make using `esy add` in the future less noisy.
> chore: reformat package.json with esy add

- src/Core/ConfigurationDefaults.re
- src/Core/ConfigurationValues.re
Fixes #1826. The default value itself was fixed in #1580
> fix(configuration/#1826): initial value of editor.insertSpaces deviates from default

- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/ExtensionClientStoreConnector.re
- src/Store/StoreThread.re
__Issue:__ We'd see assertion failures from the extension host when opening a buffer, like:
```
[ERROR]    +1ms Oni2.Extension.ClientStore : {"$isError":true,"name":"Error","message":"Assertion failed (document 'file:///Users/bryphe/oni2/NodeTask2.re already exists!')","stack":"Error: Assertion failed (document 'file:///Users/bryphe/oni2/NodeTask2.re already exists!')
```
__Defect:__ We were sending multiple requests to add the document.
__Fix:__ Move the document synchronization (at least the adding / removing) to a subscription - this will always keep it in sync with the set of buffers in view. We can also use a similar subscription model to keep the list of visible editors in sync with the extension host, and this will also simplify keeping the filetype in sync (ie, to finish up #933)
> fix(exthost): Assertion Failure - document already exists

- src/Exthost/Client.re
- src/Exthost/Msg.re
- src/Exthost/dune
__Issue:__ As described in #1839 and #1840 - when opening a second javascript file, the editor would crash on parsing a `$changeMany` message from the extension host.
__Defect:__ This was likely introduced by https://github.com/onivim/oni2/pull/1835, in which we send 'close' messages more aggressively for buffers not in view. In the case where a buffer (textDocument) was closed, we'd get a `$changeMany` request from the extension host with `null` as the diagnostics. We expect an array, and we currently use a parse strategy that throws (even though we shouldn't throw - we should return the `result` corresponding to the parse).
__Fix:__ Switch from using `Yojson.Safe.Util.to_list` - which throws - to a decoder-based strategy, which returns a `result`.
- Upgrade the …
> fix(exthost/#1839): Fix crash when switching JS files

- src/Core/Utility/File.re
- src/Core/Utility/Utility.re
- src/Syntax_Client/Oni_Syntax_Client.re
- src/Syntax_Client/Oni_Syntax_Client.rei
- src/bin_editor/HealthCheck.re
The healthcheck for windows, for the syntax server, has been failing - an exit code of 2 intermittently comes from the syntax service, but just for the windows builds.
An exit code of 2 is usually indicative of an ocaml exception, so we should be dropping a crash log in that case - this updates the health check to look for a crash log and output the results to give us a clue on where it is crashing.
> chore(windows): Investigate syntax health failure

- src/Store/StoreThread.re
We were running the `Msg.show` for every action dispatched to the store, and `Msg.show` does some heavy allocations to produce the `string` associated with the `Msg.t`. This switches to use `Log.infof`, which will only call the callback function if logging is enabled.
> perf(exthost): Switch info -> info in onBeforeMsg

- src/Feature/Editor/CompletionsView.re
The [`codicons`](https://microsoft.github.io/vscode-codicons/dist/codicon.html) icons set has a full set of icons for the various completion options, so we should use those, instead of the ones we picked from font awesome.
> feat(completion): Use codicons for completion icons

- src/Exthost/Edit.re
- src/Exthost/ExtensionId.re
- src/Exthost/Exthost.re
- src/Exthost/Exthost.rei
- src/Exthost/FormattingOptions.re
- src/Exthost/Msg.re
- src/Exthost/Request.re
- test/Exthost/LanguageFeaturesTest.re
- test/Exthost/Test.re
- test/collateral/extensions/oni-language-features/extension.js
This hooks up the extension host APIs for:
- `provideDocumentFormattingEdits`
- `provideDocumentRangeFormattingEdits`
- `provideOnTypeFormattingEdits`
The next step is to wire this up as a format provider for `libvim` - so that we can leverage it with `=`, `gw`, `gq`, etc.
> feat(exthost): Hook up provide*Formatting APIs

- src/Core/dune
- src/reason-textmate/Pattern.re
- src/reason-textmate/dune
- test/reason-textmate/GrammarTests.re
- test/reason-textmate/PatternTests.re
- test/reason-textmate/onivim/fixtures/nim.json
__Issue:__ The nim syntax extension causes Onivim 2 to crash
__Defect:__ There are a couple issues:
- First, failing to parse the syntax file shouldn't cause a crash
- Second, we're not handling a capture group construction:
We expect capture groups to look like:
```
{"1":{"name":"meta.preprocessor.pragma.nim"}}
```
(be nested in a JSON object with a `name` property).
However, there are some capture groups that have a simplified syntax:
```
{"0":"punctuation.definition.string.end.nim"}
```
which our JSON parser wasn't handling.
__Fix:__ Update our capture group parsing to handle the streamlined form.
Fixes #1825
> fix(textmate/#1825): Crash when parsing Nim syntax

- bench/lib/EditorSurfaceBench.re
- integration_test/lib/Oni_IntegrationTestLib.re
- src/Core/Utility/OptionEx.re
- src/Feature/Editor/Colors.re
- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/Feature_Editor.re
- src/Feature/Editor/Minimap.re
- src/Feature/Editor/Msg.re
- src/Feature/Editor/SurfaceView.re
- src/Feature/Theme/GlobalColors.re
- src/Model/Actions.re
- src/Model/EditorReducer.re
- src/UI/EditorGroupView.re
- src/UI/GlobalContext.re
- src/bin_editor/Oni2_editor.re
This implements several fixes for the minimap, described in #250 :
- Scrolling while dragging was unintuitive, because we were using relative-scroll when we should be setting the scroll to an absolute scroll position. This caused erratic and unpredictable scrolling.
- Mouse position was calculated relative to the window, which was problematic in the case where there were splits - it would not be possible to scroll from the top or bottom.
- Implements click-to-line behavior - clicking on a particular line would result in an unpredictable scroll, because it would move to a line as if it were a vertical scrollbar. However, this now moves to the particular line that was clicked. This is helpful when clicking on a line marked as having an error, for example.
- Refactor to use descriptive …
> fix(editor/#250): Unintuitive minimap scrolling behavior

- azure-pipelines.yml
- scripts/docker-build.sh
- scripts/docker-test.sh
- test/Exthost/Test.re
This splits out the build /test for Linux, as the portal builds (which are run daily) are failing due to flakiness in the extension host tests (extensions are intermittently failing to activate). While I investigate this, I'm going to disable the unit test run for the linux portal builds, until they are stable again.
> chore(ci): Fix portal build failure

- src/UI/FileTreeView.re
- src/UI/TreeView.re
This is a minor one, but:
- Switches to use the foreground-color `SideBar` provided by the theme
- Switches icon to the `angle`-one
- Adjusts some margins in order to align things vertically (see `CODE_OF_CONDUCT.md`)
- Increases the font-size by 1pt 
**Before:**
**After:**
> refactor(explorer): new arrow icon, v alignments

- test/reason-textmate/bin/TextmateCli.re
- test/reason-textmate/bin/dune
@CrossR  - here's the CLI tool I promised, to compliment the work you're doing here: https://github.com/onivim/reason-tree-sitter/pulls
This adds a CLI tool that takes a textmate grammar, a source file, and a line number, and outputs the textmate tokens we parse from it.
An example invocation is:
```
esy '@test' x TextmateCli --file=package.json --grammar=test/reason-textmate/json.json --line=2
```
with output:
```
** Welcome to TextmateCli **
Using arguments:
- sourceFile: package.json
- grammarFile: test/reason-textmate/json.json
- lineNumber: 2
Loading grammar: test/reason-textmate/json.json
Grammar loaded - using scope: source.json
Trying to read file: package.json
Read 274 lines.
Line 2:   "version": "0.4.0",
** Tokens: **
Token(0,2:, meta.structure.dictionary.json, source.json) …
```
> feature(textmate): CLI Tool to print scopes

- src/UI/FileTreeView.re
- src/UI/TreeView.re
Switches the icon to a thinner variant, uses the icon-color from the sidebar of the theme instead of its foreground-color.
**Before:**
**After:**
> refactor(sidebar): switch arrow-icon and use sidebar-color for it

- src/Feature/Layout/AbstractTree.re
- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Layout.re
- src/Feature/Layout/Positioned.re
Implements minimum sizes and "cascading", fixes the tracking of the handle relative to the mouse pointer, and remembers the window state before dragging a handle so that moving the handle back reverts it. It also lays the groundwork for implementing maximization and directional resizing.
> feat(layout): minimum window sizes and cascading

- src/Feature/Editor/EditorSurface.re
- src/Feature/Editor/GutterView.re
__Issue:__ The experimental scroll shadow (https://github.com/onivim/oni2/pull/1907) is showing up over line numbers, even when the configuration is disabled (the default).
__Defect:__ We weren't gating the line-number rendering by the configuration.
__Fix:__ Add `showScrollShadow` parameter
> fix(ui): Scroll shadow is showing on line numbers

- docs/docs/configuration/key-bindings.md
Updates the keybindings reference with the latest additions to layout. Keybindings that don't work because of bugs in `editor-input` have been formatted with strike-through.
> docs: update keybinding reference with layout additions

- src/Feature/Layout/Feature_Layout.re
- src/Feature/Layout/Feature_Layout.rei
- src/Feature/Layout/Layout.re
- src/Store/Features.re
- src/Store/PaneStore.re
- src/Store/SideBarReducer.re
This adds keyboard navigation between editors, the sidebar and the bottom pane as an extension of the existing window movement keybindings. We lack good visual indication of where the keyboard focus actually is, but otherwise it works great!
Adding proper indication of focus will require some design work and is too big to in scope for this PR I think, but let me know if you think it should be added before merging.
> feat(layout): keyboard navigation between sidebar, pane and editors

- src/Store/VimStoreConnector.re
- src/reason-libvim/Effect.re
- src/reason-libvim/Format.re
- src/reason-libvim/Goto.re
- src/reason-libvim/Native.re
- src/reason-libvim/Vim.re
- src/reason-libvim/Vim.rei
- src/reason-libvim/bindings.c
- test/reason-libvim/FormatTest.re
This hooks up the externalization of the indentation and formatting operators in `libvim` (https://github.com/onivim/libvim/pull/204) such that they can be used as the interface for triggering format operations from the VSCode exthost format providers.
> feat(formatting): Hook up '=' operator to exthost formatting strategy

- src/Store/FileExplorerStore.re
**Issue:** The file explorer would not initially set the focus to a file opened from outside of the file explorer. Additionally, the focus would be set to invalid paths, or paths that do not exist in the tree, in certain conditions such as initially when the welcome screen is shown and the focus would be set to `oni://Welcome`
**Defect:** When setting the focus, the path was not checked against the tree. Additionally, the focus was set before the nodes in the path had been loaded.
**Fix:** Validate that the path exists on the tree when settings focus, and set the focus only after loading and revealing the path.
> fix(file-explorer): focus issues

- src/Feature/Editor/CursorView.re
- src/Feature/Editor/Draw.re
- src/Feature/Editor/GutterView.re
- src/Service/Font/FontLoader.re
This fixes #1937 by ensuring monospace fonts in resolutions and prefetching the monospaced variants.
> fix(editor/#1937): non mono font resolution

- src/Store/ThemeStoreConnector.re
Investigating #1933 - we weren't actually logging out the theme name / file being loaded (which would've been useful information to diagnose the bug). This does not address the root cause of #1933, but means it'll be easier to investigate from the log in the future.
> refactor(theme/#1933): Theme name / file path is not logged

- extensions/laserwave/package.json
Bring `LaserWave Italic` back in, since we now support the italics:
> feat(extensions): Add LaserWave Italic extension back

- src/Exthost/Exthost.rei
- src/Exthost/MarkdownString.re
- src/Exthost/SignatureHelp.re
- src/Feature/Hover/Feature_Hover.re
- src/Feature/Hover/Feature_Hover.rei
- test/Exthost/LanguageFeaturesTest.re
- test/collateral/extensions/oni-language-features/extension.js
This change wires up the `documentation` properties for the `ParameterInformation` and `Signature` information coming from the extension host, and updates the test case so that we're actually sending some signature info and validating it comes through.
> fix(exthost): Signature Help - hook up documentation of parameters / signature

- bench/lib/Helpers.re
- src/Model/Actions.re
- src/Service/Exthost/Service_Exthost.re
- src/Service/Exthost/Service_Exthost.rei
- src/Store/ExtensionClientStoreConnector.re
- src/Store/Features.re
- src/Store/VimStoreConnector.re
__Issue:__ Several of the extension host APIs - like signature help and completion - need a reliable way to request with a trigger key, _after_ a buffer update has been processed. We have some complicated interplay to handle this with completion, but it's not really maintainable.
__Fix:__ Add some additional context around buffer updates, specifically, what, if any, character triggered the update. In addition, add a message to report once a buffer update has been queued, along with the trigger character - we can use this context to then trigger features that require the trigger character (ie, signature help / completion).
This could be improved further by moving more of the state / effects from `ExtensionClientStoreConnector` to `Service_Exthost` and `Feature_Exthost` - the `modelChanged` …
> refactor(exthost): Add msg for buffer update queued + trigger key

- test/Feature/Editor/BufferLineColorizerTests.re
- test/OniUnitTestRunnerCI.re
- test/dune
A unit test failure snuck in - there was a suite we weren't running as part of `esy '@test' run-ci` - this brings in the missing suites and a fix for the test failure.
> chore(ci): Fix failing unit test

- extensions/reason-vscode/package.json
__Issue:__ Our bundled `rls` was showing the module path by default, which is a bit unexpected.
__Defect:__ We were defaulting the setting to `true`.
__Fix:__ Change to `false` by default.
Related to #1947
> fix(hover/#1947): RLS - turn module path off by default

- src/Feature/Editor/BufferLineColorizer.re
- src/Feature/Editor/BufferLineColorizer.rei
- src/Feature/Editor/Helpers.re
- test/Feature/Editor/BufferLineColorizerTests.re
This removes a large array allocation, called for every line in the editor (and minimap) - which added GC pressure during the rendering critical path.
> perf(colorizer): Remove array allocations from BufferLineColorizer

- src/Components/Markdown.re
- src/Feature/Hover/Feature_Hover.re
This is to address the second half of #1947. If there isn't/an invalid language, we fallback to this default.
In use with the RLS
> fix(markdown): add default language parameter to Markdown component
